### ISSUE TITLE
parallel_for_each should not ignore exceptions

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#100]
The implementation of parallel_for_each contains the comment: "We can only store one exception.  For more, use when_all()."

The question is - with this limitation, can parallel_for_each be used correctly? I think the answer is no: What happens today if multiple invocations resolve with an exception, is that one of them is returned, and the rest produce "WARNING: exceptional future ignored" warning messages. There is no real way to avoid warnings in this case, so there is no real way to use parallel_for_each() correctly today.

I think it would make more sense for the API to throw a vector of exception pointers. I did this in the collect() function I proposed in ScyllaDB's repair.cc), and Tomek proposed a new multiple_exception type for holding this vector of exceptions.

It's not like we're saving much by *not* collecting all these exceptions - in any case, parallel_for_each() needs to wait for every single invocation to complete, and it already checks if each one failed.

**Comment by tgrabiec** [comment]
To give credit where it's due, I think it was @pdziepak who proposed multiple_exception.

**Comment by avikivity** [comment]
In many cases we don't care about the multiple exceptions.  We can just make parallel_for_each discard all but the exception reported, silencing the warning.

multiple_exception is problematic because it is hard to filter on it (OTOH, if you want to filter, then you don't want to discard; maybe it makes sense (and maybe we should call it parallel_exception so it is tied to its use case)).

For the cases where we do want fine grained control, use when_all().

**Comment by nyh** [comment]
Fixed by commit ee8a11f34c9e60a26fcc818b6fc192f37473ce26.

The fix chosen by Gleb is, as suggested by Avi above, is to ignore all exceptions except one random one. This is indeed a fix for this issue, and in the "common" case where all of the exceptions from all the parallel futures will be the same one, no real information is lost (I'm a bit worried about the non-common case of two completely unrelated exceptions from two different futures). Moreover, this behavior is consistent with the documentation which states that "the return value contains one of the exceptions." and doesn't say anything about what happens to the rest of the exceptions (so they might as well be lost).

**Comment by nyh** [comment]
We already made our decision, that in case multiple exceptions were caught parallel_for_each (and other similar functions) will return only one of the exceptions (at random). But for posterity, I just wanted to note that the C++ standard, Parallelism TS, seems to be going the other way: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0024r2.html:

```
The class exception_list owns a sequence of exception_ptr objects. Parallel algorithms use the exception_list to communicate uncaught exceptions encountered during parallel execution to the caller of the algorithm. 
```

**Comment by nyh** [comment]
For posterity, I just want to point out that at the end, `std::exception_list` wasn't accepted into the C++ standard. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0776r0.html explains why, and http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0322r0 was the last attempt to get it into the standard.
