### ISSUE TITLE
seastar::sstring.find() is not compatible with std::string.find()

### ISSUE THREAD

**Issue by longqimin** [scylladb/seastar#1001]
```
    seastar::sstring empty = "";
    std::string std_empty = "";
    CHECK_EQ(empty.find(empty), std_empty.find(std_empty));
```

the above check will fail because `seastar::sstring.find()` return 4294967295 while `std::string.find()` returns 0.

**Comment by nyh** [comment]
This is not the only difference between `seastar::sstring` and `std::string` - see issue #634 for more, but you're right that this sort of difference is completely unnecessary and can and should be fixed. A patch (and an accompanying test) would be welcome :-)
