### ISSUE TITLE
shared_ptr: static analysis reports 'nonsensical comparison'

### ISSUE THREAD

**Issue by OfekShilon** [scylladb/seastar#1009]
PVS-studio gives several medium-level warnings on trying to order a pointer and nullptr:
![image](https://user-images.githubusercontent.com/73080/151664157-95acd157-9622-4204-b085-92ba124e2def.png)

The warning documentation is [here](https://pvs-studio.com/en/docs/warnings/v503/).  
It does seem [ordering a pointer and nullptr_t is undefined](https://stackoverflow.com/questions/65185742/can-you-compare-nullptr-to-other-pointers-for-order-is-it-always-smaller) - maybe it's best to remove these overloads entirely?

**Comment by avikivity** [comment]
It's not undefined, just unspecified. And comparing pointers is not a nonsensical operation. File a bug in PVS-Studio.
