### ISSUE TITLE
make_exception_future() gets confused by an move of *const* std::exception_ptr

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#1010]
One of the uses of `make_exception_future()` is to return a pre-existing `std::exception_ptr` as an exceptional future.  For example:
```c++
       return do_something.handle_exception([] (std::exception_ptr ep) {
            return some_recovery().then([ep = std::move(ep)] {
                return make_exception_future<>(ep);
            });
       })
```
In this example, the exception returned by do_something() is handled, but also re-thrown as an error after the recovery.

The bug I want to report here is that if the last line is changed to:
```c++
                return make_exception_future<>(std::move(ep));
```
with an extra `std::move()`, it doesn't work. It compiles fine, but does the wrong thing: Instead of returning the same error, it appears that an std::exception_ptr is returned as the actual content of the error (i.e., the future holds an exception_ptr containing an exception_ptr).

This is bad because developers (like myself) might think that using `std::move(ep)` is slightly more efficient (one less reason to diddle with the reference counter inside the exception_ptr), and not realize that while it compiles just - it does the wrong thing. Unless you are testing the error path you won't even notice this bug.

A quick grep in the Scylla project, for example, yields around 20 cases of `make_exception_future<>(std::move(ep))`.

By the way, this leads me to wonder if this is not a recent regression in Seastar - because if it always worked like this, it means none of the above 20 error-handling paths in Scylla were ever tested, which would be surprising (though not impossible).

**Comment by avikivity** [comment]
How can an exception_ptr contain an exception_ptr?

I think you're confusing it with

```c++
    make_exception_future(std::move(ep))
```

where the future type T is inferred.

I agree the ambiguity is bad. We should add an overload to resolve it.

**Comment by nyh** [comment]
No, I most definitely had `make_exception_future<>(std::move(ep))`, which compiled just fine, but did something different from `make_exception_future<>(ep)`.

I'll try to write a test for this later to get a clearer view of what exactly is the problem.

**Comment by avikivity** [comment]
Ah, I understand it now. Yes, it's very unfortunate.

**Comment by avikivity** [comment]
The functions should have had different names. Unfortunately the standard makes the same mistake [1].

[1] https://en.cppreference.com/w/cpp/experimental/make_exceptional_future

**Comment by nyh** [comment]
The plot thickens. I verified that `make_exception_future()` does accept an `std::exception_ptr&&` just fine. For example, the following test does work:
```c++
    std::exception_ptr e5 = std::make_exception_ptr(3);
    future<> f5 = make_exception_future<>(std::move(e5)); // note std::move()
    BOOST_REQUIRE(f5.failed());
    BOOST_REQUIRE_THROW(f5.get(), int); // expecting int, not std::exception_ptr
```

What it does **not** work like is a **const std::exception_ptr &&**! The original code I had that failed looked like
```
       return do_something.handle_exception([] (std::exception_ptr ep) {
            return some_recovery().then([ep = std::move(ep)] {
                return make_exception_future<>(std::move(ep)); // note this std::move()
            });
       })
```
But because the lambdas are not marked "mutable", the "ep" apparently cannot be moved - but we don't get a copy either (which would have been fine! the same code works without the std::move()) but something broken. The following test fails:

```c++
    const std::exception_ptr e6 = std::make_exception_ptr(3); // note const!
    future<> f6 = make_exception_future<>(std::move(e6)); // note std::move()
    BOOST_REQUIRE(f6.failed());
    BOOST_REQUIRE_THROW(f6.get(), int); // expecting int, not std::exception_ptr
```
In the failed test, the type we get for f6.get() is std::exception_ptr instead of int.

**Comment by nyh** [comment]
By the way, this last observation also explains why with the dozens of uses of `make_exception_future<>(std::move(ep))` in Scylla we never noticed this problem - those uses of this idiom had a non-constant exception_ptr - either the exception_ptr was not captured at all (so we non-const) or it was captured in a "mutable" lambda.

**Comment by nyh** [comment]
By the way, this issue was probably introduced in commit 31a8e65551e36c416daab6487b54f7ea395296ff

**Comment by nyh** [comment]
Patch on the mailing list, titled `[PATCH] future: fix make_exception_future(const exception_ptr&&)
External`, dated Jan 30, 2022.
