### ISSUE TITLE
note: ‘seastar::condition_variable::condition_variable() noexcept’ is implicitly deleted because its exception-specification does not match the implicit exception-specification

### ISSUE THREAD

**Issue by foxhunter72143** [scylladb/seastar#1028]
When I build seastar,failed 
`[39/310] Building CXX object CMakeFiles/seastar.dir/src/core/reactor.cc.o
FAILED: CMakeFiles/seastar.dir/src/core/reactor.cc.o 
/usr/bin/g++  -DFMT_LOCALE -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -I../../include -Igen/include -I../../src -Igen/src -O2 -g -DNDEBUG   -std=gnu++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -Wno-error=unused-result -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -std=gnu++17 -MD -MT CMakeFiles/seastar.dir/src/core/reactor.cc.o -MF CMakeFiles/seastar.dir/src/core/reactor.cc.o.d -o CMakeFiles/seastar.dir/src/core/reactor.cc.o -c ../../src/core/reactor.cc
../../src/core/reactor.cc: In constructor ‘seastar::reactor::reactor(std::shared_ptr<seastar::smp>, seastar::alien::instance&, unsigned int, seastar::reactor_backend_selector, seastar::reactor_config)’:
../../src/core/reactor.cc:926:90: error: use of deleted function ‘seastar::condition_variable::condition_variable()’
  926 |     , _thread_pool(std::make_unique<thread_pool>(this, seastar::format("syscall-{}", id))) {
      |                                                                                          ^
In file included from ../../include/seastar/core/reactor.hh:74,
                 from ../../src/core/reactor.cc:32:
../../include/seastar/core/condition-variable.hh:157:5: note: ‘seastar::condition_variable::condition_variable() noexcept’ is implicitly deleted because its exception-specification does not match the implicit exception-specification ‘’
  157 |     condition_variable() noexcept = default;
      |     ^~~~~~~~~~~~~~~~~~
[52/310] Building CXX object CMakeFiles/seastar.dir/src/core/io_queue.cc.o
ninja: build stopped: subcommand failed.`

My gcc version and OS: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04)

**Comment by psarna** [comment]
Looks like a regression from 79dfb83cc93f147eb34f4ca4aa5519a3a55e309d, since neither I nor our CI runs tests on gcc 9.x... @avikivity am I correct to assume, after reading https://github.com/scylladb/seastar/blob/master/doc/compatibility.md#compilers , that we know officially support gcc 10 and gcc 11?

**Comment by psarna** [comment]
if that's the case, then based on the documentation we should still fix the issue for gcc 9 if trivial, but I haven't done any research on it

**Comment by foxhunter72143** [comment]
> Looks like something we should fix in order to restore the compatibility with gcc 10. Meanwhile, if you don't care about this particular test, you can work around it by disabling test compilation:
> 
> * if you use configure.py, add this flag: `./configure.py --without-tests`
> * if you use cmake, add this flag: `cmake .. -DSeastar_EXCLUDE_TESTS_FROM_ALL=YES`

yes,it work when I skip the tests.
