### ISSUE TITLE
perftune.py should switch to AWS IMDSv2 calls

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/seastar#1051]
perftune's [__check_host_type](https://github.com/scylladb/seastar/blob/41be7cc6d3bdf99df21adb6508e62354134b331a/scripts/perftune.py#L549) method uses IMDSv1 for retrieving instance metadata. It turns out that - as described in https://github.com/scylladb/scylla/issues/10490 - Ec2 instances may have only [IMDSv2](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/) HTTP calls allowed.

When requests to IMDSv1 fail, calling `is_aws_i3_non_metal_instance()` will evaluate to `False`, which means that i3.nonmetal instance types will get tuned as if they weren't i3 instances.

**Comment by tomer-sandler** [comment]
https://github.com/scylladb/scylladb/issues/10490 is fixed (closed) and is part of OSS 5.2 release notes.
What's the ETA to get this fixed as well?

**Comment by mykaul** [comment]
Doesn't seem to have been prioritized so far. There's code we can use @ https://github.com/scylladb/scylla-machine-image/blob/next/lib/scylla_cloud.py#L640

**Comment by mykaul** [comment]
BTW, this will also break on IPv6 only environments. There you need to use fd00:ec2::254

**Comment by mykaul** [comment]
@yaronkaikov , can your team (@syuu1228 ) handle it?

**Comment by yaronkaikov** [comment]
@mykaul yes
