### ISSUE TITLE
Is seastar::thread a stackful coroutine?

### ISSUE THREAD

**Issue by xiaoming-qxm** [scylladb/seastar#1053]
> Seastar allows writing such code, by using a seastar::thread object which comes with its own stack.
> 
> The seastar::thread allocates a 128KB stack, and runs the given function until then it blocks on the call to a future's get()  method. Outside a seastar::thread context, get() may only be called on a future which is already available. But inside a  thread, calling get() on a future which is not yet available stops running the thread function, and schedules a continuation for this future, which continues to run the thread's function (on the same saved stack) when the future becomes available.

The above sentences are quoted from [seastar tutorial](https://github.com/scylladb/seastar/blob/master/doc/tutorial.md#seastarthread), Does this mean that seastar::thread is a kind of stackful coroutine?

**Comment by nyh** [comment]
This is Seastar's bug tracker, meant to report issues and request specific features. Questions are better written on the Seastar mailing list (seastar-dev at googlegroups.com) or - I see that you already wrote a question in https://stackoverflow.com/questions/72135948/is-seastarthread-a-stackful-coroutine. I'll respond there.
.
