### ISSUE TITLE
Files created by seastar ignore XFS project inheritance bit

### ISSUE THREAD

**Issue by zimnx** [scylladb/seastar#1057]
Directories created by Scylla have their [project inheritance bit](https://man.archlinux.org/man/core/xfsprogs/ioctl_xfs_fssetxattr.2.en#XFS_XFLAG_PROJINHERIT) set, so files created in them, should inherit project settings. 
```
# xfs_io /tmp/volumes/c24e8552-569c-4fde-bb26-e92f373d128e/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/
xfs_io> stat
fd.path = "/tmp/volumes/c24e8552-569c-4fde-bb26-e92f373d128e/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/"
fd.flags = non-sync,non-direct,read-write
stat.type = directory
fsxattr.xflags = 0x200 [--------P--------]
fsxattr.projid = 2
[...]
```

This isn't the case when Scylla creates a file (notice projid):
```
# xfs_io /tmp/volumes/c24e8552-569c-4fde-bb26-e92f373d128e/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/0000000000000001.sstable/mc-1-big-TOC.txt.tmp 
xfs_io> stat
fd.path = "/tmp/volumes/c24e8552-569c-4fde-bb26-e92f373d128e/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/0000000000000001.sstable/mc-1-big-TOC.txt.tmp"
fd.flags = non-sync,non-direct,read-write
stat.type = regular file
fsxattr.xflags = 0x800 [----------e------]
fsxattr.projid = 0
fsxattr.extsize = 1048576
```

It prevent Scylla from starting up when data directory is under XFS Quota, because when Scylla tries to make a hardlink during sstable writing, kernel complains about cross-device links:
```
ERROR 2022-05-09 13:00:56,227 [shard 0] table - failed to write sstable /var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-34-big-Data.db: storage_io_error (Storage I/O error: 18: filesystem error: rename failed: Invalid cross-device link [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/0000000000000034.sstable/mc-34-big-TOC.txt.tmp] [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-34-big-TOC.txt.tmp])
```
Devices in both locations are the same, although projects IDs are different and hence `link` syscall fails with `EXDEV`.

File created manually in the source link location, can be hard linked in destination location without any issues, only files created by Scylla are affected.
When XFS Quota is disabled on Scylla data directory, these exceptions aren't happening.

I suspect that default value of `fsx_projid` in `fsxattr`
```
struct fsxattr {
	__u32         fsx_xflags;
	__u32         fsx_extsize;
	__u32         fsx_nextents;
	__u32         fsx_projid;
	__u32         fsx_cowextsize;
	unsigned char fsx_pad[8];
};
```
sets invalid project id explicitely here:
https://github.com/scylladb/seastar/blob/6b077f6b068f57a8e45deb20078cba62a5ce0b12/src/core/reactor.cc#L1634-L1647

**Comment by zimnx** [comment]
Thanks for fixing it, can we backport it to Scylla 5.0? 
I tried latest 5.0 image from scylla-nightly and it fails with the same exception about cross-link reference.

**Comment by fruch** [comment]
> Thanks for fixing it, can we backport it to Scylla 5.0? I tried latest 5.0 image from scylla-nightly and it fails with the same exception about cross-link reference.

Run into this issue also in `2021.1.19` while testing upgrades for scylla-operator release.
@mykaul this mean that 2021.1 / 5.0 won't work with operator 1.9, not sure it important, should we consider 2021.1 EOL ?

**Comment by zimnx** [comment]
Small correction:
> this mean that 2021.1 / 5.0 won't work with operator 1.9

Only when xfs quotas are enabled on the volume used by Scylla.
