### ISSUE TITLE
foreign_ptr does not work with abstract base classes

### ISSUE THREAD

**Issue by adamemerson** [scylladb/seastar#106]
I am unable to use a foreign pointer to any class with pure virtual methods due to make_local_and_release. This function copies the actual value pointed to by the encased smart_ptr onto the stack if non-local and makes compilation fail (even if it's not called) for any abstract class.

It would be possible to make this function conditional using a template, but given that it's prone to slicing of subclasses it might be better to remove it.

**Comment by avikivity** [comment]
Maybe we should disappear make_local_and_release() using enable_if<!std::is_polymorphic<...>...>.  @tgrabiec ?

**Comment by tgrabiec** [comment]
@avikivity We could. Or we could remove it like @adamemerson suggests, the method doesn't seem to be used.
