### ISSUE TITLE
RPC send path is prone to producing extra latency

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1067]
(originated from scylladb/scylla#9505)

When sending an RPC message it goes via a dedicated send fiber:

```c++
void connection::send_loop() {
    _send_loop_stopped = do_until([this] { return _error; }, [this] {
        return _outgoing_queue_cond.wait([this] { return !_outgoing_queue.empty(); }).then([this] {
            ...
            auto d = std::move(_outgoing_queue.front());
            _outgoing_queue.pop_front();
            ...
}

future<> connection::send(snd_buf buf, std::optional<rpc_clock_type::time_point> timeout, cancellable* cancel) {
    ...
    _outgoing_queue.emplace_back(std::move(buf));
    ...
    _outgoing_queue_cond.signal();
}
```

The fiber, queue and condvar in question were added by e536555081cde5c8b6eac5f70f691d1fc3da7a8a
Since `condition_variable.signal()` queued the send-loop's fiber for execution, the task in question may happen at the tail of a very long execution queue thus rendering unwanted extra latency for no reason.

The solution can be to replace send fiber with semaphore-guarded continuation chain. One thing to care about it the ability to cancel requests from the middle of the queue. The most important consequence of cancelling should be releasing of the message memory,

**Comment by DoronArazii** [comment]
@xemul can you please consider backport ^^

**Comment by xemul** [comment]
AFAIK we don't backport new features, only fixes. And perf optimization is like a new feature for me
