### ISSUE TITLE
How to open raw socket

### ISSUE THREAD

**Issue by keunjun92** [scylladb/seastar#1077]
Hi,

I am a newbie and want to ask how to open raw socket using seastar.

With posix api,
```c++
int s = socket (PF_INET, SOCK_RAW, IPPROTO_TCP);
```

Thank you in advance.

**Comment by keunjun92** [comment]
I think `demos/l3_demo.cc` could help me. Am I right?

**Comment by xemul** [comment]
Please, send your question to the mailing list
seastar-dev@googlegroups.com . Issues are to report problems or improvement requests
