### ISSUE TITLE
tls_test fails on "NONE:+VERS-TLS-ALL:+AES-128-CBC:+RSA:+SHA1:+COMP-NULL:+SIGN-RSA-SHA1"

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1079]
The `test_x509_client_with_priority_strings` case gets -326(`GNUTLS_E_NO_PRIORITIES_WERE_SET`) from
```c
gnutls_priority_init(&p, "NONE:+VERS-TLS-ALL:+AES-128-CBC:+RSA:+SHA1:+COMP-NULL:+SIGN-RSA-SHA1", &err)
```

Happened most likely after upgrade
```
gnutls-debugsource-3.6.16-1.fc33.x86_64
gnutls-debuginfo-3.6.16-1.fc33.x86_64
gnutls-3.7.4-1.fc34.x86_64
gnutls-dane-3.7.4-1.fc34.x86_64
gnutls-c++-3.7.4-1.fc34.x86_64
gnutls-devel-3.7.4-1.fc34.x86_64
gnutls-utils-3.7.4-1.fc34.x86_64
```

@elcallio , need your help here :)

**Comment by elcallio** [comment]
What is the contents of "err"? 
This does not happen on 3.7.2 (default fedora version)?

**Comment by xemul** [comment]
Upd: it's `test_x509_client_with_priority_strings` test case.

> What is the contents of "err"?

The same as it is before calling the method: `NONE:+VERS-TLS-ALL:+AES-128-CBC:+RSA:+SHA1:+COMP-NULL:+SIGN-RSA-SHA1`.
It's the `tls::certificate_credentials::impl::set_priority_string` that calls it and it initializes err into `prio.c_str()`.

> This does not happen on 3.7.2 (default fedora version)?

I cannot say for 3.7.2, fedora-34 suggests either 3.7.4 or 3.7.1. On 3.7.1-2 it passes.

**Comment by elcallio** [comment]
From what I can tell, it is simply that gnutls/fedora conf thereof no longer allows SHA1 as hash (sign) algo. Changing SHA1 -> SHA256 seems to fix the `set_priority` issue. I am still seeing an error though, so must debug some more.

**Comment by elcallio** [comment]
I sent a patch just removing the line, as trying to make it SHA256 will instead make the prio string unconnectable (apparently).
