### ISSUE TITLE
on_internal_error_noexcept() may return, is that useful?

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#1095]
In commit 3c095cd66f8dbd33ef10abbc6ed425103fe7d96c, @denesb added a `on_internal_error_noexcept` function.

Whereas the regular `on_internal_error` is `[[noreturn]]` - it always crashes or throws - the "noexcept" variant is **not** `[[noreturn]]`. Depending on the setting of the abort_on_internal_error flag, it either crashes or... just returns.

It's not clear to me why would anyone want such a behavior, or how such a function can ever be used correctly. For example, in one Scylla commit https://github.com/scylladb/scylla/pull/10691/commits/93e8ffec1cb79cbf12b0818df843f33c7f95023e @bhalevy ended up using it in the following way:
```c++
               on_internal_error_noexcept(tlogger, format("Memtable flush failed due to: {}", e));
                // If the node is configured to not abort on internal error,
                // but propagate it up the chain, we can't do anything reasonable
                // at this point.
                abort();
```

Isn't this what all callers would want?

Or maybe there's some other use case of on_internal_error_noexcept that I'm not familiar with?

**Comment by denesb** [comment]
> Isn't this what all callers would want?

I personally think @bhalevy misused `on_internal_error_noexcept()` here, we should have added a new variant that just always aborts for this use-case, or just simply log and abort.

> Or maybe there's some other use case of on_internal_error_noexcept that I'm not familiar with?

The original use case is reporting errors in a noexcept context, e.g. in a destructor. `on_internal_error()` was intended to be conditionally fatal so the noexcept variant is also conditionally fatal. Since one cannot throw exception in a noexcept context, the next best thing is log with error.

**Comment by nyh** [comment]
> > Or maybe there's some other use case of on_internal_error_noexcept that I'm not familiar with?
> 
> The original use case is reporting errors in a noexcept context, e.g. in a destructor. `on_internal_error()` was intended to be conditionally fatal so the noexcept variant is also conditionally fatal. Since one cannot throw exception in a noexcept context, the next best thing is log with error.

If users think of the abort_on_internal_error as choosing between an **exception** or a **crash** (it is even documented as "_Abort the server instead of throwing exception when internal invariants are violated_") then arguably, if we're at a point where we can't throw an exception (e.g., a destructor), it makes sense to crash. The original `on_internal_error()` will do that in noexcept context because the throw will cause an abort (albeit an ugly one).

But to your (and `log_on_internal_error_noexcept()`'s) defense, `log_on_internal_error_noexcept()` is accurately documented, and it should already be understandable what it does. Maybe an explicit sentence about it sometimes returning could have made this even clearer.

So I don't know if there's even an issue to fix here. But it's worth discussing.

**Comment by bhalevy** [comment]
I see `on_internal_error_noexcept()` similar to `assert()` that may return under certain conditions (`NDEBUG`).
Maybe adding `abort_on_internal_error` makes sense since there are few places already we call `on_internal_error_noexcept` immediately followed by `abort()` to put an extra nail in the coffin in case the deceased will try to escape from their grave :)

**Comment by denesb** [comment]
I think we should add another variant for the case you describe above. This will basically be a log + abort. The main value of this over an abort is that it logs with the desired logger and is more compact on the call-site.

**Comment by xemul** [comment]
I +1 the helper that logs the error and aborts without looking at `abort_on_internal_error` option.

Regarding the `on_internal_error` family itself -- what kind of ... "internal invariants" are those that allow for user-configurable selection between "crash immediately, the system is fubar" and "throw an exception, I'm feeling lucky today"?

**Comment by denesb** [comment]
`on_internal_error()` can replace `throw` but not `assert()`. Its purpose is to allow generating a coredump on-demand to investigate an otherwise non-fatal problem, that would be near-impossible to debug just based on an exception message in the log.
