### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by goldenleaves** [scylladb/seastar#1102]
Our project depends on seastar as a submodule, however, it's been more than two years since the last stable release version 20.05，we want to rebase the lastest code of seastar, can we check a new stable version of seastar like 22.05?

**Comment by avikivity** [comment]
My recommendation is to base on master, and advance the submodule regularly (weekly or so) so that you get the benefit of new features or improvements.

I am happy to cut a release branch if you prefer.

**Comment by kun-lu20** [comment]
@avikivity It would be great if you can release a new stable version. Thanks!

**Comment by avikivity** [comment]
ok

**Comment by avikivity** [comment]
https://groups.google.com/g/seastar-dev/c/IxkC4eAYjiU/m/8eIuUB7kAAAJ
