### ISSUE TITLE
Install failed, cmake cannot find `FindUring.cmake`

### ISSUE THREAD

**Issue by yanniszark** [scylladb/seastar#1107]
Install from master fails as cmake can't find `FindUring.cmake`.
I suspect it's a typo and the intended file is `FindLiburing.cmake`.

cc @avikivity who made the relevant commit https://github.com/scylladb/seastar/commit/1247be44b01b3402e8694dd622f8ed8306053c32

**Comment by avikivity** [comment]
I have

```
-- Checking for one of the modules 'liburing'
-- Performing Test HAVE_IOURING_FEATURES
-- Performing Test HAVE_IOURING_FEATURES - Success
-- Found LibUring: /usr/lib64/liburing.so (Required is at least version "2.0") 
```

but I don't understand how.

**Comment by avikivity** [comment]
Ah, it's just the install target, which I don't normally use.
