### ISSUE TITLE
long replenishing delay generate zero extra

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1111]
The replenising code:

```c++
    void replenish(typename Clock::time_point now) noexcept {
        auto ts = _replenished.load(std::memory_order_relaxed);
        auto delta = now - ts;
        auto extra = accumulated_in(delta);
        ...
    }
    template <typename Rep, typename Per>
    T accumulated_in(const std::chrono::duration<Rep, Per> delta) const noexcept {
       auto delta_at_rate = rate_cast(delta);
       return std::round(_replenish_rate * delta_at_rate.count());
    }
```

it's assumed, that if delta is huge the accumulated_in() renders some "sane" 64-bit value, however it seems that it doesn't:

```c++
int main() {
    uint64_t x = 2562047788015215;
    double y = 60 * 60 * 4;
    fmt::print("raw {} {:x}\n", x * y, uint64_t(std::round(x * y)));
}
```
clang++-13 -> `raw 3.6893488147419095e+19 4a0000011c1`
g++-11 -> `raw 3.6893488147419095e+19 ffffffffffffffff`

**Comment by piodul** [comment]
Isn't this undefined behavior? https://en.cppreference.com/w/cpp/language/implicit_conversion#Floating.E2.80.93integral_conversions

Citing section "Floating–integral conversions":

> If the value cannot fit into the destination type, the behavior is undefined (even when the destination type is unsigned, modulo arithmetic does not apply).

**Comment by xemul** [comment]
You quoted the standard, so it most likely is
