### ISSUE TITLE
ioqueue: account for request size and type

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#114]
Right now each request has a weight of 1 when considering whether to admit it into the kernel or not.  But we know from diskplorer that large requests require a lower concurrency, and in turn have higher latency.

For example my desktop SSD requires an iodepth of 6 to reach 80% bw @ 4k, and an iodepth of 4 @ 64k.  We should assign a weight to requests so that we don't admit too many large requests.

**Comment by avikivity** [comment]
@glommer

**Comment by glommer** [comment]
That is not true
Look at queue_request, you will see:

        unsigned weight = 1 + len/(16 << 10);

That is the weight that is passed down to the fair queue.

**Comment by avikivity** [comment]
That is only used for accounting.

But if we allow N concurrent 4k reads into the kernel, we'll also allow N concurrent 128k writes, even though a lot fewer would be sufficient.  Allowing fewer 128k writes would reduce the probability of problems in xfs, and will increase the accuracy of the io scheduler on top.

**Comment by avikivity** [comment]
(for instance, a new read will have to wait less time for service, if its priority class allows it in)

**Comment by glommer** [comment]
So you would like to see a queue with capacity = n, using x > 1 for a request larger than 4k in size?

**Comment by avikivity** [comment]
If by x you mean the parameter passed to semaphore::wait(), then maybe.  But it's probably not len / 4k, the relationship is likely more complicated.  I imaging there is a minimum concurrency that is needed for even large requests.  We will need to explore more.

**Comment by avikivity** [comment]
IOW, call semaphore::wait(f(len)), where f(4k) = 1 and is monotonically decreasing.

**Comment by glommer** [comment]
@avikivity  this can be closed

**Comment by glommer** [comment]
@avikivity we support this now, please close
