### ISSUE TITLE
RPC: server::connection::negotiate is not synchronous

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1154]
The code in question looks like

```c++
    auto f = make_ready_future<>();
    for (auto&& e : requested) {
        switch (e.kind) {
        case STREAM_PARENT:
            f = handle_parent_registration();
            break;
        case ISOLATION:
            f = handle_isolation();
            break;
        }
    }
    return f;
```

if ISOLATION is processed after STREAM_PARENT then parent registration is sent to the background. The consequences are:
* server socket finishes negotiation and sends the response back to client
* client gets its stream sink await_connection() resolved and proceeds
* client may send some message containing the stream ID
* server receives stream_id and cannot find it

(seen in https://github.com/scylladb/scylla/issues/10950)

**Comment by bhalevy** [comment]
f = f.then should serialize them, right?

**Comment by xemul** [comment]
Yes. that's exactly the fix I'm going to implement

**Comment by asias** [comment]
A summary of the impact of this hack hang issue:

4.6.x, 5.0.x, 2021.1.x  (was broken in .13 and .14) 2022.1.x (was broken in .0 / .1 / .2), 2022.2.x are all safe
