### ISSUE TITLE
perftune.py - Ensure VIRTIO RX / TX IRQs are bound to the same core

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/seastar#1165]
This is an extension to https://github.com/scylladb/seastar/issues/503 . As it was seen in the field, VirtIO (KVM backed up) NICs have a separate RX and TX IRQ per HW queue, even reducing the number of HW queues to the number of IRQ vCPUs, it can happen that one core receives more RX or TX IRQs than others, which may create an imbalance such as: 

![image](https://user-images.githubusercontent.com/82817126/181415280-8bf8aa37-6971-4132-8659-48b580b0c51c.png)

In particular, in the above picture the 'yellow' CPU is over-utilized whereas the rest is underutilized. As a result, the overutilized core becomes a bottleneck.

@vladzcloudius

**Comment by vladzcloudius** [comment]
This is a VIRTIO specific issue, @fee-mendes.
Could you, please, update the description?

**Comment by fee-mendes** [comment]
Updated.
