### ISSUE TITLE
perftune.py: Error on parsing CPU mask

### ISSUE THREAD

**Issue by FlorianHockmann** [scylladb/seastar#1179]
We use `perftune.py` in our setup of Scylla and fetch it directly from the `master` branch of this repo because we run Scylla as a Docker container, but want `perftune.py` to tune the host system.

A recent change in that script has apparently introduced an error in our setup. Here are the logs from our service which wraps the `perftune.py` script:

```bash
scylla_tune.service - scylla_tune
     Loaded: loaded (/etc/systemd/system/scylla_tune.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-08-11 08:44:11 UTC; 40s ago
    Process: 4256 ExecStart=/opt/scylla_scripts/perftune.py --cpu-mask all --nic bond0 --mode sq_split --tune net (code=exited, status=1/FAILURE)
   Main PID: 4256 (code=exited, status=1/FAILURE)

Aug 11 08:44:10 [host - redacted] perftune.py[4258]: Restricting the topology: Invalid argument
Aug 11 08:44:11 [host - redacted] perftune.py[4256]: File /etc/default/irqbalance.scylla.orig already exists - not overwriting.
Aug 11 08:44:11 [host - redacted] perftune.py[4256]: Restarting irqbalance: going to ban the following IRQ numbers: 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 3>
Aug 11 08:44:11 [host - redacted] perftune.py[4256]: Restarting irqbalance via systemctl...
Aug 11 08:44:11 [host - redacted] perftune.py[4256]: Setting bond0 bonding interface...
Aug 11 08:44:11 [host - redacted] perftune.py[4256]: Setting up enp68s0f1...
Aug 11 08:44:11 [host - redacted] perftune.py[4256]: ERROR: invalid literal for int() with base 16: '0x00000001,0x00000001'. Your system can't be tuned until the issue is fixed.
Aug 11 08:44:11 [host - redacted] systemd[1]: scylla_tune.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 08:44:11 [host - redacted] systemd[1]: scylla_tune.service: Failed with result 'exit-code'.
Aug 11 08:44:11 [host - redacted] systemd[1]: Failed to start scylla_tune.
```

`Restricting the topology: Invalid argument` was already logged before, so I guess it's not related to this problem. The relevant error should be:
```
ERROR: invalid literal for int() with base 16: '0x00000001,0x00000001'. Your system can't be tuned until the issue is fixed.
```

We currently have a version of this script in production from [this commit](https://github.com/scylladb/seastar/commit/730fa800ede8d67247135dd59e0954493b81a479), so June 7, with the same arguments.

I think [this commit from 9 days ago](https://github.com/scylladb/seastar/commit/db1c8ae1ab61fc990126c9bdae08a7a3ef00411d#diff-3308b1dbea6a75007234eacc16bcf645c9245ab6e28b1c216dd77771838d30b5R919) is the problematic one for us and especially line 919:

```python
num_irq_cpus = bin(int(self.irqs_cpu_mask, 16)).count('1')
```

If I'm not mistaken, then this expects the CPU mask to represent a single CPU, but this fails in our case as we have 2 CPUs which should lead to this CPU mask here: `0x00000001,0x00000001`. That can't be parsed as an integer. I guess first splitting the CPU mask on `,` should solve this. I could prepare a PR for this simple change if you want and agree with my analysis.

**Comment by vladzcloudius** [comment]
Thanks for reporting, @FlorianHockmann.
This is a regression introduced by d3dbf7dbaa24131dc960a0f4019d96c0db211700.

The offending line is 923 (based on the HEAD dd9577d7e03e33da6337542b2493445ce774df1f).

I'm going send a fix ASAP.

**Comment by vladzcloudius** [comment]
A quick workaround is to use `--num-rx-queues 2`

**Comment by vladzcloudius** [comment]
> I could prepare a PR for this simple change if you want and agree with my analysis.

I do agree with your analysis but I stumbled on this bug myself in the context of another series I'm working on.

I already have a patch ready, so, probably don't bother.
I'm going to post this big PR today and it's going to include a patch that fixes this issue too.
