### ISSUE TITLE
wrong path used in tutorial.md example

### ISSUE THREAD

**Issue by UrbanskiDawid** [scylladb/seastar#1203]
example included in [tutorial.md](https://github.com/scylladb/seastar/blob/master/doc/tutorial.md)

```
docker run -it --rm -v $(pwd):/seastar seastar-dev /seastar/build/dev/demos/hello-world -c1
```

results in 

> runc create failed: unable to start container process: exec: "/seastar/build/dev/demos/hello-world": stat /seastar/build/dev/demos/hello-world: no such file or directory: unknown.

after a quick check it seems that the file name is different:
```
$ root@9c99b84ea7a1:/# ls -1  seastar/build/dev/demos/
(...)
hello-world_demo
(...)
```

fix recommendation:
```
$ docker run -it --rm -v $(pwd):/seastar seastar-dev /seastar/build/dev/demos/hello-world_demo -c1
```

**Comment by UrbanskiDawid** [comment]
[https://github.com/scylladb/seastar/pull/1204](fix)

**Comment by xemul** [comment]
52434eec5ee17f3886ea50ef41bc35b39f3b4b61
