### ISSUE TITLE
Add hold() method for futures

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#123]
This suggestion is due to Gleb, raised in this thread: https://groups.google.com/d/msg/seastar-dev/7fjd7kJiIOQ/cV3tTGGpIwAJ

We commonly use finally() in the following idiom:

``` c++
   fut.finally([obj = std::move(obj)] {});
```

to hold an object alive until a future is concluded.
This idiom is common enough that we started to worry that finally is inefficient in this case (see issue #92).

There are times when we need the full finally(), of course, but Gleb's idea was that for this specific use case, it would be better to have its own method, hold(T&&):

``` c++
    fut.hold(std::move(obj));
```

In a mail in the above thread, I tried to enumerate the benefits of this hold() over the existing finally()-based idiom, and another proposal of a "with_shared()" function:

The hold() syntax,

``` c++
    auto fut = async_call(obj);
    fut.hold(std::move(obj));
```

is cleaner and more natural than the baroque syntax we currently recommend:

``` c++
    auto fut = async_call(obj);
    fut.finally([obj = std::move(obj)] { });
```

Avi's alternative suggestion of "with_shared" is even simpler in this example:

``` c++
    with_shared(obj, async_call);
```

However, the with_shared syntax become much uglier if obj is not the only parameter you need to pass to async_call - e.g., consider:

``` c++
     async_call(i, j, k, obj).hold(std::move(obj));
```

while with with_shared, you find yourself having to write this:

``` c++
     with_shared(ptr, [i, j, k] (auto& obj ) { return async_call(i, j, k, obj); });
```

It should be carefully documented that "hold" has a limitation on what kind of objects it can hold: For example, imagine you try to do:

``` c++
    future<> async_call(T&);
    T obj;
    return async_call(obj).hold(std::move(obj));
```

Is this safe? It is _NOT_ safe if obj and async_call are such that moving the object after calling async_call(obj) can cause async_call to later (as part of some later async processing) access obj again, after it was moved. It _is_ safe for all T which are "smart pointers and similar" because with smart pointers, async_call remembers the pointed-to object object, and never tries to look at the content of the pointer object itself after the function returns.
I don't know how we can formalize this requirement from T.
In particular, consider this question can T be "class file"? Can someone do:

``` c++
    file f;
    return f.close().hold(std::move(f));
```

I believe the answer is true in the "class file" case - all "class file" methods retrieve the "_file_impl" member when called, so f can be safely moved after they return. (incidentally, in our class file case, which resembles a shared pointer, one can also do f.close().hold(f) which is only a tiny bit less efficient because the reference count needs to be modified once more).

The hold() proposal has another interesting advantage over the current finally()-based idioms when it comes to unique_ptr, and similar objects which can't be captured by copy:

If you try to do this seemingly-innocent code:

``` c++
    unique_ptr<T> p = ...;
    return async_call(*p).finally([p = std::move(p)] {});
```

It can fail, because C++ does not (as far as we know) make any guarantee whether std::move(p) or the *p actually happens first... This is a trap for every new Seastar user, and I believe each of us fell into it or some variant of it at least once in the past. The way around this trap is the following idiom, which we used many times (including in do_with's implementation):

``` c++
   unique_ptr<T> p = ...;
   auto fut = async_call(*p);
   return fut.finally([p = std::move(p)] {});
```

It's hard to under-state how ugly, unnatural and unreadable this looks to anybody but the most seasoned Seastar programmers. With hold(), one would be able to do this instead:

``` c++
   unique_ptr<T> p = ...;
   return async_call(*p).hold(std::move(p));
```

And this (unless I'm missing something!?) would be correct, because C++ guarantees that that async_call(*p) is called first, and only when it returns, hold() will be called which will cause the unique_ptr to actually be moved (the std::move(p) itself did nothing, it is just a type cast).

**Comment by duarten** [comment]
So it's not forgotten, I published a patch for this, but seems to be lacking consensus on whether we should go with hold() or with_shared(): https://groups.google.com/forum/#!topic/seastar-dev/HpBExIIMyWM

**Comment by raphaelsc** [comment]
@nyh after do_with() and coroutines, I think we can close this. this is an issue that we'll probably never close.

**Comment by nyh** [comment]
> @nyh after do_with() and coroutines, I think we can close this. this is an issue that we'll probably never close.

I agree that after coroutines became the new fashion, there is zero motivation to ever do this if we haven't done it for 6 years. So I'll close the issue.
