### ISSUE TITLE
Shared library question

### ISSUE THREAD

**Issue by volodyaleo** [scylladb/seastar#1238]
Our application need to use seastar as shared library.

What was the reason for removing support of shared libraries?

If I prepare patch/pr with optional shared library build, will it be approved for merge?

**Comment by avikivity** [comment]
It's a performance issue. Seastar uses thread_local extensively, and shared_local is very slow when built as a shared library.

See https://www.uclibc.org/docs/tls.pdf for the gory details.

I don't mind a shared library option (I may use it for debug builds).

**Comment by dotnwat** [comment]
I've been using a shared library build with Meson for a while and it works for development. We have a lot of tests binaries, so it saves space and linking time.

**Comment by brain5lug** [comment]
@avikivity
How big i performance slowdown of using dymanic seastar in real-world apps? Is it a percents or tens of percents?
Have you made any performance benchmarks for scylladb?
I'm just trying to figure out what shall I expect from dynamic linkage.

**Comment by tchaikov** [comment]
closing. as we now expose `BUILD_SHARED_LIBS` and it is supported. there are still some glitches when building with sanitizers but they are known and root-caused, and we use `Seastar_TEST_ENVIRONMENT` to workaround them.
