### ISSUE TITLE
flush hangs if called many times in parallel

### ISSUE THREAD

**Issue by glommer** [scylladb/seastar#124]
I have recently ran into an Issue in ScyllaDB, where triggering many SSTable writes in parallel would hang the system.

I have managed to come up with a reproducer that does not use any ScyllaDB infrastructure at all, meaning the bug is either in Seastar, or the Kernel

I have put the reproducer in [my seastar tree](https://github.com/glommer/seastar/tree/issue-flushes), branch issue-flushes, 6c30c64355e5e

After more than 5 minutes of waiting, this test does not complete. I monitor its activities with iostat during the whole duration of the test, and at some point, all disk activity just ceases.

Replacing the `parallel_for_each` call with `do_for_each`, the test finishes in slightly over a minute - with mild disk activity always present.

That indicates that the kernel is probably not the culprit, since from the kernel PoV, both cases are the almost the same (since the thread pool will serialize the flushes). Also, I have ran this test both in XFS and ext4, with similar results. On top of that, @penberg ran it with BTRFS, and also see similar hangs.

However, for completeness of information, here is what I am running:

```
$ uname -a
Linux trueserverstrongandfree 4.4.5-300.vanilla.knurd.1.fc23.x86_64 #1 SMP Thu Mar 10 06:32:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
Reducing the number of iterations, from 10000 to something lower makes it work. But if aside from the flush, I also write something to the file, then I can reproduce this with as little as 500 iterations. The code for that is in the branch issue-flushes-writes, c8eec3dcd71d34f7d of [my seastar tree](https://github.com/glommer/seastar/tree/issue-flushes)

I have suspected that the syscall mechanism by itself may be at fault. To test that hypothesis, I have implemented a version of sleep that calls into posix_sleep, and issued as many as 10000 calls that would sleep for 10ms each. I did not manage to trigger the issue by doing that. 

Other things that I have already ruled out:

- seastar sleep mode: running with `--poll-mode`, I can still reproduce the issue
- I/O scheduler: running with `--max-io-requests 100000` I can still reproduce the issue. Also, the fact that I have seen this without any writes, just flushes, pretty much bypass much of the I/O queue, if not all.

**Comment by glommer** [comment]
I have run strace -C, and after some minutes, killed the process. I have this output:

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.312445          31      9980           fdatasync
------ ----------- ----------- --------- --------- ----------------
100.00    0.312445                  9980           total
```

**Comment by glommer** [comment]
Forgot to add, I have also changed our fdatasync code to fsync. Still the same.

**Comment by glommer** [comment]
Ok, the problem really seem to be related to the thread queue processing.

With the following patch, my test program succeeds, even though of course I am not advocating for the patch itself
```
diff --git a/core/reactor.hh b/core/reactor.hh
index a97bbba..60ddcd5 100644
--- a/core/reactor.hh
+++ b/core/reactor.hh
@@ -267,7 +267,7 @@ class syscall_work_queue {
     lf_queue _pending;
     lf_queue _completed;
     writeable_eventfd _start_eventfd;
-    semaphore _queue_has_room = { queue_length };
+    semaphore _queue_has_room = { 1 };
     struct work_item {
         virtual ~work_item() {}
         virtual void process() = 0;
```

**Comment by glommer** [comment]
I have applied the following patch instead of the previous one:

```
diff --git a/core/reactor.cc b/core/reactor.cc
index 8a419cc..280a931 100644
--- a/core/reactor.cc
+++ b/core/reactor.cc
@@ -1959,7 +1968,9 @@ void syscall_work_queue::complete() {
         wi->complete();
         delete wi;
     });
+    printf("pre-signal: current %ld, waiters %ld, completed: %ld\n", _queue_has_room.current(), _queue_has_room.waiters(), nr);
     _queue_has_room.signal(nr);
+    printf("post-signal: current %ld, waiters %ld\n", _queue_has_room.current(), _queue_has_room.waiters());
 }

 smp_message_queue::smp_message_queue(reactor* from, reactor* to)
@@ -2139,10 +2150,11 @@ void thread_pool::work() {
         if (_stopped.load(std::memory_order_relaxed)) {
             break;
         }
-        inter_thread_wq._pending.consume_all([this] (syscall_work_queue::work_item* wi) {
+        auto nr = inter_thread_wq._pending.consume_all([this] (syscall_work_queue::work_item* wi) {
             wi->process();
             inter_thread_wq._completed.push(wi);
         });
+        printf("thread pool consumed %ld\n", nr);
         pthread_kill(_notify, SIGUSR1);
     }
 }
```

The first lines printed are:
```
Running 1 test case...
Starting test
thread pool consumed 2
thread pool consumed 7
thread pool consumed 23
pre-signal: current 0, waiters 9872, completed: 44
post-signal: current 0, waiters 9828
```

Because there are no messages before that, we can be sure this is from the start of the system execution. So we can see here that the thread pool consumed 2 + 7 + 23 = 32, but the first execution took 44 elements out of the queue.

Those of course come from different threads, so it is hard to guarantee the ordering of those messages. So I am not saying this is definitely wrong, but doesn't it look suspicious? Could it be that boost have a bug in this implementation? That would certainly explain this behavior. If we overwrite the memory pointed by elements in the queue, some of the futures would never be set to ready.

**Comment by glommer** [comment]
I have just posted a patch to the seastar mailing list. It is also available in [my tree](https://github.com/glommer/seastar/tree/issue-124/assert) , commit 4f22ddfc47f3.

The patch adds asserts to the push operations. The assertions do trigger in this test case of mine.
Because the boost documentation says about the return of push:

> true, if the pop operation is successful, false if ringbuffer was empty.

I am assuming we are trying to push into a full queue. Now, I have no idea why does that happen, since our semaphore is supposed to protect against that.

**Comment by glommer** [comment]
@avikivity  I've been looking at this problem for way too long, and I am totally clueless (and wasted). Help is appreciated.

**Comment by avikivity** [comment]
Did any exception happen?  For example due to `ENFILE`?

**Comment by glommer** [comment]
I've ran it on gdb with catch throw and saw no exceptions.

**Comment by avikivity** [comment]
Changing then() to then_wrapped() (handling the return value from parallel_for_each()) makes it work for me (my machine has a limit of 1024 open files).

**Comment by glommer** [comment]
I have a bit more.

```
$ ulimit -n
1000000
```

**Comment by avikivity** [comment]
And with the limit raised, the reproducer passes for me.

**Comment by glommer** [comment]
Did you try both reproducers? I have found that the one with just the flush is a lot more fragile.
(But I wanted of course to have it because it do less operations).

I find if very unlikely that this is a nofile issue, since as I've shown you, I have 1000000 for that value, and we're not opening nowhere near as many files as that.

Also, I've saw no exceptions (assuming gdb catch throw would show them)

Lastly, the assert that I've added do trigger, meaning that if we do have an exception going on here (maybe, who knows?) then seastar is not handling it correctly.

**Comment by glommer** [comment]
@penberg, for one, reported that merely by putting the test in strace, it started working for him. Thankfully it keeps breaking for me (so I could use strace to debug it).

So it does look like timing-sensitive.

**Comment by glommer** [comment]
Ok. It works for me (both reproducers) if I replace the `consume_all` call with a loop that does `consume_one()` for all elements. At this point, I would place my bets in a buggy implementation of consume_all

**Comment by glommer** [comment]
@avikivity which version of boost do you use ?

**Comment by avikivity** [comment]
boost-1.58.0-11.fc23.x86_64

**Comment by avikivity** [comment]
If the bug is in consume_all(), then it should be easy to find.  Maybe start by looking at commit logs.

**Comment by glommer** [comment]
Already did. That file does not get updates for more than one year. So it is either a commit in another file that affects consume_all - in which case I'm looking for a needle in a haystack, or people don't use consume_all all that often.

It could also be that we are doing something wrong in its usage. But I can't really find out what.

**Comment by avikivity** [comment]
What about https://svn.boost.org/trac/boost/ticket/10953?

**Comment by glommer** [comment]
About one year old, fixed in 1.57. Moreover, in my debug prints I printed the output of consume_all - exactly because of that ticket, and it was sane.

I suspect something messes up with the read_index inside the queue.

**Comment by avikivity** [comment]
Maybe it's an overflow.  Try increasing `syscall_work_queue::queue_length`.

**Comment by glommer** [comment]
overflow of what? It doesn't make a lot of sense. If the queue has a capacity of X, the semaphore should guarantee that only those X will get in, no?

On a side note: I've just ran my initial, more complex, memtable test with consume_all -> consume_one. It passes now.

**Comment by avikivity** [comment]
Maybe `consume_all()` has a bug when the queue is filled to capacity.

**Comment by glommer** [comment]
I'll try reading their code a bit more tomorrow. And also coming up with a test case if I find them to be really at fault.

**Comment by avikivity** [comment]
Changing `syscall_work_queue` to have:

    using lf_queue = boost::lockfree::spsc_queue<work_item*,
                            boost::lockfree::capacity<queue_length*2>>;

fixes the problem for me.

**Comment by glommer** [comment]
Yes, for me as well. Changing the semaphore to queue_length / 2 does the same thing for me (I've tried that a while ago)

But that's cheating: it is saying that we have a queue of size n, but we're only allowing n / 2 requests on it.

**Comment by avikivity** [comment]
It's working around an iverflow in boost lockfree, I don't see why you
think it's cheating.

**Comment by glommer** [comment]
First of all you are not sure this is an overflow.
And worse yet, if you are wrong, and it can be triggered by some other scenario with a bigger queue, some futures will disappear and the system will misbehave in a mysterious way. And we'll take days to figure out what's wrong because it will happen silently.

So we'd better be sure this is the problem.

Also, doing that will allocate twice as much memory for the queue (it's not GBs, but even...), even though it is almost certain that the bug has nothing to do with memory access, but with indexes management. If we're going to merge something like that, I would feel safer to merge consume_all -> consume_one instead

**Comment by avikivity** [comment]
I agree we need to find the root cause.  But as long as we don't, there's no reason to assume consume_one() is any safer than increasing the queue size.

Regarding the memory load, it's one kilobyte per thread.

**Comment by glommer** [comment]
I will start looking at it again right now. So I don't want to start a discussion about which quick fix would be better - because we need to understand it. But from what I saw when investigating this, different values of queue size will make this problem disappear, even if they are the same size as the semaphore.

Sometimes it goes away if I increase the queue size, sometimes it goes away if we decrease it.

I am not affirming this is the cause, but it really seems to me that boost is mishandling the writer and reader index. It's from this impression that I believe that consume_one is safer. But again, that is only true insofar as I am right.

Let me go back to it and I'll report back.

**Comment by avikivity** [comment]
Patch posted.

**Comment by avikivity** [comment]
(boost was innocent)

**Comment by glommer** [comment]
That's actually great news. It could have been a deployment hell otherwise
