### ISSUE TITLE
CMake, FreeBSD support & build server scripts

### ISSUE THREAD

**Issue by fuzz** [scylladb/seastar#1254]
I am working on getting Seastar running with FreeBSD’s Linux ABI compatibility (see https://github.com/redpanda-data/redpanda/issues/3729) and also getting it compiled natively on FreeBSD.

My first step is to get `cmake-cooking` and the rest of the build/tests working on a Linux cloud instance I can start/destroy at will because I am impatient, cheap and don’t typically develop on Linux. I don’t want to rely on system packages as eventually I want `cmake-cooking` to also work on FreeBSD. My copy of **Modern CMake for C++** just arrived today.

To this end I have put together some simple scripts to spin up a Digital Ocean droplet, install the prerequisite packages needed for cooking, clone seastar + dpdk and start the cooking process in a tmux session on the droplet, teed to a log for grepping pleasure.

https://github.com/fuzz/galley

I have not made it beyond cooking yet as I’m running into

“FAILED: _cooking/ingredient/yaml-cpp/stamp/ingredient_yaml-cpp-build                                        [1553/1923]
cd /build/seastar/build/_cooking/ingredient/yaml-cpp/build && /usr/bin/cmake --build /build/seastar/build/_cooking/ingr
edient/yaml-cpp/build && /usr/bin/cmake -E touch /build/seastar/build/_cooking/ingredient/yaml-cpp/stamp/ingredient_yam
l-cpp-build                                                                                                            
Scanning dependencies of target yaml-cpp                                                                               
[  1%] Building CXX object CMakeFiles/yaml-cpp.dir/src/binary.cpp.o                                                    
[  3%] Building CXX object CMakeFiles/yaml-cpp.dir/src/convert.cpp.o                                                   
In file included from /build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/iterator.h:13,       
                 from /build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/impl.h:11,           
                 from /build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/convert.h:17,        
                 from /build/seastar/build/_cooking/ingredient/yaml-cpp/src/src/convert.cpp:3:                         
/build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/detail/iterator.h: In member function ‘void
 YAML::detail::iterator_base<V>::increment()’:
/build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/detail/iterator.h:48:54: error: ‘next’ is n
ot a member of ‘boost’
   48 |   void increment() { this->base_reference() = boost::next(this->base()); }
      |                                                      ^~~~
/build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/detail/iterator.h:48:54: note: suggested al
ternatives:
In file included from /usr/include/c++/9/bits/stl_algobase.h:66,
                 from /usr/include/c++/9/algorithm:61,
                 from /build/seastar/build/_cooking/ingredient/yaml-cpp/src/src/convert.cpp:1:
/usr/include/c++/9/bits/stl_iterator_base_funcs.h:213:5: note:   ‘std::next’
  213 |     next(_InputIterator __x, typename
      |     ^~~~
In file included from /build/seastar/build/_cooking/installed/include/boost/mpl/next.hpp:17,
                 from /build/seastar/build/_cooking/installed/include/boost/mpl/bind.hpp:25,”

I’m going to dig into that over the weekend—boost/yaml-cpp version compatibility?— but if anyone just happens to know the fix that would be swell :)

Note there’s currently a stale URL in `cooking_recipe.cmake` — I have a fix for that but I’m waiting to get the whole build going before I submit a PR—it’s in `https://github.com/fuzz/seastar` branch: `seamake`. My current fix just updates the URL, but as zlib-1.2.12 has been moved to “fossils” I’ll look at updating the version once the build is working.

Also, building on a fresh Ubuntu server install requires installing the packages `autogen cmake g++ guile-2.2 libidn11-dev libnuma-dev libtool libunbound-dev m4 ninja-build pkg-config stow trousers xutils-dev`—some of these should probably be folded into `cmake-cooking` so I’ll look into that as well.

**Comment by tchaikov** [comment]
> In file included from /build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/iterator.h:13,
> from /build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/impl.h:11,
> from /build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/convert.h:17,
> from /build/seastar/build/_cooking/ingredient/yaml-cpp/src/src/convert.cpp:3:
> /build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/detail/iterator.h: In member function ‘void
> YAML::detail::iterator_base::increment()’:
> /build/seastar/build/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/detail/iterator.h:48:54: error: ‘next’ is n
> ot a member of ‘boost’
> 48 | void increment() { this->base_reference() = boost::next(this->base()); }
> | ^~~~

@fuzz hi Jason, which boost version are you using? i see your branch does not change it (https://github.com/fuzz/seastar/blob/seamake/cooking_recipe.cmake#L136). i am asking because, apparently, you ran into a known issue that yaml-cpp does not compile with older boost. you might want to use the cooked one instead of the one from ports (https://www.freshports.org/devel/boost-all).

also, my bigger concern is that you are using an older version of clang, but to compile redpanda you need at least clang-14 instead of clang-9 (https://www.freshports.org/devel/llvm).

**Comment by fuzz** [comment]
@tchaikov I’m using Boost 1.77 as specified in `cooking_recipe.cmake`. Thanks! This error is from Ubuntu—I haven’t made it to FreeBSD yet. I did find the known yaml-cpp/boost issue, but as I hadn’t touched the versions in `cooking_recipe.cmake` it didn’t give me much to go on as I assume people have used `cooking.sh` successfully in the past and the hashes for the boost and yaml-cpp source are correct :)

Looking at the history there was a boost update from 1.64 to 1.77

https://github.com/scylladb/seastar/commit/bbb290ef1b75e14484af8735aa64a11be0435764

Perhaps the bug was introduced there and hasn’t been triggered because no one has tried to run `cooking.sh` in a clean environment since?

**Comment by tchaikov** [comment]
@fuzz my guess is that you installed an older version of packaged boost in your system, and yaml-cpp picked it up when being cooked.

```mermaid
graph TD;
    ubuntu --> older_boost
    subgraph cooking
      recipe --> boost_1.77;
      recipe --> yaml-cpp
      older_boost-->yaml-cpp;
    end
    boost_1.77-->Seastar;
    yaml-cpp-->Seastar;
```

**Comment by fuzz** [comment]
Boost 1.77 is reported as the boost version in the `cooking.sh` error I reported.

**Comment by tchaikov** [comment]
@fuzz i think you missed the point that the boost used by yaml-cpp is the one you installed in the system. please take a look at https://github.com/scylladb/seastar/issues/1254#issuecomment-1287965520 .

**Comment by fuzz** [comment]
Closing this as I've given up on FreeBSD for data work.
