### ISSUE TITLE
Disk stall detector

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1311]
Similarly to cpu stall detector that prints warnings and calltraces when reactor doesn't tick when it needs, it would be nice to have IO stall detector that warns us about disk being slow.

`scylla_io_queue_total_exec_sec` metrics exists, but short spikes still can come under the radar

**Comment by bhalevy** [comment]
@xemul what else needs to be done here other than #1492?

**Comment by xemul** [comment]
I've the branch already :) Need to polish it and push

**Comment by mykaul** [comment]
With the issues we've seen with some customer setup, I wonder if this could be helpful? If so, @xemul - please try to push this (so it'll get into 5.3).

**Comment by xemul** [comment]
> With the issues we've seen with some customer setup, I wonder if this could be helpful?

This was implemented this way _exactly_ after looking at the issue with "some customer"'s cluster
