### ISSUE TITLE
TCP Stack does not close connection imediately when receving RST,ACK in SYN_SENT state

### ISSUE THREAD

**Issue by thanhcongbui97** [scylladb/seastar#1334]
Hi, i'm working with seastar framework for it's native TCP network stack.
Currently, i'm having trouble with connect() function of tcp, when trying to connect with another server address that does not listen on that port. Normaly, a client when trying to connect to a adress that does not servered by a server may be imediately rejected with a message "Connection refused". According to [RFC 9293](https://datatracker.ietf.org/doc/html/rfc9293):

> The receiver of a RST first validates it, then changes state. If the receiver was in the LISTEN state, it ignores it. If the receiver was in SYN-RECEIVED state and had previously been in the LISTEN state, then the receiver returns to the LISTEN state; otherwise, the receiver aborts the connection and goes to the CLOSED state. If the receiver was in any other state, it aborts the connection and advises the user and goes to the CLOSED state.

But with seastar, the connect() function just hanging and only drop whentimeout expired.
In tcp.hh, i found that in SYN_SENT state, if we receive an RST flag in a segment, seastar only call do_reset() in tcp but the `connection` won't be close in do_reset().

```
void tcp<InetTraits>::tcb::input_handle_syn_sent_state(tcp_hdr* th, packet p) {
...
// 3.2 second check the RST bit
    if (th->f_rst) {
        // If the ACK was acceptable then signal the user "error: connection
        // reset", drop the segment, enter CLOSED state, delete TCB, and
        // return.  Otherwise (no ACK) drop the segment and return.
        if (acceptable) {
            return do_reset();
        } else {
            return;
        }
    }
...
}
```

To fix this, i think better do shutdown_connect() in do_reset() function. Can you review this issue and my solution.
Best Regards!

**Comment by avikivity** [comment]
Looks reasonable, please open a pull request (easier to review against the existing code).

**Comment by thanhcongbui97** [comment]
Thanks, please review my solution here 
https://github.com/scylladb/seastar/pull/1339
