### ISSUE TITLE
Timer signal may render std::cout bad preventing further output on console

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#134]
strace:
```
7726  write(1, "Something", 44) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
7726  --- SIGRT_3 {si_signo=SIGRT_3, si_code=SI_TIMER, si_timerid=0x1, si_overrun=0, si_value={int=28500144, ptr=0x1b2e0b0}} ---
7726  rt_sigreturn({mask=~[HUP INT QUIT ILL ABRT FPE KILL USR1 SEGV ALRM TERM CONT STOP TSTP TTIN TTOU RTMIN RT_1 RT_2 RT_3]}) = -1 EINTR (Interrupted system call)
```

When this happens the stream becomes "bad" and output no longer appears on the console.

**Comment by nyh** [comment]
In `reactor::run()` we have:
```c++
    struct sigaction sa_task_quota = {};
    sa_task_quota.sa_handler = &reactor::clear_task_quota;
    r = sigaction(task_quota_signal(), &sa_task_quota, nullptr);
```

This is missing a
```c++
    sa.sa_flags = SA_SIGINFO | SA_RESTART;
```

As we do for example in the signal_handler() function in the same file.

Not setting the SA_RESTART causes the possibility that system calls return with EINTR, and apparently as you noticed stdio can't handle this case (although I wonder why).

**Comment by avikivity** [comment]
Don't we want EINTR for epoll?

**Comment by tgrabiec** [comment]
FWIW adding `SA_RESTART` to the site mentioned by @nyh fixes my case.

**Comment by nyh** [comment]
@avikivity as far as I know, epoll_wait() isn't restarted even with SA_RESTART. In general, not all system calls are restarted, but write() is.

**Comment by nyh** [comment]
https://groups.google.com/forum/#!topic/linux.kernel/qqK0HKBCw98 mentions that "By analogy with poll syscall family, epoll_wait should be interrupted by signals regardless of SA_RESTART, thus ERESTARTNOHAND is used, not ERESTARTSYS."
