### ISSUE TITLE
Build testing library when embed seastar with `add_subdirectory`?

### ISSUE THREAD

**Issue by lightmelodies** [scylladb/seastar#1380]
The CMakeLists.txt explicitly disables `seastar::testing` library when `CMAKE_CURRENT_SOURCE_DIR` differs from `CMAKE_SOURCE_DIR`, which makes writing tests using `seastar::testing` with embed seastar impossible. Is there any reason for this decision, as the testing library itself (without seastar's test cases) take only a little space?

https://github.com/scylladb/seastar/blob/28f8042abbbbb4c70c9750eecf94360987c6018f/CMakeLists.txt#L349

https://github.com/scylladb/seastar/blob/28f8042abbbbb4c70c9750eecf94360987c6018f/CMakeLists.txt#L1049

**Comment by tchaikov** [comment]
in general, `seastar::testing` is just used for testing Seastar. but if you can always enable `Seastar_TESTING` like
```cmake
set(Seastar_TESTING ON CACHE BOOL "" FORCE)
```

in the parent project.

**Comment by lightmelodies** [comment]
Well, it's convenience to use `seastar::testing` as boilerplate code for a async test context.

> in general, `seastar::testing` is just used for testing Seastar. but if you can always enable `Seastar_TESTING` like
> 
> ```cmake
> set(Seastar_TESTING ON CACHE BOOL "" FORCE)
> ```
> 
> in the parent project.

I have tried this approach. However It seems that this line always overwrite `Seastar_TESTING` to `OFF`.
https://github.com/scylladb/seastar/blob/28f8042abbbbb4c70c9750eecf94360987c6018f/CMakeLists.txt#L355

A minimal `CMakeLists.txt`: 
```cmake
cmake_minimum_required(VERSION 3.20.0)
project(sample VERSION 0.1.0)

set(Seastar_TESTING ON CACHE BOOL "" FORCE)
add_subdirectory(seastar)

add_executable(sample main.cc)

target_link_libraries(sample PRIVATE seastar seastar_testing)
```
