### ISSUE TITLE
Semaphore uses a contiguous array

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#140]
Our semaphore implementation currently uses circular_buffer<entry> to hold the list of waiters.
circular_buffer<>, unlike std::deque<>,  uses a **contiguous** array to hold the list. This is a problem when for some reason we have a lot (e.g., 100,000) waiters on a semaphore and this requires a very large contiguous allocation which can fail because of memory fragmentation.

Can we develop a data structure which uses a linked list of buffers (like std::deque), but have performance closer to circular_buffer and not to std::deque? Some of the guarantees which std::deque makes, like random access, we don't need, for example.
By the way, If we just used the existing std::deque without inventing any new data structure, how much performance does semaphore actually lose? (and note that when the semaphore units are available, no performance loss can happen in any case).

**Comment by pdziepak** [comment]
Basically, what we need is a singly linked list of fixed-capacity ring buffers. Pushes go to the last one, pops are done from the first one and there is always at least one buffer in the list.
It will be more expensive in the fast path that current circular_buffer implementation, but not much – pointer dereference to get appropriate buffer from the list + additional check whether to current buffer is empty in pop().

**Comment by nyh** [comment]
I didn't understand the extra "pointer dereference" worry: circular_buffer also has a pointer pointing to the buffer (T* storage), so couldn't the chunked version use the same pointer (actually two of these pointers for head and for tail) - without yet another layer of indirection?
It just that in the relatively-rare case where we find the buffer is full (on push) or empty (on pop) we need to do some extra work to take the next buffer on the linked list.

**Comment by avikivity** [comment]
The standard implementation will have a list node pointing to an array, but we can also have it inline with the array.

**Comment by nyh** [comment]
Yes - each "chunk" could have a fixed number N objects plus links to next and/or previous chunks. You can think of this as an "intrusive list" but really, it's the classic computer-science linked list, no reason to use any Boost here ;-)

**Comment by pdziepak** [comment]
...and each chunk will also need its `begin` and `end` pointers, so that we don't introduce another layer of indirection.
It still may cause more cache misses than the current circular_buffer if there is more than one buffer in the list and each push and pop access different (begin, end) pair.

**Comment by nyh** [comment]
@pdziepak we should just implement this instead of talking ;-) I'll try to find time today it later today.

But I am not sure why we need each chunk to have begin and end - I think we just need them for the first and last chunk (the middle chunks are all full, and just need a "begin") so perhaps can hold them in the top level object, and maybe even fit them in the same cache line. I didn't give this issue too much thought.

Anyway, as I noted in my original comment, I think all these details are extremely interesting, but inconsequential for actual performance, which will only use this queue once we need to defer a task because of a semaphore, and this deferring code has, I believe, much more overhead than the kind of overheads we're discussing here.

**Comment by nyh** [comment]
I wrote a chunked fifo queue implementation as I suggested above (it was a bit harder than I thought), and measured its performance with the following silly test of random pushes and pops while the queue becomes smaller and larger:

``` c++
    unsigned int seed = 0;
    constexpr int N = 1'000'000'000;
    chunked_fifo<int> fifo;  // try also std::deque<int> and circular_buffer<int>
    int entropy = 0;
    for (int i = 0; i < N; i++) {
        if (!entropy) entropy = rand_r(&seed);
        if (entropy & 1) {
            fifo.push_back(i);
        } else {
            if (!fifo.empty()) {
                fifo.pop_front();
            }
        }
        entropy >>= 1;
    }
```

In this benchmark, circular_buffer is merely 10% faster than std::deque - and unfortunately my new chunked_fifo gets almost exactly the same performance as std::deque.

I can continue to optimize by chunked_fifo, but this measurement makes me wonder: On what did we base our belief that circular_buffer is signficantly faster than std::deque? If std::deque is only 10% slower than circular_buffer, why should we not use std::deque everywhere?

**Comment by pdziepak** [comment]
Correct me if I'm wrong but the way std::deque is implemented adds one more layer of indirection than circular_buffer has (it is basically a circular_buffer of fixed size chunks) in order to guarantee O(1) random access.
That additional indirection may increase the gap between std::deque and circular_buffer when cache misses start to happen.

**Comment by nyh** [comment]
Yes, I think std::deque indeed adds one more layer of indirection, but I don't know how to find a benchmark where this actually matters. In particular, if cache misses happen because of other computation which is going on, then the circular_buffer/deque code would probably not be a big percentage of the runtime anyway.

**Comment by nyh** [comment]
Commit d4d9e1617c6b7905e7e8499267684c05fa4bd092 already switched sempahore to using chunked_fifo.
