### ISSUE TITLE
error: ‘GNUTLS_SEC_PARAM_MEDIUM’ was not declared in this scope

### ISSUE THREAD

**Issue by jamperry** [scylladb/seastar#142]
I was curious to give seastar a spin but I cannot build it for Ubuntu 14.04.

There's no installation instruction for recommended `gnutl`s so I installed `libgnutls28-dev` and I get the following build issue:

```
net/tls.cc:119:40: error: ‘GNUTLS_SEC_PARAM_MEDIUM’ was not declared in this scope
```

**Comment by nyh** [comment]
This is an antique build problem. Seastar's code, build system and Ubuntu have all changed considerably since, so it is unlikely to still be relevant. Please reopen or create a new issue if this is still relevant.
