### ISSUE TITLE
E: Unable to locate package liburing-dev

### ISSUE THREAD

**Issue by yigalirani** [scylladb/seastar#1448]
hi, I am trying to follow the installation instructions on https://github.com/scylladb/seastar

VERSION="20.04.5 LTS (Focal Fossa)"

After running $ sudo ./install-dependencies.sh I get an error

E: Unable to locate package liburing-dev

**Comment by tchaikov** [comment]
@yigalirani hi Yigal, liburing-dev is not a must have for building Seastar. but we don't provide an option in `install-dependencies.sh` to disable the optional build dependencies yet. you can either just comment it out, or you might need to install liburing-dev manually from https://github.com/axboe/liburing or from another ubuntu distro (https://packages.ubuntu.com/jammy/liburing-dev for instance) if your distro does not provide this package. 

HTH.

**Comment by yigalirani** [comment]
It is now working for me, thanks. what I did was to try again using the latest ubuntu version
VERSION="22.04.1 LTS (Jammy Jellyfish)"

it looks like the ubnutu team have added liburing-dev to the Jammy Jelly fish so everything worked smoothly including configure and build

**Comment by tchaikov** [comment]
i created a pull request in hope to alleviate this pain. see #1463
