### ISSUE TITLE
return multiple values in continuation

### ISSUE THREAD

**Issue by wenyong-h** [scylladb/seastar#151]
First I write:
```c++
future<std::tuple<int,string>> res = someFuture.then([] { return std::make_tuple(1, "ok")})
```
then I find the value of future is already a tuple, so I want to write like this:
```c++
future<int,string> res = someFuture.then([] { return ???(1, "ok")})
```
but what shoud I return?

**Comment by avikivity** [comment]
return make_ready_future<int, string>(1, "ok");

**Comment by wenyong-h** [comment]
if I `return make_ready_future<int, string>(1, "ok");  `
wouldn't the type of res become `future<<future<int,string>>`??

**Comment by avikivity** [comment]
No.


Please ask questions on the mailing list, not in issues.
