### ISSUE TITLE
lw_shared_ptr's get() method may have illegal memory access

### ISSUE THREAD

**Issue by wenyong-h** [scylladb/seastar#162]
`T* get() const noexcept { return _p->to_value(); }`  
_p is null when lw_shared_ptr  is not pointed to some object.

**Comment by avikivity** [comment]
Confirmed.  Can you post a patch to the mailing list?

**Comment by wenyong-h** [comment]
OK.

**Comment by raphaelsc** [comment]
This is already fixed, closing...
