### ISSUE TITLE
Proposal to remove `shared_ptr::operator=(T&&)`

### ISSUE THREAD

**Issue by dotnwat** [scylladb/seastar#1621]
This overload was added 9 years ago in https://github.com/scylladb/seastar/commit/319ae0b530107dce510c27f45d21b4ad696ef07d.

```
    shared_ptr& operator=(T&& x) {
        this->~shared_ptr();
        new (this) shared_ptr(new data(std::move(x)));
        return *this;
    }
```

This recently burned me when I had mistakenly typed `p = std::string();` but what I meant was `*p = std::string()` expecting holders of copies of `p` to see the update. FWIW std::shared_ptr won't allow such mistakes to compile.

I guess I'm interested in there is some history here for this, and if it should be removed.

**Comment by tchaikov** [comment]
this helper is convenient, but semantically a little bit confusing. as it allows move a value into a pointer.  i'd vote for deprecating this operator first, as there are still a handful consumers in other projects.

@tgrabiec what do you think?

**Comment by tgrabiec** [comment]
I don't remember what we needed it for. I'm fine with deprecating it.
