### ISSUE TITLE
unified format file for seastar

### ISSUE THREAD

**Issue by infdahai** [scylladb/seastar#1636]
does seastar has a unified format for the coding style? Maybe a `.clang-format` file can make the thing easy.

just like rocksdb `clang-format` https://github.com/facebook/rocksdb/blob/main/.clang-format

**Comment by xemul** [comment]
@infdahai , https://github.com/scylladb/seastar/blob/master/coding-style.md

**Comment by infdahai** [comment]
maybe we can add something for `check format`.
