### ISSUE TITLE
cannot store unique_ptr in future object

### ISSUE THREAD

**Issue by wenyong-h** [scylladb/seastar#164]
could this be fixed?

**Comment by avikivity** [comment]
Can you give the error message?

We should be able to store move-only objects in futures.

**Comment by wenyong-h** [comment]
I don't have access to my working enviroment now.   
As i remeber, the compiler complains use of deleted functions, i. e., unique_ptr's copy constructor.

**Comment by avikivity** [comment]
future<> doesn't require a copy constructor, please post the error message when you have it.

**Comment by wenyong-h** [comment]
ok.

**Comment by wenyong-h** [comment]
I was wrong.
I simply forget to convert the unique_tpr to rvalue before return it.
because tempalte expansion, the error looks like occured in the seastart framework.
Thanks for your reply.
