### ISSUE TITLE
create a histogram for stall detection

### ISSUE THREAD

**Issue by amnonh** [scylladb/seastar#1674]
Not all stalls are the same, it would be helpful to have a histogram of the stalls, we can report a single histogram per node

**Comment by amnonh** [comment]
@mykaul I had thoughts about if it should be in seastar or ScylaDB, we'll need to move some of the histogram related code to seastar to support it.
The alternative is to add a call-back that would take care of the histogram code.

**Comment by mykaul** [comment]
> @mykaul I had thoughts about if it should be in seastar or ScylaDB, we'll need to move some of the histogram related code to seastar to support it. The alternative is to add a call-back that would take care of the histogram code.

It makes sense to move the code to seastar, IMHO.
