### ISSUE TITLE
debug builds: warn that -m parameters is not applied

### ISSUE THREAD

**Issue by gusev-p** [scylladb/seastar#1691]
Debug builds use `ASAN` allocator and ignore this parameter. Currently there are no clear signs that it's not applied, which causes misunderstanding and wasted time. For example, it took some time to get why [this test](https://github.com/scylladb/scylladb/blob/5acb137c2e9b14d15e8147d8c071671446873e09/test/cql-pytest/test_shedding.py#L76) test was failing in debug builds. It made some assumptions about available memory, which break in debug builds. Recently, @alecco stumbled upon the same problem.

**Comment by denesb** [comment]
@gusev-p for some reason this was not closed even though https://github.com/scylladb/seastar/pull/1693 was merged. Can we close this?

**Comment by nyh** [comment]
According to https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue, one has to write "Fixes #1691" - adding a colon "Fixes: #1691" is not ok :-(

**Comment by gusev-p** [comment]
> According to https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue, one has to write "Fixes #1691" - adding a colon "Fixes: #1691" is not ok :-(

thanks
