### ISSUE TITLE
system cpu usage high running Seastar 

### ISSUE THREAD

**Issue by caiqunli** [scylladb/seastar#1713]
I use seastar to develop a disk cache system. When we run server online, we found the cpu usage is very high. The perf top shows the smp_call_function_many_cond is the top system call. 
![image](https://github.com/scylladb/seastar/assets/7923332/fc699627-c766-4a56-aadd-9a9cb7dbf388)
We use smp::submit_to to call dma_read on other cpu cores,  is this may result in high system cpu usage?

**Comment by tchaikov** [comment]
i'd avoid cross-core communication on the critical paths, or better off avoiding it in general. why do you perform i/o on a different shard from the one which actually issues the i/o?

**Comment by caiqunli** [comment]
> i'd avoid cross-core communication on the critical paths, or better off avoiding it in general. why do you perform i/o on a different shard from the one which actually issues the i/o?

Thanks for reply.Requests will be served on all shards to get the data in the specificate offset of the disk.So in the system, a shard id will be calculated by request url to submit i/o request.I found the system call smp_call_function_many_cond/membarrier_private_expedited takes too much system cpu raised by function try_systemwide_memory_barrier, it happends when issues i/o frequently, any methods to reduce this system call? I run io_tester with multiple shards and perf the top cpu, this system call also very high.
`- name: randread
  shards: [1, 2, 3,4]
  type: randread
  data_size: 3000GB
  shard_info:
    parallelism: 10
    reqsize: 512kB
    shares: 10
    think_time: 0`
![image](https://github.com/scylladb/seastar/assets/7923332/4e643e59-4e29-46a5-bdec-513da62273ac)

**Comment by tchaikov** [comment]
> > i'd avoid cross-core communication on the critical paths, or better off avoiding it in general. why do you perform i/o on a different shard from the one which actually issues the i/o?
> 
> Thanks for reply.Requests will be served on all shards to get the data in the specificate offset of the disk.So in the system, a shard id will be calculated by request url to submit i/o request.I found the system call smp_call_function_many_cond/membarrier_private_expedited takes too much system cpu raised by function try_systemwide_memory_barrier, it happends when issues i/o frequently, any methods to reduce this system call? I run io_tester with multiple shards and perf the top cpu, this system call also very high.
> 

i am not sure you answered my question directly. and i think you missed my point -- to avoid cross-core communications. but i think the way how you distribute the load fails to enforce the share-nothing design encouraged by Seastar. i assume that the server is connected via TCP socket. as you might know, Seastar allows us to specify the `load_balancing_algorithm` as a parameter passed to `seastar::listen()` or `seastar::tls::listen()`. so, one can use `load_balancing_algorithm::port` to avoid cross-core communications.

since you are aiming at a better performance, i think you might want to investigate into how to improve the protocol between your client and server, so the client can calculate the port from which part the disk it wants to access -- put in other way, to use a shard-aware protocol.

but i doubt if sharding a single disk into smaller pieces and let different CPU cores to drive them would improve the overall performance. unless your disk is extremely fast.

> > * name: randread
> >   shards: [1, 2, 3,4]
> >   type: randread
> >   data_size: 3000GB
> >   shard_info:
> >   parallelism: 10
> >   reqsize: 512kB
> >   shares: 10
> >   think_time: 0
> 
> ![image](https://user-images.githubusercontent.com/7923332/250431630-4e643e59-4e29-46a5-bdec-513da62273ac.png)

**Comment by caiqunli** [comment]
> > > i'd avoid cross-core communication on the critical paths, or better off avoiding it in general. why do you perform i/o on a different shard from the one which actually issues the i/o?
> > 
> > 
> > Thanks for reply.Requests will be served on all shards to get the data in the specificate offset of the disk.So in the system, a shard id will be calculated by request url to submit i/o request.I found the system call smp_call_function_many_cond/membarrier_private_expedited takes too much system cpu raised by function try_systemwide_memory_barrier, it happends when issues i/o frequently, any methods to reduce this system call? I run io_tester with multiple shards and perf the top cpu, this system call also very high.
> 
> i am not sure you answered my question directly. and i think you missed my point -- to avoid cross-core communications. but i think the way how you distribute the load fails to enforce the share-nothing design encouraged by Seastar. i assume that the server is connected via TCP socket. as you might know, Seastar allows us to specify the `load_balancing_algorithm` as a parameter passed to `seastar::listen()` or `seastar::tls::listen()`. so, one can use `load_balancing_algorithm::port` to avoid cross-core communications.
> 
> since you are aiming at a better performance, i think you might want to investigate into how to improve the protocol between your client and server, so the client can calculate the port from which part the disk it wants to access -- put in other way, to use a shard-aware protocol.
> 
> but i doubt if sharding a single disk into smaller pieces and let different CPU cores to drive them would improve the overall performance. unless your disk is extremely fast.
> 
> > > * name: randread
> > >   shards: [1, 2, 3,4]
> > >   type: randread
> > >   data_size: 3000GB
> > >   shard_info:
> > >   parallelism: 10
> > >   reqsize: 512kB
> > >   shares: 10
> > >   think_time: 0
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/7923332/250431630-4e643e59-4e29-46a5-bdec-513da62273ac.png)

**Comment by caiqunli** [comment]
> > > i'd avoid cross-core communication on the critical paths, or better off avoiding it in general. why do you perform i/o on a different shard from the one which actually issues the i/o?
> > 
> > 
> > Thanks for reply.Requests will be served on all shards to get the data in the specificate offset of the disk.So in the system, a shard id will be calculated by request url to submit i/o request.I found the system call smp_call_function_many_cond/membarrier_private_expedited takes too much system cpu raised by function try_systemwide_memory_barrier, it happends when issues i/o frequently, any methods to reduce this system call? I run io_tester with multiple shards and perf the top cpu, this system call also very high.
> 
> i am not sure you answered my question directly. and i think you missed my point -- to avoid cross-core communications. but i think the way how you distribute the load fails to enforce the share-nothing design encouraged by Seastar. i assume that the server is connected via TCP socket. as you might know, Seastar allows us to specify the `load_balancing_algorithm` as a parameter passed to `seastar::listen()` or `seastar::tls::listen()`. so, one can use `load_balancing_algorithm::port` to avoid cross-core communications.
> 
> since you are aiming at a better performance, i think you might want to investigate into how to improve the protocol between your client and server, so the client can calculate the port from which part the disk it wants to access -- put in other way, to use a shard-aware protocol.
> 
> but i doubt if sharding a single disk into smaller pieces and let different CPU cores to drive them would improve the overall performance. unless your disk is extremely fast.
> 
> > > * name: randread
> > >   shards: [1, 2, 3,4]
> > >   type: randread
> > >   data_size: 3000GB
> > >   shard_info:
> > >   parallelism: 10
> > >   reqsize: 512kB
> > >   shares: 10
> > >   think_time: 0
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/7923332/250431630-4e643e59-4e29-46a5-bdec-513da62273ac.png)

you‘re right.it is not the best practices on Seastar. We deploy the server as clusters backend in Nginx upstreams, we can't manage these upstreams convenient if we use 'load_balancing_algorithm::port' . 
The purpose to let different cpu cores to access disk is not to improve the performance, but to load balance on the io_queue, the system will manage many disk devices. If disk io was drive on one shard, it still can't avoid cross-core communication.
