### ISSUE TITLE
ninja build failed: 'genpkey: Unrecognized flag quiet' 

### ISSUE THREAD

**Issue by LimingFang** [scylladb/seastar#1728]
- system: debian10
- steps:
  - `sudo ./install-dependencies.sh`
  - `./configure.py --mode=debug`

Error message:
```
fangliming.xxm@n37-051-191:~/seastar/build/debug$ ninja
[1/75] Generating other.key
FAILED: tests/unit/other.key
cd /data00/home/fangliming.xxm/seastar/build/debug/tests/unit && /usr/bin/openssl genpkey -quiet -out other.key -algorithm RSA -pkeyopt rsa_keygen_bits:4096
genpkey: Unrecognized flag quiet
genpkey: Use -help for summary.
[2/75] Generating caother.key
FAILED: tests/unit/caother.key
cd /data00/home/fangliming.xxm/seastar/build/debug/tests/unit && /usr/bin/openssl genpkey -quiet -out caother.key -algorithm RSA -pkeyopt rsa_keygen_bits:4096
genpkey: Unrecognized flag quiet
genpkey: Use -help for summary.
[3/75] Generating test.key
FAILED: tests/unit/test.key
cd /data00/home/fangliming.xxm/seastar/build/debug/tests/unit && /usr/bin/openssl genpkey -quiet -out test.key -algorithm RSA -pkeyopt rsa_keygen_bits:4096
genpkey: Unrecognized flag quiet
genpkey: Use -help for summary.
[4/75] Generating catest.key
FAILED: tests/unit/catest.key
cd /data00/home/fangliming.xxm/seastar/build/debug/tests/unit && /usr/bin/openssl genpkey -quiet -out catest.key -algorithm RSA -pkeyopt rsa_keygen_bits:4096
genpkey: Unrecognized flag quiet
genpkey: Use -help for summary.
[9/75] Building CXX object demos/CMakeFile..._echo_server.dir/tls_echo_server_demo.[10/75] Building CXX object demos/CMakeFiles/demo_rpc.dir/rpc_demo.cc.o
ninja: build stopped: subcommand failed.
```
```
[143/179] Generating mtls_client1.crt
Signature ok
subject=C = GB, ST = London, L = London, O = Redpanda Data, OU = Core, CN = client1.org
Getting CA Private Key
[146/179] Generating mtls_client2.crt
Signature ok
subject=C = GB, ST = London, L = London, O = Redpanda Data, OU = Core, CN = client2.org
Getting CA Private Key
[149/179] Generating mtls_server.crt
Signature ok
subject=C = GB, ST = London, L = London, O = Redpanda Data, OU = Core, CN = redpanda.com
Getting CA Private Key
[150/179] Generating other.key
FAILED: tests/unit/other.key
cd /data00/home/fangliming.xxm/seastar/build/debug/tests/unit && /usr/bin/openssl genpkey -quiet -out other.key -algorithm RSA -pkeyopt rsa_keygen_bits:4096
genpkey: Unrecognized flag quiet
genpkey: Use -help for summary.
[159/179] Building CXX object tests/unit/CMakeFiles/test_unit_rpc.dir/rpc_test.cc.o
ninja: build stopped: subcommand failed.
```

**Comment by mykaul** [comment]
Can you provide the version of openssl used? Is running the command manually working for you?

**Comment by tchaikov** [comment]
hi @LimingFang , the `genpkey -quiet` option was added to openssl back in openssl 3.0.0, see https://github.com/openssl/openssl/commit/7d72dc78ee54cc3b9163ef9b23cf22bb85015552 . while only debian bookworm and up have it. see https://packages.debian.org/search?keywords=openssl&searchon=names&suite=all&section=all

please either consider using debian bookworm or use a docker container (https://github.com/scylladb/seastar/blob/master/docker/dev/Dockerfile for instance) for building Seastar.

also, please note, we only support the latest two major releases of Clang and GCC, which are clang {15,16} and gcc {12,13}, while debian buster fails to provide any of them, see https://packages.debian.org/buster/clang and https://packages.debian.org/buster/gcc. you will still have to install them manually or use a newer release of debian.

**Comment by LimingFang** [comment]
> Can you provide the version of openssl used? Is running the command manually working for you?

![image](https://github.com/scylladb/seastar/assets/28479651/a6e12502-6e1c-4234-a635-b51e6790fbde)

libssl 1.1

**Comment by LimingFang** [comment]
@tchaikov ok，I'll update both of Debian version and libssl and have a try again. Thanks

**Comment by LimingFang** [comment]
@tchaikov One more question, if I build Seastar in docker(debian12) and install the libseastar.a in my host machine(debian10), IIUC, I can also use the static library, right?

**Comment by tchaikov** [comment]
i'd suggest try it out. in general, it depends. for instance, the ABI of third party libraries. but if i were you, i won't even want to spend my time on this unless i have to.

**Comment by tchaikov** [comment]
closing as we don't support ancient openssl.
