### ISSUE TITLE
Server-side streams are not deregistered on parent socket abort

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1732]
In client connection:
```
          return stop_send_loop(ep).then_wrapped([this] (future<> f) {
              f.ignore_ready_future();
              _outstanding.clear();
              if (is_stream()) {
                  deregister_this_stream();
              } else {
                  abort_all_streams();
              }
```
and the `abort_all_streams()` aborts the whole `_streams` list

But in server connection

```
          return stop_send_loop(ep).then_wrapped([this] (future<> f) {
              f.ignore_ready_future();
              get_server()._conns.erase(get_connection_id());
              if (is_stream()) {
                  return deregister_this_stream();
              } else {
                  return make_ready_future<>();
              }
```

and the `_streams` list remains intact

@gleb-cloudius , are server-side streams supposed to clean themselves somehow else, or is it a bug?

**Comment by gleb-cloudius** [comment]
> @gleb-cloudius , are server-side streams supposed to clean themselves somehow else, or is it a bug?

What is the point to do a cleanup from both sides (client and server)? If client connection fails it is enough to abort the streams on a client side (the fact that parent connection failure causes streams created through it to be aborted as well is out artificial requirement anyway).

Shouldn't such things be discussed on the mailing list before an issue is created?

**Comment by mykaul** [comment]
@xemul - what's the next step here?

**Comment by xemul** [comment]
Review and merge #1757 , @mykaul
