### ISSUE TITLE
make backtrace optional

### ISSUE THREAD

**Issue by a16bitsysop** [scylladb/seastar#1743]
execinfo.h was remove from alpine linux here:
https://gitlab.alpinelinux.org/alpine/aports/-/commit/50795a14dee639ce2dcc836e2b2baca9bad4a1b1

In seastar commit https://github.com/scylladb/seastar/commit/a48fe69724492ffec64625a081f6dea54a50e470 changed from using libunwind to execinfo.h

alpine linux still has libunwind but the above link makes it sound like it would not give useful information with musl

**Comment by tchaikov** [comment]
was trying to use musl-gcc and musl-clang wrappers to build Seastar, it turns out they are supposed to serves as the C compiler. to build C++ projects with musl, we'd need to use a different way on a distro where glibc use the default libc.

**Comment by a16bitsysop** [comment]
Here is a far as I got: https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/1070721#L577 
Is that the same errors you were getting?

**Comment by a16bitsysop** [comment]
@neopsykose got it building with these diffs: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/49224/diffs

**Comment by tchaikov** [comment]
@a16bitsysop thank you Duncan, i see the patchset practically removes the backtrace.

unfortunately i cannot find psykose's handle on github. will need to contact him/her via email i guess to see if he/she's willing to contribute these changes to Seastar.

**Comment by a16bitsysop** [comment]
this is her github page https://github.com/nekopsykose, I can add a note on my alpine merge request as well so she can see this

**Comment by tchaikov** [comment]
@a16bitsysop that'd be great! thanks.

**Comment by nekopsykose** [comment]
i'm fine with it but they are not complete to actually upstream, so they would have to be edited anyway which doesn't need my permission :)
