### ISSUE TITLE
-fsanitize=vptr is broken, disabling

### ISSUE THREAD

**Issue by maishi** [scylladb/seastar#178]
I want to build seastar on centos7
first excue  ./install-dependencies.sh, it's ok,
then ./configure.py --compiler=/opt/scylladb/bin/g++  --static-stdc++  --disable-xen 

it  show "-fsanitize=vptr is broken, disabling",I don't why?
can  anyone help me?

**Comment by eflyinghi** [comment]
I met the same issue in Ubuntu 14.04/16.04
Run ./install-dependencies.sh ok, and then
./configure.py --comipler=g++-5 ,then output "-fsanitize=vptr is broken, disabling"

**Comment by avikivity** [comment]
It is just a notice.  Everything will work fine.

**Comment by penberg** [comment]
@avikivity Perhaps we should add a "warning" prefix to the warning message?

**Comment by avikivity** [comment]
Good idea.  "notice" is even better.

**Comment by penberg** [comment]
I only have good ideas and am very experienced with ``git am`` but we now need someone to send a patch.
