### ISSUE TITLE
epoll backend: Aborted (EPOLLERR|EPOLLHUP) connections cause 100% reactor util until the respective socket is closed

### ISSUE THREAD

**Issue by StephanDollberg** [scylladb/seastar#1785]
Hi,

using the epoll backend connections that error out and are not closed in timely fashion can cause 100% reactor util due to spinning on `reactor_backend_epoll::wait_and_process`. Examples are RSTed server connections or client connections that failed to connect.

**How to reproduce:**

We originally saw this on a Redpanda cluster that showed 100% reactor utilization on shards even though no load was applied at the same time we were busy polling:

![image](https://github.com/scylladb/seastar/assets/2904723/b5c7a7c6-d745-47f9-8c07-b418e413eca7)

I have since then reproduced it with either the uploaded code from https://github.com/scylladb/seastar/issues/762 and also with the following small modification to the sctp clients demo apps (all using latest seastar):

``` cpp
diff --git a/demos/tcp_sctp_client_demo.cc b/demos/tcp_sctp_client_demo.cc
index 3de72776..2ab8b5e1 100644
--- a/demos/tcp_sctp_client_demo.cc
+++ b/demos/tcp_sctp_client_demo.cc
@@ -43,7 +43,7 @@ transport protocol = transport::TCP;

 class client {
 private:
-    static constexpr unsigned _pings_per_connection = 10000;
+    static constexpr unsigned _pings_per_connection = 160000; // gives more time to kill the client
     unsigned _total_pings;
     unsigned _concurrent_connections;
     ipv4_addr _server_addr;
diff --git a/demos/tcp_sctp_server_demo.cc b/demos/tcp_sctp_server_demo.cc
index 6918ab2e..9d942ee9 100644
--- a/demos/tcp_sctp_server_demo.cc
+++ b/demos/tcp_sctp_server_demo.cc
@@ -19,6 +19,7 @@
  * Copyright 2014 Cloudius Systems
  */

+#include "seastar/core/sleep.hh"
 #include <seastar/core/reactor.hh>
 #include <seastar/core/app-template.hh>
 #include <seastar/core/temporary_buffer.hh>
@@ -77,13 +78,16 @@ class tcp_server {
             connected_socket fd = std::move(ar.connection);
             socket_address addr = std::move(ar.remote_address);
             auto conn = new connection(*this, std::move(fd), addr);
-            (void)conn->process().then_wrapped([conn] (auto&& f) {
+            (void)conn->process().then_wrapped([conn] (auto&& f) -> future<void> {
+                return seastar::sleep(std::chrono::seconds(5)).then([conn, f = std::move(f)] () mutable  {
+                std::cout << "closing" << std::endl;
                 delete conn;
                 try {
                     f.get();
                 } catch (std::exception& ex) {
                     std::cout << "request error " << ex.what() << "\n";
                 }
+                });
             });
             do_accepts(listeners);
         }).then_wrapped([] (auto&& f) {

```

The idea is to add a sleep after the connection got aborted and before we close/destroy the connection. During this time the reactor will be spinning.

One can then run the server with something like:

```
demos/tcp_sctp_server_demo --reactor-backend epoll -m 1G -c 1
```

and the client with

```
demos/tcp_sctp_client_demo --reactor-backend epoll -m 1G -c 1 --server 127.0.0.1:10000 --conn 1
```

Killing the client while it's sending will trigger the condition. From the time the client is killed up until "closing" is printed you will see the server shard spinning.

**Cause:**

The issue is caused because of how `reactor_backend_epoll::wait_and_process` is implemented.

The error chain works like this:

 - `epoll_pwait` returns an event for the socket with `EPOLLIN|EPOLLHUP` (or `EPOLLOUT` in a different respective case)
 - We enter the error branch and set `evt.events` -  https://github.com/scylladb/seastar/blob/master/src/core/reactor_backend.cc#L863. This doesn't make much difference at this point as `pfd->events_requested` is still equal to `EPOLLIN`
 - `events_to_remove` is calculated to `0`
 - `complete_epoll_event` is called setting `pfd->events_requested` to 0
 - The loop concludes without removing the socket from the epoll set as we calculate `events_to_remove` before changing it. I think this is intended to avoid unneeded syscalls in the good case (so usually only receiving an event when not waiting for it will remove the socket from the set)
 - Given we run in level triggered mode `epoll_wait` again returns with `EPOLLIN|EPOLLHUP` for our socket
 - This time around in the error branch we set `evt.events` to `0`
 - This causes `events_to_remove` again to be calculated to `0` even though `pfd->events_requested` is `0` as well
 - Above continues until the socket is eventually closed and hence implicitly removed from the epoll set

**Possible Fix:**

Below patch makes the issue go away by always removing the socket from the epoll set if an error occurred and we are no longer waiting for any events. Not sure whether there is better ways.

``` cpp
diff --git a/src/core/reactor_backend.cc b/src/core/reactor_backend.cc
index e4a6a8f6..6609598d 100644
--- a/src/core/reactor_backend.cc
+++ b/src/core/reactor_backend.cc
@@ -857,10 +857,12 @@ reactor_backend_epoll::wait_and_process(int timeout, const sigset_t* active_sigm
             _steady_clock_timer_deadline = {};
             continue;
         }
+        bool has_error = false;
         if (evt.events & (EPOLLHUP | EPOLLERR)) {
             // treat the events as required events when error occurs, let
             // send/recv/accept/connect handle the specific error.
             evt.events = pfd->events_requested;
+            has_error = true;
         }
         auto events = evt.events & (EPOLLIN | EPOLLOUT | EPOLLRDHUP);
         auto events_to_remove = events & ~pfd->events_requested;
@@ -882,6 +884,9 @@ reactor_backend_epoll::wait_and_process(int timeout, const sigset_t* active_sigm
             auto op = evt.events ? EPOLL_CTL_MOD : EPOLL_CTL_DEL;
             ::epoll_ctl(_epollfd.get(), op, pfd->fd.get(), &evt);
         }
+        else if (has_error && pfd->events_requested == 0) {
+            pfd->events_epoll = 0;
+            ::epoll_ctl(_epollfd.get(), EPOLL_CTL_DEL, pfd->fd.get(), nullptr);
+        }
     }
     return nr;
 }
```

**Related Issues:**

I suspect all the following issues are caused by this issue or at least related:

 - https://github.com/scylladb/seastar/issues/762
 - https://github.com/scylladb/scylladb/issues/12774
 - https://github.com/scylladb/scylladb/issues/7753
 - https://github.com/scylladb/scylladb/issues/13377

Finally I know that the epoll backend doesn't get much love and we'd also rather not use it but given that RHEL8 only ships with Linux 4.18 and `IOCB_CMD_POLL‎` is only available as of 4.19 people will be using the epoll backend for a long time to come.

Hope this makes sense,
Stephan

**Comment by avikivity** [comment]
@StephanDollberg if you have a fix for this, please submit it upstream so others can enjoy it too

**Comment by StephanDollberg** [comment]
Yes, sorry have opened a PR with my now at https://github.com/scylladb/seastar/pull/1945
