### ISSUE TITLE
op size/type aware I/O scheduler

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#179]
Most disks have different performance for reads and writes, and of course need different queue depths for different size ops.

Right now we benchmark the disk for the cheapest operation (4k reads) and apply it to all operations.  While we do charge large transfers more in fair_queue, we disregard size and type when determining the queue depth.  This can cause excessive latency if the queue is filled with 128k writes and we want to sneak in a 4k read.

**Comment by glommer** [comment]
Avi, please close with iotune v2
