### ISSUE TITLE
Compile fail on Debian g++-4.9

### ISSUE THREAD

**Issue by uttampawar** [scylladb/seastar#180]
Hi All,
I'm getting compile time error as follows,
FAILED: g++-4.9 -MMD -MT build/debug/rpc/rpc.o -MF build/debug/rpc/rpc.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined  -DASAN_ENABLED -O0 -DDEBUG -DDEBUG_SHARED_PTR -DDEFAULT_ALLOCATOR -I build/debug/gen -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -Ifmt -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -c -o build/debug/rpc/rpc.o rpc/rpc.cc
In file included from ./net/api.hh:31:0,
                 from rpc/rpc.hh:28,
                 from rpc/rpc.cc:1:
./core/print.hh:25:25: fatal error: fmt/ostream.h: No such file or directory
 #include <fmt/ostream.h>
                         ^
compilation terminated.

Am I missing any package to install?

Any help is appreciated.

--Uttam

**Comment by avikivity** [comment]
Try 'git submodule update --init --recursive'.

**Comment by uttampawar** [comment]
Thanks. This helped but failed different error, 
8/278] CXX build/debug/core/prometheus.o
FAILED: g++-4.9 -MMD -MT build/debug/core/prometheus.o -MF build/debug/core/prometheus.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined  -DASAN_ENABLED -O0 -DDEBUG -DDEBUG_SHARED_PTR -DDEFAULT_ALLOCATOR -I build/debug/gen -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -Ifmt -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -c -o build/debug/core/prometheus.o core/prometheus.cc
core/prometheus.cc:23:45: fatal error: google/protobuf/io/coded_stream.h: No such file or directory
 #include <google/protobuf/io/coded_stream.h>

**Comment by raphaelsc** [comment]
On Fri, Aug 12, 2016 at 12:41 PM, uttampawar <notifications@github.com>
wrote:

> Thanks. This helped but failed different error,
> 8/278] CXX build/debug/core/prometheus.o
> FAILED: g++-4.9 -MMD -MT build/debug/core/prometheus.o -MF
> build/debug/core/prometheus.o.d -fsanitize=address -fsanitize=leak
> -fsanitize=undefined -DASAN_ENABLED -O0 -DDEBUG -DDEBUG_SHARED_PTR
> -DDEFAULT_ALLOCATOR -I build/debug/gen -std=gnu++1y -g -Wall -Werror
> -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE -Ifmt
> -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_XEN -DHAVE_HWLOC
> -DHAVE_NUMA -c -o build/debug/core/prometheus.o core/prometheus.cc
> core/prometheus.cc:23:45: fatal error: google/protobuf/io/coded_stream.h:
> No such file or directory
> #include
>
It looks like you're missing the protobuf package. I think this is what you
need: https://packages.debian.org/wheezy/libprotobuf-dev
