### ISSUE TITLE
reactor::file_system_at() doesn't distinguish ext* file systems

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/seastar#183]
reactor::file_system_at always return fs_type::ext2 for a ext* file system because the same magic number is used for ext2, ext3, and ext4. We may distinguish them by looking at other properties such as max link.

**Comment by avikivity** [comment]
It's not really interesting, nobody uses ext2/3 any more.

**Comment by raphaelsc** [comment]
@avikivity at least, we should fix reactor::file_system_at() to only return fs_type::ext. It currently returns fs_type::ext2 for a dir on ext4.
