### ISSUE TITLE
enable -Wdeprecated compiler option

### ISSUE THREAD

**Issue by tchaikov** [scylladb/seastar#1863]
this option is an umbrella option which enables a bunch of different `-Wdeprecated-*` options. for the Clang option, see https://clang.llvm.org/docs/DiagnosticsReference.html#wdeprecated.

these options help us to identify potentially dangerous code or non-standard compliant implementation, which in turn, can also be dangerous in practice.

**Comment by avikivity** [comment]
If we enable it, it should be as a warning, not an error, since newer C++ versions can deprecate some features while they're still supported on others.
