### ISSUE TITLE
drop zlib from cooking_recipe.cmake

### ISSUE THREAD

**Issue by tchaikov** [scylladb/seastar#1901]
zlib is used as the software implementation of [compressdev](https://doc.dpdk.org/guides/prog_guide/compressdev.html), and its hardware accelerated counterpart is QAT.

probably we can drop it as we are not using it. or encourage the upstream to switch to zlib-ng if we plan to use this API in our application, but i doubt that we are going in this direction.

**Comment by mykaul** [comment]
What other DPDK features (such as 'compressdev') we are not using, yet compiling?

**Comment by mykaul** [comment]
Back to the original issue, I wonder what can we disable from DPDK build?
```
=================
Libraries Enabled
=================

libs:
	kvargs, telemetry, eal, ring, rcu, mempool, mbuf, net, 
	meter, ethdev, pci, cmdline, metrics, hash, timer, acl, 
	bbdev, bitratestats, bpf, cfgfile, compressdev, cryptodev, distributor, efd, 
	eventdev, gpudev, gro, gso, ip_frag, jobstats, kni, latencystats, 
	lpm, member, pcapng, rawdev, regexdev, mldev, dmadev, rib, 
	reorder, sched, security, stack, vhost, ipsec, pdcp, fib, 
	pdump, graph, node, 

Message: 
===============
Drivers Enabled
===============

common:
	cpt, dpaax, iavf, idpf, octeontx, cnxk, mlx5, qat, 
	sfc_efx, 
bus:
	auxiliary, cdx, dpaa, fslmc, ifpga, pci, platform, vdev, 
	vmbus, 
mempool:
	bucket, cnxk, dpaa, dpaa2, octeontx, ring, stack, 
dma:
	cnxk, dpaa, dpaa2, hisilicon, idxd, ioat, skeleton, 
net:
	af_packet, ark, atlantic, avp, axgbe, bnx2x, bnxt, bond, 
	cnxk, cpfl, cxgbe, dpaa, dpaa2, e1000, ena, enetc, 
	enetfec, enic, failsafe, fm10k, gve, hinic, hns3, i40e, 
	iavf, ice, idpf, igc, ionic, ixgbe, kni, mana, 
	memif, mlx4, mlx5, netvsc, nfp, ngbe, null, octeontx, 
	octeon_ep, pfe, qede, ring, sfc, tap, thunderx, txgbe, 
	vdev_netvsc, vhost, virtio, vmxnet3, 
raw:
	cnxk_bphy, cnxk_gpio, dpaa2_cmdif, ntb, skeleton, 
crypto:
	bcmfs, caam_jr, cnxk, dpaa_sec, dpaa2_sec, mlx5, nitrox, null, 
	octeontx, scheduler, virtio, 
compress:
	mlx5, octeontx, zlib, 
regex:
	mlx5, cn9k, 
ml:
	cnxk, 
vdpa:
	ifc, mlx5, sfc, 
event:
	cnxk, dlb2, dpaa, dpaa2, dsw, opdl, skeleton, sw, 
	octeontx, 
baseband:
	acc, fpga_5gnr_fec, fpga_lte_fec, la12xx, null, turbo_sw, 
gpu:
	
```

**Comment by tchaikov** [comment]
> What other DPDK features (such as 'compressdev') we are not using, yet compiling?

we were not compiling `compressdev`.

**Comment by tchaikov** [comment]
> Back to the original issue, I wonder what can we disable from DPDK build?
> 
> ```
> =================
> Libraries Enabled
> =================
> 
> libs:
> 	kvargs, telemetry, eal, ring, rcu, mempool, mbuf, net, 
> 	meter, ethdev, pci, cmdline, metrics, hash, timer, acl, 
> 	bbdev, bitratestats, bpf, cfgfile, compressdev, cryptodev, distributor, efd, 
> 	eventdev, gpudev, gro, gso, ip_frag, jobstats, kni, latencystats, 
> 	lpm, member, pcapng, rawdev, regexdev, mldev, dmadev, rib, 
> 	reorder, sched, security, stack, vhost, ipsec, pdcp, fib, 
> 	pdump, graph, node, 
> 
> Message: 
> ===============
> Drivers Enabled
> ===============
> 
> common:
> 	cpt, dpaax, iavf, idpf, octeontx, cnxk, mlx5, qat, 
> 	sfc_efx, 
> bus:
> 	auxiliary, cdx, dpaa, fslmc, ifpga, pci, platform, vdev, 
> 	vmbus, 
> mempool:
> 	bucket, cnxk, dpaa, dpaa2, octeontx, ring, stack, 
> dma:
> 	cnxk, dpaa, dpaa2, hisilicon, idxd, ioat, skeleton, 
> net:
> 	af_packet, ark, atlantic, avp, axgbe, bnx2x, bnxt, bond, 
> 	cnxk, cpfl, cxgbe, dpaa, dpaa2, e1000, ena, enetc, 
> 	enetfec, enic, failsafe, fm10k, gve, hinic, hns3, i40e, 
> 	iavf, ice, idpf, igc, ionic, ixgbe, kni, mana, 
> 	memif, mlx4, mlx5, netvsc, nfp, ngbe, null, octeontx, 
> 	octeon_ep, pfe, qede, ring, sfc, tap, thunderx, txgbe, 
> 	vdev_netvsc, vhost, virtio, vmxnet3, 
> raw:
> 	cnxk_bphy, cnxk_gpio, dpaa2_cmdif, ntb, skeleton, 
> crypto:
> 	bcmfs, caam_jr, cnxk, dpaa_sec, dpaa2_sec, mlx5, nitrox, null, 
> 	octeontx, scheduler, virtio, 
> compress:
> 	mlx5, octeontx, zlib, 
> regex:
> 	mlx5, cn9k, 
> ml:
> 	cnxk, 
> vdpa:
> 	ifc, mlx5, sfc, 
> event:
> 	cnxk, dlb2, dpaa, dpaa2, dsw, opdl, skeleton, sw, 
> 	octeontx, 
> baseband:
> 	acc, fpga_5gnr_fec, fpga_lte_fec, la12xx, null, turbo_sw, 
> gpu:
> 	
> ```

could you provide more context? what does this output imply? where did it come from?

**Comment by mykaul** [comment]
@tchaikov - I thought it was part of the ./configure output (or the build) of DPDK - wanted to ensure we build the minimal set of features/drivers from DPDK that we actually use.
