### ISSUE TITLE
Unnecessary hard-coding of dpdk RTE_MAX_MEMSEG_LISTS

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#1922]
As @tmonjalo notes, RTE_MAX_MEMSEG_LISTS can be configured dynamically (https://github.com/scylladb/dpdk/commit/cafaa3cf457584de), so scylladb/dpdk@cafaa3cf457584de3c4de1998fc67bd03b26f2f7 is unnecessary provided we supply the correct runtime configuration.

/cc @tchaikov

**Comment by tchaikov** [comment]
@avikivity i think you misread Thomas' proposal. unlike `RTE_MAX_MEMZONE`, `RTE_MAX_MEMSEG_LISTS` *cannot* be dynamically configured at runtime at this moment. but we *could* update dpdk so that it offers the ability to configure`RTE_MAX_MEMSEG_LISTS` at runtime as well.

**Comment by avikivity** [comment]
Oh. We can just keep the patch then.

**Comment by tchaikov** [comment]
i am closing this issue at this moment. as it does not to existing dpdk and seastar.
