### ISSUE TITLE
pass informative string to `[[nodiscard]]` attribute in C++20

### ISSUE THREAD

**Issue by tchaikov** [scylladb/seastar#1936]
per https://en.cppreference.com/w/cpp/language/attributes/nodiscard, `[[nodiscard]]` is able to accept a string literal for the error message. we should use it for better error when a `[[nodiscard]]` value is discarded. unfortunately, this feature is only available in C++20. so, once we drop the C++17 support, we should do this. or at least revert #1935 .

see also #1932

**Comment by avikivity** [comment]
Note the messages deleted by 6d14c36b40fa7b20df8055283ed7bc27e77a6e86 are not in fact informative.

**Comment by tchaikov** [comment]
fair enough. i am closing this issue. thought my change would introduce a regression on the usability regard.
