### ISSUE TITLE
Please support using NFS (with caveats or performance issue is fine)

### ISSUE THREAD

**Issue by hiqsociety** [scylladb/seastar#1951]
as in this issue here.
https://github.com/scylladb/scylladb/issues/16069

nfs should be used. whether for experimental mode or otherwise. please make this happen.

do provide an ETA on when this can be done. thx

**Comment by nyh** [comment]
Please don't open unnecessary duplicate issues. We already have this issue on this project:
https://github.com/scylladb/seastar/issues/1947
