### ISSUE TITLE
configure.py with --enable-dpdk error

### ISSUE THREAD

**Issue by moon-fall** [scylladb/seastar#1959]
./configure.py --mode=release --without-tests --enable-dpdk --prefix=/usr/local

/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_zip.a(otx_zip.o):(.bss+0x0): multiple definition of `octtx_zip_logtype_driver'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_zip.a(otx_zip_pmd.o):(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[5]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.app.mk:406: dpdk-test-crypto-perf] Error 1
make[4]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.subdir.mk:37: test-crypto-perf] Error 2
collect2: error: ld returned 1 exit status
make[5]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.app.mk:406: dpdk-test-compress-perf] Error 1
make[4]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.subdir.mk:37: test-compress-perf] Error 2
collect2: error: ld returned 1 exit status
make[5]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.app.mk:406: dpdk-test-eventdev] Error 1
make[4]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.subdir.mk:37: test-eventdev] Error 2
  LD testbbdev
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_bus_fslmc.a(qbman_debug.o):(.bss+0x0): multiple definition of `qman_version'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_bus_fslmc.a(qbman_portal.o):(.bss+0x0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_rxtx.o):(.bss+0x0): multiple definition of `igb_flow_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_rxtx.o):(.bss+0x10): multiple definition of `igb_filter_rss_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x10): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_rxtx.o):(.bss+0x20): multiple definition of `igb_filter_flex_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x20): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_rxtx.o):(.bss+0x30): multiple definition of `igb_filter_syn_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x30): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_rxtx.o):(.bss+0x40): multiple definition of `igb_filter_ethertype_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x40): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_rxtx.o):(.bss+0x50): multiple definition of `igb_filter_ntuple_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x50): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_pf.o):(.bss+0x0): multiple definition of `igb_flow_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_pf.o):(.bss+0x10): multiple definition of `igb_filter_rss_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x10): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_pf.o):(.bss+0x20): multiple definition of `igb_filter_flex_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x20): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_pf.o):(.bss+0x30): multiple definition of `igb_filter_syn_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x30): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_pf.o):(.bss+0x40): multiple definition of `igb_filter_ethertype_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x40): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_pf.o):(.bss+0x50): multiple definition of `igb_filter_ntuple_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x50): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_flow.o):(.bss+0x50): multiple definition of `igb_filter_ntuple_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x50): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_flow.o):(.bss+0x30): multiple definition of `igb_filter_syn_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x30): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_flow.o):(.bss+0x20): multiple definition of `igb_filter_flex_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x20): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_flow.o):(.bss+0x0): multiple definition of `igb_flow_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_flow.o):(.bss+0x10): multiple definition of `igb_filter_rss_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x10): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_flow.o):(.bss+0x40): multiple definition of `igb_filter_ethertype_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x40): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_ethdev.o):(.bss+0x0): multiple definition of `igb_flow_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_ethdev.o):(.bss+0x30): multiple definition of `igb_filter_syn_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x30): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_ethdev.o):(.bss+0x10): multiple definition of `igb_filter_rss_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x10): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_ethdev.o):(.bss+0x40): multiple definition of `igb_filter_ethertype_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x40): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_ethdev.o):(.bss+0x50): multiple definition of `igb_filter_ntuple_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x50): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_ethdev.o):(.bss+0x20): multiple definition of `igb_filter_flex_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x20): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_rxtx.o):(.bss+0x0): multiple definition of `igb_flow_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_rxtx.o):(.bss+0x10): multiple definition of `igb_filter_rss_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x10): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_rxtx.o):(.bss+0x20): multiple definition of `igb_filter_flex_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x20): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_rxtx.o):(.bss+0x30): multiple definition of `igb_filter_syn_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x30): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_rxtx.o):(.bss+0x40): multiple definition of `igb_filter_ethertype_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x40): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(em_rxtx.o):(.bss+0x50): multiple definition of `igb_filter_ntuple_list'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_e1000.a(igb_ethdev.o):(.bss+0x50): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_virtio.a(vhost_kernel.o):(.rodata+0x140): multiple definition of `vhost_msg_strings'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_virtio.a(vhost_user.o):(.rodata+0x120): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_virtio.a(virtio_user_dev.o):(.rodata+0x120): multiple definition of `vhost_msg_strings'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_virtio.a(vhost_user.o):(.rodata+0x120): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_virtio.a(virtio_user_ethdev.o):(.rodata+0x300): multiple definition of `vhost_msg_strings'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_virtio.a(vhost_user.o):(.rodata+0x120): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_null_crypto.a(null_crypto_pmd_ops.o):(.bss+0x0): multiple definition of `null_logtype_driver'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_null_crypto.a(null_crypto_pmd.o):(.bss+0x0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_crypto.a(otx_cryptodev_hw_access.o):(.bss+0x0): multiple definition of `cpt_logtype'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_crypto.a(otx_cryptodev.o):(.bss+0x4): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_crypto.a(otx_cryptodev_mbox.o):(.bss+0x0): multiple definition of `cpt_logtype'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_crypto.a(otx_cryptodev.o):(.bss+0x4): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_crypto.a(otx_cryptodev_ops.o):(.bss+0x4): multiple definition of `cpt_logtype'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_crypto.a(otx_cryptodev.o):(.bss+0x4): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_crypto.a(otx_cryptodev_ops.o):(.bss+0x0): multiple definition of `otx_cryptodev_driver_id'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_crypto.a(otx_cryptodev.o):(.bss+0x0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_dpaa_sec.a(dpaa_sec.o):(.bss+0x4): multiple definition of `rta_sec_era'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_dpaa2_sec.a(dpaa2_sec_dpseci.o):(.data+0xe0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_caam_jr.a(caam_jr.o):(.bss+0x0): multiple definition of `rta_sec_era'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_dpaa2_sec.a(dpaa2_sec_dpseci.o):(.data+0xe0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_virtio_crypto.a(virtio_pci.o):(.bss+0x0): multiple definition of `virtio_hw_internal'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_virtio.a(virtio_ethdev.o):(.bss+0x0): first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_zip.a(otx_zip.o):(.bss+0x0): multiple definition of `octtx_zip_logtype_driver'; /var/dpdk/seastar-seastar-20.05.0/build/release/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/lib/librte_pmd_octeontx_zip.a(otx_zip_pmd.o):(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[5]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.app.mk:406: testbbdev] Error 1
make[4]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.subdir.mk:37: test-bbdev] Error 2
make[3]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.sdkbuild.mk:48: app] Error 2
make[2]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.sdkroot.mk:99: all] Error 2
make[1]: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.sdkinstall.mk:61: pre_install] Error 2
make: *** [/var/dpdk/seastar-seastar-20.05.0/dpdk/mk/rte.sdkroot.mk:77: install] Error 2
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./configure.py", line 229, in <module>
    configure_mode(mode)
  File "./configure.py", line 226, in configure_mode
    subprocess.check_call(ARGS, shell=False, cwd=dir)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./cooking.sh', '-i', 'dpdk', '-d', '/var/dpdk/seastar-seastar-20.05.0/build/release', '--', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_C_COMPILER=gcc', '-DCMAKE_CXX_COMPILER=g++', '-DCMAKE_INSTALL_PREFIX=/usr/local', '-DSeastar_API_LEVEL=2', '-DSeastar_EXCLUDE_TESTS_FROM_ALL=yes', '-DSeastar_EXCLUDE_APPS_FROM_ALL=no', '-DSeastar_EXCLUDE_DEMOS_FROM_ALL=no', '-DSeastar_CXX_FLAGS=', '-DSeastar_LD_FLAGS=', '-DSeastar_CXX_DIALECT=gnu++17', '-DSeastar_DPDK=yes', '-DSeastar_DPDK_MACHINE=native', '-DSeastar_HWLOC=yes', '-DSeastar_ALLOC_FAILURE_INJECTION=no', '-DSeastar_ALLOC_PAGE_SIZE=no', '-DSeastar_STD_OPTIONAL_VARIANT_STRINGVIEW=0', '-DSeastar_SPLIT_DWARF=no', '-DSeastar_HEAP_PROFILING=no', '-DSeastar_EXPERIMENTAL_COROUTINES_TS=no', '-DSeastar_UNUSED_RESULT_ERROR=no']' returned non-zero exit status 1.

**Comment by moon-fall** [comment]
or how to  
> Modify the CMake cache (CMakeCache.txt) to inform CMake of the location of the installed DPDK SDK.
in the README-DPDK.md

**Comment by tchaikov** [comment]
@moon-fall could you put more details? like which version of seastar you are using? i could put a guess based on the path: 20.05. but that version was cut 3 years ago.

if you are not using the latest seastar, i'd suggest you give it a try.

**Comment by tchaikov** [comment]
closing for now. please reopen this issue if it still exists.
