### ISSUE TITLE
`sharded::map()` is receiving a function of parameter `const Service &`

### ISSUE THREAD

**Issue by unknownzerx** [scylladb/seastar#199]
With
```cpp
sharded<Service> server;
```

Instead of
```cpp
server.map([](Service &s) { ... });
```
I have to write
```cpp
server.map([](const Service &s) { ... });
```

Am I missing something for using it without `const`?

If the `const` is required, is there a good practice to map a non-const function over all cores?

**Comment by tgrabiec** [comment]
@unknownzerx Please rebase. You should be able to take service by non-const reference now.
