### ISSUE TITLE
Failed to open '/build/release/seastar.pc': No such file or directory && cannot find -lunistring

### ISSUE THREAD

**Issue by ztms123** [scylladb/seastar#2009]
I build seastar and then want run example 
first  i build 

> c++ main.cc `pkg-config --cflags --libs --static $SEASTAR/build/release/seastar.pc`

Then **ERROR**

> Failed to open '/build/release/seastar.pc': No such file or directory
No package '/build/release/seastar.pc' found
main.cc:1:10: fatal error: seastar/core/app-template.hh: No such file or directory
    1 | #include <seastar/core/app-template.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
 
SO i change path seastar.pc

> c++ main.cc `pkg-config --cflags --libs --static seastar.pc`

and **ERROR**

> /usr/bin/ld: cannot find -lunistring: No such file or directory
/usr/bin/ld: cannot find -lunistring: No such file or directory
/usr/bin/ld: cannot find -ludev: No such file or directory
collect2: error: ld returned 1 exit status

![image](https://github.com/scylladb/seastar/assets/81799631/fd843d65-db00-42cf-9c34-2f70609e8ff6)

**Comment by sqddk** [comment]
It seems that your $SEASTAR variable has not been set. Do you need to set the absolute path to the Seastar folder first?

**Comment by ztms123** [comment]
> It seems that your $SEASTAR variable has not been set. Do you need to set the absolute path to the Seastar folder first?
@sqddk Thank  but i change path  and  this ERROR

> /usr/bin/ld: cannot find -lunistring: No such file or directory
/usr/bin/ld: cannot find -lunistring: No such file or directory
/usr/bin/ld: cannot find -ludev: No such file or directory
collect2: error: ld returned 1 exit status

**Comment by sqddk** [comment]
This looks like the library has not been compiled into binary. Have you configured and run ninja?
