### ISSUE TITLE
input_stream::read_exactly_part() uses recursion which may overflow the stack for large sizes

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#202]
Refs #195

**Comment by niekbouman** [comment]
We seem to have hit this issue recently.

@avikivity 
If I'd like to fix this and submit a PR or patch, can I do so by transforming `read_exactly_part` into a coroutine?

(given that you just switched to c++20/c++23 standards? 
https://github.com/scylladb/seastar/commit/5d3ee980730b49c2379a2728d69698ee68f5dbeb )

**Comment by avikivity** [comment]
Yes

**Comment by niekbouman** [comment]
> Yes

thanks
please see https://github.com/scylladb/seastar/pull/2093
