### ISSUE TITLE
post support in http.

### ISSUE THREAD

**Issue by xiyanxiyan10** [scylladb/seastar#203]
If support for post in http is needed? I'm trying to add parser in httpd.h for http post support.

**Comment by cuongtv51** [comment]
Support POST in Http is important, Please support POST http, thanks all.

**Comment by avikivity** [comment]
Seems like it's not. The best way to ensure it is fixed, is to fix it yourself and send a patch.

**Comment by binbowang1987** [comment]
Okay, thank you for reply. @avikivity
