### ISSUE TITLE
Web App with MySQL backend

### ISSUE THREAD

**Issue by hpcmachines** [scylladb/seastar#212]
I would like to build a web app using seastar. I am planning to use either MariaDB or MySQL as database backend. My question is, how do I connect to MySQL database from seastar app? Can I just use MySQL's C++ connector directly or do I need to follow any async pattern to connect to the database?

**Comment by avikivity** [comment]
You need an async mysql driver; the synchronous one won't work with seastar.

Use the mailing list for questions, not the bug tracker.
