### ISSUE TITLE
zero-copy interface of output_stream is lacking batching

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#213]
Applies to:

```
future<> write(net::packet p);
future<> write(scattered_message<char_type> msg);
future<> write(temporary_buffer<char_type>);
```

They will pass each message directly to the underlying data sink. This may result in high number of small packets to be generated and as a result worse performance than what we get with the copying writes.

We could buffer the messages until the stream is flushed, and pass them to the underlying data sink using vectored put: `put(std::vector<temporary_buffer<char>> data)`. The posix data sink issues a single vectored sendmsg() for this.

Refs scylladb/scylla#1786

**Comment by avikivity** [comment]
Here's another idea: when we flush(), share and split the temporary_buffer, giving the front to the data sink, and keep the back in the output_stream.  The sink pushes it to the protocol adapter.

The protocol adapter keeps a queue of temporary_buffers; when it gets the first one, it registers itself in a poller (native tcp does this already, so we eliminate a layer).  When it gets a non-first buffer, it checks whether it can merge it into the back buffer -- contiguous buffer, same allocator.  If that's the case, then we also reduce succeeding work by defragmenting the buffers.  We also reduce 8k allocations (but increase much smaller deleter allocations).
