### ISSUE TITLE
Arbitrary-precision reactor utilization metric

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#214]
Currently the value exported for `reactor-*/gauge-load` represents average utilization from the last 5 seconds, updated every second. 

This has disadvantage of smoothing out spikes in utilization which happened within that 5 seconds. 

We can expose a new metric which will allow monitoring average utilization with arbitrary precision depending on the monitoring client's poll period. This can be achieved by exposing a monotonically increasing metric for total idle time. The client then calculates utilization like this:

`sum(1 - irate(collectd_reactor_derive{type="idle_nanos"}[30s]) / 1000000000) by (instance)`

Comparing old utilization metric with the new metric in a running system:

![load](https://cloud.githubusercontent.com/assets/283695/19805997/2065357a-9d18-11e6-8d9e-b1f40c9f0068.png)

**Comment by avikivity** [comment]
Cheaper to compute, too.  Collectd's disk plugin uses a similar method for disk utilization, ms_per_sec or similar.
