### ISSUE TITLE
iotune per-shard depth underflow

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#2169]
```
    unsigned per_shard_io_depth() const {
        auto iodepth = _test_directory.max_iodepth() / smp::count;
        if (this_shard_id() < _test_directory.max_iodepth() % smp::count) {
            iodepth++;
        }
        return std::min(iodepth, 128u);
    }               
    seastar::sharded<test_file> _iotune_test_file;
```

if max_iodepth is less than smp::count (and this is possible for non-raid disk with 127 depth on large node with 128 cores) the iodepth is 0 and e.g. wrire random workload doesn't send any requests and the throws `No data collected`

Correct behavior would be if iotune just ignores shards above io-depth

refs: scylladb/scylladb#5181

Cc @pwrobelse

**Comment by pwrobelse** [comment]
The fix was merged yesterday. I am closing the issue.
