### ISSUE TITLE
metrics: trying to add summaries is unsafe

### ISSUE THREAD

**Issue by amnonh** [scylladb/seastar#2191]
It does not make sense to aggregate a summary, but if some have a reason to do it, the code should not throw as it does today.
Instead, it should act like a histogram

**Comment by nyh** [comment]
I can't say I understand this issue. You're say that it doesn't make sense to add summaries - so why implement it?
If you say that it **does** make sense to add summaries, then I understand this issue (and the fix), but if it **doesn't** make sense? :-)
