### ISSUE TITLE
Compile 'core/reactor.cc' failed on centos7

### ISSUE THREAD

**Issue by q96456** [scylladb/seastar#222]
hi .
When i compile appeared some mistakes：
/home/bojue/seastar/seastar/core/reactor.cc:1872：对‘reactor::total_busy_time()’未定义的引用
collect2: 错误：ld 返回 1
[19/107] LINK build/release/apps/httpd/httpd
FAILED: /opt/scylladb/bin/g++  -O2 -I build/release/gen -g -Wl,--no-as-needed   -fvisibility=hidden -pthread  -o build/release/apps/httpd/httpd build/release/apps/httpd/main.o build/release/http/transformers.o build/release/http/json_path.o build/release/http/file_handler.o build/release/http/common.o build/release/http/routes.o build/release/json/json_elements.o build/release/json/formatter.o build/release/http/matcher.o build/release/http/mime_types.o build/release/http/httpd.o build/release/http/reply.o build/release/http/api_docs.o build/release/net/proxy.o build/release/net/virtio.o build/release/net/dpdk.o build/release/net/ip.o build/release/net/ethernet.o build/release/net/arp.o build/release/net/native-stack.o build/release/net/ip_checksum.o build/release/net/udp.o build/release/net/tcp.o build/release/net/dhcp.o build/release/net/tls.o build/release/core/reactor.o build/release/core/systemwide_memory_barrier.o build/release/core/fstream.o build/release/core/posix.o build/release/core/memory.o build/release/core/resource.o build/release/core/scollectd.o build/release/core/metrics.o build/release/core/app-template.o build/release/core/thread.o build/release/core/dpdk_rte.o build/release/util/conversions.o build/release/util/log.o build/release/net/packet.o build/release/net/posix-stack.o build/release/net/net.o build/release/net/stack.o build/release/rpc/rpc.o build/release/rpc/lz4_compressor.o -laio -lboost_program_options -lboost_system -lboost_filesystem  -lm -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -llz4 -lprotobuf -ldl -lgcc_s -lunwind -static-libgcc -static-libstdc++ -lhwloc -lnuma -lpciaccess -lxml2 -lz
build/release/core/reactor.o：在函数‘operator()’中：
/home/bojue/seastar/seastar/core/reactor.cc:1872：对‘reactor::total_busy_time()’未定义的引用
collect2: 错误：ld 返回 1
[19/107] LINK build/release/apps/memcached/memcached
FAILED: /opt/scylladb/bin/g++  -O2 -I build/release/gen -g -Wl,--no-as-needed   -fvisibility=hidden -pthread  -o build/release/apps/memcached/memcached build/release/apps/memcached/memcache.o build/release/net/proxy.o build/release/net/virtio.o build/release/net/dpdk.o build/release/net/ip.o build/release/net/ethernet.o build/release/net/arp.o build/release/net/native-stack.o build/release/net/ip_checksum.o build/release/net/udp.o build/release/net/tcp.o build/release/net/dhcp.o build/release/net/tls.o build/release/core/reactor.o build/release/core/systemwide_memory_barrier.o build/release/core/fstream.o build/release/core/posix.o build/release/core/memory.o build/release/core/resource.o build/release/core/scollectd.o build/release/core/metrics.o build/release/core/app-template.o build/release/core/thread.o build/release/core/dpdk_rte.o build/release/util/conversions.o build/release/util/log.o build/release/net/packet.o build/release/net/posix-stack.o build/release/net/net.o build/release/net/stack.o build/release/rpc/rpc.o build/release/rpc/lz4_compressor.o -laio -lboost_program_options -lboost_system -lboost_filesystem  -lm -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -llz4 -lprotobuf -ldl -lgcc_s -lunwind -static-libgcc -static-libstdc++ -lhwloc -lnuma -lpciaccess -lxml2 -lz
build/release/core/reactor.o：在函数‘operator()’中：
/home/bojue/seastar/seastar/core/reactor.cc:1872：对‘reactor::total_busy_time()’未定义的引用
collect2: 错误：ld 返回 1

code version is :b5c3ac03fd40765349b389b9d3e34897a18a271e

**Comment by tgrabiec** [comment]
@q96456 I've just pushed to master a fix which I think could be your problem, please retest.

**Comment by q96456** [comment]
It's ok.Thank you.
