### ISSUE TITLE
Build error "sys/sdt.h" not found on Ubuntu

### ISSUE THREAD

**Issue by cuongtv51** [scylladb/seastar#223]
i see file core/reactor.cc line 85 not have sys/sdt.h on Ubuntu

**Comment by avikivity** [comment]
Install `systemtap-std-dev`.

**Comment by nyh** [comment]
@avikivity do we really have to (or want to) make this dependency hard? Couldn't we discover in configure.py whether we have sdt.h, and only compile the STAP stuff when it exists, or make it a do-nothing macro when it doesn't? In C++17, there is even a `#if __has_include` (see http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0061r1.html).

**Comment by ahkok** [comment]
This is really an unwanted forced dependency. Ideally, this becomes optional instead and allows people deploying this to hard disable it in production.

**Comment by avikivity** [comment]
If you don't want the dependency, send a patch to make it original

**Comment by ahkok** [comment]
I'm already working on making cryptopp obsolete, but now I run into this dependency.

BTW, systemtap hard requires python2.................................................................

I am spinning in circles, and, this is starting to ruin my weekend.

**Comment by ahkok** [comment]
hmm, looks like there's a flag to configure it for py3.... well that's one problem solved.
