### ISSUE TITLE
create_scheduling_group / scheduling_group_key_create are not safe to run in parallel

### ISSUE THREAD

**Issue by piodul** [scylladb/seastar#2231]
I observed that running those two functions in parallel may lead to data of a scheduling group key initialized twice.

Those functions work like this:

- create_scheduling_group
	- Allocate a new SG ID
	- _Preemption may happen here_
	- On all shards:
		- Initialize storage for the SG
		- Read the current SG key count and store in `num_keys` variable
		- _Preemption may happen here_
		- Initialize SG keys for the new SG up to `num_keys`

- scheduling_group_key_create
	- Allocate a new SG key ID
	- _Preemption may happen here_
	- On all shards:
		- Initialize the SG key config
		- _Preemption may happen here_
		- For all current SGs, initialize the new SG key

While I am not exactly sure what the sequence of events for my case was, looking at the implementation I think the following can happen:

- [create_scheduling_group] allocates a new SG ID
- [scheduling_group_key_create] allocates a new SG key ID
- [create_scheduling_group] reads the SG key count and stores to `num_keys` var
- [scheduling_group_key_create] initializes storage for the new SG key
- [create_scheduling_group] initializes storage for the new SG
- [scheduling_group_key_create] initializes the new SG key for all existing SGs
- [create_scheduling_group] initializes the new SG and all existing SG keys for it, including the new one.

Perhaps there might be other kinds of races. I think that operations like `create_scheduling_group` and `scheduling_group_key_create` should be serialized.

Relevant code:

https://github.com/scylladb/seastar/blob/d3657ec70e934a1e747ed9e3e970bd8102648bf6/src/core/reactor.cc#L5016-L5030
https://github.com/scylladb/seastar/blob/d3657ec70e934a1e747ed9e3e970bd8102648bf6/src/core/reactor.cc#L4859-L4926

**Comment by avikivity** [comment]
Makes sense. These are not data plane operations so can safely be serialized.
