### ISSUE TITLE
[project unrelated] Question about solving __common_cmp_cat duplicate definition problem

### ISSUE THREAD

**Issue by neko-para** [scylladb/seastar#2234]
I've encountered the same problem that [this commit](https://github.com/scylladb/seastar/commit/131f637ac25583e79366ef716bf6812fd02bec6f) refered.
I've tried add `#include <compare>` ahead in my project, but it seems not work. @tchaikov Could you please share some extra information about how this could work? i.e. where exactly this header should been added to if multiple modules raise this problem.

---

The action is performed on archlinux with clang17.

I've tried with [this commit](https://github.com/MaaXYZ/MaaFramework/commit/00d31b9826ae01d149041648648c633ebcda72ae), but in [action](https://github.com/MaaXYZ/MaaFramework/actions/runs/9029928130/job/24813223768) it just failed as [previous one](https://github.com/MaaXYZ/MaaFramework/actions/runs/9029744079/job/24812681606).

**Comment by tchaikov** [comment]
@neko-para , i don't have enough bandwidth looking into your issue. actually, this FTBFS is still a mysterious to me.

but i think, C++20 modules support in Clang-17 is still not quite ready from production use. in addition to try out Clang-18, i'd also suggest to reduce your module implementation unit until the said problem disappears and then identify what you need to workaround this problem.

in the meanwhile, i am closing your issue. as you put, it is not quite relevant to Seastar.
