### ISSUE TITLE
io_uring reactor backend not available when importing and using seastar as a module

### ISSUE THREAD

**Issue by 0xca11** [scylladb/seastar#2249]
In [src/CMakeLists.txt](/scylladb/seastar/tree/master/src/CMakeLists.txt), the `SEASTAR_HAVE_URING` macro is never included in the `target_compile_definitions` for the `seastar-module`, and the `URING::uring` library is also never linked with `target_link_libraries`.

**Comment by tchaikov** [comment]
@0xca11 #2252 should address this issue. but please note, the C++20 module support is still experimental.
