### ISSUE TITLE
file dma_read method return bad address when offset = 0

### ISSUE THREAD

**Issue by liudong1983** [scylladb/seastar#229]
future<> test_dma_read1(file_holder *holder) {
    auto rbuf = allocate_aligned_buffer<unsigned char>(4096, 4096);
    return holder->_f.dma_read(0, rbuf.get(), 4096).then([holder, rbuf = std::move(rbuf)] (size_t ret) {
        std::cout << "block size=" << 4096 << "ret size=" << ret << std::endl;
        for (size_t i = 0; i < ret; ++i) {
            printf("%c", *(rbuf.get() + i));
        }
    }).then_wrapped([holder](auto&& fut) {
        try {
            fut.get();
        } catch (std::exception& e) {
            std::cout << "dma op fail, error:" << e.what() << std::endl;
        }
    });
}

we create a file on the ext4 system, and just echo some text to file,
when dma_read offset = 0, the code print following exception info:
error:Bad address
 
it's hard to understand..

**Comment by tgrabiec** [comment]
There is an issue in the code you pasted, which could be the cause. rbuf is moved in the same expression you call get() on it. If the move is ordered so that rbuf is moved before get(), then get() will return nullptr:

```
return holder->_f.dma_read(0, rbuf.get(), 4096).then([holder, rbuf = std::move(rbuf)] (size_t ret) {
```

**Comment by liudong1983** [comment]
you are right, i make the mistake..
thanks very much
