### ISSUE TITLE
[perftune.py]: clock source is not set correctly on AWS Nitro KVM VMs

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/seastar#2363]
HEAD: 643b3c6cd84d63aae5685366e885851510d13f6d
AWS instance type: i3en.12xl

## Description
Clock source is set to `tsc` instead of `kvm-clock` on new AWS Nitro based VMs.

The reason is because on these VMs `systemd-detect-virt` is going to return `amazon` instead of `kvm` (as perftune.py expects).

Ref https://www.freedesktop.org/software/systemd/man/latest/systemd-detect-virt.html
Ref https://repost.aws/knowledge-center/manage-ec2-linux-clock-source

**Comment by vladzcloudius** [comment]
cc @avikivity @mykaul @roydahan

**Comment by avikivity** [comment]
What about GCP? Supposedly returning "google".

We should override the clocksource when we know it's safe, not when we misdetect the platform.

**Comment by vladzcloudius** [comment]
> What about GCP? Supposedly returning "google".
> 

According to https://www.freedesktop.org/software/systemd/man/latest/systemd-detect-virt.html Google's VMs report a standard `kvm` - and we also know this is what it does.

> We should override the clocksource when we know it's safe, not when we misdetect the platform.

We do that. However we decide what clocksource to use according to what is the current platform. And we decide about that according to the output of `systemd-detect-virt`.

Up until now we assumed that KVM-based VMs are going to return `kvm` and it was the case.
It got broken with these new Nitro-based Amazon VMs.

**Comment by avikivity** [comment]
> > What about GCP? Supposedly returning "google".
> 
> According to https://www.freedesktop.org/software/systemd/man/latest/systemd-detect-virt.html Google's VMs report a standard `kvm` - and we also know this is what it does.

But that page says "google" for Google Compute Engine.


> 
> > We should override the clocksource when we know it's safe, not when we misdetect the platform.
> 
> We do that. However we decide what clocksource to use according to what is the current platform. And we decide about that according to the output of `systemd-detect-virt`.


```python
    def _get_arch(self):
        try:
            virt = run_read_only_command(['systemd-detect-virt']).strip()
            if virt == "kvm":
                return virt
        except:
            pass
        return platform.machine()
```
So it looks like we ignore anything that's not "kvm".


> 
> Up until now we assumed that KVM-based VMs are going to return `kvm` and it was the case. This assumption got broken with these new Nitro-based Amazon VMs.
> 
> We need to patch `perftune.py` to support this new "platform" - that's all.

**Comment by vladzcloudius** [comment]
> > > What about GCP? Supposedly returning "google".
> > 
> > 
> > According to https://www.freedesktop.org/software/systemd/man/latest/systemd-detect-virt.html Google's VMs report a standard `kvm` - and we also know this is what it does.
> 
> But that page says "google" for Google Compute Engine.

Oh, they "shifted" the result one column to the left.

Interesting. So far we never saw the Google VMs printing anything except for `kvm`:

```
$ systemd-detect-virt
kvm
```

> 
> > > We should override the clocksource when we know it's safe, not when we misdetect the platform.
> > 
> > 
> > We do that. However we decide what clocksource to use according to what is the current platform. And we decide about that according to the output of `systemd-detect-virt`.
> 
> ```python
>     def _get_arch(self):
>         try:
>             virt = run_read_only_command(['systemd-detect-virt']).strip()
>             if virt == "kvm":
>                 return virt
>         except:
>             pass
>         return platform.machine()
> ```
> 
> So it looks like we ignore anything that's not "kvm".

We special case only `kvm`. All others will go according to the `platform.machine()`.

> 
> > Up until now we assumed that KVM-based VMs are going to return `kvm` and it was the case. This assumption got broken with these new Nitro-based Amazon VMs.
> > We need to patch `perftune.py` to support this new "platform" - that's all.

**Comment by vladzcloudius** [comment]
@avikivity please, take a look at https://github.com/scylladb/seastar/pull/2364
