### ISSUE TITLE
Automatically log backtrace of long running tasks

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#237]
We could print backtrace to logs from preemption timer if it fires for the same task more than once.

This would help to identify certain causes of latency spikes. Refs scylladb/scylla#1634

**Comment by avikivity** [comment]
The preemption timer is now gone.  On the other hand, g_need_preempt got converted into a counter.  We can add an if () to see if it is < -large_number and log.  Won't be a backtrace, but a task type name.

**Comment by tgrabiec** [comment]
could we have a timer for this purpose then, but with a larger quota?

**Comment by tgrabiec** [comment]
I expect that task name alone may not be enough information.

**Comment by avikivity** [comment]
The timer thread could notice that counter < -large_value && !sleeping and pthread_kill(reactor_thread, SIGLOGBACKTRACE).

**Comment by tgrabiec** [comment]
Sounds good to me.

**Comment by tgrabiec** [comment]
Fixed by 1501f67c50b59309718cbad333b1a05aeaa2115c
