### ISSUE TITLE
Steal time constantly goes down

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#2374]
The formula is

```c++
    return std::chrono::duration_cast<std::chrono::nanoseconds>(now() - _start_time - _total_sleep) -
           std::chrono::duration_cast<std::chrono::nanoseconds>(thread_cputime_clock::now().time_since_epoch());
```

it does (time_point - time_point - duration) - time_point which it technically "time", but substracting time_point from duration shouldn't work

**Comment by xemul** [comment]
![image](https://github.com/user-attachments/assets/7aa8244f-f48b-4594-8544-1ee79cfb2f73)

**Comment by travisdowns** [comment]
I have a fox for this. Let me dig it up.
