### ISSUE TITLE
Are there any clang-related compilation options?

### ISSUE THREAD

**Issue by MalikHou** [scylladb/seastar#2378]
We prefer to use clang in production environments. So are there any compilation options related to clang?

**Comment by avikivity** [comment]
CMAKE_CXX_COMPILER=clang

**Comment by tchaikov** [comment]
better off using `clang++` instead, so depending on which tool you use:
```
configure.py --compiler clang++ ...
```

or 
```
cmake -DCMAKE_CXX_COMPILER=clang++
```

**Comment by tchaikov** [comment]
probably you can ask similar question in https://github.com/scylladb/seastar/discussions . we have a "Q&A" category out there.
