### ISSUE TITLE
Log CPU numbers assigned to shards

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#238]
Would help in figuring out which CPU number to pass to `perf -C` while knowing only the shard number exported via metrics.

Refs scylladb/scylla#2010

**Comment by avikivity** [comment]
Another option (perhaps do both) is to use `pthread_setname_np()` to set thread names.  Can be `prog-$shard` (for shard>0) and `$prog-shard-iothread` etc.

**Comment by tgrabiec** [comment]
Commit 762249f implemented thread naming.

**Comment by avikivity** [comment]
I think we can close. The logs would get rotated away and are thus less useful.
