### ISSUE TITLE
seastar::format doesn't accept std::string_view as its format string argument

### ISSUE THREAD

**Issue by dawmd** [scylladb/seastar#2389]
`fmt::format` allows for passing `std::string_view` as its format string argument, but `seastar::format` does not. `std::string_view` should be preferred as it's more generic.

**Comment by tchaikov** [comment]
i think #1727 should help.

**Comment by tchaikov** [comment]
#1727 has been merged. and i tested it with 
```c++
std::ignore = seastar::format(std::string_view("{}"), 42);
```

which compiles fine with fmtlib v10. so i am closing this issue. please reopen it if the issue is not resolved.
