### ISSUE TITLE
The future of OSv support

### ISSUE THREAD

**Issue by travisdowns** [scylladb/seastar#2392]
Will seastar continue to support OSv? 

Currently I believe this backend does not compile, e.g., this function:

```
void
reactor_backend_osv::wait_and_process_events(const sigset_t* sigset) {
    return process_events_nowait();
}
```

calls `process_events_nowait` which does not seem to exist. 

I ask in part because when making changes to reactor backends it is not clear if OSv should be included, and if it is I am not sure how to test or even compile those changes.

**Comment by nyh** [comment]
I don't think Seastar actually worked on OSv for many years now, as we started to use more and more Linux features that never worked on OSv. If there are any vestiges of OSv support in Seastar, we should probably remove them.

**Comment by travisdowns** [comment]
Thanks for the pointer @nyh , I will send a PR to remove OSv support and we can continue the discussion there.
