### ISSUE TITLE
Why seastar takes about 1% of CPU per core even there is no work to do

### ISSUE THREAD

**Issue by andy-yx-chen** [scylladb/seastar#2395]
To repro, just start an app like following
```c++
app.run(
        argc,
        argv,
        [&app]
        {
             return seastar::sleep(std::chrono::seconds(10000);
        };
```
A meaningful stack shown by perf is as below,
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/bd9c89d0-ec81-485d-bba4-419603385beb">

Can someone help me out?

**Comment by avikivity** [comment]
It's updating the low-resolution timer.
