### ISSUE TITLE
Compilation failed using the CMake method in the readme (without installation)

### ISSUE THREAD

**Issue by xuqing-er** [scylladb/seastar#2397]
I am new to seastar. I get the following error when I compile using the CMake method in the README, 
<img width="1910" alt="image" src="https://github.com/user-attachments/assets/3fd14e68-73dd-4b72-9492-e3b0e19657e2">

but it compiles correctly using pkg-config. 
<img width="859" alt="QQ20240822-103028@2x" src="https://github.com/user-attachments/assets/ffbd636e-b334-4dd5-85f7-424eaf01bd1e">

My application is a direct copy from demos/hello_world.c. 
<img width="371" alt="image" src="https://github.com/user-attachments/assets/f4f96fcf-8263-42aa-84f6-f7564e7471ee">

My CMakeLists is as follows. 
![image](https://github.com/user-attachments/assets/317e0acf-97eb-4943-85c0-b158430595b7)

Can anyone help me solve this problem? Thanks.

**Comment by tchaikov** [comment]
please paste in text not in pictures. so that other users it using search facilities.

**Comment by tchaikov** [comment]
anyway, i think it *might* be a dup of #2181. but i cannot tell as you didn't paste the building environment or more infor for further diagnostics.
