### ISSUE TITLE
Can we wait all futures produced inside seastar::async?

### ISSUE THREAD

**Issue by kononovk** [scylladb/seastar#2399]
In such case:
```cpp
seastar::async([]{
    with_timeout(sleep(10s), 5s).handle_ecxeption([] { /*ignore*/ }).get0();
})
```
we have a problem:
`sleep` produce some callback and allocates some sleep's state. Sleep's callback will be executed after 10s, but timeout is 5s, so we will exit `async` function and will have memory leak. Does seastar have some primitives to wait all futures produced inside `seastar::async`?

For example, if we have control over thread pool we can write such code:
```cpp
async(thread_pool, [] { 
    with_timeout(sleep(10s), 5s).handle_ecxeption([] { /*ignore*/ }).get0();
    thread_pool::current()->wait();
}
```

**Comment by avikivity** [comment]
No such thing exists. with_timeout() is a bad API for this very reason. It's better to use abort_source or condition_variable to actively cancel your long-running tasks rather than orphan them with with_timeout().
