### ISSUE TITLE
(Why not) write from multiple shards into the same file?

### ISSUE THREAD

**Issue by niekbouman** [scylladb/seastar#2469]
The documentation of Seastar's `file` api suggests that writing from multiple shards to the same file simultaneously is not supported, at least not through the `dup` mechanism:

> `seastar::file::dup()`
> ...
>Note
> Use on read-only files.
> 

Assuming that we would ensure that there is enough space in the file (by pre-allocating space), and by ensuring that each shard performs aligned writes in non-overlapping regions,
then is this actually supported by the OS (for the async-IO_DIRECT mode that Seastar uses)?

In case if it would be supported by the OS, then why not by Seastar's file api?

**Comment by avikivity** [comment]
It should work. Note performance on large machines may be bad.
