### ISSUE TITLE
seastar-addr2line appears broken in Scylla images

### ISSUE THREAD

**Issue by PhipBlitch-Arcadia** [scylladb/seastar#2487]
Trying to run seastar-addr2line to [decode a traceback in logs](https://opensource.docs.scylladb.com/branch-6.0/kb/decode-stack-trace.html), It fails to find an `addr2line` module.

This is with the `scylla-server-dbg` package installed.
Tested on 6.0.3 docker image, 6.0.3 AMI, and 6.0.4 AMI (all x86_64).

```
$ /opt/scylladb/scripts/seastar-addr2line
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/seastar-addr2line", line 26, in <module>
    from addr2line import BacktraceResolver
ModuleNotFoundError: No module named 'addr2line'
```

**Comment by tchaikov** [comment]
@PhipBlitch-Arcadia hi Phip, thank you for reporting this issue. but i think it is an issue of scylladb. so i created https://github.com/scylladb/scylladb/issues/21077 instead.
