### ISSUE TITLE
c-ares version support

### ISSUE THREAD

**Issue by travisdowns** [scylladb/seastar#2496]
What version of c-ares is needed to build sesatar?

Currently I can't build seastar at the tip of master because I have 1.18 (distro installed, 22.04 ubuntu) with the following error:

```
akeFiles/seastar-objects.dir/src/net/dns.cc.o -c /home/tdowns/dev/seastar/src/net/dns.cc
/home/tdowns/dev/seastar/src/net/dns.cc:269:5: error: ‘ares_channel_t’ does not name a type; did you mean ‘ares_channel’?
  269 |     ares_channel_t* _channel;
      |     ^~~~~~~~~~~~~~
      |     ares_channel
```

When I `./configure --cook c-ares` it tries to download 1.13:

```
-- Downloading...
   dst='/home/tdowns/dev/seastar/build/release/_cooking/ingredient/c-ares/src/c-ares-1.13.0.tar.gz'
```

Which seems to fail (404) but also wouldn't work because it's too old.

**Comment by travisdowns** [comment]
Here's a PR that might resolving the cooked side of things, cc @tchaikov :

https://github.com/scylladb/seastar/pull/2497

**Comment by p12tic** [comment]
This PR https://github.com/scylladb/seastar/pull/2493 should have fixed the problem on seastar side

**Comment by travisdowns** [comment]
Thanks @p12tic , it works for me, so closing this.
