### ISSUE TITLE
Cross-sharded inheritance of scheduling group

### ISSUE THREAD

**Issue by cppden** [scylladb/seastar#2518]
From the code it's clear how current scheduling group is inherited for new tasks spawned by a task on current shard. But it seems the current scheduling group is lost when coroutine is invoked on another shard.
Is it so or am I missing something?
Thank you very much in advance!

**Comment by avikivity** [comment]
Why is it lost?

**Comment by cppden** [comment]
Task is passed between shards via one _qs queue and then finally executed in target shard in default scheduling group. But maybe I just could not follow the code properly. I am sorry if so. Can you please give me a hint where the scheduling group is restored?

**Comment by avikivity** [comment]
smp_message_queue::work_item, see task's initializer

**Comment by cppden** [comment]
❤️ Thanks a lot!
