### ISSUE TITLE
ninja-build failed on Cent-OS 7.3

### ISSUE THREAD

**Issue by gubadi** [scylladb/seastar#252]
![image](https://cloud.githubusercontent.com/assets/25256502/23241645/0f8ab5fa-f929-11e6-9a53-03b921fe3885.png)

**Comment by dorlaor** [comment]
You need to run ./configure.py --disable-xen
It may not be the only thing that you'll need to change.
Pekka, would you mind to go through the install readme and update it for
newbies ?

**Comment by gubadi** [comment]
[dorlaor], it is still failing with same error. Please let me know what other things need to change. Here is some building log
=====
./core/future.hh: In instantiation of ‘struct future_state<rpc::rcv_buf>’:
./core/future.hh:670:24:   required from ‘class future<rpc::rcv_buf>’
rpc/rpc_impl.hh:723:51:   required from here
./core/future.hh:123:5: error: static assertion failed: Types must be no-throw move constructible
     static_assert(std::is_nothrow_move_constructible<std::tuple<T...>>::value,
---
---
--
./core/future.hh:856:5: note:   template argument deduction/substitution failed:
./core/future.hh:854:30: error: no type named ‘type’ in ‘class std::result_of<rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable::<lambda()> mutable [with Serializer = serializer; MsgType = unsigned int]::<lambda(std::experimental::fundamentals_v1::optional<long unsigned int>, unsigned int, int64_t, std::experimental::fundamentals_v1::optional<rpc::rcv_buf>)>(std::experimental::fundamentals_v1::optional<long unsigned int>&&, unsigned int&&, long int&&, std::experimental::fundamentals_v1::optional<rpc::rcv_buf>&&)>’
     template <typename Func, typename Result = futurize_t<std::result_of_t<Func(T&&...)>>>
                              ^
In file included from ./rpc/rpc.hh:557:0,
                 from tests/rpc.cc:24:
./rpc/rpc_impl.hh: In instantiation of ‘future<> rpc::protocol<Serializer, MsgType>::server::connection::process() [with Serializer = serializer; MsgType = unsigned int]’:
./rpc/rpc_impl.hh:611:13:   required from ‘rpc::protocol<Serializer, MsgType>::server::accept()::<lambda()> mutable::<lambda(connected_socket, socket_address)> mutable [with Serializer = serializer; MsgType = unsigned int]’
./rpc/rpc_impl.hh:607:35:   required from ‘struct rpc::protocol<Serializer, MsgType>::server::accept()::<lambda()> mutable [with Serializer = serializer; MsgType = unsigned int]::<lambda(class connected_socket, class socket_address)>’
./rpc/rpc_impl.hh:613:5:   required from ‘rpc::protocol<Serializer, MsgType>::server::accept()::<lambda()> mutable [with Serializer = serializer; MsgType = unsigned int]’
./rpc/rpc_impl.hh:606:17:   required from ‘struct rpc::protocol<Serializer, MsgType>::server::accept() [with Serializer = serializer; MsgType = unsigned int]::<lambda()>’
./rpc/rpc_impl.hh:606:15:   required from ‘void rpc::protocol<Serializer, MsgType>::server::accept() [with Serializer = serializer; MsgType = unsigned int]’
./rpc/rpc_impl.hh:596:11:   required from ‘rpc::protocol<Serializer, MsgType>::server::server(rpc::protocol<Serializer, MsgType>&, server_socket, rpc::resource_limits, rpc::server_options) [with Serializer = serializer; MsgType = unsigned int]’
./rpc/rpc_impl.hh:589:78:   required from ‘rpc::protocol<Serializer, MsgType>::server::server(rpc::protocol<Serializer, MsgType>&, rpc::server_options, ipv4_addr, rpc::resource_limits) [with Serializer = serializer; MsgType = unsigned int]’
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/unique_ptr.h:765:69:   required from ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = rpc::protocol<serializer>::server; _Args = {rpc::protocol<serializer, unsigned int>&, rpc::server_options&, ipv4_addr, rpc::resource_limits&}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<rpc::protocol<serializer>::server>]’
tests/rpc.cc:282:108:   required from here
./rpc/rpc_impl.hh:992:6: error: no matching function for call to ‘future<>::then_wrapped(rpc::protocol<Serializer, MsgType>::server::connection::process() [with Serializer = serializer; MsgType = unsigned int]::<lambda(future<>)>)’
     });
      ^
In file included from ./core/seastar.hh:45:0,
                 from ./core/reactor.hh:25,
                 from tests/rpc.cc:22:
./core/future.hh:902:5: note: candidate: template<class Func, class Result> Result future<T>::then_wrapped(Func&&) [with Func = Func; Result = Result; T = {}]
     then_wrapped(Func&& func) noexcept {
     ^
./core/future.hh:902:5: note:   template argument deduction/substitution failed:
./core/future.hh:900:30: error: no type named ‘type’ in ‘class std::result_of<rpc::protocol<Serializer, MsgType>::server::connection::process() [with Serializer = serializer; MsgType = unsigned int]::<lambda(future<>)>(future<>)>’
     template <typename Func, typename Result = futurize_t<std::result_of_t<Func(future)>>>

	      typedef typename boost::detail::iterator_traits<Iterator>::reference type;
                                                                          ^
In file included from ./core/iostream-impl.hh:26:0,
                 from ./core/iostream.hh:227,
                 from ./core/reactor.hh:26,
                 from tests/rpc.cc:22:
./core/future-util.hh:316:10: error: ‘future<> do_until(StopCondition&&, AsyncAction&&) [with AsyncAction = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = serializer; MsgType = unsigned int]::<lambda()>; StopCondition = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = serializer; MsgType = unsigned int]::<lambda()>]’, declared using local type ‘rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = serializer; MsgType = unsigned int]::<lambda()>’, is used but never defined [-fpermissive]
 future<> do_until(StopCondition&& stop_cond, AsyncAction&& action) {
          ^
In file included from ./core/seastar.hh:45:0,
                 from ./core/reactor.hh:25,
                 from tests/rpc.cc:22:
./core/future.hh:856:5: error: ‘Result future<T>::then(Func&&) [with Func = rpc::protocol<Serializer, MsgType>::server::connection::process() [with Serializer = serializer; MsgType = unsigned int]::<lambda()>; Result = future<>; T = {}]’, declared using local type ‘rpc::protocol<Serializer, MsgType>::server::connection::process() [with Serializer = serializer; MsgType = unsigned int]::<lambda()>’, is used but never defined [-fpermissive]
     then(Func&& func) noexcept {
     ^
[65/324] mkdir -p build/release/c-ares && cd build/release/c-ares && cmake -DCARES_STATIC=ON -DCARES_SHARED=OFF -DCMAKE_BUILD_TYPE=Release /opt/seastar/seastar/c-ares
-- The C compiler identification is GNU 5.3.1
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Looking for res_servicename in resolv
-- Looking for res_servicename in resolv - not found
-- Looking for gethostbyname in nsl
-- Looking for gethostbyname in nsl - found
-- Looking for gethostbyname in socket
-- Looking for gethostbyname in socket - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for include file sys/types.h
-- Looking for include file sys/type
--
--
---
 Looking for strnicmp
-- Looking for strnicmp - not found
-- Looking for writev
-- Looking for writev - found
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/seastar/seastar/build/debug/c-ares
[81/324] CXX build/release/apps/memcached/memcache.o
ninja: build stopped: subcommand failed.

**Comment by tgrabiec** [comment]
@gubadi Looks like you ran into #207, that's about too old version of boost library. We require at least libboost1.55

**Comment by gubadi** [comment]
@tgrabiec It seems i am able to build seastar after i upgraded libboost to 1.63.  But when i ran test.py all the test are failing with following error. I have downloaded source code of libboost-1.63 and compiled and installed using ./bootstrap.sh and ./b2 install. As test.py is failing because of "libboost_program_options.so.1.63.0" library i have manually copied it from the location where i built libboost-1.63 to /user/local/lib/ but it did not help. any clue? 

another question is how do i confirm that seasta is ready to use? like i am able to build using ninja-build without error but test.py is failing so not sure how to confirm

=================
root@sjcenga7st16 seastar]# ./test.py 
FAILED: build/debug/tests/smp_test       
  with error code 127              
=== stdout START ===
=== stdout END ===
=== stderr START ===
build/debug/tests/smp_test: error while loading shared libraries: libboost_program_options.so.1.63.0: cannot open shared object file: No such file or directory

=== stderr END ===
FAILED: build/debug/tests/timertest       
  with error code 127               
=== stdout START ===
=== stdout END ===
=== stderr START ===
build/debug/tests/timertest: error while loading shared libraries: libboost_program_options.so.1.63.0: cannot open shared object file: No such file or directory

**Comment by tgrabiec** [comment]
Looks like the linker is not able to find the library. Is the directory you copied to on your link path? If you're using defaults, then instead of `/user/local/lib/`, it should be `/usr/local/lib/`.

**Comment by nyh** [comment]
I think this issue should be closed: the originally reported problem was just configure.py failing because it was given a non-existent compiler. The other issues were because of too old libraries or incorrect installation of new libraries. 
It would be nice if configure.py could recognize libraries or compilers which are too old and warn about them, but if we want this, we should open a new issue for that.
