### ISSUE TITLE
iotune don't properly support EC2's i3.16xlarge instances

### ISSUE THREAD

**Issue by glommer** [scylladb/seastar#253]
EC2 advertises 3.3M IOPS, and we didn't get anywhere close to that. Here's one example output:

```
Generating evaluation file sized 10GB...10GB written in 2 seconds
Refining search for maximum. So far, 477592 IOPS
Maximum throughput: 477592 IOPS
IOtune timed out before it could finish. An estimate will be provided but accuracy may suffer
Recommended --max-io-requests: 1140
```

i3's have 8 NVMes that this setup is putting in RAID0 mode.

**Comment by avikivity** [comment]
Are you sure you need >1140 iodepth to reach maximum throughput?  It's almost impossible to have the application drive such concurrency.  There must be some other bottleneck here.

**Comment by glommer** [comment]
No, I am not. As a matter of fact, that's why I opened this bug =)

In general iotune performed really poorly in i3 boxes. The displorer graph in the beginning looks really ugly as well. AWS claims that those boxes would need kernel >= 4.4 to achieve peak ops, and CentOS is much older than that.

In general we'll need to make sure that we can achieve good estimates there. That will likely be a combination of getting the right kernel into the AMI + some work. Right now I am just opening this here so we can track.

**Comment by slivne** [comment]
Can we run diskplorer on AWS Linux AMI and see what we get.

**Comment by glommer** [comment]
Old issue, iotune was since then rewritten from scratch
