### ISSUE TITLE
support multiple I/O Queues

### ISSUE THREAD

**Issue by glommer** [scylladb/seastar#255]
There are scenarios in which more than one storage array is used in a system. For instance, we can have a fast storage for hot data, and a slow storage for cold data.

With a single I/O Scheduler instance, the results can be suboptimal. We should support more than one so each array gets its own scheduler.

**Comment by slivne** [comment]
@glommer - this is already true for the case you are introducing with
commitlog storage on ephemeral and data storage on ebs.

**Comment by glommer** [comment]
That's precisely why I opened this bug.
