### ISSUE TITLE
socket_address compares ipv6 addresses incorrectly

### ISSUE THREAD

**Issue by SlowTurtlesEscape** [scylladb/seastar#2566]
Comparision of addresses like
socket_address addr1(ipv6_addr("::1"));
socket_address addr2(ipv6_addr("::2"));
is false positive.

Problem is in last line of operator== of socket_address.
IN6_ARE_ADDR_EQUAL macro should compare in6_addr structures, while passed types are of sockaddr_in6.

**Comment by dawmd** [comment]
scylladb/seastar#2567 has been merged, so this can be closed

**Comment by dawmd** [comment]
scylladb/seastar#2567 has been merged, so this can be closed
