### ISSUE TITLE
Configuring fail on Ubuntu 16.04

### ISSUE THREAD

**Issue by devlo** [scylladb/seastar#259]
hey i have trouble running ./configure script:

./configure.py --compiler=g++-5 --enable-dpdk --disable-xen

make: Entering directory '/home/dd/seastar/dpdk'
Configuration done
make: Leaving directory '/home/dd/seastar/dpdk'
Traceback (most recent call last):
  File "./configure.py", line 587, in <module>
    sanitize_flags = sanitize_vptr_flag(args.cxx)
  File "./configure.py", line 148, in sanitize_vptr_flag
    '''))
  File "./configure.py", line 111, in try_compile_and_run
    return subprocess.call([xfile.name], stdout = subprocess.DEVNULL, stderr = subprocess.DEVNULL, env=env) == 0
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

**Comment by avikivity** [comment]
What happens if your type

    g++-5 --version

on your terminal?

**Comment by devlo** [comment]
g++-5 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


It's fresh installation of ubuntu, the only thing that was run on it was installing seastar dependencies

**Comment by avikivity** [comment]
So I wonder what's the cause.  Try running

    strace -fF -o /tmp/trace python3 ./configure.py --compiler g++-5

and look for the last `EPERM` in /tmp/trace.

**Comment by devlo** [comment]
can't find exactly EPERM in trace

But I see a lot of permissions errors (EACCESS etc)

here is whole trace: http://pasted.co/a1df9533

**Comment by avikivity** [comment]
Is your /tmp mounted in a way that prevents running executables from it?

**Comment by devlo** [comment]
Yes, I just tested and can't run test script from /tmp

**Comment by devlo** [comment]
Should I remove noexec on /tmp or there is  some workaround to set other temporary directory ?

**Comment by avikivity** [comment]
There is no way currently.  Keep this issue open, and we'll change ./configure.py not to execute from /tmp.
