### ISSUE TITLE
Using seastar in a CMake projects

### ISSUE THREAD

**Issue by thongpv3** [scylladb/seastar#264]
I wrote this CMakeLists to use seastar in my project.

```
execute_process(COMMAND ./configure.py WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
execute_process(COMMAND ninja -C ${CMAKE_CURRENT_SOURCE_DIR})
#todo move seastar build directory into cmake build directory


set(SEASTAR_LIB_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/build)
if (CMAKE_BUILD_TYPE MATCHES RELEASE)
set(SEASTAR_LIB_LOCATION ${SEASTAR_LIB_LOCATION}/release)
else ()
set(SEASTAR_LIB_LOCATION ${SEASTAR_LIB_LOCATION}/debug)
endif ()
find_package(PkgConfig REQUIRED)
execute_process(COMMAND pkg-config --cflags --libs ${SEASTAR_LIB_LOCATION}/seastar.pc OUTPUT_VARIABLE SEASTAR_LIB)
string(STRIP "${SEASTAR_LIB}" SEASTAR_LIB) #remove trail while space
#string(REPLACE " -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr " " " SEASTAR_LIB ${SEASTAR_LIB})
message(STATUS ${SEASTAR_LIB})
#add library
add_library(seastar INTERFACE)
target_link_libraries(seastar INTERFACE ${SEASTAR_LIB})
```

But build folder of seastar still in source directory. I want to modified configure.py to move seastar's build folder into my CMake's build folder. How I can do it.

Sorry for my bad English.

**Comment by senior7515** [comment]
i use cmake here: 

https://github.com/senior7515/smf/blob/master/CMake/Seastar.cmake#L1

Feel free to copy paste, it's apache2 the project.

**Comment by hakuch** [comment]
Once #313 is resolved, then using Seastar in a CMake project should be considerably easier. Experimental support for CMake may be present in the tree prior to it replacing the current build system and prior to it being officially supported.
