### ISSUE TITLE
Ninja build failed out of the box

### ISSUE THREAD

**Issue by nirhenn** [scylladb/seastar#266]
Hi There,

Trying to build seastar out of the box and it fails.

Using Ubuntu 14.04
    8  git clone https://github.com/scylladb/seastar.git
    9  cd seastar/
   10  ls
   11  ./install-dependencies.sh 
   12  ./configure.py --compiler=g++-5
   13  git submodule update --init
   14  ./configure.py --compiler=g++-5
   15  ninja
   16  apt-get install cmake
   17  ninja
root@seastar:/var/soft/seastar# ninja
[6/302] CXX build/debug/rpc/rpc.o
FAILED: g++-5 -MD -MT build/debug/rpc/rpc.o -MF build/debug/rpc/rpc.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DASAN_ENABLED -O0 -DDEBUG -DDEBUG_SHARED_PTR -DDEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -I build/debug/gen -I build/debug/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error-deprecated -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -Ifmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -c -o build/debug/rpc/rpc.o rpc/rpc.cc
In file included from rpc/rpc.hh:27:0,
                 from rpc/rpc.cc:1:
./core/future.hh: In instantiation of ‘struct future_state<rpc::rcv_buf>’:
./core/future.hh:696:24:   required from ‘class future<rpc::rcv_buf>’
rpc/rpc_impl.hh:723:51:   required from here
./core/future.hh:123:5: error: static assertion failed: Types must be no-throw move constructible
     static_assert(std::is_nothrow_move_constructible<std::tuple<T...>>::value,
     ^
./core/future.hh: In instantiation of ‘struct future_state<long int, std::experimental::fundamentals_v1::optional<rpc::rcv_buf> >’:
./core/future.hh:696:24:   required from ‘class future<long int, std::experimental::fundamentals_v1::optional<rpc::rcv_buf> >’
rpc/rpc_impl.hh:1014:86:   required from here
./core/future.hh:123:5: error: static assertion failed: Types must be no-throw move constructible
cc1plus: error: unrecognized command line option ‘-Wno-error-deprecated’ [-Werror]
cc1plus: all warnings being treated as errors
[6/302] CXX build/debug/tests/circular_buffer_test.o
ninja: build stopped: subcommand failed.

**Comment by gleb-cloudius** [comment]
This is the same as https://github.com/scylladb/seastar/issues/207

--
			Gleb.

**Comment by avikivity** [comment]
Duplicate, closing.
