### ISSUE TITLE
bool_class doesn't build on clang/zapcc

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#268]
bool_class::yes doesn't compile, because clang considers bool_class an incomplete type at the time it sees it, and therefore refuses to consider it a LiteralType.  g++ says the same thing if we make it a non-template, suggesting it accepted it only accidentally.

Converting yes and no to functions works on both compilers, but breaks backward compatibility.  We could make yes and no instances of another template, literal_base<Tag>, that is implicitly convertible to literal<Tag>, but that may still not be compatible enough.

**Comment by pdziepak** [comment]
I think we could have `internal::bool_class_helper` which would have all members of the current `bool_class` except for `yes` and `no`. Then, `bool_class` could derive from the `internal::bool_class_helper` and also use that type to define `yes` and `no` with appropriate implicit casts between the helper and the actual `bool_class` I believe this should work without breaking compatibility.
I will check and send a patch if this works.

**Comment by pdziepak** [comment]
...or we could just switch `yes` and `no` to be const instead of consexpr. `bool_class` cannot be used as non-type template parameter anyway.
