### ISSUE TITLE
build failed on ubuntu14

### ISSUE THREAD

**Issue by mytliulei** [scylladb/seastar#276]
CXX build/release/tests/scollectd_test.o
FAILED: g++ -MD -MT build/release/tests/scollectd_test.o -MF build/release/tests/scollectd_test.o.d -O2 -I build/release/gen -I build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -DHAVE_DPDK -I/home/test/seastar/seastar/build/dpdk/include -march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_MACHINE_CPUFLAG_PCLMULQDQ -DRTE_MACHINE_CPUFLAG_RDRAND -DRTE_MACHINE_CPUFLAG_FSGSBASE -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -Ifmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -c -o build/release/tests/scollectd_test.o tests/scollectd_test.cc
tests/scollectd_test.cc: In member function ‘virtual future<> test_bind_callable_raw::run_test_case()’:
tests/scollectd_test.cc:124:94: warning: ‘scollectd::type_instance_id scollectd::add_polled_metric(const scollectd::type_instance_id&, Arg&&) [with Arg = scollectd::typed<test_bind_callable_raw::run_test_case()::<lambda()>&>]’ is deprecated (declared at ./core/scollectd.hh:805): Use the metrics layer [-Wdeprecated-declarations]
     scollectd::registration r = add_polled_metric(id, make_typed(data_type::DERIVE, callable));
                                                                                              ^
In file included from tests/scollectd_test.cc:32:0:
./core/scollectd.hh: In instantiation of ‘scollectd::type_instance_id scollectd::add_polled_metric(const scollectd::type_instance_id&, Arg&&) [with Arg = scollectd::typed<test_bind_callable_raw::run_test_case()::<lambda()>&>]’:
tests/scollectd_test.cc:124:94:   required from here
./core/scollectd.hh:807:81: warning: ‘scollectd::type_instance_id scollectd::add_polled_metric(const scollectd::type_instance_id&, scollectd::description, Arg&&, bool) [with Arg = scollectd::typed<test_bind_callable_raw::run_test_case()::<lambda()>&>; scollectd::description = seastar::metrics::description]’ is deprecated (declared at ./core/scollectd.hh:792): Use the metrics layer [-Wdeprecated-declarations]
     return std::move(add_polled_metric(id, description(), std::forward<Arg>(arg)));
                                                                                 ^
In file included from ./core/future-util.hh:30:0,
                 from ./core/iostream-impl.hh:26,
                 from ./core/iostream.hh:227,
                 from ./core/reactor.hh:26,
                 from tests/scollectd_test.cc:27:
./core/shared_ptr.hh: In instantiation of ‘shared_ptr_count_for<T>::shared_ptr_count_for(A&& ...) [with A = {seastar::metrics::impl::data_type&, std::function<seastar::metrics::impl::metric_value()>, seastar::metrics::description&, bool&}; T = seastar::metrics::impl::registered_metric]’:
./core/shared_ptr.hh:492:80:   required from ‘static shared_ptr<T> shared_ptr_make_helper<T, false>::make(A&& ...) [with A = {seastar::metrics::impl::data_type&, std::function<seastar::metrics::impl::metric_value()>, seastar::metrics::description&, bool&}; T = seastar::metrics::impl::registered_metric]’
./core/shared_ptr.hh:510:46:   required from ‘shared_ptr<T> make_shared(A&& ...) [with T = seastar::metrics::impl::registered_metric; A = {seastar::metrics::impl::data_type&, std::function<seastar::metrics::impl::metric_value()>, seastar::metrics::description&, bool&}]’
./core/scollectd.hh:796:114:   required from ‘scollectd::type_instance_id scollectd::add_polled_metric(const scollectd::type_instance_id&, scollectd::description, Arg&&, bool) [with Arg = scollectd::typed<test_bind_callable_raw::run_test_case()::<lambda()>&>; scollectd::description = seastar::metrics::description]’
./core/scollectd.hh:807:81:   required from ‘scollectd::type_instance_id scollectd::add_polled_metric(const scollectd::type_instance_id&, Arg&&) [with Arg = scollectd::typed<test_bind_callable_raw::run_test_case()::<lambda()>&>]’
tests/scollectd_test.cc:124:94:   required from here
./core/shared_ptr.hh:329:64: error: no matching function for call to ‘seastar::metrics::impl::registered_metric::registered_metric(seastar::metrics::impl::data_type&, std::function<seastar::metrics::impl::metric_value()>, seastar::metrics::description&, bool&)’
     shared_ptr_count_for(A&&... a) : data(std::forward<A>(a)...) {}
                                                                ^
./core/shared_ptr.hh:329:64: note: candidates are:
In file included from ./core/scollectd.hh:44:0,
                 from tests/scollectd_test.cc:32:
./core/metrics_api.hh:172:5: note: seastar::metrics::impl::registered_metric::registered_metric(seastar::metrics::impl::metric_id, seastar::metrics::impl::data_type, seastar::metrics::impl::metric_function, seastar::metrics::description, bool)
     registered_metric(metric_id id, data_type type, metric_function f, description d = description(), bool enabled=true);
     ^
./core/metrics_api.hh:172:5: note:   no known conversion for argument 1 from ‘seastar::metrics::impl::data_type’ to ‘seastar::metrics::impl::metric_id’
./core/metrics_api.hh:164:7: note: seastar::metrics::impl::registered_metric::registered_metric(const seastar::metrics::impl::registered_metric&)
 class registered_metric {
       ^
./core/metrics_api.hh:164:7: note:   candidate expects 1 argument, 4 provided
[57/312] CXX build/release/tests/futures_test.o
ninja: build stopped: subcommand failed.

**Comment by yangsiran** [comment]
Building on CentOS7 has the similar problem.
```
FAILED: /opt/scylladb/bin/g++ -MD -MT build/release/tests/scollectd_test.o -MF build/release/tests/scollectd_test.o.d -O2 -I build/release/gen -I build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -Ifmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DNO_EXCEPTION_INTERCEPT -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/tests/scollectd_test.o tests/scollectd_test.cc
tests/scollectd_test.cc: In member function ‘virtual future<> test_bind_callable_raw::run_test_case()’:
tests/scollectd_test.cc:124:94: warning: ‘scollectd::type_instance_id scollectd::add_polled_metric(const scollectd::type_instance_id&, Arg&&) [with Arg = scollectd::typed<test_bind_callable_raw::run_test_case()::<lambda()>&>]’ is deprecated: Use the metrics layer [-Wdeprecated-declarations]
     scollectd::registration r = add_polled_metric(id, make_typed(data_type::DERIVE, callable));
                                                                                              ^
In file included from tests/scollectd_test.cc:32:0:
./core/scollectd.hh:805:65: note: declared here
 [[deprecated("Use the metrics layer")]] static type_instance_id add_polled_metric(const type_instance_id & id,
                                                                 ^
./core/scollectd.hh: In instantiation of ‘scollectd::type_instance_id scollectd::add_polled_metric(const scollectd::type_instance_id&, Arg&&) [with Arg = scollectd::typed<test_bind_callable_raw::run_test_case()::<lambda()>&>]’:
tests/scollectd_test.cc:124:94:   required from here
./core/scollectd.hh:807:39: warning: ‘scollectd::type_instance_id scollectd::add_polled_metric(const scollectd::type_instance_id&, scollectd::description, Arg&&, bool) [with Arg = scollectd::typed<test_bind_callable_raw::run_test_case()::<lambda()>&>; scollectd::description = seastar::metrics::description]’ is deprecated: Use the metrics layer [-Wdeprecated-declarations]
     return std::move(add_polled_metric(id, description(), std::forward<Arg>(arg)));
                                       ^
./core/scollectd.hh:792:65: note: declared here
 [[deprecated("Use the metrics layer")]] static type_instance_id add_polled_metric(const type_instance_id & id, description d,
                                                                 ^
In file included from ./core/future-util.hh:30:0,
                 from ./core/iostream-impl.hh:26,
                 from ./core/iostream.hh:227,
                 from ./core/reactor.hh:26,
                 from tests/scollectd_test.cc:27:
./core/shared_ptr.hh: In instantiation of ‘shared_ptr_count_for<T>::shared_ptr_count_for(A&& ...) [with A = {seastar::metrics::impl::data_type&, std::function<seastar::metrics::impl::metric_value()>, seastar::metrics::description&, bool&}; T = seastar::metrics::impl::registered_metric]’:
./core/shared_ptr.hh:492:80:   required from ‘static shared_ptr<T> shared_ptr_make_helper<T, false>::make(A&& ...) [with A = {seastar::metrics::impl::data_type&, std::function<seastar::metrics::impl::metric_value()>, seastar::metrics::description&, bool&}; T = seastar::metrics::impl::registered_metric]’
./core/shared_ptr.hh:510:24:   required from ‘shared_ptr<T> make_shared(A&& ...) [with T = seastar::metrics::impl::registered_metric; A = {seastar::metrics::impl::data_type&, std::function<seastar::metrics::impl::metric_value()>, seastar::metrics::description&, bool&}]’
./core/scollectd.hh:796:53:   required from ‘scollectd::type_instance_id scollectd::add_polled_metric(const scollectd::type_instance_id&, scollectd::description, Arg&&, bool) [with Arg = scollectd::typed<test_bind_callable_raw::run_test_case()::<lambda()>&>; scollectd::description = seastar::metrics::description]’
./core/scollectd.hh:807:39:   required from ‘scollectd::type_instance_id scollectd::add_polled_metric(const scollectd::type_instance_id&, Arg&&) [with Arg = scollectd::typed<test_bind_callable_raw::run_test_case()::<lambda()>&>]’
tests/scollectd_test.cc:124:94:   required from here
./core/shared_ptr.hh:329:64: error: no matching function for call to ‘seastar::metrics::impl::registered_metric::registered_metric(seastar::metrics::impl::data_type&, std::function<seastar::metrics::impl::metric_value()>, seastar::metrics::description&, bool&)’
     shared_ptr_count_for(A&&... a) : data(std::forward<A>(a)...) {}
                                                                ^
In file included from ./core/scollectd.hh:44:0,
                 from tests/scollectd_test.cc:32:
./core/metrics_api.hh:172:5: note: candidate: seastar::metrics::impl::registered_metric::registered_metric(seastar::metrics::impl::metric_id, seastar::metrics::impl::data_type, seastar::metrics::impl::metric_function, seastar::metrics::description, bool)
     registered_metric(metric_id id, data_type type, metric_function f, description d = description(), bool enabled=true);
     ^
./core/metrics_api.hh:172:5: note:   no known conversion for argument 1 from ‘seastar::metrics::impl::data_type’ to ‘seastar::metrics::impl::metric_id’
./core/metrics_api.hh:164:7: note: candidate: seastar::metrics::impl::registered_metric::registered_metric(const seastar::metrics::impl::registered_metric&)
 class registered_metric {
       ^
./core/metrics_api.hh:164:7: note:   candidate expects 1 argument, 4 provided
```

**Comment by EricYT** [comment]
same problems

**Comment by leightonbao** [comment]
me too.
