### ISSUE TITLE
why don't we realease a stable version? can we use seastar in the production enviroment?

### ISSUE THREAD

**Issue by liudong1983** [scylladb/seastar#279]
1. why don't we release a stable version?
until now,  there are't stable release, do you have concrete plan to release?

2. can we use seastar in production enviroment?
our company plan to use seastar in the production enviroment, 
in the very important system,but now, there aren't stable release, 
do you recommend to do that?  which version do you recommend to use?

**Comment by avikivity** [comment]
There are two aspects of stability:

 1. Correctness - delivering correct results and not crashing
 2. API stability - avoiding breaking changes in the API that require application code changes

Seastar is quite mature in the correctness aspect and is used in production for more than a year.  However, the API still changes.  See this [discussion](https://groups.google.com/d/topic/seastar-dev/7WLkD_aIIvA/discussion), and of course please share your views there.

With that in mind, the best way to consume seastar for production use is to create a clone ("fork" on github) and use a submodule to track the version in use.  You can then update seastar on your own schedule, or you can make private bug fixes if you need to.  ScyllaDB uses the same technique, with the [scylla-seastar](https://github.com/scylladb/scylla-seastar) repository serving as our private fork.

**Comment by noahdesu** [comment]
I don't think that a stable API should be a prerequisite for cutting releases. There are many ways to handle this, but a common way is to use semantic versioning where anything less than a 1.0 release is considered to be a non-stable API.

Forking Seastar and tracking a sha1 for use in production is a fine way to handle things for users, but it doesn't help users select the sha1 to use. For this reason I think it is very use for upstream Seastar to tag releases, or maintain a `stable` branch if upstream doesn't want to deal with versioning.

The purpose here is to give users some direction. This can be as easy as the upstream developers periodically taking a release that passes all tests, or a release that tracks the version used by Scyalla.

**Comment by avikivity** [comment]
FWIW, we did cut a release a while ago: https://github.com/scylladb/seastar/releases

We aim to have all tests pass regularly. Scylla tracks seastar on a weekly basis, so it doesn't serve as a good trigger for new releases.

We can release on a time basis (like every 6 months) if it seems useful.

**Comment by nyh** [comment]
I'm closing this issue. As Avi noted already three years ago, we do have official releases now. They are infrequent (around once a year), but they exist, and if there is a community need, can be made more frequent. If you want to continue discussing this, let's do it on the mailing list, not in the bug tracker.
