### ISSUE TITLE
Add validation of boost library version to configure.py

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#289]
Refs #288

**Comment by jvanz** [comment]
I've submitted a patch to fix this issue: https://groups.google.com/d/msg/seastar-dev/VesPGykvO5Q/ldjqjDLoAgAJ

**Comment by jvanz** [comment]
The previous link is wrong. I sent the email to the wrong mail 
list. This is the right one, the fix is committed. groups.google.com/forum/m/#!forum/seastar-dev

**Comment by avikivity** [comment]
Fixed by a2be7a4f312a62c67c79cf818970d0c954f5fc15.
