### ISSUE TITLE
Make loggers configurable from the command line

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#292]
The logging framework was moved from https://github.com/scylladb/scylla/, but command line control is still left there.

It would be good to have it in seastar now, so that all seastar apps have configurable logging out of the box. It would allow logging to be easily enabled in tests, which only have options installed by seastar's `app_template`.

**Comment by tgrabiec** [comment]
Dup of scylladb/scylla#1326

**Comment by hakuch** [comment]
I'd like to try taking this on.
