### ISSUE TITLE
scripts/perftune.py with i3 AWS instances: verify that mode auto-selection logic yields the best results on i3 instances

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/seastar#308]
*Installation details*
Scylla version (or git commit hash): 49b01e764aa99536c31a3ac8014a34f4292c7d73

*Hardware details (for performance issues)*
Platform: AWS
Hardware: i3

*Description*
Currently `perftune.py` would select the `MQ` mode for all i3 instances smaller than i3.16xlarge.
We need to verify that this configuration gives us the best results on relatively big instances like i3.4xlarge and i3.8xlarge.

We need to compare the current configuration to the `SQ` configuration.
To enforce the `SQ` mode that one has to:

1. Modify the cpuset.conf to take the CPU0 out.
2. Apply the patch below to the `/usr/lib/scylla/scylla_prepare`:
```
@@ -25,7 +25,7 @@ elif [ "$NETWORK_MODE" = "dpdk" ]; then
     fi
 else # NETWORK_MODE = posix
     if [ "$SET_NIC" = "yes" ]; then
-        /usr/lib/scylla/posix_net_conf.sh $IFNAME
+        /usr/lib/scylla/posix_net_conf.sh $IFNAME -sq
     fi
 fi
```
3. Restart `scylla-server`: `sudo systemctl restart scylla-server`.

**Comment by glommer** [comment]
@vladzcloudius can we close this ?

**Comment by vladzcloudius** [comment]
@glommer I think we can. Although it's a bit dirty. - We haven't actually verified that. ;)

**Comment by vladzcloudius** [comment]
Closing because we have verified it by now: https://github.com/scylladb/scylla-enterprise/issues/1250#issuecomment-922651769
