### ISSUE TITLE
Using CMake as a build system

### ISSUE THREAD

**Issue by hakuch** [scylladb/seastar#313]
One idea we've been toying with is switching from Python configuration scripts and Ninja to CMake.

There are a number of benefits to doing so, mostly tied to the popularity of CMake in the wider community and the resulting compatibility:

- Lower barrier to entry for contributors to the project, including the possibility to benefit from existing CMake expertise.
- Easier embedding of Seastar as part of the build process for other projects, including Scylla. We could provide both a CMake package (so users can call `find_package (Seastar)`) or just structure the CMake file so that a client application can use Git submodules and just `add_subdirectory (extern/seastar)`.
- Wide-spread IDE support, essentially for free, including CLion, KDevelop, Qt Creator, and many others (including tooling intended for Vim and Emacs).
- Tools for unit testing (CTest) and packaging (rpm, deb) with CPack -- though I don't have experience with the latter.

CMake has improved dramatically in the last several years, and there are "modern" practises such as target-specific modifiers (like `target_include_directories` instead of `include_directories`) that we should take advantage of. Some guidelines are described [here](https://docs.google.com/presentation/d/18fY0zDtJCMUW5WdY2ZOfKtvb7lXEbBPFe_I6MNJC0Qw/edit#slide=id.g15c79ae86d_0_55).

Finally, there are some small difficulties and issues to be aware of:

- DPDK and c-ares have additional code-generation steps that need to be scripted. We could do this from CMake itself (including invoking scripts).
- We should probably continue to generate the pkg-config file for clients that don't use CMake.

**Comment by hakuch** [comment]
I've started slowly working on this in the background. I have something that is currently sufficient for an IDE, but not nearly at feature-parity with `configure.py`. Once I have something which could (minimally) replace `configure.py`, I'll submit an RFC to the seastar-dev mailing list.

@denesb has similarly started investigating using CMake in Scylla.

**Comment by hakuch** [comment]
I've started the [discussion](https://groups.google.com/d/msg/seastar-dev/D4j1cm3xBeU/X8LWPA83AAAJ) on some [work-in-progress](https://github.com/hakuch/seastar/tree/jhk/cmake/v1).

**Comment by hakuch** [comment]
A new version is available at https://groups.google.com/d/msg/seastar-dev/zcajDhsSuxc/aF0kQXC7DgAJ that should be at feature parity with the current system. Please try it out and give your feedback either on the mailing list or here.h

**Comment by noahdesu** [comment]
@hakuch what's the status of this patch?

**Comment by hakuch** [comment]
@noahdesu: I haven't had the time to revisit the branch since my last comment. The remaining work necessary is:

- Rebasing the branch against the latest version of `configure.py`, reflecting any changes since the initial work.
- Documenting the helper Python scripts.
- Writing a replacement `test.py` and `configure.py` that delegate to the appropriate options in the `CMakeLists.txt` file and that are backwards compatible.
- User testing of all the major configuration options, including DPDK support and debug and release builds (like the sanitizers).

**Comment by hakuch** [comment]
A rebased and improved version is available on the mailing list at https://groups.google.com/d/msg/seastar-dev/CXV_3tc5s20/qku3Po0dAwAJ.

Now, a request: since there are so many permutations of configuration options and settings, testing is challenging. If you are interested in seeing CMake support merged, I encourage you to try it out for yourself and report and issues, bugs, or suggestions on mailing list thread I linked to above. Please also note there are some known issues that you may be able to help resolve.

**Comment by denesb** [comment]
On Thu, 2017-12-07 at 09:43 -0800, Jesse Haber-Kucharsky wrote:
> @noahdesu: I haven't had the time to revisit the branch since my last
> comment. The remaining work necessary is:
> 
> 
> Rebasing the branch against the latest version of configure.py,
> reflecting any changes since the initial work.
> Documenting the helper Python scripts.

Simple helper scipts that do very simple things, like querying system
memory can be inlined into the CMakeLists.txt to avoid adding too many
small files, see:
https://github.com/denesb/scylla/blob/bdenes/cmake-v4/CMakeLists.txt#L1
217

**Comment by hakuch** [comment]
There is an updated version on the [mailing list](https://groups.google.com/d/msg/seastar-dev/UTEAtoR8q3I/DNQJtzHOAQAJ).

You can also grab it [here](https://github.com/hakuch/seastar/tree/jhk/cmake/v4).

The new plan is that while CMake is still unsupported, having it in the tree will make it easier for us to reach feature-parity and switch over.

**Comment by bluealert** [comment]
https://github.com/bluealert/Seastar-cmake
I have use CMake to manage the build of seastar, but the apps all crashed at a same point when start. I can't find the reason now.

@hakuch 

![screenshot from 2018-03-25 04-06-10](https://user-images.githubusercontent.com/2254200/37868479-e2e00ba4-2fe1-11e8-9bae-9ab68c24d770.png)

**Comment by hakuch** [comment]
@bluealert, a new iteration of CMake support for Seastar is available at https://github.com/hakuch/seastar/tree/jhk/cmake/v5.

It is being discussed on the seastar-dev mailing list.

Please verify that your issue is not present when you use the current build system. If the issue is only present with the version of the CMake build in the latest version, then please describe the exact error you're seeing on the mailing list (and not here).

Once initial experimental support for CMake has merged, then please create new GitHub issues for bugs in the CMake build or for necessary features of the CMake build that prevent it from replacing the current system.

**Comment by hakuch** [comment]
I've written a proposal (by example) for re-thinking our build and how we handle dependencies. There is a [mailing-list](https://groups.google.com/forum/#!topic/seastar-dev/jeFQiNEb_jM) post, and you can also try the example yourself on [GitHub](https://github.com/hakuch/CMakeWorkflows).

**Comment by hakuch** [comment]
Another iteration is now on the [mailing list](https://groups.google.com/d/msg/seastar-dev/t4LRq9V533A/z_Rur4T0AAAJ).

**Comment by hakuch** [comment]
Version 3 is now on the [mailing list](https://groups.google.com/d/msg/seastar-dev/cnTdPJhr-xM/pJKpW0-iBgAJ).

I believe that it is ready to merge pending review. Feedback on the mailing list is welcome.

**Comment by NavidMitchell** [comment]
Just a thought. If seastar was built with cmake you can use conan.io for dependency management. This tool makes it very easy to integrate new dependencies to a project.

**Comment by hakuch** [comment]
@NavidMitchell, I'm glad to say I've had the same thought.

One very important characteristic of the new CMake build system is that it decouples itself from dependencies. This means that users can use Conan if they wish, cmake-cooking (something I wrote), or system packages, or a combination of many of these.

I believe this will make development and distribution of Seastar and applications and libraries built with it far easier.
