### ISSUE TITLE
Split useful functions out of configure.py

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#315]
In configure.py we started to collect some useful functions that test things in the build environment. E.g., try_compile(), try_compile_and_*(), warning_support(), etc.

I think it would be nice to split these functions into a separate python file (e.g., libconfigure.py), and also document them in this file.

This will make our configure.py a bit smaller and more focused on this project, and will also make it easier to reuse these functions in other projects (e.g., in scylladb we already copied some of these functions, and we could instead just include seastar/libconfigure.py).

At some point, when the list of functions in libconfigure.py is rich enough, this will become an autoconf replacement :-)

**Comment by avikivity** [comment]
Better to move to cmake, #313.

**Comment by nyh** [comment]
@avikivity, really?
By closing this issue you are basically saying we **will** move to cmake. Soon.
Wow. Ok. I guess I need to learn cmake now.

**Comment by avikivity** [comment]
No, I'm saying that an effort to librarify configure.py is ill-spent. Someone already librarified it, and the result is cmake. I'm not saying cmake is the greatest thing since sliced pizza, but there's no point in reinventing it to save some code duplication between seastar and scylla.

**Comment by nyh** [comment]
The reason that brought me to make this suggestion is @gleb-cloudius 's recent patch to fix the try_compile function. If it were in a separate library, it would be easier to reason about, and to reuse.
But if you want to replace the whole thing anyway, then ok....
