### ISSUE TITLE
Add primitives for loops with limited parallelism

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#319]
The tutorial section about semaphores explains how to do loops with limited parallelism. Doing this correctly is pretty involved, and there are complications on how to support loop's end (need to wait for iterations which are still running), how to support a semaphore shared by several loops (by using a gate in addition to the shared semaphore).

These idioms are complicated and error-prone enough to deserve their own primitives in Seastar e.g., limited_parallel_for_each(), etc. that users can use without trying to remember the right combination of of semaphores and gates.

These primitives should also support an optional second functor which determines the "cost" for each item on the semaphore (note to self: what can we do to protect against the cost being higher than the original value of the semaphore, as warned in the tutorial?)

**Comment by nyh** [comment]
In commit 8933f76d3373db1a291b8999a9fd87a71fabd238 @bhalevy added  `max_concurrent_for_each`. Should we consider this issue done and close it, or are we missing additional utilities in this area?

**Comment by bhalevy** [comment]
@nyh I'm not aware of any missing utilities in this area.
We can always open new issues when we encounter them...
