### ISSUE TITLE
posix signals don't scale on large machines

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#324]
We keep seeing problems with signals on large machines, since signal delivery is processwide instead of per-thread. We should get rid of any signal-related stuff in the fast path.

**Comment by avikivity** [comment]
Possible plan:

 - alarm signal for high-resolution timers: remove and rely on the scheduler existing on need_preempt() to read the current time and look at the timer list
 - syscall work queue completion: remove, replace with a poller on the response queue, or perhaps the syscall thread should write to an eventfd which is waited for by epoll_wait().
 - sleeping reactor wakeup: replace with eventfd that epoll_wait() waits on
 - slow-path signals (SIGINT/SIGTERM): instead of blocking them while entering sleep mode, have them write to an eventfd that epoll_wait() waits on, so we don't ignore them if they happen while we're going to sleep
 - pthread_sigmask() in signal_pollfn: can now remove
 - epoll_pwait(): replace with epoll_wait()

**Comment by glommer** [comment]
Not all signal delivery is process wide, thst is controlled by a `clone` flag. In the past we have discussed calling clone directly instead of pthread_create and deemed not worth it because of tls issues.

I thought a bit more about it. Can't we have a signal thread that is created with clone dedicated to receive the signals and make sure it doesn't touch any tls data - just set flags and the such ?

Having yet another thread sucks because it is yet another context switch. I am already unhappy that we now have a context switch every 250usec for the task quota. But it is a solution to consider.

**Comment by gleb-cloudius** [comment]
I do not think you've missed anything, but may be signalfd() may help
here? Although I do not see how it interacts with SIGEV_THREAD_ID.

--
			Gleb.

**Comment by avikivity** [comment]
@glommer we use the signal to wake the reactor thread. If we use it to wake a side thread, and the side thread wakes up the reactor with another method, we may as well use the other method directly.

**Comment by avikivity** [comment]
@gleb-cloudius signalfd converts a signal to an eventfd, and for thread-to-thread communications we can use the eventfd directly without intermediaries.

**Comment by avikivity** [comment]
I have no idea why that particular cluster showed the problem so drastically. GCE, 24c48t. They are all shown as one socket, perhaps bad numa reporting made the problem worse.

**Comment by gleb-cloudius** [comment]
On Wed, Aug 23, 2017 at 05:55:27AM -0700, Avi Kivity wrote:
> @gleb-cloudius signalfd converts a signal to an eventfd, and for thread-to-thread communications we can use the eventfd directly without intermediaries.
> 
For thread to thread sure. I am thinking about IO and timers. The reason
we have to block signals when we are going to sleep is to prevent a
race between checking a variable and calling epoll. If we will deliver
through signalfd there will be no race.

--
			Gleb.

**Comment by avikivity** [comment]
I/O is polled (and we never sleep while an I/O is pending[1]). Timers can work through timerfd. epoll_wait() is race-free against writing to an eventfd or a timerfd expiring.

**Comment by gleb-cloudius** [comment]
On Wed, Aug 23, 2017 at 01:40:50PM +0000, Avi Kivity wrote:
> I/O is polled (and we never sleep while an I/O is pending[1]). Timers can work through timerfd. epoll_wait() is race-free against writing to an eventfd or a timerfd expiring.
> 
So TERM/INT can be moved to signalfd instead of writing to eventfd and
we have a replacement for all signal users.

--
			Gleb.

**Comment by avikivity** [comment]
Oh indeed, I ignored SIGTERM/SIGINT because they are low frequency, but without signalfd we can't switch from epoll_pwait to epoll_wait.

**Comment by nyh** [comment]
@avikivity you made a lot of progress on this in recent years, is anything left to be done for this issue?

**Comment by avikivity** [comment]
No, it's good.

Fixed by
0b2c25d13359d56ea2673fceb08e31d0d10dc85e
51c2917e9bd71bf5f4e39d1a18264a13e3908b37
dd948d15f0720495f751257ffe996c8a98c42934
