### ISSUE TITLE
gnutls write hook shouldn't throw exceptions

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#325]
The method `session::vec_push()` from `tls.cc` throws exception in some "should not really happen" cases. Since it's invoked from a C library, throwing is not safe.

**Comment by elcallio** [comment]
The "throw" is just an assert that I _really_ want to be there in non-asserting code as well. There is no recovery from it, so C-safe is kind of irrelevant here. Should maybe convert to assert + set exception + -1 though.

**Comment by tgrabiec** [comment]
2017-08-28 11:30 GMT+02:00 Calle Wilund <notifications@github.com>:

> The "throw" is just an assert that I *really* want to be there in
> non-asserting code as well. There is no recovery from it, so C-safe is kind
> of irrelevant here.
>
Does throwing through a C code have a well defined behavior through? If
not, then we're not guaranteed to see the error being reported properly,
which we want even if there is no recovery.

> Should maybe convert to assert + set exception + -1 though.
>

**Comment by elcallio** [comment]
Well-defined, as in "will skip all the frames". Which is actually ok here, because there are not even any on-stack references (afacr). All data is kept in session.

**Comment by avikivity** [comment]
Depends if the C code does manual cleanup or not. Also depends on how it was compiled.

Isn't vec_push defined to return -ESOMETHING on error?
