### ISSUE TITLE
Build failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by duanjp8617** [scylladb/seastar#326]
**OS Distribution**: Ubuntu 16.04.3 LTS
**Linux Kernel Version**: 4.4.0
**Compiler**: g++-5

**Build command sequence**:
sudo ./install-dependencies.sh
git submodule update --init
./configure --enable-dpdk --compiler=g=+-+-5 --mode=release
ninja

**Compilation fails with the following error information**:
FAILED: g++-5 -MD -MT build/release/tests/httpd.o -MF build/release/tests/httpd.o.d -O2 -I/home/net/seastar/build/release/gen -I/home/net/seastar/build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/home/net/seastar -U_FORTIFY_SOURCE  -DHAVE_DPDK -I/home/net/seastar/build/dpdk/include -march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_MACHINE_CPUFLAG_AES -DRTE_MACHINE_CPUFLAG_PCLMULQDQ -DRTE_MACHINE_CPUFLAG_AVX -DRTE_MACHINE_CPUFLAG_RDRAND -DRTE_MACHINE_CPUFLAG_FSGSBASE -DRTE_MACHINE_CPUFLAG_F16C -DRTE_MACHINE_CPUFLAG_AVX2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -I/home/net/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/tests/httpd.o tests/httpd.cc
tests/httpd.cc: In member function ‘virtual seastar::future<> test_message_with_error_non_empty_body::run_test_case()’:
tests/httpd.cc:371:79: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
     std::vector<std::tuple<bool, size_t>> tests = {{true, 100}, {false, 10000}};
                                                                               ^
tests/httpd.cc:371:79: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
tests/httpd.cc: In member function ‘virtual seastar::future<> test_simple_chunked::run_test_case()’:
tests/httpd.cc:376:79: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
     std::vector<std::tuple<bool, size_t>> tests = {{true, 100000}, {true, 100}};
                                                                               ^
tests/httpd.cc:376:79: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
tests/httpd.cc: In member function ‘virtual seastar::future<> test_http_client_server_full::run_test_case()’:
tests/httpd.cc:381:160: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
     std::vector<std::tuple<bool, size_t>> tests = {{true, 100}, {true, 10000}, {true, 100}, {true, 0}, {true, 5000}, {true, 10000}, {true, 9000}, {true, 10000}};
                                                                                                                                                                ^
tests/httpd.cc:381:160: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
tests/httpd.cc:381:160: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
tests/httpd.cc:381:160: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
tests/httpd.cc:381:160: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
tests/httpd.cc:381:160: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
tests/httpd.cc:381:160: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’
tests/httpd.cc:381:160: error: converting to ‘std::tuple<bool, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = int; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]’

**Comment by argenet** [comment]
Hi Duan @duanjp8617 ,

The failure occurs because in C++14, tuple variadic constructor is declared explicit which prohibits direct initialization of containers of tuples with curly-braced syntax.
For C++17, it has been relaxed to be conditionally explicit so GCC 6 and 7 accept this syntax but GCC 5 fails.

The proposed fix for this issue is pending to be committed: https://groups.google.com/forum/#!topic/seastar-dev/9qgEq-jcXAM

Meanwhile, if you have GCC 6 or later available, you can try building with it as the tuple constructor declaration has been refined since GCC 6 and this code compiles fine even without the fix.
