### ISSUE TITLE
Log relative addresses in backtraces

### ISSUE THREAD

**Issue by denesb** [scylladb/seastar#334]
Currently when logging backtraces (e.g. on reactor stalls) we log instruction pointers as extracted from the instruction pointer register for each stack frame. If ASLR is enabled this means that addr2line will not be able to map them to source lines because the process's (and each loaded module's) base address will be randomized on each start. To mend this and make those backtraces useful we should log addresses that are relative to the module they originate from.
Instead of:
```
Backtrace:
  0x000055d3d54d23c9
  0x000055d3d51f1932
  0x000055d3d51f6b2d
```
Log:
```
Backtrace:
  /usr/lib/libc.so.6+0x23c9
  /usr/bin/scylla+0xd1f1932
  /usr/bin/scylla+0xd1f492
```
With the latter, it's trivial to write a simple script that feeds the addresses to `addr2line` to obtain a proper backtrace.

Implementation notes:
One way to do this is to build a map from `/proc/${pid}/maps` on boot, then in `backtrace()` match addresses to modules. We can assume most addresses originate from the current process and first try to match the address with its memory area, then fall-back to matching the other modules.

**Comment by avikivity** [comment]
[`dl_iterate_phdr`](https://linux.die.net/man/3/dl_iterate_phdr) may be an easier option than `/proc/pid/maps`.
