### ISSUE TITLE
TLS server socket may become inacssesible because of one bad client

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/seastar#335]
tls::accept() runs handshake in the foreground, so no other accept is possible while handshake is executed. One buggy client may kill a server.

**Comment by slivne** [comment]
@elcallio  / @gleb-cloudius doesn't d55c7311f7d0f7f68ab7fae280eb6338cc28edcb fix this as well ?

**Comment by gleb-cloudius** [comment]
On Wed, Sep 13, 2017 at 12:42:52AM -0700, Shlomi Livne wrote:
> @elcallio  / @gleb-cloudius doesn't d55c7311f7d0f7f68ab7fae280eb6338cc28edcb fix this as well ?
> 
Yes.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
Fixed by d55c7311f7d0f7f68ab7fae280eb6338cc28edcb
