### ISSUE TITLE
Build on docker, consume 30+G memory

### ISSUE THREAD

**Issue by shanshanpt** [scylladb/seastar#343]
Build on docker, consume 30+G memory
How can I limit the memory when build seastar.
Thanks.

**Comment by shanshanpt** [comment]
Sorry, one more question:
when I run the example code in docker, 
I encountered a error of Assertion `r == 0' failed.

WARNING: debug mode. Not for benchmarking or production
WARN  2017-09-22 04:24:23,498 seastar - Seastar compiled with default allocator, heap profiler not supported
test: core/posix.hh:460: void seastar::pin_this_thread(unsigned int): Assertion `r == 0' failed.
Aborting.
Backtrace:
  0x00000000006cbe10
  0x000000000041e11c
  0x000000000041e214
  0x00000000004693d9
  0x00000000004f0098
  0x00000000004f0137
  /usr/lib64/libpthread.so.0+0x00000000000109ff
  /usr/lib64/libc.so.6+0x0000000000034a27
  /usr/lib64/libc.so.6+0x0000000000036629
  /usr/lib64/libc.so.6+0x000000000002d226
  /usr/lib64/libc.so.6+0x000000000002d2d1
  0x00000000006bca07
  0x0000000000468ee1
  0x000000000046a046
  0x0000000000537a29
  0x00000000006f70c3
  0x0000000000992cc6
  /usr/lib64/libpthread.so.0+0x0000000000007619
  /usr/lib64/libc.so.6+0x00000000001025fc
Aborted

How to solve it in docker ? Thanks

**Comment by tgrabiec** [comment]
2017-09-22 5:44 GMT+02:00 shanshanpt <notifications@github.com>:

> Build on docker, consume 30+G memory
> How can I limit the memory when build seastar.
> Thanks.
>

You can limit the parallelism of the build by using the -j switch: ninja -j1
It will require several GB still.
