### ISSUE TITLE
PATH is not working well and install script does some polution to user's filesystem

### ISSUE THREAD

**Issue by baiwfg2** [scylladb/seastar#351]
Hi. Today I tried to build seastar on centos7 and found two issues. First, the new file `/etc/profile.d/scylla.sh`  is not working well since the newly-add path is placed behind the original PATH. What if there're some existed tools such as gcc 4.9(which may not be suitable for building seastar)in my original PATH ? So it should be:

> export PATH=/opt/scylladb/bin:/opt/scylladb/sbin:$PATH

Second, I know you intend to make the installation process more easier, but I feel a little polution to the original filesystem after installation. Some packages, especially those frequently-used executable  and customized tools such as python34, libtool, cmake, protoc, may be overrided by the setup process, which may affect other packages because of the version compabiltiy issue. Furthormore, those executables are ususally compiled by myself instead of using system's package manager since the configured yum source is out-of-dated and no access to the latest source for the moment.

So why don't you make them be installed like those `scylla-*` packages under /opt/scylladb or another` /opt/some-prefix` ?  We don't need to worry about finding them , just setting some environment variables will be ok. I think this is more friendly to users' original filesystem.  So I strongly suggest that install as many packages into some customized path like `/opt/scylladb` as possible，so that user can decide whether to delete the whole directory after building since some of them are unlikely to be used at runtime.

Anyway, thanks guys for creating seastar and making it better.

**Comment by avikivity** [comment]
Our rules are:
 - what is available from EPEL, we install from EPEL
 - otherwise, we build a custom package and install it in /opt/scylladb.

Is there a problem with EPEL packages?
