### ISSUE TITLE
can I use "--network-stack native" in docker ?

### ISSUE THREAD

**Issue by shanshanpt** [scylladb/seastar#352]
Hi, can I use "--network-stack native" in docker ?

when I exec "./server --smp=6 --cpuset=2,3,4,5,6,7 --port=10093 --network-stack=native", it reports a error "WARN  2017-10-23 14:19:00,787 [shard 0] seastar - Exceptional future ignored: std::system_error (error system:2, No such file or directory)".

So I don't if I can use  native stack in docker environment.

I configure the virbr0 follow the doc "https://github.com/scylladb/seastar/blob/master/doc/native-stack.md".

**Comment by xiaoming-qxm** [comment]
> Hi, can I use "--network-stack native" in docker ?
> 
> when I exec "./server --smp=6 --cpuset=2,3,4,5,6,7 --port=10093 --network-stack=native", it reports a error "WARN 2017-10-23 14:19:00,787 [shard 0] seastar - Exceptional future ignored: std::system_error (error system:2, No such file or directory)".
> 
> So I don't if I can use native stack in docker environment.
> 
> I configure the virbr0 follow the doc "https://github.com/scylladb/seastar/blob/master/doc/native-stack.md".

I got the same error in docker, had you fix it yet?
