### ISSUE TITLE
when to delete the memory that user alloc (use net::packet format data)

### ISSUE THREAD

**Issue by shanshanpt** [scylladb/seastar#356]
'write(net::packet)' function is a **zero copy API**, so the example as follows:

char* tmp = new char[10];
memcpy(tmp, "aaaaaaaaaa", 10);
// I want to delete the memory by myself,
// so I use deleter() here
// But, I don't know when I can delete the tmp by myself.
// Is there a way to solve this?
net::packet pack(frag, deleter());
return _out.write(std::move(pack)).then([this, tmp] {
    return _out.flush().then([tmp] { 
      // I can't delete here, becase the data may not be send actually.  
      delete tmp;  
    });
})

**Comment by nyh** [comment]
This is not a bug report, please close it (sadly I can't do it myself) if you want to ask a question or discuss a topic that isn't quite a bug or feature request, please use the Seastar mailing list and not the bug tracker.

I'll start you out with a short clarification (maybe it will help, maybe not): In the zero-copy network write API, the user gives the ownership of the buffer that needs to be written to the network driver. Note that you use std::move(pack) - you **move** (in C++-speak) the packet into the driver, and the caller cannot touch this packet any more. The driver will release this memory when it's done with it - and this may be a long time from now (the data cannot be freed until the remote side acknowledge it).

**Comment by shanshanpt** [comment]
Thanks @nyh , I will talk the issuse via mailing list.
