### ISSUE TITLE
no such file or directory when running docker image.

### ISSUE THREAD

**Issue by njcongtou** [scylladb/seastar#357]
I want to run hello world sample from docker image, but I am running into this issue locally by following this steps in 'Building seastar in Docker container' section. https://github.com/scylladb/seastar/wiki/Building-Seastar

seabuild ./configure.py

docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"./configure.py\": stat ./configure.py: no such file or directory".

**Comment by duarten** [comment]
You should change the `seabuild` function such that it mounts the directory where you cloned the seastar repo.
