### ISSUE TITLE
CXX build/release/http/transformers.o Failed

### ISSUE THREAD

**Issue by puccoonhuang** [scylladb/seastar#363]
When I build seastar with ninja， I get a failed result. The detail as below. Is this problem a bug of the code?

[29/38] CXX build/release/http/transformers.o
FAILED: g++-5 -MD -MT build/release/http/transformers.o -MF build/release/http/transformers.o.d -O2 -I/mnt/hgfs/LinuxShare/seastar/build/release/gen -I/mnt/hgfs/LinuxShare/seastar/build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/mnt/hgfs/LinuxShare/seastar -U_FORTIFY_SOURCE  -I/mnt/hgfs/LinuxShare/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-sign-compare -Wno-error=cpp -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/http/transformers.o http/transformers.cc
http/transformers.cc: In member function ‘virtual seastar::output_stream<char> seastar::httpd::content_replace::transform(std::unique_ptr<seastar::httpd::request>, const sstring&, seastar::output_stream<char>&&)’:
http/transformers.cc:205:112: error: converting to ‘std::tuple<seastar::basic_sstring<char, unsigned int, 15u>, seastar::basic_sstring<char, unsigned int, 15u> >’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[9]; _U2 = seastar::basic_sstring<char, unsigned int, 15u>&; <template-parameter-2-3> = void; _T1 = seastar::basic_sstring<char, unsigned int, 15u>; _T2 = seastar::basic_sstring<char, unsigned int, 15u>]’
     return output_stream<char>(content_replace_data_sink(std::move(s), {{"Protocol", protocol}, {"Host", host}}), 32000, true);
                                                                                                                ^
http/transformers.cc:205:112: error: converting to ‘std::tuple<seastar::basic_sstring<char, unsigned int, 15u>, seastar::basic_sstring<char, unsigned int, 15u> >’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[5]; _U2 = seastar::basic_sstring<char, unsigned int, 15u>&; <template-parameter-2-3> = void; _T1 = seastar::basic_sstring<char, unsigned int, 15u>; _T2 = seastar::basic_sstring<char, unsigned int, 15u>]’
[29/38] CXX build/release/net/tls.o

**Comment by nyh** [comment]
I cannot reproduce this compilation error. Which version of gcc are you using (from the name "g++-5" I'm guessing it's some sort of gcc 5.*?)

**Comment by nyh** [comment]
@amnonh, the error message suggests you used an implicit conversion from {{"Protocol", protocol}, {"Host", host}} to a tuple. As far as I can see (e.g., https://stackoverflow.com/questions/41895958/why-does-this-code-involving-implicit-construction-of-stdtuple-compile-in-c1), this is a new C++17 feature which we should not yet use. Can you please confirm, and if so, change this code?

**Comment by amnonh** [comment]
sure

**Comment by puccoonhuang** [comment]
I change the code just like below to elimate the compile errors.

204     sstring protocol = req->get_protocol_name();
205     sstring protocol_const("Protocol");
206     sstring host_const("Host");
207     std::vector<std::tuple<sstring,sstring>> key_value;
208     key_value.push_back(std::make_tuple(protocol_const, protocol));
209     key_value.push_back(std::make_tuple(host_const, host));
210 
211     return output_stream<char>(content_replace_data_sink(std::move(s), key_value), 32000, true);
