### ISSUE TITLE
It can not execute “write()” in parallel (A bug or the design)

### ISSUE THREAD

**Issue by shanshanpt** [scylladb/seastar#369]
The parallel here means the code like as follow: 
future<> process() {
   out.write().then({ flush... });  // 1. data size >= _size
   out.write().then({ flush... });  // 2. data size >= _size
   out.write().then({ flush... });  // 3. data size >= _size
   ...
}

If a "_flushing=true" now, it may be set by "out.write()  1".
And the "out.write()  2" may be exec the code "_in_batch.value().get_future()", and the promise(_in_batch) of out is be set, and now the promise(_in_batch) is not nullopt. 
Last the "out.write()  3" can exec the follow code also, 
so when 3 exec the "_in_batch.value().get_future()", because the task of the promise(_in_batch) is 
set by "out.write()  2", so here will be exec "assert(!_future && _state && !_task);".

template<typename CharType>
future<>
output_stream<CharType>::zero_copy_put(net::packet p) {
    // if flush is scheduled, disable it, so it will not try to write in parallel
    _flush = false;
    if (_flushing) {
        // flush in progress, wait for it to end before continuing
        return **_in_batch.value().get_future()**.then([this, p = std::move(p)] () mutable {
            return _fd.put(std::move(p));
        });
    } else {
        return _fd.put(std::move(p));
    }
}

So, I think that, I can not write code in parallel ?

Thanks so much.

**Comment by nyh** [comment]
I would say there **is** a bug, but not in the code but in the documentation, which as you can see in http://docs.seastar-project.org/master/classseastar_1_1output__stream.html says almost nothing about what the methods of this abstract class are guaranteed to behave.
We recently had a debate about flush(), and no it's about the parallelism of write():
An outputstream is designed for a **single writer**, i.e., a writer which waits for one write() to complete (i.e., its future to resolve) before starting the next write. You are not allowed to use multiple write() calls, and it's a documentation bug that this is not clearly stated in the documentation of this class.

Another thing we could have done is for the second parallel write() to wait, internally, until the first write completes. But this will complicate the code (and slow it down a bit) and I'm not sure to what gain. 
By the way, if there is real parallelism to be had, you can open several different outputstreams and write to them in parallel. For example, you can open several outputstreams to different positions in the same file, and write to them in parallel.

**Comment by shanshanpt** [comment]
Thanks @nyh , I see, I want to make sure that my understanding is right about the code.
By the way, about

>  For example, you can open several outputstreams to different positions in the same file, and write to them in parallel.

hum..., you know, a connection may just have one outputstream, so I have to give the parallelism way to write, yes ?
