### ISSUE TITLE
smp > 1 cause example code from tutorial hang

### ISSUE THREAD

**Issue by 303248153** [scylladb/seastar#374]
I'm following the [tutorial](https://github.com/scylladb/seastar/blob/master/doc/tutorial.md) and try to write a very basic seastar application, a tcp echo server.
When I run this echo server with --smp 1, every thing works fine, but the problem comes with --smp 2 or above, the server will hang after accepted uncertain number of connections.
The reproduce steps is:

- Download main.cpp and ping.py from pasted code
- Compile main.cpp with ```g++ `pkg-config --cflags --libs seastar/build/release/seastar.pc` -O0 main.cpp```
- Run `a.out --smp 2`
- Run ping.py and see the server hangs

My environments is:

- seastar: adaca37db4b213fadc25d0889c6b061a380d283e release build
- ubuntu 17.10
- gcc 7.2.0-8ubuntu3

Main.cpp

``` c++
#include "core/app-template.hh"
#include "core/reactor.hh"
#include "core/future-util.hh"

seastar::future<> handle_connection(seastar::connected_socket s,
                                    seastar::socket_address a) {
    auto out = s.output();
    auto in = s.input();
    return do_with(std::move(s), std::move(out), std::move(in),
        [] (auto& s, auto& out, auto& in) {
            std::cout << "handle connection, cpu " << seastar::engine().cpu_id() << std::endl;
            return seastar::repeat([&out, &in] {
                return in.read().then([&out] (auto buf) {
                    if (buf) {
                        return out.write(std::move(buf)).then([&out] {
                            return out.flush();
                        }).then([] {
                            return seastar::stop_iteration::no;
                        });
                    } else {
                        return seastar::make_ready_future<seastar::stop_iteration>(
                            seastar::stop_iteration::yes);
                    }
                });
            }).then([&out] {
                return out.close();
            });
        });
}

seastar::future<> service_loop() {
    seastar::listen_options lo;
    lo.reuse_address = true;
    std::cout << "enter service loop" << std::endl;
    return seastar::do_with(seastar::listen(seastar::make_ipv4_address({1234}), lo),
            [] (auto& listener) {
        std::cout << "enter do with" << std::endl;
        return seastar::keep_doing([&listener] () {
            std::cout << "enter keep doing" << std::endl;
            return listener.accept().then(
                [] (seastar::connected_socket s, seastar::socket_address a) {
                    std::cout << "acceppted connection" << std::endl;
                    // Note we ignore, not return, the future returned by
                    // handle_connection(), so we do not wait for one
                    // connection to be handled before accepting the next one.
                    handle_connection(std::move(s), std::move(a));
                });
        });
    });
}

int main(int argc, char** argv) {
    seastar::app_template app;
    app.run(argc, argv, service_loop);
}
```

ping.py

``` python
import socket
import time
import threading

def ping():
	s = socket.socket()
	s.connect(("127.0.0.1", 1234))
	for _ in xrange(3):
		print s.send("abc")
		print s.recv(1024)
	time.sleep(1)

if __name__ == "__main__":
	threads = []
	for _ in xrange(100):
		t = threading.Thread(target=ping)
		t.start()
		threads.append(t)
	for t in threads:
		t.join()
	print "all threads success"
```

**Comment by nyh** [comment]
The thing you're missing is the code shown in the tutorial which runs service_loop() not just once, but once on every core.
What is happening is that Seastar's TCP stack is sharded - each TCP connection is assigned to a specific CPU. Therefore all CPUs need to accept these connections - it's not enough that just one does. I tried to explain this in the tutorial, but I agree that this point is weird and unfamiliar enough that maybe it needs even more discussion.

Please close this issue. This is not a bug that belongs on the bug tracker. If you want to continue this discussion, let's do it on the seastar-dev mailing list.

**Comment by 303248153** [comment]
![proof](https://user-images.githubusercontent.com/16222094/34196804-ab929578-e59e-11e7-871a-3aec3104fb5a.gif)
Hmm... please see this gif and say again it's not a bug, the server just stopped without accepting new connections.

**Comment by gleb-cloudius** [comment]
On Wed, Dec 20, 2017 at 12:01:26AM -0800, 303248153 wrote:
> ![proof](https://user-images.githubusercontent.com/16222094/34196804-ab929578-e59e-11e7-871a-3aec3104fb5a.gif)
> Hmm... please see this gif and say again it's not a bug, the server just stopped without accepting new connections.
> 
It is a bug, but a bug in your code, not seastar.

--
			Gleb.

**Comment by 303248153** [comment]
The code is copied from tutorial, I just added some console output, so you mean the code in tutorial has a bug that it's not runnable with smp > 1?

**Comment by gleb-cloudius** [comment]
The tutorial has this:

In the examples we saw earlier, `main()` ran our function `f()` only once, on the first thread. Unless the server is run with the `"-c1"` option (one thread only), this will mean that any connection arriving to a different thread will not be handled. So in all the examples below, we will need to run the same service loop on all cores. We can easily do this with the `smp::submit_to` function:


```cpp
seastar::future<> service_loop();

seastar::future<> f() {
    return seastar::parallel_for_each(boost::irange<unsigned>(0, seastar::smp::count),
            [] (unsigned c) {
        return seastar::smp::submit_to(c, service_loop);
    });
}
```

Here we ask each of Seastar cores (from 0 to `smp::count`-1) to run the same function `service_loop()`. Each of these invocations returns a future, and `f()` will return when all of them have returned (in the examples below, they will never return - we will discuss shutting down services in later sections).

**Comment by 303248153** [comment]
Ok, I know where is the problem now, thanks for your explain.
I'll close this issue.

**Comment by 303248153** [comment]
This is just a note for anyone who has the same question.

I was trying to find the real reason for the problem and this is what I found.

First, for posix network stack, only core 0 will actually listen the socket,
in [reactor::listen](https://github.com/scylladb/seastar/blob/adaca37db4b213fadc25d0889c6b061a380d283e/core/reactor.cc#L848), `_network_stack` on core 0 is `posix_network_stack` and on other core is `posix_ap_network_stack`,
[posix_network_stack::listen](https://github.com/scylladb/seastar/blob/adaca37db4b213fadc25d0889c6b061a380d283e/net/posix-stack.cc#L332) will call `posix_listen` anyway,
but [posix_ap_network_stack::listen](https://github.com/scylladb/seastar/blob/adaca37db4b213fadc25d0889c6b061a380d283e/net/posix-stack.cc#L356) only calls `posix_listen` when `_reuseport` is true,
for now `_reuseport` is always false due to [posix_reuseport_detect](https://github.com/scylladb/seastar/blob/adaca37db4b213fadc25d0889c6b061a380d283e/core/reactor.cc#L816),
so only core 0 will actually call `posix_listen`.

Then when an new connection is accepted, it will distribute to other cores by load balancer no matter they would call `accept` later or not,
the core 0 will call [posix_server_socket_impl<Transport>::accept](https://github.com/scylladb/seastar/blob/adaca37db4b213fadc25d0889c6b061a380d283e/net/posix-stack.cc#L189) which calls [get_handle](https://github.com/scylladb/seastar/blob/adaca37db4b213fadc25d0889c6b061a380d283e/net/posix-stack.hh#L93) which calls [load_balancer::next_cpu](https://github.com/scylladb/seastar/blob/adaca37db4b213fadc25d0889c6b061a380d283e/net/posix-stack.hh#L49),
`next_cpu` choose a cpu with least connections then `accept` moves the connected socket there.

The problem is, if that core will never call [posix_ap_server_socket_impl<Transport>::accept](https://github.com/scylladb/seastar/blob/adaca37db4b213fadc25d0889c6b061a380d283e/net/posix-stack.cc#L213),
then the moved connected socket will remain in `conn_q` forever.

It's not a bug, but more like a design problem, it require all cores must call accept repeatedly for every listening address.
For most situation, all connections use almost the same cpu resources, this works very well,
but if some connection use more cpu and other use less, some core will be very busy while other remain idle,
a worse situation is, while a core is doing some cpu heavy job, and a connected socket distributed to that core, the connected socket will not be accepted until the job is completed,
looks like seastar has a preemption mechanism but it's undocumented yet.

Howevery, **fix** this problem is pretty easy:

- change [this line](https://github.com/scylladb/seastar/blob/adaca37db4b213fadc25d0889c6b061a380d283e/net/posix-stack.hh#L54) to `auto cpu = shard_id(engine().cpu_id())`
- comment out [this line](https://github.com/scylladb/seastar/blob/adaca37db4b213fadc25d0889c6b061a380d283e/core/reactor.cc#L816)

Just two line then only the core calls `accept` will take the connected socket.
But it's a bad solution, I'm sure it wont actually fix anything.

Since native stack is unavailable on my environment, I'm not sure how different the situation is on native stack.

Related talk on google group: [https://groups.google.com/forum/?hl=en#!searchin/seastar-dev/accept|sort:date/seastar-dev/PojoIl9NBhk/Fc-H62N6AwAJ](https://groups.google.com/forum/?hl=en#!searchin/seastar-dev/accept|sort:date/seastar-dev/PojoIl9NBhk/Fc-H62N6AwAJ)
