### ISSUE TITLE
httpd static assertion failed

### ISSUE THREAD

**Issue by markw77** [scylladb/seastar#378]
While building httpd app compilation failed on static assert:

[31/375] CXX build/release/apps/httpd/main.o
FAILED: g++ -MD -MT build/release/apps/httpd/main.o -MF build/release/apps/httpd/main.o.d -O2 -I/home/marek/scylladb/seastar/build/release/gen -I/home/marek/scylladb/seastar/build/release/c-ares -std=gnu++17 -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/home/marek/scylladb/seastar -U_FORTIFY_SOURCE  -DHAVE_DPDK -I/home/marek/scylladb/seastar/build/dpdk/include -march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_MACHINE_CPUFLAG_AES -DRTE_MACHINE_CPUFLAG_PCLMULQDQ -DRTE_MACHINE_CPUFLAG_AVX -DRTE_MACHINE_CPUFLAG_RDRAND -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -I/home/marek/scylladb/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-sign-compare -Wno-error=cpp -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/apps/httpd/main.o apps/httpd/main.cc
In file included from /home/marek/scylladb/seastar/util/alloc_failure_injector.hh:27:0,
                 from /home/marek/scylladb/seastar/core/future.hh:36,
                 from /home/marek/scylladb/seastar/core/ragel.hh:32,
                 from http/request_parser.rl:24,
                 from /home/marek/scylladb/seastar/http/httpd.hh:25,
                 from apps/httpd/main.cc:22:
/home/marek/scylladb/seastar/util/noncopyable_function.hh: In instantiation of ‘seastar::noncopyable_function<Ret(Args ...)>::noncopyable_function(Func) [with Func = std::function<seastar::future<>(seastar::output_stream<char>&&)>; Ret = seastar::future<>; Args = {seastar::output_stream<char>&&}]’:
/home/marek/scylladb/seastar/http/function_handlers.hh:104:88:   required from here
/home/marek/scylladb/seastar/util/noncopyable_function.hh:117:9: error: static assertion failed: must be nothrow move constructible
         static_assert(std::is_nothrow_move_constructible<Func>::value, "must be nothrow move constructible");
         ^
[31/375] CXX build/release/tests/futures_test.o
ninja: build stopped: subcommand failed.

Build was configured as:
./configure.py --enable-dpdk
Compiler used:
g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

**Comment by duarten** [comment]
Please retry with cdd86a3 applied (just merged).

**Comment by markw77** [comment]
this fix the issue, thanks

**Comment by markw77** [comment]
thanks, that fix the issue

2017-12-27 11:28 GMT+01:00 Duarte Nunes <notifications@github.com>:
