### ISSUE TITLE
Unable to set SCHED_FIFO scheduling policy for timer thread; 

### ISSUE THREAD

**Issue by unisqu** [scylladb/seastar#382]
seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE

What's the solution?

**Comment by avikivity** [comment]
You can try running the application with CAP_SYS_NICE, or as root.

**Comment by nyh** [comment]
I also reported this a couple of weeks ago on the Seastar mailing list.
I feel that having this message appear every time you run a Seastar program - even one of Seastar's unit test, is not a good idea as it's ugly, and scary. Seastar works correctly even without SCHED_FIFO, we are just risking that if the task quota is "small enough", we may not be able to fulfill it. But our default task quota is not set small, so maybe we shouldn't print this message then? Our unit tests definitely don't care about this at all, and it's sad to see this message every time you run a unit test.

@avikivity could we measure, on the fly, whether the timer thread is working at the desired frequency, and **only** print this message if we determine that the timer thread is not achieving its desired frequency?

**Comment by lxl910915** [comment]
Same WARNING, any suggestion?

**Comment by avikivity** [comment]
You can ignore it, run as root, run with CAP_SYS_NICE, or run on a 4.12+ kernel.

**Comment by avikivity** [comment]
@nyh your idea is too complicated for something as trivial as a warning. We can have an opt-out for unit tests, but general applications do need this warning, because Seastar can't provide good latency without it.

**Comment by travisdowns** [comment]
> or run on a 4.12+ kernel.

What changed in kernel 4.12?

**Comment by avikivity** [comment]
4.18. IOCB_CMD_POLL was implemented.

**Comment by avikivity** [comment]
4.19 actually. It was implemented in 4.18, then reverted, then reimplemented in 4.19. torvalds/linux@bfe4037e722ec672c9dafd5730d9132afeeb76e9
