### ISSUE TITLE
missing `break` in metrics.cc?

### ISSUE THREAD

**Issue by foobar** [scylladb/seastar#386]
Seems to me it should break instead of fall-through in the case of HISTOGRAM. 
I can send a PR if someone confirms this is a bug.

```c++
metric_value metric_value::operator+(const metric_value& c) {
    metric_value res(*this);
    switch (_type) {
    case data_type::HISTOGRAM:
        boost::get<histogram>(res.u) += boost::get<histogram>(c.u);
        // missing break?
    default:
        boost::get<double>(res.u) += boost::get<double>(c.u);
        break;
    }
    return res;
}
```

**Comment by amnonh** [comment]
good catch, It is is a bug (it has no effect but it still worth fixing).

Please take a look at the contributing document on how to contribute to the project
https://github.com/scylladb/seastar/blob/master/CONTRIBUTING.md

**Comment by amnonh** [comment]
I think we should just remove the download page from the search results, I can add a  noindex to the reply, but it will not do much good as the problem with Google returning the link, not with the content of the link

**Comment by foobar** [comment]
I've sent a patch to the dev mailing list.
