### ISSUE TITLE
segment fault after compiling seastar 

### ISSUE THREAD

**Issue by SungHoHong2** [scylladb/seastar#388]
Hello I have been testing the seastar in my local workstation 
and now trying to build seastar on a new server.

I believe that the configurations may be different and the reason why the compiled files are not running properly 

The gcc files in the server was clearly outdated so I had to add the compiler arguments while running the configure.py file. but that is it. and the installation was done without no errors. 
the only thing I have done is 
```
sudo ./configure.py --enable-dpdk --compiler g++-5
sudo ninja 
```

The segment fault definitely comes from the libraries that has been compiled, but I have no clue where to find the error in this case. 

the error I get is direct. it is a segment fault. and the implementation of the code is wrong. this is what I get in the dmesg 
```
p 00007fff9dac5178 error 6 in getting-started[400000+3e2000]                          
[547587.845286] httpd[3950]: segfault at 5ffffffffffa ip 000000000054b22f sp 00007fff2
79ed788 error 6 in httpd[400000+5de000]                                               
```

Anyone with some ideas with this issue would be greatly appreciated.

**Comment by duarten** [comment]
What exactly did you run? Your own test program?

**Comment by duarten** [comment]
Closed as stale.
