### ISSUE TITLE
Can someone pls provide a guidance on how to install seastar inside a Ubuntu 16.04 docker container?

### ISSUE THREAD

**Issue by unisqu** [scylladb/seastar#394]
1. Can someone pls provide a guidance on how to install seastar inside a Ubuntu 16.04 docker container?
2. How to run a http 80 server outputting "hello world"?

The current doc is very difficult to follow. I ended up with...

```
bash# c++ `pkg-config --cflags --libs $SEASTAR/build/release/seastar.pc` getting-started.cc
Failed to open '/build/release/seastar.pc': No such file or directory
No package '/build/release/seastar.pc' found
In file included from getting-started.cc:1:0:
core/app-template.hh:27:26: fatal error: core/future.hh: No such file or directory
compilation terminated.
```

Appreciate all help. Thanks.

**Comment by shanshanpt** [comment]
**build seastar:**
sudo ./install-dependencies.sh
./configure.py --compiler=/usr/bin/g++  --enable-dpdk  --mode=release
ninja -j8

**build client:**
g++  -g  -I . -I /xxx/workspace/seastar `pkg-config --cflags --libs /xxx/workspace/seastar/build/release/seastar.pc` -o client  client.cc

**Comment by unisqu** [comment]
Thanks!

**Comment by xiaqunfeng** [comment]
@shanshanpt @unisqu 	Have you two ever had this problem?
```
# g++ `pkg-config --cflags --libs build/release/seastar.pc` hellworld.cc
hellworld.cc:1:10: fatal error: core/app-template.hh: No such file or directory
 #include "core/app-template.hh"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
