### ISSUE TITLE
curl -I for seastar/apps/httpd/main.cc returns as Content-Type: application/json

### ISSUE THREAD

**Issue by unisqu** [scylladb/seastar#395]
curl -I for seastar/apps/httpd/main.cc returns as Content-Type: application/json
after compilation
How can I make it return html/text or plain/text?

**Comment by duarten** [comment]
You'll probably have to change the type passed to the `function_handler`s created in `main.cc`. Also, please use the mailing list to ask questions instead of the bug tracker.
