### ISSUE TITLE
Is it thread safe between smp_message_queue::flush_request_batch and smp_message_queue::submit_item

### ISSUE THREAD

**Issue by bigheadzen** [scylladb/seastar#400]
`smp_message_queue::flush_request_batch` called `_tx.a.pending_fifo.push_back`, and `smp_message_queue::flush_request_batch` called `_tx.a.pending_fifo.erase`.  
These two functions are not synchronized at all.  

So is it thread safe between these two functions? I thought it's undefined behavior as pending_info is a std::deque. 

Correct me if I'm wrong. Much appreciated. :)

**Comment by gleb-cloudius** [comment]
On Sun, Feb 04, 2018 at 07:33:39AM +0000, bigheadzen wrote:
> `smp_message_queue::flush_request_batch` called `_tx.a.pending_fifo.push_back`, and `smp_message_queue::flush_request_batch` called `_tx.a.pending_fifo.erase`.  
Did you mean smp_message_queue::submit_item calls _tx.a.pending_fifo.push_back?

> These two functions are not synchronized at all.  
> 
> So is it thread safe between these two functions? I thought it's undefined behavior as pending_info is a std::deque. 
> 
> Correct me if I'm wrong. Much appreciated. :)
> 
Both functions are run by the same thread.

--
			Gleb.

**Comment by bigheadzen** [comment]
Thanks a lot.. I misunderstood the message directions in _qs array.
