### ISSUE TITLE
Can not detect file type in directory_test on CentOS 7

### ISSUE THREAD

**Issue by thongpv3** [scylladb/seastar#403]
I just run directory test example: https://github.com/scylladb/seastar/blob/master/tests/directory_test.cc
and add a statement to listing directory only:

```cpp
 future<> report(directory_entry de) {
    if (de.type == directory_entry_type::directory)
        print("%s\n", de.name);
   return make_ready_future<>();
 }
```
but it does not show any sub directory in my current directory.
When use debug tool, I found that `de.type` is nullopt. I run this example on CentOS 7, kernel 3.10-327.el7.x86_64.

**Comment by avikivity** [comment]
Not a bug, some kernels/filesystems don't report the file type.

Use `reactor::file_type()` if you get nullopt.
