### ISSUE TITLE
Can we have a hello world port 80 example with seastar?

### ISSUE THREAD

**Issue by unisqu** [scylladb/seastar#409]
No idea why doesnt work when i compile...
g++ `pkg-config --cflags --libs ../seastar/build/release/seastar.pc` getting-started.cc

    getting-started.cc:6:1: error: 'future' does not name a type
     future<> service_loop() {

> #include "core/seastar.hh"
> #include "core/reactor.hh"
> #include "core/future-util.hh"
> #include <iostream>
> 
> future<> service_loop() {
>     return seastar::do_with(seastar::listen(seastar::make_ipv4_address({1234})),
>             [] (auto& listener) {
>         return seastar::keep_doing([&listener] () {
>             return listener.accept().then(
>                 [] (seastar::connected_socket s, seastar::socket_address a) {
>                     std::cout << "Accepted connection from " << a << "\n";
>                 });
>         });
>     });
> }

**Comment by duarten** [comment]
Did you previously compile seastar?

**Comment by unisqu** [comment]
this is another code. I have another code which works.

i did compile the other code, everything works perfectly. i've gotten some example tutorials online that can run on a port but the generated output is json...

what do you mean by compile seastar? the above
g++ pkg-config --cflags --libs ../seastar/build/release/seastar.pc anotherfile.cc

so long as it's anotherfile.cc <- this one i have which runs json listening port, the above compilation will work but the code example given in tutorial is giving me problem.

**Comment by duarten** [comment]
I mean, did you run ninja-build on the seastar directory to produce the
file "seastar.pc"?

**Comment by unisqu** [comment]
yes i did. how do i compile together with main.cc? sorry been quite some time i've been programming in C++. been a long time actually.

**Comment by nyh** [comment]
This example, and a few others, in the tutorial, were written before it became necessary to write `seastar::future` instead of just `future`. Can you please try changing `future` to `seastar::future` in the code, and see if it helps?

**Comment by unisqu** [comment]
it works when changed from future to seastar::future.

can we pls have a port 80 hello world example / tutorial? thanks.

**Comment by nyh** [comment]
I sent a patch for add the missing seastar namespace in the tutorial.
If you change the number "1234" in the example to "80", it will become a port 80 example :-) 
If you want a full HTTP server, recognizing the HTTP protocol, that's a more elaborate example, perhaps one day someone (I?) will add it to the tutorial. We do have an elaborate HTTP server in Seastar, in the http/ directory, but it may be more than you bargained for (it mixes a pure HTTP server with unrelated stuff like "routing" of requests to different functions, and JSON stuff I'm not even sure what they are ;-)).

**Comment by unisqu** [comment]
yes you are right, i've seen the http/ directory. the routing returns text/json

i would like to know how to return text/html will do. anywhere i can find the answer?

**Comment by nyh** [comment]
Please use the seastar-dev mailing list for such questions. This is a bug tracker, not a mailing list.
