### ISSUE TITLE
Build fail in ubuntu 16.04 and gcc 5.4

### ISSUE THREAD

**Issue by ryanhuang1014** [scylladb/seastar#412]
OS Distribution: Ubuntu 16.04.3 LTS
Linux Kernel Version: 4.4.0
Compiler: g++-5

Build command sequence:
sudo ./install-dependencies.sh
git submodule update --init
./configure --enable-dpdk --compiler=g=++-5 
ninja

Compilation fails with the following error information:
tests/fstream_test.cc: In lambda function:
tests/fstream_test.cc:494:98: error: use of deleted function ‘test_fstream_slow_start::run_test_case()::<lambda()>::<lambda()>::fstream_wrapper::fstream_wrapper(const test_fstream_slow_start::run_test_case()::<lambda()>::<lambda()>::fstream_wrapper&)’
             return fstream_wrapper{make_file_input_stream(file(mock_file), 0, file_size, options)};
                                                                                                  ^
tests/fstream_test.cc:482:20: note: ‘test_fstream_slow_start::run_test_case()::<lambda()>::<lambda()>::fstream_wrapper::fstream_wrapper(const test_fstream_slow_start::run_test_case()::<lambda()>::<lambda()>::fstream_wrapper&)’ is implicitly deleted because the default definition would be ill-formed:
             struct fstream_wrapper {
                    ^
tests/fstream_test.cc:482:20: error: use of deleted function ‘seastar::input_stream<char>::input_stream(const seastar::input_stream<char>&)’
In file included from /home/ryan/project/clang/seastar/core/reactor.hh:26:0,
                 from tests/fstream_test.cc:25:
/home/ryan/project/clang/seastar/core/iostream.hh:199:7: note: ‘seastar::input_stream<char>::input_stream(const seastar::input_stream<char>&)’ is implicitly declared as deleted because ‘seastar::input_stream<char>’ declares a move constructor or move assignment operator
 class input_stream final {
       ^
tests/fstream_test.cc: In lambda function:

**Comment by dorlaor** [comment]
I think that these days its gcc7 and above.

**Comment by ryanhuang1014** [comment]
The problem is fixed.
All things go well with gcc 7.
We should use gcc7 to build the project, and I think the maintainers should update the docs now.

**Comment by wtao0221** [comment]
Hi @dorlaor and @ryanhuang1014 

Do you mean ```./configure.py --compiler=gcc-7 --enable-dpdk```?

However, it does not generate ```ninja.build``` in my case, what's wrong?

**Comment by ryanhuang1014** [comment]
try ./configure.py --compiler=g++-7 --enable-dpdk, it works.

Tao Wang <notifications@github.com> 于2018年6月11日周一 下午11:21写道：

**Comment by wtao0221** [comment]
Hi, @ryanhuang1014 

So how can we run an app in DPDK mode?

Do we need to use the tools in DPDK folder to bind one NIC to IGB_UIO module and pass ```--dpdk-pmd``` to the app?

**Comment by ryanhuang1014** [comment]
Yes, you need to configure DPDK by the usertool.sh under the DPDK
directory.

Tao Wang <notifications@github.com> 于2018年6月12日周二 上午11:43写道：

**Comment by nyh** [comment]
I created issue #465 - the README should have said that gcc 5.4 is not new enough (if it isn't), and what is new enough.
