### ISSUE TITLE
Bad memory detection in containers

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#413]
Seastar uses hwloc which internally uses /proc/meminfo (or an equivalent) which isn't virtualized in containers. This leads to memory over-commit.

We can use `/sys/fs/cgroup/memory/memory.limit_in_bytes` instead (if it is present).

```
$ docker run -it --rm -m 1G centos:7
# cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
1073741824
```

**Comment by penberg** [comment]
We need to be careful with that. I'm seeing this on bare metal...

```
$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
9223372036854771712
```

**Comment by dorlaor** [comment]
We can detect if we're in a container and act differently:
https://stackoverflow.com/questions/20010199/determining-if-a-process-runs-inside-lxc-docker

**Comment by avikivity** [comment]
> 9223372036854771712

that's just a maxint, means no limit.

```
>>> hex(9223372036854771712)
'0x7ffffffffffff000'
```

If we see that value, ignore it.

**Comment by avikivity** [comment]
The algorithm can be

 1. try memory.limit_in_bytes. If it exists, and is smaller than the no-limit value, use it
 2. otherwise, use hwloc

**Comment by penberg** [comment]
@avikivity I think ``min(hwloc, memory.limit_in_bytes)`` is the safest option. Or are there some guarantees that the cgroup limit, if set, is going to be sane?

**Comment by avikivity** [comment]
I have a container with 1TB RAM running on my desktop.
