### ISSUE TITLE
Can we build Seastar on RHEL 7 platform? Is it really platform dependant(Fedora/CentOs/Ubuntu) ??

### ISSUE THREAD

**Issue by praveen-tdna** [scylladb/seastar#414]
Hi All,

I have been trying to build the seastar past two days & i can see lot of library dependencies.
Is it really platform dependant project ??
However, i have proceed with ninja.build with configurations similar to CentOs.

Ninja build takes a lot of time & memory in process building(Current mem: 3.6GB).

Can anyone provide me help to know, Was seastar builded successful anytime as its been failing even in github??

If so, please share your configure details & ninja build file.

**Comment by avikivity** [comment]
Please ask questions on the seastar mailing list. This issue tracker is used for bug reports.
