### ISSUE TITLE
small-task optimization

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#415]
Tasks in Seastar are moved around as `std::unique_ptr<task>`. That allows a stable address for the task object (if the derived class hands out `this` pointers, this is necessary) and occupies just 8 bytes.

However, the majority of tasks are small, usually capturing a `this` pointer and maybe one or two other scalars. We should take advantage of this fact.

We can add 32-byte `task_ptr` that acts in a similar way to `noncopyable_function`: when we capture a small lambda, hold it in the task_ptr object, and when capturing a large lambda, or a non-lambda continuation like the state of `repeat()` and friends, use indirection into the heap. This saves many allocations.

In addition, we can change the task queue to be byte based. Instead of incrementing the indexes by `sizeof(task_ptr)`, increment them by the real task size, reducing memory bandwidth needed to feed the task queue.

```c++
class task_ptr {
    struct vtable {
        void (*run_and_dispose)(storage*) noexcept;
        void (*move_and_dispose)(storage* from, storage* to) noexcept;
        void (*destroy)(storage*) noexcept; // when a promise is abandoned
        size_t storage_size; // can be < 24
    };
    vtable* _vtable;
    union [[gnu::may_alias]] storage {
        char direct[24];
        void* indirect;
    };
public:
    // left as an exercise
};

**Comment by avikivity** [comment]
Ho hum, most tasks contain a promise to forward their results to, and promises contains task_ptrs. We can't have them contain each other.

**Comment by duarten** [comment]
Isn't this very similar to #241? I had some fun with it (https://github.com/duarten/seastar/commits/task-sbo/v0), basically by making a `task` be a `noncopyable_function`, but performance wasn't stellar.

**Comment by avikivity** [comment]
Great minds think alike
