### ISSUE TITLE
How to run multiple memcached instance on one NIC?

### ISSUE THREAD

**Issue by nlfox** [scylladb/seastar#417]
My command:
`sudo ./build/release/apps/memcached/memcached --dpdk-d --network-stack native --smp=1  --dhcp 0 --host-ipv4-addr 192.168.23.2 --netmask-ipv4-addr 255.255.255.0 --port 11211`

The first instance starts fine but when I'm trying to start another instance, I encountered a segfault.
`sudo ./build/release/apps/memcached/memcached --dpdk-d --network-stack native --smp=1  --dhcp 0 --host-ipv4-addr 192.168.23.2 --netmask-ipv4-addr 255.255.255.0 --port 11212`

> EAL: Detected 40 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 15b3:1013 net_mlx5
PMD: net_mlx5: PCI information matches, using device "mlx5_0" (SR-IOV: false, MPS: false)
PMD: net_mlx5: 1 port(s) detected
Segmentation fault.
Backtrace:
  0x00000000005805a4
  0x00000000005806d8
  0x0000000000580743
  0x00007f6686fc832f
  0x000000000075a202
  0x000000000068be6c
  0x000000000067ca0b
  0x0000000000755a3c
  0x0000000000755fc1
  0x0000000000749f54
  0x00000000006471a2
  0x00000000005d096e
  0x00000000006403bb
  0x000000000041431e
  0x00007f6686c10f44
  0x000000000041693a

**Comment by avikivity** [comment]
Please ask questions on the mailing list. This issue tracker is for tracking bugs.
