### ISSUE TITLE
Seastar Project Build Taking Too Much Hightime

### ISSUE THREAD

**Issue by praveen-tdna** [scylladb/seastar#419]
Hi All,

I'm trying to build seastar framewrok in CentOs(7.4) compiling since noon(5 hrs ago).

On building the project with ninja, CPU usage is going almost 80-90% most of time & its building only 1/2 dependancies only for 20 mins.
So, please let me know the actual timetaken to build the complete project right from scratch / after ninja build start.

Is it normally consumes very huge time for building complete project??
Then how comes it is High Performance Framework???

project is cloned from github master branch, So most of latest updates are present.

Below are my findings & system details.
Please, Let me know whether existing hardware is suitable to project / Share the Required hardware details.

Build Details
===============
[root@localhost seastar]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[root@localhost seastar]#
[root@localhost seastar]# ./configure.py --compiler=/opt/scylladb/bin/g++-7.2 --static-stdc++
[root@localhost seastar]#
[root@localhost seastar]#
[root@localhost seastar]# ninja-build >> output &
[1] 8169
[root@localhost seastar]#
[root@localhost seastar]#
[root@localhost seastar]# tail -f output
[1/261] LINK build/release/apps/iotune/iotune
[2/261] CXX build/release/net/stack.o
[3/261] CXX build/release/core/thread.o
[4/261] CXX build/release/tests/test_runner.o

============
top - 06:06:16 up 15:01,  2 users,  load average: 5.97, 7.30, 5.44
Tasks: 187 total,   3 running, 184 sleeping,   0 stopped,   0 zombie
%Cpu(s):  23.5/0.7    24[||||||||||||||||||||||||                                                                            ]
KiB Mem :  3876408 total,   794308 free,  2934244 used,   147856 buff/cache
KiB Swap: 16383996 total, 14548376 free,  1835620 used.   726108 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 5574 root      20   0  936120 750432  10976 R  99.0 19.4   0:34.80 cc1plus
 5568 root      20   0  922468 660492  10524 R  90.1 17.0   0:18.31 cc1plus
 5569 root      20   0  942572 664500   3676 D   2.6 17.1   0:16.45 cc1plus
 5570 root      20   0 1579328 641508   2700 D   0.7 16.5   0:34.23 cc1plus
 5589 root      20   0  157720   1320    584 R   0.3  0.0   0:01.59 top
    1 root      20   0  193840   1856    484 S   0.0  0.0   0:04.30 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.01 kthreadd
 
 
 
top - 07:35:12 up 16:30,  2 users,  load average: 1.70, 0.79, 2.99
Tasks: 197 total,  11 running, 186 sleeping,   0 stopped,   0 zombie
%Cpu(s):  88.0/8.6    97[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||   ]
KiB Mem :  3876408 total,   520104 free,  2928316 used,   427988 buff/cache
KiB Swap: 16383996 total, 16304532 free,    79464 used.   679872 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6580 root      20   0  442344 298324   7912 R  91.4  7.7   0:04.63 cc1plus
 6566 root      20   0  443016 294868   7772 R  88.4  7.6   0:04.70 cc1plus
 6563 root      20   0  442960 294728   7720 R  88.0  7.6   0:04.60 cc1plus
 6565 root      20   0  445612 299016   7704 R  85.0  7.7   0:04.68 cc1plus
 6577 root      20   0  450488 303656   8072 R  84.4  7.8   0:04.95 cc1plus
 6561 root      20   0  441416 293168   7700 R  80.7  7.6   0:04.57 cc1plus
 6571 root      20   0  428968 282376   7760 R  76.1  7.3   0:04.10 cc1plus
 6574 root      20   0  407240 257472   7712 R  69.4  6.6   0:04.11 cc1plus
 6562 root      20   0  472288 309460   7664 R  63.5  8.0   0:03.79 cc1plus
 6564 root      20   0  415528 252236   5840 R  44.9  6.5   0:03.05 cc1plus
 5589 root      20   0  157720   1052    576 R   0.7  0.0   0:13.15 top

CPU Details
============
processor       : 7(Total)
model name      : Intel(R) Xeon(R) CPU  E5410  @ 2.33GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 2327.444
cache size      : 6144 KB
physical id     : 1
siblings        : 4
core id         : 3
cpu cores       : 4
bogomips        : 4655.05
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual

Thanks,
Praveen Kumar V

**Comment by avikivity** [comment]
Please post questions to the mailing list. This bug tracker is for tracking bugs.
