### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [scylladb/seastar#42]
I would like to point out that identifiers like "[`_APP_TEMPLATE_HH`](https://github.com/cloudius-systems/seastar/blob/5bc8d7cfadb78caf37b47e1bd351852c52de04d1/core/app-template.hh#L21)" and "[`_MEMCACHED_HH`](https://github.com/cloudius-systems/seastar/blob/5bc8d7cfadb78caf37b47e1bd351852c52de04d1/apps/memcached/memcached.hh#L18)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by nyh** [comment]
On Tue, Apr 28, 2015 at 3:24 PM, Markus Elfring <notifications@github.com>
wrote:

> I would like to point out that identifiers like "_APP_TEMPLATE_HH
> <https://github.com/cloudius-systems/seastar/blob/5bc8d7cfadb78caf37b47e1bd351852c52de04d1/core/app-template.hh#L21>"
> and "_MEMCACHED_HH
> <https://github.com/cloudius-systems/seastar/blob/5bc8d7cfadb78caf37b47e1bd351852c52de04d1/apps/memcached/memcached.hh#L18>"
> do not fit
> <https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29>
> to the expected naming convention of the C++ language standard.
> Would you like to adjust your selection for unique names?
>
My personal preference is just to use "#pragma once", and we do use it in
quite a few header files.

"#pragma once" isn't standard C++, but all the compilers I tried seem to
support it well, and it's (in my opinion) much less ugly and error-prone
than those include guards.

**Comment by hakuch** [comment]
This is fixed as of 61c905cf7fe69ddcb1bbd9fe8caa493eb41b8a85.
