### ISSUE TITLE
About the contributing to Seastar.

### ISSUE THREAD

**Issue by hellowaywewe** [scylladb/seastar#431]
Hi,
I have submitted the patch entitled "Modify the doc file to make seastar build successfully with gcc 7 in Ubuntu" by git send-email last week. However, I don't know whether I send successfully. Does anyone can help me? If it is not successful, please tell me how to do it correctlly. And if successful, can anybody review it?  Any response is appreciated.

**WedeMacBook-Pro:seastar wewe$** git send-email --to scylladb-dev@googlegroups.com 0001-Modify-the-doc-file-to-make-seastar-build-successful.patch
0001-Modify-the-doc-file-to-make-seastar-build-successful.patch
The following files are 8bit, but do not declare a Content-Transfer-Encoding.
    0001-Modify-the-doc-file-to-make-seastar-build-successful.patch
Which 8bit encoding should I declare [UTF-8]? 
(mbox) Adding cc: heluwei <simple_hlw@163.com> from line 'From: heluwei <simple_hlw@163.com>'
(body) Adding cc: heluwei <simple_hlw@163.com> from line 'Signed-off-by: heluwei <simple_hlw@163.com>'

From: heluwei <simple_hlw@163.com>
To: scylladb-dev@googlegroups.com
Cc: heluwei <simple_hlw@163.com>
Subject: [PATCH] Modify the doc file to make seastar build successfully with gcc 7 in Ubuntu
Date: Sun,  8 Apr 2018 11:22:04 +0800
Message-Id: <20180408032204.10447-1-simple_hlw@163.com>
X-Mailer: git-send-email 2.13.5 (Apple Git-94)
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

    The Cc list above has been expanded by additional
    addresses found in the patch commit message. By default
    send-email prompts before sending whenever this occurs.
    This behavior is controlled by the sendemail.confirm
    configuration setting.

    For additional information, run 'git send-email --help'.
    To retain the current behavior, but squelch this message,
    run 'git config --global sendemail.confirm auto'.

Send this email? ([y]es|[n]o|[q]uit|[a]ll): y
OK. Log says:
Sendmail: /usr/sbin/sendmail -i scylladb-dev@googlegroups.com simple_hlw@163.com
From: heluwei <simple_hlw@163.com>
To: scylladb-dev@googlegroups.com
Cc: heluwei <simple_hlw@163.com>
Subject: [PATCH] Modify the doc file to make seastar build successfully with gcc 7 in Ubuntu
Date: Sun,  8 Apr 2018 11:22:04 +0800
Message-Id: <20180408032204.10447-1-simple_hlw@163.com>
X-Mailer: git-send-email 2.13.5 (Apple Git-94)
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Result: OK

**WedeMacBook-Pro:seastar wewe$** git log
commit 995f6c02d9df839e8f28734f369f314c2bbcdb9a (HEAD -> features/foo)
Author: heluwei <simple_hlw@163.com>
Date:   Wed Apr 4 17:35:41 2018 +0800

    Modify the doc file to make seastar build successfully with gcc 7 in Ubuntu
    
    Signed-off-by: heluwei <simple_hlw@163.com>

Thx,
Helloway

**Comment by avikivity** [comment]
Please post questions to the mailing list. This bug tracker is for tracking bugs.
