### ISSUE TITLE
perftune.py causes 'ERROR: invalid literal for int() with base 16'

### ISSUE THREAD

**Issue by syuu1228** [scylladb/seastar#432]
Related with scylladb/scylla#3339, on i3.16xlarge(64vcpus) with Scylla master AMI(ami-1c01a161) we get following error when running /usr/lib/scylla/perftune.py --nic eth0 --get-cpu-mask --tune net:
```
ERROR: invalid literal for int() with base 16: '0x00000001,0x00000001'. Your system can't be tuned until the issue is fixed.
```

Maybe cpu mask format was different than the script expected, since it has > 32 cpus?

Here's traceback of python:
```
[centos@ip-172-16-99-196 ~]$ sudo  /usr/lib/scylla/perftune.py --nic eth0 --get-cpu-mask --tune net
Traceback (most recent call last):
  File "/usr/lib/scylla/perftune.py", line 939, in <module>
    mode = min([ tuner.mode for tuner in tuners ])
  File "/usr/lib/scylla/perftune.py", line 939, in <listcomp>
    mode = min([ tuner.mode for tuner in tuners ])
  File "/usr/lib/scylla/perftune.py", line 262, in mode
    self.__set_mode_and_masks()
  File "/usr/lib/scylla/perftune.py", line 338, in __set_mode_and_masks
    self.mode = self._get_def_mode()
  File "/usr/lib/scylla/perftune.py", line 274, in mode
    self.__irq_cpu_mask = PerfTunerBase.irqs_cpu_mask_for_mode(self.__mode, self.__args.cpu_mask)
  File "/usr/lib/scylla/perftune.py", line 250, in irqs_cpu_mask_for_mode
    if int(irqs_cpu_mask, 16) == 0:
ValueError: invalid literal for int() with base 16: '0x00000001,0x00000001'

ERROR: invalid literal for int() with base 16: '0x00000001,0x00000001'. Your system can't be tuned until the issue is fixed.
```

@vladzcloudius Could you take a look?

**Comment by vladzcloudius** [comment]
On Mon, Apr 9, 2018, 7:19 AM Takuya ASADA <notifications@github.com> wrote:

> Related with scylladb/scylla#3339
> <https://github.com/scylladb/scylla/issues/3339>, on i3.16xlarge(64vcpus)
> with Scylla master AMI(ami-1c01a161) we get following error when running
> /usr/lib/scylla/perftune.py --nic eth0 --get-cpu-mask --tune net:
>
> ERROR: invalid literal for int() with base 16: '0x00000001,0x00000001'. Your system can't be tuned until the issue is fixed.
>
> Maybe cpu mask format was different than the script expected, since it has
> > 32 cpus?
>

I have a patch with the fix that I'll send once the previous perftune.py
series is applied (in order to avoid conflicts).

Here's traceback of python:

**Comment by glommer** [comment]
Is this fixed? @vladzcloudius @syuu1228

**Comment by vladzcloudius** [comment]
Yup: fcf4b6c3ecfd59907f00b4635c0a3e36b4b86b3f

**Comment by glommer** [comment]
@syuu1228 please close
