### ISSUE TITLE
How to submit task to reactor thread from 3rd library thread

### ISSUE THREAD

**Issue by enjoycode** [scylladb/seastar#433]
I have a 3rd party library, it's create a thread do long time work, 
like: seastar reactor thread -> call 3rd lib -> 3rd lib create thread and run, when done , it run callback
the question is how to notify or submit task to reactor thread by callback?

PS. I try to use seastar's syscall thread invoke 3rd lib, but need wait 3rd lib callback done.

**Comment by avikivity** [comment]
Please use the mailing list for questions, not the issue tracker.

See https://groups.google.com/d/topic/seastar-dev/ft09LXwMY_4/discussion for a proposal.
