### ISSUE TITLE
Can Seastar be built and run on ARM?

### ISSUE THREAD

**Issue by hellowaywewe** [scylladb/seastar#443]
Hi all,

Could anyone can tell me whether Seastar can be built and run on ARM? Could you please provide some reference documents （such as: How does Seastar maximize the use of ARM features?） for me to read? 
Any answers are appreciated.

Thanks,
Helloway

**Comment by dorlaor** [comment]
It works with Arm, @vladzcloudius can help you and worth to have a wiki on it

**Comment by vladzcloudius** [comment]
@hellowaywewe There is nothing special in the build process for ARM. The only requirement is that EXPEDITED mode for sys_membarrier syscall - while this is optional for x86 and Power, this a requirement for ARM.

Except for that we we don't anything explicitly ARM-specific, however I assume that `g++` and standard C++ libraries ARM ports will be properly tuned to get the best out of it.

**Comment by hellowaywewe** [comment]
@vladzcloudius @dorlaor thanks a lot.
