### ISSUE TITLE
Supporting Database for Seastar Memcache

### ISSUE THREAD

**Issue by SungHoHong2** [scylladb/seastar#444]
Hello Seastar Team, 
I am trying to use the Seastar Memcache, 
Would you identify which Databases are supported by Seastar Memcache? 
Is it only NOSQL that is mentioned in the project website?

**Comment by tgrabiec** [comment]
@SungHoHong2 Please use the mailing list for posting questions in the future.

sesatar memcached is an implementation of memcached (https://memcached.org/), and is compatible with it on the protocol level (https://github.com/memcached/memcached/wiki/Commands), so any memcached client should work with it. Not sure what you mean by "supported databases" in this context.
