### ISSUE TITLE
iotune fails on loop devices on centos kernels

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#449]
iotune expects the queue/scheduler sysfs file to look like

    foo bar [quux] blah

but on centos loop devices it's

    none

with no `[]`. Maybe it's because it's the only scheduler available, or some other inconsistency.

**Comment by avikivity** [comment]
(failes with std::string::substr throwing out_of_range)

**Comment by glommer** [comment]
At least on my box, can't reproduce this. Tried a loop device both sitting on a disk and sitting on a tmpfs mount.

iotune claims:

```
/sys/devices/virtual/block/loop0/queue/scheduler set to mq-deadline
```

which is consistent with my previous testing. I can send a patch if you're willing to test it.
