### ISSUE TITLE
I/O schedulers may have to be nested

### ISSUE THREAD

**Issue by glommer** [scylladb/seastar#468]
We support multiple I/O Schedulers now, but they may have to be nested.

The reason being that there may be global limits that apply to some of the schedulers. For instance, different disks may sit at the same controller, and the controller will impose transfer limits.

**Comment by senior7515** [comment]
is nested == hierarchical ?

**Comment by glommer** [comment]
Yes -- if we find that two devices sit on a limited controller, for
instance, it may be required to have a scheduler for the controller with
subschedulers for the devices

**Comment by xemul** [comment]
Dup of #1069 + #1070
