### ISSUE TITLE
Function pure_check_for_work() seems never run

### ISSUE THREAD

**Issue by lmsreborn** [scylladb/seastar#472]
https://github.com/scylladb/seastar/blob/3e7e47aa2e3394b01363e77393987eb9d88e0f39/core/reactor.hh#L828

https://github.com/scylladb/seastar/blob/7d073eb0e7bb68fc6e3bfc3913da2cf0e2cb5ca9/core/reactor.cc#L3263

It seems that `handler_result` is always `idle_cpu_handler_result::no_more_work`......

I only find `engine().set_idle_cpu_handler` in Scylladb's `main`function.

https://github.com/scylladb/scylla/blob/a45c3aa8c73a2a57df43d7f685f50f0e94e3ce31/main.cc#L744

**Comment by tgrabiec** [comment]
It can be called from the callback installed through `set_idle_cpu_handler()`, which is a way in which seastar allows applications to install idle-time workers. It has no within-seastar users, and that's fine, except that it would be nice if it was unit tested.

Why is this an issue?

**Comment by lmsreborn** [comment]
I see. Thanks for your explanation.😆
