### ISSUE TITLE
compile failed on centos

### ISSUE THREAD

**Issue by tangwenjun3** [scylladb/seastar#478]
i am new learner , i just want know how to solve the problem.

my command
python3 configure.py --compiler=/opt/scylladb/bin/g++-7.3   --static-stdc++  --mode release
ninja-build 

FAILED: build/debug/core/reactor.o
/opt/scylladb/bin/g++-7.3 -MD -MT build/debug/core/reactor.o -MF build/debug/core/reactor.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_ASAN_ENABLED -O0 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_NO_EXCEPTION_HACK -DSEASTAR_SHUFFLE_TASK_QUEUE -I/home/seastar/build/debug/gen -I/home/seastar/build/debug/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden -Wno-attributes -pthread -I/home/seastar -U_FORTIFY_SOURCE  -fconcepts -I/home/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-error=cpp -Wno-stringop-overflow -DSEASTAR_HAVE_GCC6_CONCEPTS -DSEASTAR_NO_EXCEPTION_HACK -DNO_EXCEPTION_INTERCEPT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -c -o build/debug/core/reactor.o core/reactor.cc
core/reactor.cc: In instantiation of ‘seastar::syscall_result_extra<Extra> seastar::wrap_syscall(int, const Extra&) [with Extra = stat]’:
core/reactor.cc:2024:36:   required from here
core/reactor.cc:287:33: error: could not convert ‘{result, (* __errno_location()), extra}’ from ‘<brace-enclosed initializer list>’ to ‘seastar::syscall_result_extra<stat>’
     return {result, errno, extra};
                                 ^
core/reactor.cc: In instantiation of ‘seastar::syscall_result_extra<Extra> seastar::wrap_syscall(int, const Extra&) [with Extra = statfs]’:
core/reactor.cc:2070:36:   required from here
core/reactor.cc:287:33: error: could not convert ‘{result, (* __errno_location()), extra}’ from ‘<brace-enclosed initializer list>’ to ‘seastar::syscall_result_extra<statfs>’
core/reactor.cc: In instantiation of ‘seastar::syscall_result_extra<Extra> seastar::wrap_syscall(int, const Extra&) [with Extra = long unsigned int]’:
core/reactor.cc:2338:38:   required from here
core/reactor.cc:287:33: error: could not convert ‘{result, (* __errno_location()), extra}’ from ‘<brace-enclosed initializer list>’ to ‘seastar::syscall_result_extra<long unsigned int>’

**Comment by heguanjun** [comment]
is this issuse resoved?thanks.
