### ISSUE TITLE
master branch's latest code compile failed on centos 7.5

### ISSUE THREAD

**Issue by heguanjun** [scylladb/seastar#483]
master branch's latest code build error in centos 7.5

error info:

[13/352] CXX build/debug/core/reactor.o
FAILED: build/debug/core/reactor.o 
/opt/scylladb/bin/g++ -MD -MT build/debug/core/reactor.o -MF build/debug/core/reactor.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_ASAN_ENABLED -O0 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_NO_EXCEPTION_HACK -DSEASTAR_SHUFFLE_TASK_QUEUE -I/root/sea-official/seastar/build/debug/gen -I/root/sea-official/seastar/build/debug/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden -Wno-attributes -pthread -I/root/sea-official/seastar -U_FORTIFY_SOURCE  -fconcepts -I/root/sea-official/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-ignored-attributes -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-error=cpp -Wno-stringop-overflow -DSEASTAR_HAVE_GCC6_CONCEPTS -DSEASTAR_NO_EXCEPTION_HACK -DNO_EXCEPTION_INTERCEPT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -c -o build/debug/core/reactor.o core/reactor.cc
core/reactor.cc: In instantiation of ‘seastar::syscall_result_extra<Extra> seastar::wrap_syscall(int, const Extra&) [with Extra = stat]’:
core/reactor.cc:2024:36:   required from here
core/reactor.cc:287:33: error: could not convert ‘{result, (* __errno_location()), extra}’ from ‘<brace-enclosed initializer list>’ to ‘seastar::syscall_result_extra<stat>’
     return {result, errno, extra};
                                 ^
core/reactor.cc: In instantiation of ‘seastar::syscall_result_extra<Extra> seastar::wrap_syscall(int, const Extra&) [with Extra = statfs]’:
core/reactor.cc:2070:36:   required from here
core/reactor.cc:287:33: error: could not convert ‘{result, (* __errno_location()), extra}’ from ‘<brace-enclosed initializer list>’ to ‘seastar::syscall_result_extra<statfs>’
core/reactor.cc: In instantiation of ‘seastar::syscall_result_extra<Extra> seastar::wrap_syscall(int, const Extra&) [with Extra = long unsigned int]’:
core/reactor.cc:2338:38:   required from here
core/reactor.cc:287:33: error: could not convert ‘{result, (* __errno_location()), extra}’ from ‘<brace-enclosed initializer list>’ to ‘seastar::syscall_result_extra<long unsigned int>’
[22/352] CXX build/debug/tests/tls_test.o
ninja: build stopped: subcommand failed.

**Comment by leifjackson** [comment]
might help but I just found master requires gcc/c++ 7 as found in the .travis.yml config and master mostly builds a few test apps don't link/compile but the library compiles hope that helps.

**Comment by duarten** [comment]
Try to update GCC and compile with C++17 dialect; this seems to be an issue when building with C++14 dialect.

**Comment by leifjackson** [comment]
so I did:
on ubuntu 16.04 LTS after installing gcc/g++ 7 from the ubuntu test toolchain repo

./configure.py --enable-dpdk --compiler=g++-7 --c-compiler=gcc-7 --c++-dialect="gnu++17"

then the ninja build completed building all but the tests/circular_buffer_fixed_capacity_test
 which fails with what looks like a LD flag concat issue?

[43/399] LINK (stripped) build/debug/tests/circular_buffer_fixed_capacity_test
FAILED: g++-7  -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_ASAN_ENABLED -O0 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_NO_EXCEPTION_HACK -DSEASTAR_SHUFFLE_TASK_QUEUE -I/home/leif/sources/seastar/build/debug/gen -I/home/leif/sources/seastar/build/debug/c-ares -s -Lbuild/debug -Lbuild/debug/fmt/fmt -g -Wl,--no-as-needed   -fvisibility=hidden  -pthread  -o build/debug/tests/circular_buffer_fixed_capacity_test build/debug/tests/circular_buffer_fixed_capacity_test.o -lboost_program_options -lboost_system -lboost_filesystem -lstdc++ -lm -lstdc++fs -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -llz4 -lprotobuf -ldl -lgcc_s  -lyaml-cpp -L/home/leif/sources/seastar/build/dpdk/lib -Wl,--whole-archive -lrte_pmd_vmxnet3_uio -lrte_pmd_i40e -lrte_pmd_ixgbe -lrte_pmd_e1000 -lrte_pmd_ring -lrte_pmd_bnxt -lrte_pmd_cxgbe -lrte_pmd_ena -lrte_pmd_enic -lrte_pmd_fm10k -lrte_pmd_nfp -lrte_pmd_qede -lrte_pmd_sfc_efx -lrte_hash -lrte_kvargs -lrte_mbuf -lrte_ethdev -lrte_eal -lrte_mempool -lrte_mempool_ring -lrte_ring -lrte_cmdline -lrte_cfgfile -Wl,--no-whole-archive -lrt -lm -ldl -lhwloc -lnuma -lpciaccess -lxml2 -lz -lcares-seastar -lfmt -lasan -lubsan  -lyaml-cpp
/usr/bin/ld: unrecognized option '--push-state--no-as-needed'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
[43/399] CXX build/debug/apps/io_tester/io_tester.o
ninja: build stopped: subcommand failed.

some googling notes that ld from binutils on 16.04 maybe too old, however as noted we can use the library and test apps even with this test build failure.

for ref on the ld issue was found in https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed

**Comment by heguanjun** [comment]
thanks durarten.
with follwoing configure ,everything works fine:
./configure.py --compiler=/opt/scylladb/bin/g++-7.3  --c-compiler=gcc-7 --c++-dialect="gnu++17"

**Comment by heguanjun** [comment]
Is there any work I can do to make the build more friendly to centos 7.5 or above ?thanks.

**Comment by heguanjun** [comment]
Is there any work I can do to make the build more friendly to centos 7.5 or above ?thanks.

**Comment by duarten** [comment]
We should only have to specify the compiler if there is more than one available. The dialect is chosen automatically based on what the compiler supports, so it could be omitted.

**Comment by heguanjun** [comment]
seems like --c++-dialect="gnu++17" must be configured.

```
[root@localhost seastar]# ./configure.py --enable-dpdk --compiler=/opt/scylladb/bin/g++-7.3 --c-compiler=/opt/scylladb/bin/gcc-7.3
make: Entering directory `/root/sea-official/seastar/dpdk'
Configuration done
make: Leaving directory `/root/sea-official/seastar/dpdk'
Notice: -fsanitize=vptr is broken, disabling; some debug mode tests are bypassed.
Notice: disabling -Wattributes due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80947
[root@localhost seastar]# ninja-build 
[3/385] make -C build/debug/c-ares CC=/opt/scylladb/bin/gcc-7.3
...
[63/385] CXX build/debug/core/reactor.o
FAILED: build/debug/core/reactor.o 
/opt/scylladb/bin/g++-7.3 -MD -MT build/debug/core/reactor.o -MF build/debug/core/reactor.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_ASAN_ENABLED -O0 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_NO_EXCEPTION_HACK -DSEASTAR_SHUFFLE_TASK_QUEUE -I/root/sea-official/seastar/build/debug/gen -I/root/sea-official/seastar/build/debug/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden -Wno-attributes -pthread -I/root/sea-official/seastar -U_FORTIFY_SOURCE  -fconcepts -DSEASTAR_HAVE_DPDK -I/root/sea-official/seastar/build/dpdk/include -march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_MACHINE_CPUFLAG_AES -DRTE_MACHINE_CPUFLAG_PCLMULQDQ -DRTE_MACHINE_CPUFLAG_AVX -DRTE_MACHINE_CPUFLAG_RDRAND -DRTE_MACHINE_CPUFLAG_FSGSBASE -DRTE_MACHINE_CPUFLAG_F16C -DRTE_MACHINE_CPUFLAG_AVX2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -I/root/sea-official/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-ignored-attributes -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-error=cpp -Wno-stringop-overflow -DSEASTAR_HAVE_GCC6_CONCEPTS -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -c -o build/debug/core/reactor.o core/reactor.cc
core/reactor.cc: In instantiation of ‘seastar::syscall_result_extra<Extra> seastar::wrap_syscall(int, const Extra&) [with Extra = stat]’:
core/reactor.cc:2024:36:   required from here
core/reactor.cc:287:33: error: could not convert ‘{result, (* __errno_location()), extra}’ from ‘<brace-enclosed initializer list>’ to ‘seastar::syscall_result_extra<stat>’
     return {result, errno, extra};
                                 ^
core/reactor.cc: In instantiation of ‘seastar::syscall_result_extra<Extra> seastar::wrap_syscall(int, const Extra&) [with Extra = statfs]’:
core/reactor.cc:2070:36:   required from here
core/reactor.cc:287:33: error: could not convert ‘{result, (* __errno_location()), extra}’ from ‘<brace-enclosed initializer list>’ to ‘seastar::syscall_result_extra<statfs>’
core/reactor.cc: In instantiation of ‘seastar::syscall_result_extra<Extra> seastar::wrap_syscall(int, const Extra&) [with Extra = long unsigned int]’:
core/reactor.cc:2338:38:   required from here
core/reactor.cc:287:33: error: could not convert ‘{result, (* __errno_location()), extra}’ from ‘<brace-enclosed initializer list>’ to ‘seastar::syscall_result_extra<long unsigned int>’
[72/385] CXX build/debug/net/tls.o
ninja: build stopped: subcommand failed.
```

**Comment by duarten** [comment]
Oh, that's a bug in our `configure.py`. With this change it should work:

```diff
diff --git a/configure.py b/configure.py
index 9f6c6c10..ec7446b9 100755
--- a/configure.py
+++ b/configure.py
@@ -322,13 +322,6 @@ extralibs = {

 all_artifacts = apps + tests + ['libseastar.a', 'seastar.pc', 'fmt/fmt/libfmt.a']

-cpp_dialects = ['gnu++17', 'gnu++1z', 'gnu++14', 'gnu++1y']
-try:
-    default_cpp_dialect = [x for x in cpp_dialects if dialect_supported(x, compiler='g++')][0]
-except:
-    # if g++ is not available, fallback to something safe-ish
-    default_cpp_dialect='gnu++1y'
-
 arg_parser = argparse.ArgumentParser('Configure seastar')
 arg_parser.add_argument('--static', dest = 'static', action = 'store_const', default = '',
                         const = '-static',
@@ -349,7 +342,7 @@ arg_parser.add_argument('--compiler', action = 'store', dest = 'cxx', default =
                         help = 'C++ compiler path')
 arg_parser.add_argument('--c-compiler', action='store', dest='cc', default='gcc',
                         help = 'C compiler path (for bundled libraries such as dpdk and c-ares)')
-arg_parser.add_argument('--c++-dialect', action='store', dest='cpp_dialect', default=default_cpp_dialect,
+arg_parser.add_argument('--c++-dialect', action='store', dest='cpp_dialect', default='',
                         help='C++ dialect to build with [default: %(default)s]')
 arg_parser.add_argument('--with-osv', action = 'store', dest = 'with_osv', default = '',
                         help = 'Shortcut for compile for OSv')
@@ -385,6 +378,15 @@ arg_parser.add_argument('--use-std-optional-variant-stringview', dest='cpp17_goo
                         help='Use C++17 std types for optional, variant, and string_view. Requires C++17 dialect and GCC >= 8.1.1-5')
 args = arg_parser.parse_args()

+
+if args.cpp_dialect == '':
+    cpp_dialects = ['gnu++17', 'gnu++1z', 'gnu++14', 'gnu++1y']
+    try:
+        args.cpp_dialect = [x for x in cpp_dialects if dialect_supported(x, compiler=args.cxx)][0]
+    except:
+        # if g++ is not available, fallback to something safe-ish
+        args.cpp_dialect='gnu++1y'
+
 # Forwarding to CMake.
 if args.cmake:
     MODES = seastar_cmake.SUPPORTED_MODES if args.mode is 'all' else [args.mode]
```

**Comment by heguanjun** [comment]
duarten,it woks fine with the patch.
