### ISSUE TITLE
any pointers on how one would peek socket bytes on server accept ?

### ISSUE THREAD

**Issue by leifjackson** [scylladb/seastar#484]
I need to be able to peek the first few hundred bytes on tcp accept to check for a prefixed header before then wrapping the connected_socket with tls. How would something like this be done in seastar framework?

**Comment by duarten** [comment]
Please ask questions over the [mailing list](seastar-dev@googlegroups.com), not over the bug tracker.

You have the `wrap_server` and `wrap_client` functions that wrap an existing connection in TLS.

**Comment by leifjackson** [comment]
moved to topic https://groups.google.com/forum/#!topic/seastar-dev/uAz2_byMXUM
