### ISSUE TITLE
Is there any plan to adopt traditional networking apps?

### ISSUE THREAD

**Issue by heguanjun** [scylladb/seastar#487]
Is there any plan to adopt traditional networking apps?
for exmaple, traditional networking apps no need to change ,just pre-load a seastar lib,then traditional networking apps get on the train,and get benefit from seastar.

**Comment by duarten** [comment]
I don't know what you mean by tradicional networking apps, nor how could they be run on seastar without being design for that. 

Anyway, please ask questions over the [mailing list](https://github.com/scylladb/seastar/issues/seastar-dev@googlegroups.com), not over the bug tracker.

**Comment by nyh** [comment]
Anyway, the answer to your original question is not unmodified applications: Seastar is a library for writing new applications, which are designed to use its new asynchronous APIs, single thread per core and sharded memory (see http://nadav.harel.org.il/seastar/ for more information). An existing application written using many threads, the socket API, and shared memory and locking, will need to be significantly modified to use Seastar. This is of course possible, and recommended: We demonstrated that in the Scylladb projec, which ported Cassandra to Seastar. Other people did this for redis, memcached, and some other applications. And the performance rewards are, well, amazing.

**Comment by heguanjun** [comment]
Thanks a lot.
