### ISSUE TITLE
Seastar for a new release?

### ISSUE THREAD

**Issue by daoliker** [scylladb/seastar#491]
I want to use a stable version of seastar on my project, but I only got the **seastar-17.05-branch** and the latest commit date is **_April 30, 2017_** which is too old. Also the github said:

> This branch is **746 commits behind** master.

In addition when I see the [seastar tutorial](http://docs.seastar.io/master/md_doc_tutorial.html), It seems based on a new version(aka master), For example, the tutorial says:

>  all Seastar functions and types live in the `seastar` namespace.An user can either type this namespace prefix every time, such as seastar::app_template.

However when I use seastar::app_template in the seastar-17.05-branch, I got a error because **there is no namespace `seastar` in this release(seastar-17.05-branch)**. 

I think the new update is better for several reasons, such as using `seastar` namespace to avoid name conflict.

So could the authors consider to provide **a new release branch** for us ?

**Comment by avikivity** [comment]
The recommended way to consume seastar is via a submodule. However, asking for a release is reasonable.

**Comment by avikivity** [comment]
18.08.0 was released.
