### ISSUE TITLE
Build in Ubuntu VM fails : net/tls.cc

### ISSUE THREAD

**Issue by armandjordaan** [scylladb/seastar#494]
I have Xubuntu 18.04 set up in a Virtualbox VM, but I find that the build from the master branch fails:

Here is the output:

[39/390] CXX build/debug/net/tls.o
FAILED: build/debug/net/tls.o 
g++-5 -MD -MT build/debug/net/tls.o -MF build/debug/net/tls.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_ASAN_ENABLED -O0 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_NO_EXCEPTION_HACK -DSEASTAR_SHUFFLE_TASK_QUEUE -I/home/armand/Projects/tvserver/seastar/build/debug/gen -I/home/armand/Projects/tvserver/seastar/build/debug/c-ares -std=gnu++17 -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/home/armand/Projects/tvserver/seastar -U_FORTIFY_SOURCE  -I/home/armand/Projects/tvserver/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-error=cpp -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -c -o build/debug/net/tls.o net/tls.cc
net/tls.cc: In instantiation of ‘seastar::tls::session::handle_output_error(int)::<lambda(auto:31)> [with auto:31 = seastar::future<>]’:
/usr/include/c++/5/type_traits:2346:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__success_type<decltype (declval<_Fn>()((declval<_Args>)()...))> std::__result_of_other_impl::_S_test(int) [with _Fn = seastar::tls::session::handle_output_error(int)::<lambda(auto:31)>; _Args = {seastar::future<>}]’
/usr/include/c++/5/type_traits:2357:55:   required from ‘struct std::__result_of_impl<false, false, seastar::tls::session::handle_output_error(int)::<lambda(auto:31)>, seastar::future<> >’
/usr/include/c++/5/type_traits:2361:12:   required from ‘class std::result_of<seastar::tls::session::handle_output_error(int)::<lambda(auto:31)>(seastar::future<>)>’
/home/armand/Projects/tvserver/seastar/core/future.hh:991:30:   required by substitution of ‘template<class Func, class Result> Result seastar::future<T>::then_wrapped(Func&&) [with Func = seastar::tls::session::handle_output_error(int)::<lambda(auto:31)>; Result = <missing>]’
net/tls.cc:910:10:   required from here
net/tls.cc:906:36: error: cannot call member function ‘seastar::future<> seastar::tls::session::handle_error(int)’ without object
                 return handle_error(res);

[40/390] CXX build/debug/net/dns.o
ninja: build stopped: subcommand failed.

Any help to get pass this step would be greatly appreciated.

**Comment by chulup** [comment]
Build is broken with gcc-5: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67274
I am able to build it with gcc-8 currently, did not try other versions.

**Comment by zyfjeff** [comment]
I also met the same problem, upgrade to g + + - 8 settled, it should be clear in the document

**Comment by nyh** [comment]
Closing. Seastar is no longer usable with gcc 5 anyway...
