### ISSUE TITLE
config.h generated from incorrect .config

### ISSUE THREAD

**Issue by krisk0** [scylladb/seastar#513]
Sorry for my previous stupid bug report.

When I build seastar with DPDK, my `rte_config.h` is invalid (does not match settings changed by `configure.py`). For instance, RTE_MBUF_REFCNT_ATOMIC is 1, which triggers warnings
```
/tmp/bu/seastar/core/dpdk_rte.hh:35:2: warning: #warning "CONFIG_RTE_MBUF_REFCNT_ATOMIC should be disabled in DPDK's " "config/common_linuxapp" [-Wcpp]
 #warning "CONFIG_RTE_MBUF_REFCNT_ATOMIC should be disabled in DPDK's " \
```

I found a reason for this. `configure.py` generates this invalid `rte_config.h` from default `.config`, then changes the `.config`.

~~I suggest moving line~~
```
subprocess.check_call('make -C dpdk RTE_OUTPUT=$PWD/build/dpdk/ config T=x86_64-native-linuxapp-gcc'.format(
                                                dpdk_machine=dpdk_machine),
                          shell = True)
```
~~below line~~
```
open(dotconfig, 'w', encoding='UTF-8').writelines(lines)
```
Ops, that move was stupid. I suggest deleting `build/dpdk/include/rte_config.h`, then calling `make -C dpdk RTE_OUTPUT=$PWD/build/dpdk/ config` again after writing `.config`. That fixed the error for me.

**Comment by krisk0** [comment]
Better solution that calls `gen-config-h.sh` directly:
```
    lines += 'CONFIG_RTE_MACHINE={}'.format(dpdk_machine)
    open(dotconfig, 'w', encoding='UTF-8').writelines(lines)
    dd = 'dpdk/buildtools/gen-config-h.sh build/dpdk/.config > \
        build/dpdk/include/rte_config.h'
    subprocess.check_call(dd, shell = True)
    os.remove('build/dpdk/.config.orig')
    args.dpdk_target = os.getcwd() + '/build/dpdk'
```

**Comment by nyh** [comment]
@avikivity should this issue be closed because configure.py is obsolete, replaced by cmake?
@hakuch can you verify that this bug doesn't exist in the cmake version?

**Comment by nyh** [comment]
@hakuch ping, should this issue be closed now?

**Comment by hakuch** [comment]
@nyh: I think so, yes.
