### ISSUE TITLE
log print of exceptions should include std::system_error message part

### ISSUE THREAD

**Issue by elcallio** [scylladb/seastar#524]
Currently, when printing a std::system_error, the logger prints "(<error category name>:<error no>, <error code string>). However, std::system_error has a `what()` message part, nominally defined as "<message>:<error code string>" (or just error code string if no message). 

Should print the full message, not just static error code string.

**Comment by gleb-cloudius** [comment]
b0520f552df1ff6240a2c18a051a519ba15fa957 fixes ostream output operator for std::system_error as well.
