### ISSUE TITLE
Seastar does not compile with `c++14`

### ISSUE THREAD

**Issue by crackcomm** [scylladb/seastar#528]
I thought it's something with my setup but i tried with [smf-getting-started-cpp](https://github.com/senior7515/smf-getting-started-cpp/) and it's exactly the same and with `gnu++14`.

https://gist.github.com/crackcomm/06b85dfea2e1efd5d7411b938105e6b0

EDIT: github keeps removing my gists 😂 
https://pastebin.com/raw/fKbWbNgA

Build includes #527 fix.

```
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
```

I will appreciate any tips.

**Comment by tgrabiec** [comment]
pt., 2 lis 2018 o 19:17 Łukasz Kurowski <notifications@github.com>
napisał(a):

> I thought it's something with my setup but i tried with
> smf-getting-started-cpp
> <https://github.com/senior7515/smf-getting-started-cpp/> and it's exactly
> the same and with gnu++14.
>
> https://gist.github.com/crackcomm/06b85dfea2e1efd5d7411b938105e6b0
>
> EDIT: github keeps removing my gists 😂
> https://pastebin.com/raw/fKbWbNgA
>
> Build includes #527 <https://github.com/scylladb/seastar/issues/527> fix.
>
> gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
>
>
You need gcc 7.

We publish deb packages with the toolchain in our repo:

   sudo apt-get install scylla-gcc73-g++-7

then configure seastar to use that toolchain:

  ./configure.py --compiler=/opt/scylladb/bin/g++-7 --cflags
"-I/opt/scylladb/include " --ldflags="-L/opt/scylladb/lib/x86_64-linux-gnu/"

**Comment by senior7515** [comment]
@crackcomm  

```
CC=/usr/bin/gcc-7 CXX=/usr/bin/g++-7 ./build.sh
```
i added that to the readme. you need to install gcc-7 or greater.

**Comment by crackcomm** [comment]
can you guys link a repo, one from here: https://www.scylladb.com/download/debian8/ doesnt work

in the meantime im looking for one, thanks so far.

**Comment by crackcomm** [comment]
@tgrabiec, @senior7515 thanks! it's fixed.

here is the script I used for installation:


```sh
apt-get install -qy apt-transport-https wget gnupg2 dirmngr

apt-key adv --fetch-keys https://download.opensuse.org/repositories/home:/scylladb:/scylla-3rdparty-stretch/Debian_9.0/Release.key
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 17723034C56D4B19

echo "deb [arch=amd64] http://download.opensuse.org/repositories/home:/scylladb:/scylla-3rdparty-stretch/Debian_9.0/ ./" | sudo tee /etc/apt/sources.list.d/3rdparty.list
apt-get -y update
apt-get install -y scylla-gcc73-g++-7

update-alternatives --install /usr/bin/gcc gcc $(which gcc-7) 10
update-alternatives --install /usr/bin/g++ g++ $(which g++-7) 20
update-alternatives --install /usr/bin/cc  cc  /usr/bin/gcc   30
update-alternatives --set                  cc  /usr/bin/gcc
update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
update-alternatives --set                  c++ /usr/bin/g++
```

**Comment by nyh** [comment]
Closing. This was probably fixed long ago, and today we only support C++17 and C++20 anyway, so this issue is moot.
