### ISSUE TITLE
compilation error!!!

### ISSUE THREAD

**Issue by tracymacding** [scylladb/seastar#529]
FAILED: build/release/apps/httpd/httpd 
/opt/scylladb/bin/g++-7.3  -O2  -I/u01/jeff.dk/github/seastar/build/release/gen -I/u01/jeff.dk/github/seastar/build/release/c-ares -Lbuild/release -Lbuild/release/fmt -g -Wl,--no-as-needed   -fvisibility=hidden -Wno-attributes -pthread  -o build/release/apps/httpd/httpd build/release/apps/httpd/main.o build/release/http/transformers.o build/release/http/json_path.o build/release/http/file_handler.o build/release/http/common.o build/release/http/routes.o build/release/json/json_elements.o build/release/json/formatter.o build/release/http/matcher.o build/release/http/mime_types.o build/release/http/httpd.o build/release/http/reply.o build/release/http/api_docs.o build/release/net/proxy.o build/release/net/virtio.o build/release/net/dpdk.o build/release/net/ip.o build/release/net/ethernet.o build/release/net/arp.o build/release/net/native-stack.o build/release/net/ip_checksum.o build/release/net/udp.o build/release/net/tcp.o build/release/net/dhcp.o build/release/net/tls.o build/release/net/dns.o build/release/net/config.o build/release/core/reactor.o build/release/core/alien.o build/release/core/execution_stage.o build/release/core/systemwide_memory_barrier.o build/release/core/fstream.o build/release/core/posix.o build/release/core/memory.o build/release/core/resource.o build/release/core/scollectd.o build/release/core/metrics.o build/release/core/app-template.o build/release/core/thread.o build/release/core/dpdk_rte.o build/release/core/fsqual.o build/release/core/linux-aio.o build/release/util/conversions.o build/release/util/program-options.o build/release/util/log.o build/release/util/backtrace.o build/release/util/alloc_failure_injector.o build/release/util/read_first_line.o build/release/net/packet.o build/release/net/posix-stack.o build/release/net/net.o build/release/net/stack.o build/release/net/inet_address.o build/release/rpc/rpc.o build/release/rpc/lz4_compressor.o build/release/core/exception_hacks.o build/release/core/future-util.o -lboost_program_options -lboost_system -lboost_filesystem  -lm -lstdc++fs -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -llz4 -lprotobuf -ldl  -lyaml-cpp -static-libgcc -static-libstdc++ -lhwloc -lnuma -lpciaccess -lxml2 -lz -lcares-seastar -lfmt  
/usr/bin/ld: build/release/http/httpd.o: undefined reference to symbol '__cxa_init_primary_exception@@CXXABI_1.3.11'
/opt/scylladb/lib64//libstdc++.so.6: error adding symbols: DSO missing from command line

**Comment by denesb** [comment]
Which OS?
