### ISSUE TITLE
Build failure on Ubuntu 18.04.1 (undefined reference to boost::system::detail::system_category_ncx())

### ISSUE THREAD

**Issue by timcullen2015** [scylladb/seastar#531]
On Ubuntu 18.04.1 compiling with gcc 7.3

build/debug/net/virtio.o: In function `boost::system::system_category()':
/usr/local/include/boost/system/error_code.hpp:493: undefined reference to `boost::system::detail::system_category_ncx()'
build/debug/apps/httpd/main.o: In function `boost::system::generic_category()':
/usr/local/include/boost/system/error_code.hpp:498: undefined reference to `boost::system::detail::generic_category_ncx()'
collect2: error: ld returned 1 exit status
[118/408] CXX build/debug/tests/httpd.o
ninja: build stopped: subcommand failed.

**Comment by ashaffer** [comment]
I'm also having this issue. Same error on Ubuntu 18.04.

**Comment by dorlaor** [comment]
hmm, you may need to update boost. 
We have a new, distro-agnostic build now but I haven't built this in a while so take my
answer with a (large) grain of salt

**Comment by ashaffer** [comment]
For anyone else encountering this issue, I fixed it by upgrading gcc-7 to gcc-9.

**Comment by spinkernel** [comment]
I didn't have this issues with 1.70, but I had a weird issues where sockets where disconnecting prematurely, so i went to 1.69, 1.68, 1.65-ubuntu.  All have this issue.  Why would 1.7 work over the rest with gcc-7 vs -9?
