### ISSUE TITLE
libatomic missing from dependencies

### ISSUE THREAD

**Issue by bhalevy** [scylladb/seastar#533]
$ ninja build/release/tests/file_io_test
[1/2] /usr/bin/ninja-build -C build/release/fmt
ninja: Entering directory `build/release/fmt'
ninja: no work to do.
[2/2] LINK (stripped) build/release/tests/file_io_test
FAILED: build/release/tests/file_io_test 
g++  -O2  -I/local/home/bhalevy/dev/seastar/build/release/gen -I/local/home/bhalevy/dev/seastar/build/release/c-ares -s -Lbuild/release -Lbuild/release/fmt -g -Wl,--no-as-needed   -fvisibility=hidden  -pthread  -o build/release/tests/file_io_test build/release/tests/fileiotest.o build/release/core/reactor.o build/release/core/alien.o build/release/core/execution_stage.o build/release/core/systemwide_memory_barrier.o build/release/core/fstream.o build/release/core/posix.o build/release/core/memory.o build/release/core/resource.o build/release/core/scollectd.o build/release/core/metrics.o build/release/core/app-template.o build/release/core/thread.o build/release/core/dpdk_rte.o build/release/core/fsqual.o build/release/core/linux-aio.o build/release/util/conversions.o build/release/util/program-options.o build/release/util/log.o build/release/util/backtrace.o build/release/util/alloc_failure_injector.o build/release/util/read_first_line.o build/release/net/packet.o build/release/net/posix-stack.o build/release/net/net.o build/release/net/stack.o build/release/net/inet_address.o build/release/rpc/rpc.o build/release/rpc/lz4_compressor.o build/release/core/exception_hacks.o build/release/core/future-util.o build/release/tests/test-utils.o build/release/tests/test_runner.o -lboost_program_options -lboost_system -lboost_filesystem -lstdc++ -lm -lstdc++fs -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -llz4 -lprotobuf -ldl -latomic  -lyaml-cpp -lhwloc -lnuma -lpciaccess -lxml2 -lz -lcares-seastar -lfmt  -lyaml-cpp -lboost_unit_test_framework
/usr/bin/ld: cannot find /usr/lib64/libatomic.so.1.2.0
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

$ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)

**Comment by thomasheep** [comment]
I meet the same problem, finally manually search and  install
sudo yum install scylla-libatomic72

**Comment by nyh** [comment]
About this being Fedora's fault, I changed my mind. I see now that gcc doesn't even depend on libubsan or libstdc++, and you'll get similar errors if you try to use those libraries with only gcc installed. So I agree we need to add the "libatomic" package to our own requirements. That is, if we really need this "-latomic". I don't know why we do - we probably don't on x86 and adding it unconditionally on every platform just added this complication.

**Comment by bhalevy** [comment]
f6a064d412e330ac795604108e4e4ff250a054d6 should fix this
