### ISSUE TITLE
How does Seastar receive POSIX TCP requests?

### ISSUE THREAD

**Issue by SungHoHong2** [scylladb/seastar#534]
Hello, Seastar team, 

I am curious about how can Seastar-DPDK receive non-DPDK requests such as POSIX TCP and UDP. 
I need to create customized raw packets that can be recognized by Seastar-DPDK. 
First, I have tried to send ARP requests to DPDK first before doing this, in order to make sure that first DPDK understands the raw packet from non-DPDK requests, but strangely, DPDK does not seem to receive the packets other than sent by DPDK. 

I am trying to dig out any possible reasons of how Seastar manages to receive TCP and UDP packets that are not sent by DPDK.  
Would it be possible to know this?

**Comment by avikivity** [comment]
Please ask questions on the mailing list. The issue tracker is used for tracking issues.
