### ISSUE TITLE
Support per-device num_io_queues

### ISSUE THREAD

**Issue by bhalevy** [scylladb/seastar#542]
See scylladb/scylla#2415

We have a single configuration for number of I/O queues, and we are forced to pick one of them to serve all devices (usually the lower --num-io-queues). There are plenty of situations in which this may lead to bad performance in the faster device. @glommer tried a couple of approaches to fix that in an automatic way and they all failed (they worked extremely well in some cases and regressed in others); see #485. The safe fallback is just to allow each device to calculate its own independent number of I/O Queues. At this point.

**Comment by senior7515** [comment]
Pretty excited about this change. One can reason intelligently about hierarchical storage (HDD vs SSD NVMe's) via an abstraction. 

So the gist is Given N cores and M devices. You will have NxM io queues ?

**Comment by bhalevy** [comment]
On Tue, Dec 4, 2018, 18:59 Alexander Gallego <notifications@github.com
wrote:

> Pretty excited about this change. One can reason intelligently about
> hierarchical storage (HDD vs SSD NVMe's) via an abstraction.
>
Hi Alexander,

Thanks! That's indeed the main motivation for doing this.

So the gist is Given N cores and M devices. You will have NxM io queues ?
>

We will have up to NxM queues.
Each device may have up to N queues. Some may have fewer queues to limit
parallelism, as per iotune's calibration (or manual tweaking, that is
possible but never trivial).
