### ISSUE TITLE
Seastar is build without any warning flags

### ISSUE THREAD

**Issue by pdziepak** [scylladb/seastar#543]
Looks like after the switch to CMake we've lost our warning flags. After configuring seastar without any additional flags (i.e. just `$ ./configure.py`) and runing `ninja -v -C build/release` I get output like this:
```
[6/197] /usr/lib64/ccache/g++  -DFMT_SHARED -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_GCC6_CONCEPTS -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -I../../include -Igen/include -I../../src -Igen/src -isystem _cooking/installed/include -O2 -g -DNDEBUG   -std=gnu++17 -fconcepts -MD -MT CMakeFiles/seastar.dir/src/core/fsqual.cc.o -MF CMakeFiles/seastar.dir/src/core/fsqual.cc.o.d -o CMakeFiles/seastar.dir/src/core/fsqual.cc.o -c ../../src/core/fsqual.cc
```

We should build with the same flags as we did before the switch to cmake.

**Comment by pdziepak** [comment]
@espindola

**Comment by avikivity** [comment]
@hakuch

**Comment by hakuch** [comment]
@pdziepak , on the mailing list I pointed you to a previous commit I had made which explained the rational for removing warnings. It is at b3e0aa5b442e2a397709ce46c77de0975ee6306b.

Does this justification make sense to you? Why or why not?

**Comment by espindola** [comment]
The commit message talks about transitivity, but I don't think that applies in here. Note that the file in the issue description is CMakeFiles/seastar.dir/src/core/fsqual.cc.o. That is part of seastar, not of a program using seastar. 

I am taking a quick look.

**Comment by pdziepak** [comment]
I fully agree that Seastar shouldn't infect external projects that depend on it with any non-essential flags. However, all targets that are part of the Seastar should be built with those warning flags (with, perhaps, an option to disable `-Werror` but that's unrelated). Since, they are private for the seastar target, it looks like the need to be repeated for all tests, demos, etc.

However, this is a bit more complicated because as of now (current master: 81e9f31c2df90803249764fecab4737adbf1648c) freshly configured (no additional flags) seastar doesn't apply any warning flags even to core seastar files:
```
[22/162] /usr/lib64/ccache/g++  -DFMT_SHARED -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_GCC6_CONCEPTS -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -I../../include -Igen/include -I../../src -Igen/src -isystem _cooking/installed/include -O2 -g -DNDEBUG   -std=gnu++17 -UNDEBUG -fconcepts -MD -MT CMakeFiles/seastar.dir/src/core/prometheus.cc.o -MF CMakeFiles/seastar.dir/src/core/prometheus.cc.o.d -o CMakeFiles/seastar.dir/src/core/prometheus.cc.o -c ../../src/core/prometheus.cc
```

**Comment by hakuch** [comment]
@pdziepak , I think I agree. We want some warnings to be enabled as `PRIVATE` flags so that they apply when we're compiling Seastar but not when Seastar is used in another library or application (i.e., transitively).

However, I don't think we want to enable `-Werror`, since that introduces backwards incompatibilities. Is the overhead of optionally enabling it even worthwhile?

You're correct that we want these private properties to apply to tests and demos as well.

One solution to this problem that I've used in the past is to create a non-exported (not in the `Seastar::` CMake name space) target with these properties set as `PUBLIC` which the exported library links against privately.

Something like:

```cmake
add_library (impl
  my_source_file1.cc
  my_source_file2.cc)

target_compile_options (impl
  PUBLIC
    -Wall
    -Wextra)

# There's a way to add a library without any sources, but I forget at the moment.
# This exact line won't work, I don't think.
add_library (seastar)

target_link_libraries (seastar
  PRIVATE impl)

add_execuable (my_test
  test_source.cc)

target_link_libraries (my_test
  PRIVATE impl)
```

**Comment by espindola** [comment]
In the interest of making incremental forward progress I would ask that we keep this issue about restoring old behaviour to the seastar library itself.

Discussion on which changes we want (-Werror being the default?) and non library target can be followups.

**Comment by hakuch** [comment]
@espindola, that's fair.

To be clear, we will focus this issue on restoring `PRIVATE` warnings to Seastar itself, and subsequently refine those flags, and also compile tests, apps, and demos with those same flags. Yes?

**Comment by pdziepak** [comment]
The developers want `-Werror`, the CI wants `-Werror`. I realise that there may be some cases when somebody just wants to compile old seastar with a new compiler, which is why I said that we should have an option to opt out of `-Werror`, but I don't think that this justifies not using `-Werror` by default.

As for propagating the flags, most of my knowledge about CMake is less than a month old so I certainly cannot speak from experience but it looks like we can use either dummy targets (which looks quite hacky because, like you said, one can't have a target without sources) are just variables, something along the lines:
```cmake
set(SEASTAR_PRIVATE_COMPILE_FLAGS -Wall -Wextra)

target_compile_options(seastar PRIVATE ${SEASTAR_PRIVATE_COMPILE_FLAGS})

target_compile_options(my_test1 PRIVATE ${SEASTAR_PRIVATE_COMPILE_FLAGS})
```
I don't know which is better.

**Comment by espindola** [comment]
correct. We can do this in 3 steps
* Change the library flags to pretty much what they were before (I sent a patch with this)
* Refactor so that demos and tests use the same flags.
* Tune what the flags are.

**Comment by pdziepak** [comment]
@hakuch Right, interface libraries should do the trick.
