### ISSUE TITLE
SEASTAR_DEFAULT_ALLOCATOR got lost in translation

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#547]
SEASTAR_DEFAULT_ALLOCATOR used to be defined in debug mode, but is no longer. As a result tests/unit/alloc fails, and AddressSanitizer doesn't work.

Probably introduced by c79e9dec76186f76d1a2e48187e3073449a60bfe.

**Comment by hakuch** [comment]
`SEASTAR_DEFAULT_ALLOCATOR` is defined during compilation of Seastar itself, but not during unit tests (since it's a `PRIVATE` flag).

This is related to #544 and the discussion in #543 (though not the subject line).

**Comment by avikivity** [comment]
It should not be a private flag, it affects the application which will need to take different code paths depending on whether it is defined or not.

Bundling this private/public change in the cmake transition was a mistake, this way it evaded review in an unreadable mega-patch. Everything should have been public, with separate patches proposing to privatize individual flags later.

**Comment by hakuch** [comment]
> It should not be a private flag, it affects the application which will need to take different code paths depending on whether it is defined or not.
> 
> Bundling this private/public change in the cmake transition was a mistake, this way it evaded review in an unreadable mega-patch. Everything should have been public, with separate patches proposing to privatize individual flags later.

I agree. Experience is often a good teacher.

I think the subject line of this bug should be something like "SEASTAR_DEFAULT_ALLOCATOR should be defined transitively".

**Comment by hakuch** [comment]
This was fixed in 332141f02afe7af58dbda44a90f9b86369fe6531.
