### ISSUE TITLE
./cookiing.sh -r dev fail

### ISSUE THREAD

**Issue by xmm1989218** [scylladb/seastar#553]
-- Found c-ares: /home/livexmm/seastar/build/_cooking/installed/include (Required is at least version "1.13.0") 
-- Found cryptopp: /home/livexmm/seastar/build/_cooking/installed/include (Required is at least version "5.6.5") 
-- Found dpdk: /home/livexmm/seastar/build/_cooking/installed/include/dpdk  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found lz4: /home/livexmm/seastar/build/_cooking/installed/include (found suitable version "1.8.0", minimum required is "1.8.0") 
-- Looking for LZ4_compress_default
-- Looking for LZ4_compress_default - found
-- Performing Test Concepts_FOUND
-- Performing Test Concepts_FOUND - Failed
-- Found GnuTLS: /home/livexmm/seastar/build/_cooking/installed/include (found suitable version "3.5.18", minimum required is "3.5.18") 
-- Performing Test LinuxMembarrier_FOUND
-- Performing Test LinuxMembarrier_FOUND - Failed
-- Found Protobuf: /home/livexmm/seastar/build/_cooking/installed/lib/libprotobuf.so;-lpthread (found suitable version "3.3.0", minimum required is "3.3.0") 
-- Performing Test Sanitizers_ADDRESS_FOUND
-- Performing Test Sanitizers_ADDRESS_FOUND - Success
-- Performing Test Sanitizers_UNDEFINED_BEHAVIOR_FOUND
-- Performing Test Sanitizers_UNDEFINED_BEHAVIOR_FOUND - Success
-- Performing Test Sanitizers_FIBER_SUPPORT
-- Performing Test Sanitizers_FIBER_SUPPORT - Failed
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Sanitizers (missing: Sanitizers_FIBER_SUPPORT)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSanitizers.cmake:53 (find_package_handle_standard_args)
  CMakeLists.txt:228 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/livexmm/seastar/build/CMakeFiles/CMakeOutput.log".
See also "/home/livexmm/seastar/build/CMakeFiles/CMakeError.log".
livexmm@iZ23r0r7784Z:~/seastar$ vim cmake/FindSanitizers.cmake

**Comment by xmm1989218** [comment]
ubuntu 16.04  kernel linux 4.4.0

**Comment by momordica1996** [comment]
I met the same problem and didn't fix

**Comment by momordica1996** [comment]
This maybe solved by the new patch on the problem #554

**Comment by hakuch** [comment]
This should be fixed now.
