### ISSUE TITLE
CMake Error at /home/ubuntu/cmake-3.12.4/Modules/FindPackageHandleStandardArgs.cmake:137 (message):   Could NOT find Sanitizers (missing: Sanitizers_FIBER_SUPPORT)

### ISSUE THREAD

**Issue by momordica1996** [scylladb/seastar#554]
@hakuch 
Please help fix the failure, thanks!
build failed on master branch, with Ubuntu 16.04, g++ 5.4.0, cmake 3.12.4
running command: ./cooking.sh -r dev

compiler information:
-- Looking for LZ4_compress_default
-- Looking for LZ4_compress_default - found
-- Performing Test Concepts_FOUND
-- Performing Test Concepts_FOUND - Failed
-- Found GnuTLS: /home/livexmm/seastar/build/_cooking/installed/include (found suitable version "3.5.18", minimum required is "3.5.18")
-- Performing Test LinuxMembarrier_FOUND
-- Performing Test LinuxMembarrier_FOUND - Failed
-- Found Protobuf: /home/livexmm/seastar/build/_cooking/installed/lib/libprotobuf.so;-lpthread (found suitable version "3.3.0", minimum required is "3.3.0")
-- Performing Test Sanitizers_ADDRESS_FOUND
-- Performing Test Sanitizers_ADDRESS_FOUND - Success
-- Performing Test Sanitizers_UNDEFINED_BEHAVIOR_FOUND
-- Performing Test Sanitizers_UNDEFINED_BEHAVIOR_FOUND - Success
-- Performing Test Sanitizers_FIBER_SUPPORT
-- Performing Test Sanitizers_FIBER_SUPPORT - Failed
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
Could NOT find Sanitizers (missing: Sanitizers_FIBER_SUPPORT)
Call Stack (most recent call first):
  /home/ubuntu/cmake-3.12.4/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSanitizers.cmake:53 (find_package_handle_standard_args)
  CMakeLists.txt:228 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/projects/seastar/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/projects/seastar/build/CMakeFiles/CMakeError.log".

**Comment by hakuch** [comment]
I've identified a number things that the existing find-modules do that can be improved and that will resolve similar errors as well as this one. I'm preparing a patch now.
