### ISSUE TITLE
"--whole-archive" needed to link Seastar, but shouldn't be

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#556]
Our recent rewrite to cmake dropped the whole-archive trick which we had in seastar.pc to link Seastar:
```
 -Wl,--whole-archive,-lseastar,--no-whole-archive
```
Unfortunately, this "whole-archive" thing is in fact necessary, and should not have been dropped. It was needed because of the way Seastar initializes various modules (like the different network options) using static constructors. These work well for shared libraries (they are run automatically when the library is loaded), but for a static library - the problem is that linking doesn't include the object file (because nothing from the outside refers to it).

We can return the whole-archive song and dance to seastar.pc (note that the static DPDK library also needs it, by the way), but alternatively, we can change the initialization to explicitly initialize the different network modules, instead of using static constructors. Almost four years ago, I suggested this in 
 https://groups.google.com/d/msg/seastar-dev/U2B2S1ckgO8/UUIevCIL8u8J :

> I know the registrator thing is a cool C++ trick, but one obvious solution is simply not to use this pattern - if each network stack had a register_* function, and we have one function calling it -
>
>      register_networks() {
>            register_native_network();
>            register_posix_network();
>       }
>
>we wouldn't have this linking problem. Since our code anyway has central knowledge of all the known >network options (e.g., in the command line parsing code), it won't be more centralized than it is today.

**Comment by hakuch** [comment]
See also: https://gitlab.kitware.com/cmake/cmake/issues/16947

My preference is to avoid the auto-regeristering trick. It makes consuming Seastar harder for application and library developers (they have to configure their build systems with extra stuff) and changes global state in a way that can be harder to reason about. Ideally we do nothing that depends on linking order, but I'm not at all an expert here.
