### ISSUE TITLE
"taskset" ignored by Seastar applications

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#56]
Seastar applications by default create a thread on each of the machine's CPUs. However, Linux provides a mechanism for limiting a child process to only a subset of the CPUs (see taskset(1) and sched_setaffinity(2)), but Seastar silently ignores it.

For example, on a 4-cpu machine, if someone runs:

```
    taskset -c 0,1 some_seastar_program
```

Thinking the Seastar program will be limited only to these two CPUs, he'll be mistaken.

Seastar does provide options to override the default of taking over all the cpus (-c and --cpuset), but it's still confusing that "taskset" is silently ignored. I think we have two options to fix it:
1. Respect the CPU set returned by sched_getaffinity(2), and only use a subset of it.
2. At least _warn_ that one or more of the CPUs we've picked to run on is not in sched_getaffinity(2) - which will let the user realize his "taskset" attempt is being ignored.

**Comment by slivne** [comment]
seastar applications have --cpuset flag that allows setting cpus - so we
support it internally

**Comment by nyh** [comment]
On Wed, Sep 16, 2015 at 10:54 AM, slivne <notifications@github.com> wrote:

> seastar applications have --cpuset flag that allows setting cpus - so we
> support it internally
>

Please read my bug report. I know about the "cpuset" flag, and mentioned it
in the bug report, but before I noticed it (when Avi pointed it out to me),
I incorrectly assumed that "taskset" was being respected, which it wasn't.

I'm not saying it's a super-important or urgent, but I do think that
silently ignoring "taskset" is a bug, not a feature.
