### ISSUE TITLE
HELP! how to compile getting-started.cc

### ISSUE THREAD

**Issue by helloBingGeGe** [scylladb/seastar#564]
i`m a beginner for this project, i`ve spent many time to build seastar follow these steps:
* git clone git@github.com:scylladb/seastar.git
* git submodule update --init
* ./install-dependencies.sh
* wget https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-Linux-x86_64.sh and installed it
* export CXX=/opt/scylladb/bin/g++-7.3
* ln -s /opt/scylladb/bin/g++-7.3  /opt/scylladb/bin/g++
* . /etc/profile.d/scylla.sh
* ./cooking.sh -r dev
* ninja-build -C build -j1 (add "-j1" because it will Out Of Memory on my 2 Cores 2 G CentOS7 machine _(¦3」∠)_)
* ./cooking.sh -r dev -- -DCMAKE_INSTALL_PREFIX=/root/tmp/
* export LD_LIBRARY_PATH=/root/seastar/build/_cooking/installed/lib/:/root/seastar/build/_cooking/installed/lib64/:/root/tmp/lib64/:/opt/scylladb/lib64/

when all this successfully finished(GOD BLESS !), then execute:
g++ $(pkg-config --libs --cflags --static /root/tmp/lib64/pkgconfig/seastar.pc) getting-started.cc -I /root/tmp/include/ -I ./fmt/include/ /root/tmp/lib64/libseastar.a like the HACKING.md say,
but the result is a pile of errors like this:

collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
compilation terminated.
/root/tmp/lib64/libseastar.a(virtio.cc.o): In function `__gnu_cxx::__exchange_and_add(int volatile*, int)':
/opt/scylladb/include/c++/7/ext/atomicity.h:49: undefined reference to `__asan_report_store4'
/root/tmp/lib64/libseastar.a(virtio.cc.o): In function `__gnu_cxx::__atomic_add(int volatile*, int)':
/opt/scylladb/include/c++/7/ext/atomicity.h:53: undefined reference to `__asan_report_store4'
/root/tmp/lib64/libseastar.a(virtio.cc.o): In function `__gnu_cxx::__exchange_and_add_single(int*, int)':
/opt/scylladb/include/c++/7/ext/atomicity.h:67: undefined reference to `__ubsan_handle_type_mismatch'
/opt/scylladb/include/c++/7/ext/atomicity.h:67: undefined reference to `__asan_report_load4'
/opt/scylladb/include/c++/7/ext/atomicity.h:68: undefined reference to `__ubsan_handle_type_mismatch'
/opt/scylladb/include/c++/7/ext/atomicity.h:68: undefined reference to `__ubsan_handle_add_overflow'
/opt/scylladb/include/c++/7/ext/atomicity.h:68: undefined reference to `__ubsan_handle_type_mismatch'
/root/tmp/lib64/libseastar.a(virtio.cc.o): In function `__gnu_cxx::__atomic_add_single(int*, int)':
/opt/scylladb/include/c++/7/ext/atomicity.h:74: undefined reference to `__ubsan_handle_type_mismatch'
/opt/scylladb/include/c++/7/ext/atomicity.h:74: undefined reference to `__asan_report_load4'
/opt/scylladb/include/c++/7/ext/atomicity.h:74: undefined reference to `__ubsan_handle_add_overflow'
/opt/scylladb/include/c++/7/ext/atomicity.h:74: undefined reference to `__ubsan_handle_type_mismatch'
/root/tmp/lib64/libseastar.a(virtio.cc.o): In function `seastar::virtio::qp::txq::txq(seastar::virtio::qp&, seastar::virtio::ring_config)':

**Comment by nyh** [comment]
It appears that you built the "debugging" version of Seastar, which requires the ASAN libraries, but the linking did not provide them (I have no idea why, I don't understand that new "cooking" stuff).

Note that you many not want to be compiling a debugging version of Seastar. Unlike most other projects where "debug" means "slightly slower, slightly larger, easier to debug code", in Seastar means "much slower, harder to debug (!), but adds additional sanity checks automatically". If you didn't intend that and intended to go with a "release build" of Seastar, you probably need to tell the "cooking" command to do that. There are instructions in HACKING.md, if I remember correctly.

**Comment by helloBingGeGe** [comment]
@nyh this is my fault, when i had executed:
`g++ foo.cc $(pkg-config --libs --cflags --static ./build/seastar.pc)`
i ignored the warning:
`Package 'Seastar' requires 'gnutls >= 3.5.18' but version of GnuTLS is 3.3.29`
therefore it reports many compile errors.
when i had fixed this warning and use `-t Release` all thing goes well
think you for your advice!
