### ISSUE TITLE
Tutorial needs a simple compilation example

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#565]
The Seastar tutorial in its getting started section, https://github.com/scylladb/seastar/blob/master/doc/tutorial.md#getting-started, had a simple one-line compilation command using c++ and pkg-config. This was replaced (by @hakuch ?) by a more elborate cmake example. I think it was a mistake (which unfortunately I missed at real time) to **replace** the example instead of add it. The cmake example is unusable for people who have no intention of using cmake (yes, there are still some rarae aves who use make, ninja, or just their own script to build code). 

Moreover, while the old pkg-config technique allowed one to build his program with an *uninstalled* Seastar, it appears (but please correct me if I'm wrong) that the new cmake technique requires you to have installed Seastar, which is not always practical or desirable. The tutorial should probably mention how one can avoid installing Seastar, instead of requiring that one does. Also, where the tutorial says "first make sure you have downloaded, built, and installed Seastar." it should point to a document in seastar's repository or to Seastar's homepage or something) explaining how to do that.

So I think we should have *both* pkg-config and cmake examples.

**Comment by nyh** [comment]
Note that the compilation line needs to change from the old examples which assumed --whole-archive (which we no longer put in pkg-config).
The command should look like:
```
g++ getting-started.cc $(pkg-config --libs --cflags --static ../seastar/build/release/seastar.pc)
```
However, @haaawk reported on the mailing list that while this compiles, it fails to run:
```
[haaawk@desktop seastar-sample]$ ./a.out
./a.out: error while loading shared libraries: libfmt.so.5: cannot open shared object file: No such file or directory
```
He didn't have any problems to build Seastar so I am guessing (?) that that build maybe used an fmt submodule, NOT the system-installed libfmt. In that case, the pkg-config needs to also specify the full pathname of that library - and not expect libfmt to have been installed on the system.

**Comment by nyh** [comment]
@haaawk reports this works:
```
LD_LIBRARY_PATH=../seastar/build/release/_cooking/ingredient/fmt/build/ ./a.out
```

**Comment by haaawk** [comment]
@hakuch Why do we keep fmt as a submodule if it's "external public dependency"? I expected stuff in submodules being internal private dependencies that we may be changing as we need. Isn't that the purpose of git submodules?

**Comment by haaawk** [comment]
There's one more thing. If fmt is an external public dependency then it should be in install-dependencies.sh. When I run the script and build Seastar successfully I'm expect it to work on my system. Otherwise it is very confusing. In general I expect external public dependencies to be installed by install-dependencies.sh script and all private dependencies to be git submodules. Is this intuition wrong?

**Comment by nyh** [comment]
@hakuch I agree wirth @haaawk here: I think there are two options here:
1. fmt is an external dependency. In which case the user should be asked to *install* it first, perhaps via some automated script (like we have install-dependencies.sh). But the user needs to install it to where he wants it, and Seastar will use it from there.
2. fmt is an internal dependency, provided by us, and we compile it. In this case we need to either merge it into libseastar.a, or install libfmt.a (or libfmt.so) when Seastar is installed.

The mixture you (@hakuch) describe doesn't sound right to me: The build system builds its own libfmt and uses it - not the one installed on the system, and does NOT install the libfmt it built - and yet, assume that when you try to run the resulting program, you will have the same libfmt installed on your system. Where would it appear from, if the build system didn't install it?

**Comment by hakuch** [comment]
On Wed, Jan 2, 2019 at 4:36 PM Piotr Jastrzębski <notifications@github.com>
wrote:

> @hakuch <https://github.com/hakuch> Why do we keep fmt as a submodule if
> it's "external public dependency"? I expected stuff in submodules being
> internal private dependencies that we may be changing as we need. Isn't
> that the purpose of git submodules?
>
Exactly! :-)

I originally removed the submodule, but Avi wanted to keep it. Now that fmt
is available in Fedora 29, Avi has sent a patch to remove that submodule.
