### ISSUE TITLE
operator new() doesn't conform to __STDCPP_­DEFAULT_­NEW_­ALIGNMENT__

### ISSUE THREAD

**Issue by pdziepak** [scylladb/seastar#569]
The standard says [1] that `operator new` returns memory aligned to `__STDCPP_DEFAULT_NEW_ALIGNMENT__`. On x64 Linux that definition has a value of 16.

However, seastar allocator uses pools for small object allocator and the returned addresses are more or less `page_aligned_pool_address + n * sizeof(object)`. This means that for objects of size that's not a multiple of `__STDCPP_DEFAULT_NEW_ALIGNMENT__` (e.g. 24) the allocator will violate the alignment requirements. This is obviously wrong and may lead to crashes since the compiler is allowed to use instructions that assume alignment (e.g. [2]). Several tests crash in seastar development build with clang because of that.

The solution is to either change the allocator to guarantee the default `__STDCPP_DEFAULT_NEW_ALIGNMENT__` alignment or use `-faligned-new=X` flag to change the value of that definition.

[1] http://eel.is/c++draft/cpp.predefined#1.6
[2] https://godbolt.org/z/034t4w

**Comment by avikivity** [comment]
I hate wasting even a bit but I guess we should conform. We can probably get away with size 8 being not aligned to 16.

We probably don't have many 24-byte heap objects.

**Comment by pdziepak** [comment]
Right, not the best example, one crash that I've looked into more closely was a 56 byte allocation from `make_lw_shared<parallel_for_each_state>`.

One cannot put an object with alignment requirements of 16 in a 8 byte buffer (by the standard rule that alignof(T) <= sizeof(T)), so 8 byte and smaller objects should be all right, indeed. I am not a standard lawyer though.
