### ISSUE TITLE
Use logic or instead of bitwise or?

### ISSUE THREAD

**Issue by xiaoming-qxm** [scylladb/seastar#570]
https://github.com/scylladb/seastar/blob/5a6080185c791fcb927b8d5ba8c20dbfd978da0a/src/core/reactor.cc#L3521-L3523

In the code above, I think there is a typo to use | (bitwise or). It would be better to use || (logic or).

**Comment by raphaelsc** [comment]
usage of bitwise OR is intentional, to avoid short-circuiting call of poll_queues() on alien threads.
