### ISSUE TITLE
Is the example which named tcp_demo.cc wrong?

### ISSUE THREAD

**Issue by caiyaodeng** [scylladb/seastar#572]
`int main(int ac, char** av) {
    boost::program_options::variables_map opts;
    opts.insert(std::make_pair("tap-device", boost::program_options::variable_value(std::string("tap0"), false)));

    auto vnet = create_virtio_net_device(opts);
    interface netif(std::move(vnet));    **// segfults here, because the varaible "local_engine" is nullptr**
    ipv4 inet(&netif);
    inet.set_host_address(ipv4_address("192.168.122.2"));
    tcp_test tt(inet);
    engine().when_started().then([&tt] { tt.run(); });
    engine().run();
}`

I haven't change the example. I think the varaible "local_engine" must be allocated by function "smp::allocate_reactor".
Am i right？

**Comment by aprilweet** [comment]
I think you are right...

**Comment by caiyaodeng** [comment]
don't  care any more

**Comment by sjyMystery** [comment]
the issue also exists for many years. @caiyaodeng
