### ISSUE TITLE
future should probably be nodiscard

### ISSUE THREAD

**Issue by espindola** [scylladb/seastar#573]
It is too easy to forget to use a future. 

And if one forgets to return a future or call .get() when in a seastar thread, all that happens is that we don't wait for it, so the bug is not immediately obvious.

We should probably tag future with [[nodiscard]] and have an empty dont_wait() method or function that is the canonical way of disabling the warning when we really don't want to wait on a future.

**Comment by hakuch** [comment]
I've hit this bug before. The idea of a function without `[[nodiscard]]` is good one.

**Comment by xemul** [comment]
5ce62e6e638aa3a8861f8b9c1b200e307d839672
