### ISSUE TITLE
Compilation will fail due to private `io_queue` header

### ISSUE THREAD

**Issue by hakuch** [scylladb/seastar#583]
Observed with: 8e7d1057c18e907c1de386759f6262581f83e89d

Commit a4b393d7eed92eaf35cb54b5ef485113470cd785 moved the definition of `io_queue` to a private header.

However, there is a public member function of the `reactor` in a public header (`reactor.hh`), [`get_io_queue`](https://github.com/scylladb/seastar/blob/master/include/seastar/core/reactor.hh#L566), which requires that the definition of `io_queue` is accessible.

While Seastar itself will compile (since it appears no code actually invokes `get_io_queue`), a consumer of Seastar, Scylla, does fail to compile:

```
main.cc: In lambda function:                                                                                                                                                                                         
main.cc:241:50: error: invalid use of incomplete type ‘class seastar::io_queue’                                                                                                                                      
             auto capacity = engine().get_io_queue().capacity(); 
```

**Comment by avikivity** [comment]
I think Scylla is at fault for reaching into the internals like that, but let's undo the breakage first, find a way to clean it up, then make it private again.

**Comment by hakuch** [comment]
Perhaps `get_io_queue` should be a private member of `reactor`? Otherwise, the definition of the class must be public.

**Comment by avikivity** [comment]
Patch on list.
