### ISSUE TITLE
Why did it take so much effort to do it in "message_queue"?

### ISSUE THREAD

**Issue by caiyaodeng** [scylladb/seastar#585]
I read the source code about "message_queue" and find that may wakeup "remote reactor-thread" by "_pending.maybe_wakeup()" when we call "message_queue::submit_item".
I continue to dig deeper try to trace "reactor::wakeup",and i find that "reactor::wakeup" just send a signal which named "alarm_signal()" to the thread that running with remote "ractor::run".
Keep on going, i find that the reactor-thread registered the signal processing function for "alarm_signal()". If thread recv "alarm_signal()",then call the Lamda function.
The Lamda just like this.
```
[this] {
        complete_timers(_timers, _expired_timers, [this] {
            if (!_timers.empty()) {
                enable_timer(_timers.get_next_timeout()); // restart timer for what (an other question) ？
            }
        }
```
I see the "complete_timers()", but it just handle "expired_timers",Why? I think it should handle "_pending" data from the other "reactor-thread".Can anybody help me out?

**Comment by nyh** [comment]
This is a bug tracker, for bugs or specific feature requests, not questions or general discussions. Please close this issue and repeat your question on the seastar-dev mailing list on googlegroups.

**Comment by caiyaodeng** [comment]
all right
