### ISSUE TITLE
cooking.sh should have a default recipe file

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#587]
I all our examples of how to use cooking.sh in Seastar, we ask the user to type "-r dev". Beyond being tedious, it's also confusing for beginners because they have no idea what this option does (which is to use recipe/dev.cmake) and many will initially assume (like I did) that it relates to a "development build" (the fact we also have "-t Dev" meaning *that* adds to this confusion).

@hakuch  I think cooking.sh should have a default recipe name, and a project (like Seastar) which only has one recpie, should put it under that default name so a user will not have to specify it. This is exactly how "make" takes a file called "Makefile" (or "makefile", etc.) by default: make still allows you to pick a different file (via "make -f ..." or "make -C ..."), but there is a default name which allows a project that has only one makefile to call it "Makefile", and the user doesn't need to type "make -f Makefile" every time.

**Comment by espindola** [comment]
This was fixed when cooking.sh was upgraded, no?

**Comment by hakuch** [comment]
@espindola: Yes, it was.
