### ISSUE TITLE
Cooking.cmake is being created in the source directory

### ISSUE THREAD

**Issue by espindola** [scylladb/seastar#595]
It is in general bad practice to create files in the source directory, it should be regarded as read only.

In this case, this also causes an unnecessary cmake rerun:

$ ./configure.py
....
$ ninja -n -d explain -C build/release build.ninja
ninja: Entering directory `build/release'
ninja explain: output build.ninja older than most recent input ../../cmake/Cooking.cmake (1548785812 vs 1548785816)
[0/1/0] Re-running CMake...

**Comment by hakuch** [comment]
This is a cmake-cooking (`cooking.sh`) change, and one which makes a lot of sense.

I'll create a corresponding issue on the project's home-page and see if I can make the change quickly.
