### ISSUE TITLE
SEASTAR_SHUFFLE_TASK_QUEUE lost in the cmake transition

### ISSUE THREAD

**Issue by espindola** [scylladb/seastar#601]
It used to be defined in debug builds.

**Comment by hakuch** [comment]
I'll try to get a patch out for this quickly. Apologies for the omission.

**Comment by hakuch** [comment]
Patch on the [mailing list](https://groups.google.com/d/msg/seastar-dev/o0FvFdqbw2s/Lbf7BG6CGgAJ).
