### ISSUE TITLE
Can't deprecate a class

### ISSUE THREAD

**Issue by avikivity** [scylladb/seastar#602]
If I add [[deprecated]], the build fails because of -Werror and no -Wno-error-deprecated (or whatever). This is a regression from the pre-cmake days.

**Comment by avikivity** [comment]
@hakuch example trigger: https://github.com/avikivity/seastar/commit/d62bc3865c20ff35a736a2461c1a3d7bb529b36d

**Comment by hakuch** [comment]
The solution (if we wish to keep `-Werror` enabled) is to add `-Wno-deprecated` to `Seastar_DEVELOPMENT_FLAGS`.

Do you have any objection to that, @avikivity?

**Comment by avikivity** [comment]
That means we won't get warnings for deprecated names.

There's -Wno-error=deprecated-declarations that emits warnings but does not upgrade them to errors.

**Comment by hakuch** [comment]
Let's do that, then!
