### ISSUE TITLE
future<> api docs are missing from doxygen output

### ISSUE THREAD

**Issue by nacl** [scylladb/seastar#605]
Recently, I have noticed that the API documentation generated by Seastar is missing a few entries that used to be there, most notably the description of the [future object](http://docs.seastar.io/master/group__future-module.html#classseastar_1_1future).

Doxygen seems to be confused by the concept syntax that is normally wrapped in the `GCC6_CONCEPT` macro, which doxygen is not managing to find while preprocessing.  Setting `INCLUDE_PATH` in dox/Doxyfile.in like so:

```
INCLUDE_PATH           = @Seastar_SOURCE_DIR@/include @Seastar_BINARY_DIR@/gen
```

Will cause it to find the gcc6-concepts header, which will result in the concepts never hitting the Doxygen parser (this is the same as the INPUT argument).  With this in place, one can enable the parsing of the concepts by adding `SEASTAR_HAVE_GCC6_CONCEPTS` to the `PREDEFINED` list in doc/Doxyfile.in.

You can view Doxygen's preprocessor diagnostics if you run `doxygen` with the `-d Preprocessor` argument.   I have tried this with Doxygen 1.8.11 and 1.8.15 on Ubuntu 16.04 with success in both cases.

Thanks!

**Comment by hakuch** [comment]
Thank you for the clear information!

I can probably prepare a patch for this tomorrow morning, or you're welcome to do so yourself.

**Comment by hakuch** [comment]
This [patch series](https://groups.google.com/d/msg/seastar-dev/vB7c5ccQZMw/Bt_nMc63AQAJ) fixes this and some other issues.
