### ISSUE TITLE
sporadic test_stream_simple test failure

### ISSUE THREAD

**Issue by espindola** [scylladb/seastar#606]
Even with mine or @gleb-cloudius  patch to fix connections surviving their server, I still get a sporadic failure in tests/unit/rpc.

It can be reproduced with 

set -e
while true
do
      ./tests/unit/rpc -t test_stream_simple -- -c 2
done

and the failure is
../../tests/unit/rpc_test.cc(401): fatal error: in "test_stream_simple": critical check !r.sink_close_exception has failed

**Comment by gleb-cloudius** [comment]
On Wed, Feb 13, 2019 at 03:58:19PM -0800, Rafael Ávila de Espíndola wrote:
> Even with mine or @gleb-cloudius  patch to fix connections surviving their server, I still get a sporadic failure in tests/unit/rpc.
> 
The patch did not suppose to fix problems with streaming since with
streaming enable we would not hit the bug.

> It can be reproduced with 
> 
> set -e
> while true
> do
>       ./tests/unit/rpc -t test_stream_simple -- -c 2
> done
> 
> and the failure is
> ../../tests/unit/rpc_test.cc(401): fatal error: in "test_stream_simple": critical check !r.sink_close_exception has failed
> 
I'll try to reproduce.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Thu, Feb 14, 2019 at 09:59:48AM +0200, Gleb Natapov wrote:
> > and the failure is
> > ../../tests/unit/rpc_test.cc(401): fatal error: in "test_stream_simple": critical check !r.sink_close_exception has failed
> > 
> I'll try to reproduce.
> 
How often it happens for you? Runs here for a while and no errors so far.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Thu, Feb 14, 2019 at 10:46:43AM +0200, Gleb Natapov wrote:
> On Thu, Feb 14, 2019 at 09:59:48AM +0200, Gleb Natapov wrote:
> > > and the failure is
> > > ../../tests/unit/rpc_test.cc(401): fatal error: in "test_stream_simple": critical check !r.sink_close_exception has failed
> > > 
> > I'll try to reproduce.
> > 
> How often it happens for you? Runs here for a while and no errors so far.
> 
After running it for hours I saw one failure with smp 4.

--
			Gleb.

**Comment by espindola** [comment]
I have found why this fails only sometimes.

We are closing streams twice and that throws an exception in loopback_socket.hh

    future<> push(temporary_buffer<char>&& b) {
        if (_aborted) {
            return make_exception_future<>(std::system_error(EPIPE, std::system_category()));
        }

99% of the time that call to close came from connection::stop_send_loop, which is called from  client::client which eats the exception:

     return stop_send_loop().then_wrapped([this] (future<> f) {
             f.ignore_ready_future();

1% of the time the close call is from connection::stream_close, which doesn't eat the exception and the test fails.

The code seems designed to close the stream only once. Trying to see if that is the root bug, that is, the stream should have been closed only once.

But apart from that, do we really want to eat *every* exception in client::client?

**Comment by espindola** [comment]
There are a few problem in here:

shutdown_output eats a future:

    void shutdown_output() override {
        smp::submit_to(_tx.get_owner_shard(), [this] {

Even with that fixed, the synchronization between stream_close and stop_send_loop seems incomplete.

stream_close can execute until  _write_buf.close() is scheduled and then stop_send_loop starts executing and we have two close calls running in parallel.

**Comment by gleb-cloudius** [comment]
On Fri, Feb 15, 2019 at 05:40:14PM +0000, Rafael Ávila de Espíndola wrote:
> There are a few problem in here:
> 
> shutdown_output eats a future:
> 
>     void shutdown_output() override {
>         smp::submit_to(_tx.get_owner_shard(), [this] {
> 
Why is it a problem?

> Even with that fixed, the synchronization between stream_close and stop_send_loop seems incomplete.
> 
> stream_close can execute until  _write_buf.close() is scheduled and then stop_send_loop starts executing and we have two close calls running in parallel.
> 
At this point _sink_closed_future will not be ready, so when_all() in
stop_send_loop() will wait for it.

--
			Gleb.
