### ISSUE TITLE
http  can't compile 

### ISSUE THREAD

**Issue by normandie199** [scylladb/seastar#61]
kwg@u14:~/seastar/apps/httpd$ g++ -Wall -g -ggdb  -std=c++1y -o httpd main.cc  -I ../../
In file included from main.cc:22:0:
../../http/httpd.hh:25:34: fatal error: http/request_parser.hh: No such file or directory
 #include "http/request_parser.hh"
                                  ^
compilation terminated.
kwg@u14:~/seastar/apps/httpd$

**Comment by normandie199** [comment]
kwg@u14:~/seastar/apps/httpd$ g++ -Wall -g -ggdb  -std=c++1y -o httpd main.cc  -I ../../
In file included from ../../http/httpd.hh:25:0,
                 from main.cc:22:
../../http/request_parser.hh:74:8: warning: multi-character character constant [-Wmultichar]
 crlf = '\r\n';
        ^
../../http/request_parser.hh:87:16: warning: character constant too long for its type
 http_version = 'HTTP/' (digit '.' digit) >mark %store_version;
                ^
../../http/request_parser.hh:95:37: error: stray '@' in program
 main := start_line header* :> (crlf @done);
                                     ^
main.cc:26:35: fatal error: apps/httpd/demo.json.hh: No such file or directory
 #include "apps/httpd/demo.json.hh"
                                   ^
compilation terminated.

**Comment by avikivity** [comment]
http/request_parser.hh is a generated file.  Compile regularly using ninja and it will work.  Don't rename request_parser.rl to .hh.
