### ISSUE TITLE
difference between seastar::smp::submit_to and sharded<>

### ISSUE THREAD

**Issue by songziqin** [scylladb/seastar#611]
I see doc/tutorial.md there is a example:
seastar::future<> f() {
return seastar::parallel_for_each(boost::irange(0, seastar::smp::count),
[] (unsigned c) {
return seastar::smp::submit_to(c, service_loop);
});
}
that can implement each of Seastar cores (from 0 to smp::count-1) to run the same function service_loop(). and the document also says sharded<> can do better. and I want to know how the
sharded<> do the same thing. can you give a simple example.

**Comment by denesb** [comment]
The issue tracker is for reporting defects, please use the [seastar-dev mailing list](mailto:seastar-dev@googlegroups.com) for asking questions.

`sharded<>` allows creating an object on each shard. It is essentially an object that is replicated to every shard.

```c++
class my_service {
    sstring _name;
public:
    explicit my_service(sstring name) : _name(std::move(name)) { }
    void run() { log.info("{} running on {}", _name, engine().cpu_id()); }
    void stop() {}
};

future<> start_my_service(sstring name) {
    return async([name] {
        sharded<my_service> s;
        // Will create a my_service instance on each shard
        s.start(name).get();
         // this will be called on each shard, and passed as parameter the shard-local instance
        s.invoke_on_all([] (my_service& local_service) {
            local_service.run();
        }).get();
    });  
}
```

**Comment by denesb** [comment]
You are welcome. Please close this issue :). And remember to ask questions on the mailing list in the future.
