### ISSUE TITLE
After cmake rewrite, "ninja doc/split" doesn't rebuild correctly

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#614]
If I do
```
touch doc/tutorial.md
ninja -C build/dev doc/split
```
The first time it works correctly, but the second time it only does the first necessary step - "Generating tutorial.html", but forgets to do the second step - "Generating split". It needs to also do this second step of splitting tutorial.html into separate files in the split/ directory. The mere fact that this directory already exists is not a sign this step is not needed, if the tutorial.html is newer than that directory or the files in it.

**Comment by nyh** [comment]
CC @hakuch

**Comment by hakuch** [comment]
Thanks for the report. I'll try to get to this soon.

**Comment by hakuch** [comment]
I sent a patch, and more information on the source of the error is [here](https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands/) (in the last section).
