### ISSUE TITLE
httpd POST Request object not returning Content

### ISSUE THREAD

**Issue by gopigrip7** [scylladb/seastar#615]
Hi,

We are in process of adopting Seastar and as the first MVP, trying to create HTTP based flatbuffer service.  I could able to compile and run seastar service and make a request but couldn't access content from the request object. It's always empty. Also tried with simple json, still its empty. Not sure where I'm missing. Please can you anyone of you throw some light or provide direction.

Regards
Gopi

**Comment by avikivity** [comment]
Fixes by f43b7ead2c27bf6fe43c381ea5078bb14dfbdf29.
