### ISSUE TITLE
Unable to install on RHEL

### ISSUE THREAD

**Issue by pradeepp2019** [scylladb/seastar#620]
Hi, I am facing the below error when I am trying to install on RHEL. Is there a way to install dependencies easily?

[root@tdnasrv10191 seastar-master]# ./install-dependencies.sh
Your system (rhel) is not supported by this script. Please install dependencies manually.

**Comment by hakuch** [comment]
You can install dependencies into local directory for development purposes using the `cooking.sh` script to configure Seastar instead of `configure.py`.

Instructions for this are in `HACKING.md`. If it's unclear or you have errors, please respond here and I'll try to address them.

**Comment by pradeepp2019** [comment]
I tried to install it globally (using clone and make install and some using yum install after enabling the repo) of all the depend libraries. Now, I am getting this error even when I have cloned the updated version of c-ares (c-ares-1.15.0). Earlier, I installed c-ares 1.10.0 version using yum install but when I got this error, I removed the 1.10.0 package using yum remove. But, still getting the same error. Can you please let me know if I need to delete any reference or clean up something?  

CMake Error at /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find c-ares: Found unsuitable version "1.10.0", but required is
  at least "1.13.0" (found /usr/lib64/libcares.so)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findc-ares.cmake:47 (find_package_handle_standard_args)
  CMakeLists.txt:232 (find_package)

**Comment by pradeepp2019** [comment]
I was able to fix the c-ares unsuitable version error by installing the rpm but now, I am encountering the below error. Any help would be appreciated.

-- Could NOT find dpdk (missing: dpdk_INCLUDE_DIR dpdk_PMD_VMXNET3_UIO_LIBRARY dpdk_PMD_I40E_LIBRARY dpdk_PMD_IXGBE_LIBRARY dpdk_PMD_E1000_LIBRARY dpdk_PMD_BNXT_LIBRARY dpdk_PMD_RING_LIBRARY dpdk_PMD_CXGBE_LIBRARY dpdk_PMD_ENA_LIBRARY dpdk_PMD_ENIC_LIBRARY dpdk_PMD_FM10K_LIBRARY dpdk_PMD_NFP_LIBRARY dpdk_PMD_QEDE_LIBRARY dpdk_RING_LIBRARY dpdk_KVARGS_LIBRARY dpdk_MEMPOOL_LIBRARY dpdk_MEMPOOL_RING_LIBRARY dpdk_PMD_SFC_EFX_LIBRARY dpdk_HASH_LIBRARY dpdk_CMDLINE_LIBRARY dpdk_MBUF_LIBRARY dpdk_CFGFILE_LIBRARY dpdk_EAL_LIBRARY dpdk_ETHDEV_LIBRARY)
CMake Error at CMakeLists.txt:236 (find_package):
  By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.

  Could not find a package configuration file provided by "fmt" (requested
  version 5.0.0) with any of the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

**Comment by pradeepp2019** [comment]
Also, when I am running ./cooking.sh, I am getting below error. There seems to be some issue with script as download works when I execute manually using curl command.

CMake Error at stamp/download-ingredient_libpciaccess.cmake:159 (message):
  Each download failed!

    error: downloading 'https://www.x.org/releases/individual/lib/libpciaccess-0.13.4.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

**Comment by hakuch** [comment]
The error with `fmt` was CMake informing you that it can't find `fmt` on your system.

The second error seems to indicate that your version of `curl` doesn't support HTTPS. I'm not sure specifically, but I suspect that there is a package you can install to enable it.

**Comment by pradeepp2019** [comment]
fmt package is there as you can see below.

[root@tdnasrv10191 seastar-master]# fmt --version
fmt (GNU coreutils) 8.22
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Ross Paterson.

**Comment by hakuch** [comment]
`fmt` refers to [this project](http://fmtlib.net/latest/index.html), not anything from GNU.

It looks like the version of `curl` on your system doesn't support HTTPS. You need to install a version of `curl` that does.

**Comment by closertotheheart** [comment]
In general, try to get the packets from a yum repo, not via that script.

sudo yum install libpciaccess-devel

for example.

**Comment by nyh** [comment]
Closing this old issue - both Seastar itself and its dependencies - and the common distributions changed a lot in the two and a half years that passed. If we still have problems on RHEL we should have a new issue, with new information.
