### ISSUE TITLE
Memory allocator wastes 1 page when allocating 3 pages

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#625]
When allocating 3 pages (some small pools use that size), `allocate_large_and_trim()` will get a span of 4 pages in size from `find_and_unlink_span_reclaiming()`. The trimming loop will not trim it, because the remainder is smaller than `n_pages`, and the loop looks like this:

```
    while (span_size >= n_pages * 2) {
        span_size /= 2;
        auto other_span_idx = span_idx + span_size;
        free_span_no_merge(other_span_idx, span_size);
    }
```

The small allocator won't use the unfreed pages which are in the span.

I think this was introduced in 33d8f74fc83a12601618a4a9fa7ad1f3a9955c73

**Comment by tgrabiec** [comment]
We should either free the page or let the small pool use all the pages.

I'm not sure if freeing the remaining pages would violate some invariants of the buddy allocator or not.

**Comment by avikivity** [comment]
It would, the buddy allocator expects everything to be in nice power-of-two. I had an idea to allow 3/4 - 1/4 allocations (with extra marking in the first and last page of both parts) but did not follow up on it.

Making the small pool work with powers-of-two seems like an easy fix.
