### ISSUE TITLE
HTTP server: interface for reading long request bodies

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#637]
Currently, the `seastar::httpd::request` object has a `content` field, into which the entire body of the request is read. This is fine for most requests which either have an empty body or a small one, but POST and PUT requests may have very large bodies, and it is inefficient and/or impossible to read the entire body up-front into a string. We need to change this interface.

A better interface is for the the request object to have a `content_stream` field which will be an `input_stream<char>` from which the handler can (and should...) read the entire content at its own pace. This stream will be a wrapper around the original connection stream; It needs to be a wrapper because it needs to end at position `Content-Length`, or to unwrap a chunked-encoded stream (see https://tools.ietf.org/html/rfc7230#section-4.1) or even to uncompress a compressed stream (see https://tools.ietf.org/html/rfc7230#section-4.2).

**Comment by psarna** [comment]
I thought about it for a while, and there's one problem I don't see a perfect solution for. My initial zero-copy idea was to just allow the `request` to create a sub-stream (stream view?) on top of the connection's stream, but limited to `Content-Length` or `Chunked-Encoding`, but then we would need a mechanism for the base stream to know about its sub-streams in order not to free their buffers too soon - which sounds rather complicated. The base stream must be allowed to continue operating right after creating a `request`, since other requests will follow, so the other crude idea is to simply consume and copy `Content-Length` bytes from the base stream, not necessarily to a contiguous buffer to avoid large allocations, and only then present it to the user. One problem with that solution is that it only works for `Content-Length`, not for `Chunked-Encoding`. The other problem is that it involves copying. We could elide copying by splicing (as in https://www.man7.org/linux/man-pages/man2/splice.2.html) the data from the base stream to the request, but, again, we would need to know the total size upfront. Another idea would be for one request to "borrow" the base stream until it reads everything it needs, but then the next request would need to wait for the first one to finish processing, which would effectively reduce request parallelism to 1 and thus slow down the server.

Thoughts?

**Comment by nyh** [comment]
The "sub-stream" as you called it will be a stream **wrapper** - an object that will implement its own stream methods by calling methods of the base stream. In particular, close() or destroy of the wrapper does not close or destroy the base stream (as you said, further requests will continue to read from it!). I don't see any reason why the base stream needs to know about its substreams. The code holding the base stream is the handler of the connection, and it will keep it alive while the substreams are needed (it already does - as you noticed it needs to continue using the same stream again to process the next request coming on the same connection). Maybe there are some bugs in this lifetime management in edge case (like when the connection is closed?) but if there are, they can be fixed.

I don't like "partial" solutions like building a non-contiguous strings. These partial solutions help for "big" request but not for really huge requests (if you have a 1 GB "PUT" request, it is still inappropriate), nor will it help chunked-encoding or compression, which are legitimate HTTP features which we will definitely need to implement in the future as well (it's a shame we don't already have them, but I guess it was never a priority).

**Comment by psarna** [comment]
On 6/17/20 2:06 PM, nyh wrote:
>
> The "sub-stream" as you called it will be a stream *wrapper* - an 
> object that will implement its own stream methods by calling methods 
> of the base stream. In particular, close() or destroy of the wrapper 
> does not close or destroy the base stream (as you said, further 
> requests will continue to read from it!). I don't see any reason why 
> the base stream needs to know about its substreams. The code holding 
> the base stream is the handler of the connection, and it will keep it 
> alive while the substreams are needed (it already does - as you 
> noticed it needs to continue using the same stream again to process 
> the next request coming on the same connection). Maybe there are some 
> bugs in this lifetime management in edge case (like when the 
> connection is closed?) but if there are, they can be fixed.
>
I get it, but what I'm worried about is that once you create a request 
which contains this wrapper, nobody else is allowed to consume the base 
stream (unless I misunderstand the idea). Right now, a request consumes 
everything it needs from a stream and then the server code processes it 
in its own pace, while other requests can be parsed from the stream 
right away. However, when we create a request with a wrapper, this 
wrapper would need to consume everything it needs from the base stream 
first, and only then we'll be able to continue reading new requests from 
the base stream. Isn't that potentially problematic? We would be giving 
the stream exclusively to a single request without any promises when 
it's supposed to give it back - the code can call complex logic on the 
wrapper which takes a long time, effectively blocking other requests 
from being parsed from the base stream.

**Comment by nyh** [comment]
> I get it, but what I'm worried about is that once you create a request which contains this wrapper, nobody else is allowed to consume the base stream (unless I misunderstand the idea). Right now, a request consumes everything it needs from a stream and then the server code processes it in its own pace, while other requests can be parsed from the stream right away. However, when we create a request with a wrapper, this wrapper would need to consume everything it needs from the base stream first, and only then we'll be able to continue reading new requests from the base stream. Isn't that potentially problematic? We would be giving the stream exclusively to a single request without any promises when it's supposed to give it back - the code can call complex logic on the wrapper which takes a long time, effectively blocking other requests from being parsed from the base stream.

You are right here. Until the request processor consumes this request, we cannot read and process
another request. This is not a lifetime issue, it's a basic single-stream TCP issue: Until someone actually reads all the current request, the next request may not even be sent because the sender buffer is full!

As an example of what I mean, consider someone sending over a connection a 1-GB PUT request followed by a 100 byte request. You truly cannot start the second request before you finished reading the first 1 GB request. Not only can you not start the second request, you can't even read it before you finished reading the entire 1GB first request. This is because HTTP 1.1 only uses a single HTTP stream, and requests cannot be interleaved (this was changed in HTTP 2, but we don't support that).

If we do want to support the limited form of pipelining that HTTP 1.1 does support, namely - that we can start the second request as soon as we read the first one (not waiting for the response for the first one to be available), it's quite easy to do, I think:

1. When the wrapper reads from the base stream, the base stream knows its position. The server code cannot start to read the next request because the base stream reaches the end of the previous request (after content-length). We will probably need to add a promise or something to support this notification. Note we really have no choice here: If somebody sends a 1GB PUT request, we really do need the client code to read all of it before we can read and start the next request!
2. As an optimization, if the content-length is known to be shorter than some threshold, the server can read it immediately instead of waiting for the client's query processor to read it and waste a few continuations until realizing that this happened.
