### ISSUE TITLE
g++: error: -gz is not supported in this configuration

### ISSUE THREAD

**Issue by chenweijing** [scylladb/seastar#642]
when i compile the seastar by g++5.3.1, have error.

and many errors , like:
../../include/seastar/util/std-compat.hh:218:38: error: ‘nullopt_t’ in namespace ‘std::experimental’ does not name a type
 using nullopt_t = std::experimental::nullopt_t;
                                      ^
../../include/seastar/util/std-compat.hh:220:26: error: ‘nullopt’ is not a member of ‘std::experimental’
 constexpr auto nullopt = std::experimental::nullopt;
                          ^
../../include/seastar/util/std-compat.hh:220:26: note: suggested alternative:
../../include/seastar/util/std-compat.hh:220:16: note:   ‘seastar::compat::nullopt’
 constexpr auto nullopt = std::experimental::nullopt;
                ^
../../include/seastar/util/std-compat.hh:223:18: error: ‘optional’ does not name a type
 inline constexpr optional<std::decay_t<T>> make_optional(T&& value) {
                  ^
../../include/seastar/util/std-compat.hh:228:46: error: ‘basic_string_view’ in namespace ‘std::experimental’ does not name a template type
 using basic_string_view = std::experimental::basic_string_view<CharT, Traits>;
                                              ^
../../include/seastar/util/std-compat.hh:231:41: error: ‘basic_string_view’ does not name a type
 std::string string_view_to_string(const basic_string_view<CharT, Traits>& v) {
                                         ^
../../include/seastar/util/std-compat.hh:231:58: error: expected ‘,’ or ‘...’ before ‘<’ token
 std::string string_view_to_string(const basic_string_view<CharT, Traits>& v) {

**Comment by duarten** [comment]
Please update your compiler and try again.
