### ISSUE TITLE
Seastar Ubuntu 16.04 error

### ISSUE THREAD

**Issue by pltrzglrb** [scylladb/seastar#644]
I am trying to compile seastar on Ubuntu 16.04
1. gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1) 
2. ./configure.py --mode=release --enable-dpdk --cook fmt --c++-dialect c++17
3. ninja -C build/release

I get following errors:

../../tests/unit/rpc_test.cc:728:79:   required from here
/usr/include/c++/7/bits/stl_construct.h:75:7: error: use of deleted function \u2018seastar::temporary_buffer<CharType>::temporary_buffer(const seastar::temporary_buffer<CharType>&) [with CharType = char]\u2019
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../include/seastar/core/sstring.hh:38:0,
                 from ../../include/seastar/core/scheduling.hh:24,
                 from ../../include/seastar/core/task.hh:25,
                 from ../../include/seastar/core/future.hh:25,
                 from ../../include/seastar/core/iostream.hh:38,
                 from ../../tests/unit/loopback_socket.hh:25,
                 from ../../tests/unit/rpc_test.cc:24:
../../include/seastar/core/temporary_buffer.hh:83:5: note: declared here
     temporary_buffer(const temporary_buffer&) = delete;

----------------------------------------------------------------------------
I have tried  c++-dialect c++14, not specify c++14 dialect and I get the same error

Can someone please help me ? Thanks

**Comment by kostja** [comment]
What boost version is installed on your system?

**Comment by xiaoming-qxm** [comment]
> I am trying to compile seastar on Ubuntu 16.04
> 
> 1. gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1)
> 2. ./configure.py --mode=release --enable-dpdk --cook fmt --c++-dialect c++17
> 3. ninja -C build/release
> 
> I get following errors:
> 
> ../../tests/unit/rpc_test.cc:728:79: required from here
> /usr/include/c++/7/bits/stl_construct.h:75:7: error: use of deleted function \u2018seastar::temporary_buffer::temporary_buffer(const seastar::temporary_buffer&) [with CharType = char]\u2019
> { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from ../../include/seastar/core/sstring.hh:38:0,
> from ../../include/seastar/core/scheduling.hh:24,
> from ../../include/seastar/core/task.hh:25,
> from ../../include/seastar/core/future.hh:25,
> from ../../include/seastar/core/iostream.hh:38,
> from ../../tests/unit/loopback_socket.hh:25,
> from ../../tests/unit/rpc_test.cc:24:
> ../../include/seastar/core/temporary_buffer.hh:83:5: note: declared here
> temporary_buffer(const temporary_buffer&) = delete;
> 
> I have tried c++-dialect c++14, not specify c++14 dialect and I get the same error
> 
> Can someone please help me ? Thanks

I got the same error in ubuntu18.04 in seastar-19.06-branch.

**Comment by pltrzglrb** [comment]
The only way I have been able to build seastar on base ubuntu image is:

1. export BOOST_INCLUDEDIR=/home/plrtzglrb/src/boost_1_67_0 (I built boost)
2. install-dependencies.sh 
3. g++ (Ubuntu 9.1.0-2ubuntu2~16.04) 9.1.0
3. configure.py --enable-dpdk --cook fmt --cook c-ares  --compiler=g++ --c-compiler=gcc --c++-dialect=gnu++17 --mode="release"

This gives me a clean build. I was not able to build with gcc-8

**Comment by pltrzglrb** [comment]
I can build seastar so closing this issue.
