### ISSUE TITLE
the `project()` macro created `cmake/Cooking.cmake` changes its behavior

### ISSUE THREAD

**Issue by tchaikov** [scylladb/seastar#645]
we include seastar as a subproject using cmake. in addition to seastar, we are including other subprojects using cmake. but after preparing some seastar dependencies using `./cooking.sh`, i found that some variables which are supposed to be set by `project()`  are not set (correctly) anymore after `add_subdirectory(seastar)`.

for instance, without `cmake/Cooking.cmake`, `project()` of the subprojects included after seastar always set `PROJECT_NAME`, `PROJECT_SOURCE_DIR` and `<PROJECT-NAME>_SOURCE_DIR`. but with it, none of `PROJECT_NAME`, `PROJECT_SOURCE_DIR` and `<PROJECT-NAME>_SOURCE_DIR` is set correctly. if the subprojects in question rely on these cmake variables, cmake will fail to configure them.

in my case, we have a project with
```cmake
target_include_directories(dmclock PUBLIC
  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>
  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/support/src>)
```
so, after including  `cmake/Cooking.cmake` in seastar indirectly, the parent project won't be able to include the specified directories anymore.

**Comment by hakuch** [comment]
Hi @tchaikov. This sounds like it may be an issue with cmake-cooking rather than Seastar.

You can open an issue at [its repository](https://github.com/hakuch/CMakeCooking) if you would like. I'll try to investigate too.

**Comment by tchaikov** [comment]
@hakuch sure, see https://github.com/hakuch/CMakeCooking/issues/38

**Comment by tchaikov** [comment]
closing see https://github.com/hakuch/CMakeCooking/issues/38
