### ISSUE TITLE
Support sleeping (non-polling) mode

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#65]
While Seastar's endless polling improves performance, it is an annoyance for:
* people who just want to try a Seastar application out on their desktop, and are surprised it uses 100% cpu even when idle.
* people who want to run a fairly idle Seastar application on a shared server, when there is not enough CPU to spare a whole CPU for the Seastar application.

It would be great if we had a sleep-based event-loop mode that the user can configure, or better yet - Seasstar will switch to sleep-based on its own when it has no work to do. Of course it is important not to give up any of the performance when the load is high and poll-based loop is used: hopefully without adding more overheads like memory fencing.

**Comment by avikivity** [comment]
Fixed by 9f9182e4cef251ffbb7bd542e507a016bb5d9b5f.
