### ISSUE TITLE
A new release with support for coroutine?

### ISSUE THREAD

**Issue by LiSu** [scylladb/seastar#650]
Dear Authors,

We would like to use Seastar in our project. As the latest release "seastar-18.08-branch" has no support for coroutine, and we plan to use coroutine in our project, is it possible to provide us a stable release branch with support for coroutine? Thanks in advance!

**Comment by avikivity** [comment]
The recommended way to consume Seastar is as a submodule, that you advance when new fixes and features are pulled. However I'm happy to create a new release.

**Comment by avikivity** [comment]
seastar-19.06.0 was released after a lengthy QA process.
