### ISSUE TITLE
when_N, when_any ?

### ISSUE THREAD

**Issue by niekbouman** [scylladb/seastar#676]
Would it be easy to add a `when_N` function to the Future Utilities, which completes when _N_ out of _K_ (where _K_ >=_N_) futures are done? (Then, one could immediately define a function `when_any` for the special case _N_=1.)

**Comment by avikivity** [comment]
It should not be too hard (such things are never really easy).

**Comment by niekbouman** [comment]
I actually meant it as a feature request / suggestion for enhancement ;-) 
(assuming those are welcome)

But now that I re-read my earlier post I realise that I should have phrased that more explicitly.

**Comment by nyh** [comment]
when_any() is definitely possible, but there is one delicate issue which its users will need to be aware of. It leaves some of the futures it was given unwaited (i.e., background work). This means that if one of them will have an exception, the application won't know, and it means that if the application wants to shut down, it won't be able to find out when this background work finishes so it can shut down at a safe time. Background work can also pile up if started too quickly, finishing the machine's memory. These problems can be solved using handle_exception(), semaphore and gate - I recently sent a patch to tutorial.md explaining similar issues with discarded futures. abort_source can also come in handy sometime. But to use when_any() safely the user will need to pay attention to these issues. 

That being said, because these problems are relevant to any type of background work - not just when_any(), I'm not opposed to a when_any() implementation, if properly documented.

**Comment by gleb-cloudius** [comment]
when_N() can return a future (future<future<>>) that will resolve when all background work
is done.

--
			Gleb.

**Comment by nyh** [comment]
@gleb-cloudius a future<future<>> nice idea. It's one complication we don't have yet in Seastar, so let's add it to confuse people further! :-) But seriously, you're right, it's an option. I'm worried, though, it will be difficult to use, and most of the time people will just discard the inner future. It will also not directly solve the issue of amount of background work left behind (the user will still need to use a semaphore to avoid starting too much background work).

**Comment by avikivity** [comment]
seastar::when_all() returns a future of futures, as does std::experimental::when_any().

**Comment by nyh** [comment]
when_all() returns a future vector (yes, of futures), so it's not exactly a future<future<>> but you're right, it's not very far. The idea to look at std::experimental::when_any() and provide a similar interface is good.

**Comment by niekbouman** [comment]
Thank you very much for your responses.
Here is my first attempt for a `wait_for_N` out of K>=N futures, where those futures are passed as a parameter pack. I do not (yet) deal with the problem of unwaited futures, as pointed out @nyh . 

I actually made two versions of `wait_for_N`.
In version 1, I manage the lifetime of everything (the GreedyWaitN obj and the futures) via `do_with`. In version 2, I manage the lifetime of the GreedyWaitN obj via a `lw_shared_ptr` instead. Which approach would be the preferred one?

Somewhat ugly is that the user has to explicitly specify the type `T`; it should be deduceable from the parameter pack `Futures...`, but I didn't find a nice way yet to do that... any suggestions? 

Any feedback would be very welcome.
```cpp

template<size_t N, typename T>
struct GreedyWaitN_Size_at_compile_time {
// This is a helper class with a condition variable, which does not complete
// until enough (N) futures are ready, where those futures should call 
// notify() in their '.then'-continuation  
//
// We assume that all futures involved return the same type T
//
// The return value to the user is of type: tuple< array<size_t, N>, array<T, N>>, 
// where the first array stores the indices of the N futures that completed first,
// the second array stores the return values of those futures (in that order)  
private:
  std::array<size_t,N> indices;
  std::array<T,N> values;
  size_t j = 0;
  seastar::condition_variable cond;

public:
  inline auto wait() {
    return cond.wait([this] { return j >= N; })
               .then([this] { return std::make_tuple(indices,values); });
  }

  inline void notify(size_t index, T&& value) {
    indices[j] = index;
    values[j] = std::move(value);
    ++j;
    cond.signal();
  }
};



template <size_t N, typename T, typename... Futures> 
auto wait_for_N_version1(Futures&&... futures) {
// all futures in the pack must be of type T
  return seastar::do_with(GreedyWaitN_Size_at_compile_time<N, T>(),
		  std::move(futures)..., [] (auto& done, auto&... futures) {
  int i = 0;
  (
    (futures.then([&done, i] (auto&& x) { done.notify(i, std::move(x)); } ), ++i)
    , ... ); // compile-time unrolled for loop, by folding over the comma operator
  return done.wait();
  });
}

template <size_t N, typename T, typename... Futures> 
auto wait_for_N_version2(Futures&&... futures) {
// all futures in the pack must be of type T
  auto done = seastar::make_lw_shared<GreedyWaitN_Size_at_compile_time<N, T>>(); 
  return seastar::do_with(
		  std::move(futures)..., 
		  [done]
		  (auto&... futures) {
  int i = 0;
  (
    (futures.then([done, i] (auto&& x) { done->notify(i, std::move(x)); } ), ++i)
    , ... ); // compile-time unrolled for loop, by folding over the comma operator

  return done->wait();
  
  });
}


// client code

auto some_fut = seastar::sleep(1s).then([] { return 1; });
	
// wait for 2 out of 3 futures, where those futures in the parameter pack can be lvalues and rvalues	
auto new_fut = wait_for_N<2,int>(some_fut, 
seastar::sleep(10s).then([] { return 2; }),
seastar::sleep(2s).then([] { return 3; }))
.then([] (auto&& x) { /* do something useful here */} );

```

**Comment by avikivity** [comment]
Please move the conversation to the mailing list.

I think you should support futures of heterogeneous types, like std::when_any.

**Comment by niekbouman** [comment]
> Please move the conversation to the mailing list.

I'll do that, after I've given it some more thought.
