### ISSUE TITLE
ignore_ready_future doesn't ignore exception

### ISSUE THREAD

**Issue by bhalevy** [scylladb/seastar#678]
Seen with scylladb/scylla@6c4ad932969749ee132c3a13b3c79328a1c575b5
seastar version cb7026c16fca265685cd6350db9cec3fc3c8f7f0
[dtest-release/231/artifact/logs-release.2/1567408407135_nodetool_additional_test.TestNodetool.concurrent_drain_test/node2.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/231/artifact/logs-release.2/1567408407135_nodetool_additional_test.TestNodetool.concurrent_drain_test/node2.log):
```
WARN  2019-09-02 07:12:45,703 [shard 1] seastar - Exceptional future ignored: std::system_error (error system:103, Software caused connection abort), backtrace:   0x2afadad
  0x27f97a4
  0xf36f0d
  0xf397d3
  0xf39adc
  0x27f6cd1
  0x27f6edf
  0x28b110d
  0x28cf59c
  0x27d849d
  /jenkins/workspace/scylla-master/dtest-release/scylla-dtest/../scylla/dynamic_libs/libpthread.so.0+0x85a1
  /jenkins/workspace/scylla-master/dtest-release/scylla-dtest/../scylla/dynamic_libs/libc.so.6+0xfb302

seastar::current_backtrace() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/util/backtrace.hh:55
 (inlined by) seastar::current_backtrace() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/util/backtrace.cc:84
seastar::report_failed_future(std::__exception_ptr::exception_ptr const&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:5809
{lambda()#1}<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::bool_class<seastar::stop_iteration_tag> >::apply<cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}, seastar::accept_result>(cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}&&, seastar::accept_result&&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:287
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:338
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:380
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1306
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/transport/server.cc:234
 (inlined by) apply<cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::<lambda()>::<lambda(seastar::future<seastar::accept_result>)>, seastar::future<seastar::accept_result> > at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1426
seastar::future<seastar::accept_result>::then_wrapped_impl<cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}, seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >(cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}&&)::{lambda()#1}::operator()() const::{lambda(seastar::future_state<seastar::accept_result>&&)#1}::operator()({lambda()#1}) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1116
seastar::continuation<seastar::future<seastar::accept_result>::then_wrapped_impl<cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}, seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >(cql_transport::cql_server::do_accepts(int, bool, seastar::socket_address)::{lambda()#1}::operator()() const::{lambda(seastar::future<seastar::accept_result>)#1}&&)::{lambda()#1}::operator()() const::{lambda(seastar::future_state<seastar::accept_result>&&)#1}, seastar::accept_result>::run_and_dispose() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:414
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:3825
seastar::reactor::run_some_tasks() [clone .part.0] at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:4252
seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:4235
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:4396
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/reactor.cc:5661
seastar::posix_thread::start_routine(void*) at /usr/include/c++/9/bits/std_function.h:690
 (inlined by) seastar::posix_thread::start_routine(void*) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/src/core/posix.cc:52
```

It looks like this is caused by 72d209bf7d8a3d9b2fb22b72511df4716973d5c6 where previously the exception_ptr was silently destroyed in `~future_state()` and with this change it is always reported by `~future_state_base()`

**Comment by bhalevy** [comment]
@espindola please look into this

**Comment by bhalevy** [comment]
@espindola please see warnings in `tests/unit/futures_test`

**Comment by gleb-cloudius** [comment]
It was deliberately made this way.

--
			Gleb.

**Comment by bhalevy** [comment]
> It was deliberately made this way.
@gleb-cloudius not according to its comment:
```
    /// Ignore any result (value or exception) hold by this future.
```

**Comment by gleb-cloudius** [comment]
On Wed, Sep 04, 2019 at 03:14:02AM -0700, Benny Halevy wrote:
> > It was deliberately made this way.
> @gleb-cloudius not according to its comment:
> ```
>     /// Ignore any result (value or exception) hold by this future.
> ```
> 
Hmm. I misremember then. I remember there were reservation that it will
make very easy to ignore errors this way. Now I see that the function
started its life as ignore_result_and_exception() to make it clear and
then changed its name to more ambiguous one.

--
			Gleb.

**Comment by bhalevy** [comment]
> On Wed, Sep 04, 2019 at 03:14:02AM -0700, Benny Halevy wrote: > It was deliberately made this way. @gleb-cloudius not according to its comment: ``` /// Ignore any result (value or exception) hold by this future. ```
> Hmm. I misremember then. I remember there were reservation that it will make very easy to ignore errors this way. Now I see that the function started its life as ignore_result_and_exception() to make it clear and then changed its name to more ambiguous one.

I'm ok with having 2 functions to resolve the ambiguity and explicitly use `ignore_result_or_exception` where needed. while changing `ignore_ready_future` to ignore only non-error results.

**Comment by gleb-cloudius** [comment]
On Wed, Sep 04, 2019 at 03:29:58AM -0700, Benny Halevy wrote:
> > On Wed, Sep 04, 2019 at 03:14:02AM -0700, Benny Halevy wrote: > It was deliberately made this way. @gleb-cloudius not according to its comment: ``` /// Ignore any result (value or exception) hold by this future. ```
> > Hmm. I misremember then. I remember there were reservation that it will make very easy to ignore errors this way. Now I see that the function started its life as ignore_result_and_exception() to make it clear and then changed its name to more ambiguous one.
> 
> I'm ok with having 2 functions to resolve the ambiguity and explicitly use `ignore_result_or_exception` where needed. while changing `ignore_ready_future` to ignore only non-error results.
> 
The later is used in many places already with current semantics. Such
rename will only add churn.

--
			Gleb.
