### ISSUE TITLE
Required `cryptopp` dependency for.... `md5`?

### ISSUE THREAD

**Issue by ahkok** [scylladb/seastar#680]
I'm seeing if we can put `scylla` into `clearlinux`. But while packaging `seastar` I see it has a hard dependency for `cryptopp`.

It seems that this dependency is absolutely unwanted because (1) it's yet another copy of crypto algorithms we need to vet, secure and keep patched, and (2) it's probably unoptimized. (3) it's only needed for `md5` - do I see that right? Why? /sadface.

Can you please make `cryptopp` optional and allow distributions to link alternative `md5` implementations? Any of the algorithms from `openssl`, `gnutls` is fine, there's even the Linux kernel one available.

In the current condition I don't see `cryptopp` ever making it into clearlinux, so, this would be a blocker for us.

**Comment by ahkok** [comment]
I'd appreciate a reply, even if it is "please send a patch" or "rejected, we want to keep this" so I can move on or decide to do the work...

**Comment by 303248153** [comment]
You can just send a patch to the mailing list, it would be eaiser to get response.

**Comment by ahkok** [comment]
Didn't know there was one... looking at the state of this issue tracker.. I wonder if it should be advertised better ;)

**Comment by avikivity** [comment]
The mailing list is https://groups.google.com/forum/#!forum/seastar-dev. 

I agree that dropping cryptopp in favor of the existing gnutls is a net win.

**Comment by nyh** [comment]
I second (or third) this opinion. When we needed an HMAC implementation for Alternator, we also used the GnuTLS one, not cryptopp (by the way, please don't introduce a new dependency on openssl).
Someone just needs to verify that GnuTLS really has the required hash-function functionality, and do the switch. Looks like it should be a fairly easy task.

**Comment by ahkok** [comment]
I've got a patch compiling - it's indeed incredibly trivial and only a single call to the md5 hash function.

Since I can't compile against today's 809b3ef875e7edb7c56643812dc8347ff9a82cee for some reason (various other build issues unrelated to my changes) I'll need a bit of time to sort it out.

**Comment by espindola** [comment]
Probably the easiest way to test a build is with dbuild.  It uses a fedora
image in docker.

Cheers,
Rafael

**Comment by ahkok** [comment]
> Probably the easiest way to test a build is with dbuild.  It uses a fedora image in docker.

My ulitmate goal is to include Scylla in Clear Linux OS (since, dev), so, segwaing out to Fedora solves nothing for me :)

**Comment by nyh** [comment]
@ahkok, if you can send a patch that you prepared for Seastar to use GnuTLS's md5 instead of cryptopp's, I can help you test it if you have other problems in the build.
Scylla (which you mentioned in the first report) also has its own uses of cryptopp (for md5 and sha) but let's fix the Seastar ones first (plus, this is the Seastar issue tracker...).

**Comment by ahkok** [comment]
I came up with this, which compiles. But I haven't had the time to validate this and would appreciate it is actually tested by someone who can vouch for it :)

[0001-Remove-Cryptopp-dependency-replace-with-GNUTLS-md5.patch.log](https://github.com/scylladb/seastar/files/3913443/0001-Remove-Cryptopp-dependency-replace-with-GNUTLS-md5.patch.log)

**Comment by espindola** [comment]
The patch seems reasonable. Please send it to
seastar-dev@googlegroups.com.

Thanks,
Rafael

**Comment by espindola** [comment]
But there are still a few places that need to be updated:

$ git grep -l cryptopp
cooking_recipe.cmake
install-dependencies.sh
kvm/scripts/bootstrap.sh
pkgconfig/seastar.pc.in

Cheers,
Rafael

**Comment by ahkok** [comment]
Sent!

**Comment by ahkok** [comment]
@nyh would appreciate your testing :)

**Comment by nyh** [comment]
Hi @ahkok, I want to finally get this issue fixed. You sent to the mailing list a patch:
```
[PATCH 1/2] Remove Cryptopp dependency, replace with GNUTLS md5.
```
(there was a second patch in this series, but it was irrelevant).

@avikivity had some comments on your patch, but you didn't reply or send a new version of this patch. I want to see this patch moving forward  - are you still interested in this patch, or would you like me to continue pushing it myself? Thanks.

**Comment by ahkok** [comment]
I would love to, but I've run out of space cycles for something like this. Moreover, I have little confidence that my patch actually does the right thing - while I understand crypto mechanics, most of the crypto API's are wholly unfamiliar to me. I'd love to be able to ship ScyllaDB in clear linux, though, so perhaps best to keep me in the loop and if I have time to review/test I'll try and contribute it.

**Comment by tchaikov** [comment]
@nyh hey Nadav, are you still working on this? if not, i'd like to try to fix it.

**Comment by nyh** [comment]
@tchaikov sure. It's yours. Note that there was one patch above, but it may be out of date.

**Comment by tchaikov** [comment]
@nyh thanks. i checked that patch. as the change is quite trivial, so i started from scratch.
