### ISSUE TITLE
Build error on Fedora 30

### ISSUE THREAD

**Issue by castillobgr** [scylladb/seastar#687]
I'm following the instructions on the readme to build seastar on a fresh Fedora 30 Workstation install, but regardless of the alternative I use, I always get the following error:
```sh
/usr/bin/ld: ../lib/.libs/libgnutls.so: undefined reference to `_idn2_punycode_decode'
```
GCC version:
`gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)`

Things I've tried:

- `./configure.py --mode=release && ninja -C build/release`
- `./configure.py --mode=release --cook c-ares --cook lz4 --cook GnuTLS --cook nettle`
- `./cooking.sh`

GnuTLS is installed:
```
$ dnf list --installed | grep gnutls
gnutls.x86_64                                     3.6.8-1.fc30                        @updates        
gnutls-c++.x86_64                                 3.6.8-1.fc30                        @updates        
gnutls-dane.x86_64                                3.6.8-1.fc30                        @updates        
gnutls-devel.x86_64                               3.6.8-1.fc30                        @updates
```
but if I leave it out of the list passed to `configure.py` I get this:
```CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GnuTLS: Found unsuitable version "", but required is at
  least "3.3.26" (found /usr/lib64/libgnutls.so)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGnuTLS.cmake:47 (find_package_handle_standard_args)
  cmake/SeastarDependencies.cmake:101 (find_package)
  CMakeLists.txt:275 (seastar_find_dependencies)
```

Any help is much appreciated!

**Comment by avikivity** [comment]
Strange, I have the same rpms installed, and plain ./configure.py works for me.

Perhaps some files are missing? Try `dnf reinstall` on those packages, or rpm  -q --verify to just check.

Unfortunately, I can't help with understanding why cmake did not find the library, as I don't know it will enough.

**Comment by castillobgr** [comment]
Thanks for the suggestion!

However, reinstalling didn't change anything, and `rpm -q --verify gnutls` executes normally.

**Comment by nyh** [comment]
On Sat, Sep 28, 2019 at 8:16 PM David Castillo <notifications@github.com>
wrote:

> I'm following the instructions on the readme to build seastar on a fresh
> Fedora 30 Workstation install, but regardless of the alternative I use, I
> always get the following error:
>
> /usr/bin/ld: ../lib/.libs/libgnutls.so: undefined reference to `_idn2_punycode_decode'
>
>
The fact you see here "../lib/.libs/libgnutls.so"  suggests the "cook"
stuff built your own copy of gnutls.so, and probably did it wrong -
libgnutls.so needs to DT_REQUIRE libdn2.so. It would be nice to investigate
why, but personally my suggestion is that you should not use "cook" at all
if you can. Fedora 30 can easily compile Seastar with the libraries coming
with the system - you don't need to "cook" anything. Just don't forget to
run (I guess you did...)

    sudo ./install_dependencies.sh

If this doesn't work, I think we have another problem - but shouldn't use
"cook" to work around it.


> GnuTLS is installed:
>
> $ dnf list --installed | grep gnutls
> gnutls.x86_64                                     3.6.8-1.fc30                        @updates
> gnutls-c++.x86_64                                 3.6.8-1.fc30                        @updates
> gnutls-dane.x86_64                                3.6.8-1.fc30                        @updates
> gnutls-devel.x86_64                               3.6.8-1.fc30                        @updates
>
> but if I leave it out of the list passed to configure.py I get this:
>
>   Could NOT find GnuTLS: Found unsuitable version "", but required is at
>   least "3.3.26" (found /usr/lib64/libgnutls.so)
>
>
This looks like a bug in our cmake scripts. I don't know where it finds
this ""  version thing, and why this
bug happens on your system but not on others. But it's definitely a bug -
if gnutls is outright missing,
the message should should say so. If it's not missing, it shouldn't be
missing its version number
(there is the GNUTLS_VERSION_NUMBER macro).

Anybody without a cmake allergy willing to take a look at this issue?

**Comment by castillobgr** [comment]
On Sun, Sep 29, 2019, 2:19 AM nyh <notifications@github.com> wrote:

> On Sat, Sep 28, 2019 at 8:16 PM David Castillo <notifications@github.com>
> wrote:
>
> > I'm following the instructions on the readme to build seastar on a fresh
> > Fedora 30 Workstation install, but regardless of the alternative I use, I
> > always get the following error:
> >
> > /usr/bin/ld: ../lib/.libs/libgnutls.so: undefined reference to
> `_idn2_punycode_decode'
> >
> >
> The fact you see here "../lib/.libs/libgnutls.so" suggests the "cook"
> stuff built your own copy of gnutls.so, and probably did it wrong -
> libgnutls.so needs to DT_REQUIRE libdn2.so. It would be nice to investigate
> why, but personally my suggestion is that you should not use "cook" at all
> if you can. Fedora 30 can easily compile Seastar with the libraries coming
> with the system - you don't need to "cook" anything. Just don't forget to
> run (I guess you did...)
>
> sudo ./install_dependencies.sh
>
I did, yes.

>
> If this doesn't work, I think we have another problem - but shouldn't use
> "cook" to work around it.
>
>
> > GnuTLS is installed:
> >
> > $ dnf list --installed | grep gnutls
> > gnutls.x86_64 3.6.8-1.fc30 @updates
> > gnutls-c++.x86_64 3.6.8-1.fc30 @updates
> > gnutls-dane.x86_64 3.6.8-1.fc30 @updates
> > gnutls-devel.x86_64 3.6.8-1.fc30 @updates
> >
> > but if I leave it out of the list passed to configure.py I get this:
> >
> > Could NOT find GnuTLS: Found unsuitable version "", but required is at
> > least "3.3.26" (found /usr/lib64/libgnutls.so)
> >
> >
> This looks like a bug in our cmake scripts. I don't know where it finds
> this "" version thing, and why this
> bug happens on your system but not on others. But it's definitely a bug -
> if gnutls is outright missing,
> the message should should say so. If it's not missing, it shouldn't be
> missing its version number
> (there is the GNUTLS_VERSION_NUMBER macro).
>

This part made me suspect something was misconfigured or broken (even
though it was a fresh Fedora 30 install). I couldn't find any way to fix
it, so I just went ahead and reinstalled the OS and everything works fine
now.

If it's ok, I think this issue can be closed.

**Comment by castillobgr** [comment]
Thanks everyone for your help!

**Comment by sunzhenkai** [comment]
According to logs
```
...
-- Found PkgConfig: /home/linuxbrew/.linuxbrew/bin/pkg-config (found version "0.29.2") 
...
```
Then removed brew config in `~/.bash_profile`
```
...
#eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
...
```

This fixed my problem.
