### ISSUE TITLE
IPV6 socket_address does not take scope_id into consideration

### ISSUE THREAD

**Issue by elcallio** [scylladb/seastar#692]
When using link-local ipv6 addresses (fec0::/10), "scope" must be taken into account for bind, where Linux defines scope as "interface index". 

Seastar currently completely ignores this part of sockaddr6 and even does not even zero it. 

To fully handle this, we probably need to do the same sort of ugly mix-of-concerns that Java inetaddress does, and include scope in inet_address (even though this is the wrong level for this) for ipv6, handling parsing <address>%scope syntax. However, since scope is what it is, this sort of depends on implementing an actual network interface abstraction as well (as scope is mucg easier to express as "eth0" than looking at hex values in /proc and figuring out the actual if index).

**Comment by slivne** [comment]
this was merged in 2963970f6bd238a03c6d1d928ee2c076d534bb8c
