### ISSUE TITLE
 parallel_for_each() got stuck when I called seastar::sleep()

### ISSUE THREAD

**Issue by xiaoming-qxm** [scylladb/seastar#717]
```cpp
#include <seastar/core/sleep.hh>
#include <seastar/core/future-util.hh>
#include <seastar/core/app-template.hh>
#include <boost/range/irange.hpp>
#include <seastar/core/reactor.hh>

using namespace seastar;
using namespace std::chrono_literals;

int main(int ac, char** av) {
    app_template app;
    app.run(ac, av, [] {
        return parallel_for_each(boost::irange(0u, smp::count), [] (unsigned c) {
            return smp::submit_to(c, [] {
                return sleep(1s).then([] {
                    fmt::print("After sleep on shard {}\n", engine().cpu_id());
                });
            });
        });
    });
}
```
This is my example program above. My terminal only print `After sleep on shard 0` then got stuck when I ran the program. 

Is there any bug for `seastar::sleep()`?

**Comment by nyh** [comment]
I tried the same code, and it works for me... I also added a "Before sleep" message and got:

```
$ ./a.out -m1G -c4
Before sleep on shard 0
Before sleep on shard 0
Before sleep on shard 0
Before sleep on shard 0
After sleep on shard 0
After sleep on shard 3
After sleep on shard 1
After sleep on shard 2
```
And then the program exited.
In other runs I got a different message order, of course, but it never hung in about 10 times I tried.

I wonder what we're doing differently.

**Comment by xiaoming-qxm** [comment]
@nyh Sorry for less information. I'm using seastar-19.06-branch on debug mode.

**Comment by nyh** [comment]
I tested (latest master version) also in debug mode, and it works fine - same as release mode...
Can you please test "master" branch too?

**Comment by xiaoming-qxm** [comment]
It works for me on master branch.
