### ISSUE TITLE
idea: "closable" concept

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#724]
RAII is a very powerful C++ technique, but without coroutines and without assuming a `seastar::thread`, it is very difficult to use it in Seastar for two reasons:

1. Usually you can't just create the object - you need to call a factory function returning a **future** object.

2. Usually you can't just destroy the object - you need to call a function returning a future, which you should wait for before destroying the object. This function is typically called "close()".

`seastar::do_with()` could be modified (or a different-named function created) to help us with both parts.
First, do_with() could wait for a future value - that is exactly issue #376. 
Second, the present issue is about the second part: do_with() should, when the object is "closable", i.e., has a future<> close() method, call it before destroying the object.

With both features in place, someone could write code like:

```c++
return do_with(open_file_dma("filename"), [] (file& f) {
    // do something with f
    return(...);
 }
```

In this example, do_with() automatically waits for the future returned by open_file_dma() before starting the user's function, and close()es the file before destroying.

Note that "closable" types would need to have an idempotent close(), i.e., closing an already closed file should do nothing. This is to allow the code to choose to wait for close() explicitly itself (e.g., to check for errors). 
(by the way, Java actually has two types of interfaces - Closable with an idempotent close(), and AutoClosable without it).

**Comment by denesb** [comment]
Very good idea.

Python's [with statement](https://docs.python.org/2/reference/compound_stmts.html#the-with-statement) is also similar.

**Comment by denesb** [comment]
Types that need `future<>` returning `close()` could enforce special treatment by making their destructor private and having some other named method that calls it.

**Comment by bhalevy** [comment]
Cc @espindola

**Comment by nyh** [comment]
An interesting question is whether `close()` should be allowed to return an exceptional future:

1.  On one hand, it shouldn't, for the same reason that ordinary C++ destructors are not allowed to throw: If `close()` throws, what does it mean? Was the closing done, or not? Is it safe now to destroy the object, or not? Remember that the whole idea of `close()` is that we must wait for it before we destroy the object, so did we wait enough?
2. On the other hand, we already have `close()` methods which do resolve with an exception - for example `output_stream::close()` can resolve with an exception if it has an I/O failure writing the buffered output; In commit 9c9d943e3a3773335ab38c20c778adf23dc886f5 we added a `file::close()` and one of the stated reasons for doing it was that it can report "latent errors that did not have the opportunity to be reported earlier".

So I think we should allow  `close()` can to resolve with an exception, but **require** that even in that case, `close()` must guarantee that the closed object may now be safely destroyed. If a `close()` implementation finds that it cannot make this guarantee, it should be abort (just like happens in C++ if a destructor throws).

Note that if a closable object holds multiple other closable objects, its `close()` will naturally want to call `close()` for the
sub-objects it holds, but will be **wrong** to do something like the following:
```c++
    }).then([this] {
        return _object1->close();
    }).then([this] {
        return _object2->close();
```
The problem is that if object1's `close()` reported an error, object2's `close()` will never be called. This means we return before waiting for object2's closing to finish, and when we return, and the caller destroys the big object and object2 in it, we can crash. Implementations should use `finally()` here, or start all sub-object `close()` operations in parallel and then `when_all_succeed()` on them.

An alternative approach would have been to decide that close() can never fail (neither throw nor return an exceptional future), and instead *after* close() is done, a separate method could be used to retrieve an error to log (or, if not retrieved, this error will just be logged). But if we do this, we will need to change some of the existing `close()` methods which we already have, which is probably too late.

**Comment by bhalevy** [comment]
1f1c0a23a89329b63b95dcb0372f12c9243e29f1
4d6952630b46f569452b481278147e9c980b9671
d2dcda96bb266b4c501eb14ba3d26105fc22271c

**Comment by bhalevy** [comment]
FWIW, in https://github.com/bhalevy/scylla/commits/flat_mutation_reader-close-v4 (that uses the closeable concept introduced by the above patches), flat_mutation_reader::close can never fail, as you described above, without a separate method to collect errors post close, as the object is expected to never be used again after `close()`, until be destroyed.

**Comment by nyh** [comment]
As @bhalevy noted, a <seastar/util/closable.hh> appeared in Seastar, with `with_closable()` that does what I described above (holds the closable object and runs the given function with `do_with`, and finally closes the object).

I'm not sure I like everything I see in the current implementation - for example there's also an idempotent `deferred_close` class but it is only for Seastar threads, and I don't see any mentions of whether close may return an exception or not.. but what's done is done, and it seems that there is no room for such a general issue any more and it should have been closed earlier.
