### ISSUE TITLE
http server is missing support for percent decoding

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#725]
When an HTTP client encodes a URL, it usually encodes each of its components and subcomponents - **separately** - using so-called "percent encoding" (see https://en.wikipedia.org/wiki/Percent-encoding or the detailed definition in https://tools.ietf.org/html/rfc3986#section-2.1). Each character inside one of the subcomponents (e.g. one of the query parameters) which isn't alphanumeric, -, ., _ or ~ - is usually replaced by "%" and the two-byte hexadecimal representation of that character.

Seastar's HTTP server should do the reverse transformation, percent decoding, before passing the URL components (the path, query parameters, etc.) to the application code. But Seastar's HTTP server is missing this decoding part.

As an example of bugs this causes, see the Scylla bug https://github.com/scylladb/scylla/issues/5883. In that bug, the client fetched the URL "/column_family/metrics/write_latency/moving_average_histogram/a#usertable:usertable", which was encoded: The client changed the "#" into "%23", as it should (it could have changed also the ":" but decided not too). The Scylla code got it as "a%23usertable:usertable"  and reported that it couldn't find the table "a%23usertable:usertable" - which of course doesn't exist, the real table name is "a#usertable:usertable".

Another Scylla bug caused by this is https://github.com/scylladb/scylla/issues/9614.

**Comment by fruch** [comment]
here's this example as a unit test:
```
diff --git a/tests/unit/httpd_test.cc b/tests/unit/httpd_test.cc
index aeeaa304..2991b7df 100644
--- a/tests/unit/httpd_test.cc
+++ b/tests/unit/httpd_test.cc
@@ -72,6 +72,10 @@ SEASTAR_TEST_CASE(test_match_rule)
     res = mr.get("/hell/val1", param);
     httpd::handler_base* nl = nullptr;
     BOOST_REQUIRE_EQUAL(res, nl);
+
+    res = mr.get("/hello/a%23usertable", param);
+    BOOST_REQUIRE_EQUAL(param["param"], "a#usertable");
+
     return make_ready_future<>();
 }
```

would using https://github.com/cpp-netlib/url is solid enough ? 
seems like easy enough contribution for seastar, at least as my first one...

**Comment by nyh** [comment]
Just git bitten by this bug in another ScyllaDB use case :-( The user wanted to pass the "!" character to our HTTP server inside one of the path components. The user's library decided to percent-encode this character to "%21" (which according to the RFC, is not necessary, but legal) and the HTTP server got the string "%21" in the path instead of "!".

**Comment by nyh** [comment]
Looking at the code, it seems that the **query** part of the URI (what's after the "?") is already decoded correctly - in src/http/request.cc, `request::add_param()`, which is called for each parameter in the query part of the URI seperately, correctly calls `http::internal::url_decode()`.

But for the **path** part of the URI, `request::parse_query_param()` fails to call the decoding function on the path string it returns. The fix to this function looks trivial - just call `http::internal::url_decode()` before returning.

So the bug is only in the **path** part of the URI. Indeed in all the buggy examples quoted above, the encoded character was always part of the path, not the query parameters (after a "?").

We should write a test that verifies that decoding works appropriately in both cases - path and query. I suspect this will be the bulk of the PR fixing this issue (the fix itself will be just one line, if I understand correctly).
