### ISSUE TITLE
perftune.py: CPU configuration mode choosing logic should be changed

### ISSUE THREAD

**Issue by eliransin** [scylladb/seastar#729]
The logic should ignore the: `rx_queues_count == num_PUs` condition that causes it to choose
mq mode over sq/sq_split modes.
Field experience shows that sq is better for latencies.
/cc @glommer @gleb-cloudius 
Ref #308 - discusses this configuration in relation to i3 instances.

**Comment by eliransin** [comment]
After talking with @vladzcloudius he clarified that the reason for doing this is that
sharing the queues with interrupt handling routines impacts high percentage latencies.

**Comment by tarzanek** [comment]
hello guys, what is the progress? 
I see the thread [seastar-dev] [PATCH] perftune.py - ignore num rx queues when chosing default cpuset mode
( https://groups.google.com/g/seastar-dev/c/5EkX0KMh-TM/m/3sB8qKXMAwAJ  )
is kinda blocked ... @eliransin can it be pushed?
@avikivity help? :-)

**Comment by vladzcloudius** [comment]
I believe this was resolved together with #949
