### ISSUE TITLE
compile error.

### ISSUE THREAD

**Issue by kenryhuang** [scylladb/seastar#736]
there's numerous compile error when building seastar master branch...

/usr/local/gcc-9.2/bin/g++  -DFMT_LOCALE -DSEASTAR_API_LEVEL=2 -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_GCC6_CONCEPTS -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_USE_STD_OPTIONAL_VARIANT_STRINGVIEW -I../../include -Igen/include -I../../src -Igen/src -O2 -g -DNDEBUG   -std=gnu++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -Wno-error=unused-result -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -fconcepts -MD -MT CMakeFiles/seastar.dir/src/core/file.cc.o -MF CMakeFiles/seastar.dir/src/core/file.cc.o.d -o CMakeFiles/seastar.dir/src/core/file.cc.o -c ../../src/core/file.cc
In file included from /usr/local/gcc-9.2/include/c++/9.2.0/bits/char_traits.h:39,
                 from /usr/local/gcc-9.2/include/c++/9.2.0/ios:40,
                 from /usr/local/gcc-9.2/include/c++/9.2.0/ostream:38,
                 from /usr/local/gcc-9.2/include/c++/9.2.0/iterator:64,
                 from /usr/local/include/boost/iterator/iterator_traits.hpp:10,
                 from /usr/local/include/boost/range/mutable_iterator.hpp:23,
                 from /usr/local/include/boost/range/iterator.hpp:20,
                 from /usr/local/include/boost/range/begin.hpp:24,
                 from /usr/local/include/boost/range/numeric.hpp:27,
                 from ../../src/core/file.cc:32:
/usr/local/gcc-9.2/include/c++/9.2.0/bits/stl_algobase.h:268:56: error: macro "max" passed 3 arguments, but takes just 2
  268 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |                                                        ^
In file included from /usr/include/xfs/platform_defs.h:9,
                 from /usr/include/xfs/xfs.h:36,
                 from ../../src/core/file.cc:30:

compiler: gcc9.2
boost : 1.72.0

it all be ok when switch to seastar-19.06-branch use same configuration, am I miss something?

**Comment by avikivity** [comment]
There is a macro "max" in xfs/platform_defs that screws things up.

**Comment by avikivity** [comment]
Update your xfsprog-devel package.
