### ISSUE TITLE
[shard 0] cql_server - exception while processing connection: std::system_error (error GnuTLS:-10,  The specified session has been invalidated for some reason.)

### ISSUE THREAD

**Issue by krisdaniels** [scylladb/seastar#737]
Issue is caused by clients with TLS1.3 support, in my case it was prestosql 330 on java11 which will try tls1.3 before any other versions.  

The version of GNUTLS that is currently in use does not support TLS1.3 yet and gives this weird exception.
 
in cooking_recipe.cmake, line 162 : 
EXTERNAL_PROJECT_ARGS
URL https://www.gnupg.org/ftp/gcrypt/gnutls/v3.5/gnutls-3.5.18.tar.xz

TLS1.3 support was added in GNUTLS 3.6.4
https://gnutls.org/news.html

Current workaround for java11/prestosql is to only allow TLS1.2 :
-Djdk.tls.client.protocols=TLSv1.2

**Comment by avikivity** [comment]
What version of scylla are you using?

**Comment by avikivity** [comment]
Also, this should be on the scylla tracker, not Seastar. The version in cooking_recipe is for when there isn't a gnutls already installed.

**Comment by krisdaniels** [comment]
sure, scylla version 3.3.0, and cassandra-stress inside the official dockerimage has the same issue, since seastar handles the tls for scylla i posted it here

**Comment by avikivity** [comment]
scylla-3.3.0 uses gnutls-3.6.11.  So this should have worked.

Please file an issue in the scylla tracker.
