### ISSUE TITLE
Is it safe to suppress strict-aliasing error(warning) when I build seastar with gcc-6

### ISSUE THREAD

**Issue by xiaoming-qxm** [scylladb/seastar#752]
I got an error "dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]" when I compile seastar-19.06-branch using gcc-6. But it works fine when I use gcc-8. However, gcc-6 is only available for my application.

So, my question is that is it safe to just suppress this warning(error) by disabling strict-aliasing checks on gcc-6?

P.S. the error log is list as follow:

> ../../src/net/posix-stack.cc: In lambda function:
> ../../src/net/posix-stack.cc:552:85: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
>                  dst = ipv4_addr(reinterpret_cast<const in_pktinfo*>(CMSG_DATA(cmsg))->ipi_addr, _address.port());

**Comment by avikivity** [comment]
This can be rewritten in a way that doesn't trigger the warning. I'll post a patch.

**Comment by xiaoming-qxm** [comment]
> This can be rewritten in a way that doesn't trigger the warning. I'll post a patch.

Awesome. I would be grateful if you keep me informed when you have posted this patch.
