### ISSUE TITLE
Buding error

### ISSUE THREAD

**Issue by mjrao** [scylladb/seastar#758]
commitid: 2a09fe6c5e28a981e7936741575cf226a9f54c41

ubuntu 20.04 & gcc9.3/g++9.3

../../src/rpc/rpc.cc:181:31: error: use of deleted function ‘seastar::output_stream<CharType>& seastar::output_stream<CharType>::operator=(seastar::output_stream<CharType>&&) [with CharType = char]’
  181 |       _write_buf = _fd.output()

../../src/net/dns.cc:818:58: error: use of deleted function ‘std::optional<seastar::output_stream<char> >& std::optional<seastar::output_stream<char> >::operator=(std::optional<seastar::output_stream<char> >&&)’

**Comment by avikivity** [comment]
Can you provide more context?

**Comment by mjrao** [comment]
ninja: Entering directory `build/release'
[2/29] Building CXX object CMakeFiles/seastar.dir/src/net/dns.cc.o
FAILED: CMakeFiles/seastar.dir/src/net/dns.cc.o 
/usr/bin/g++  -DFMT_LOCALE -DSEASTAR_API_LEVEL=3 -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -I../../include -Igen/include -I../../src -Igen/src -O2 -g -DNDEBUG   -std=gnu++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -Wno-error=unused-result -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -MD -MT CMakeFiles/seastar.dir/src/net/dns.cc.o -MF CMakeFiles/seastar.dir/src/net/dns.cc.o.d -o CMakeFiles/seastar.dir/src/net/dns.cc.o -c ../../src/net/dns.cc
../../src/net/dns.cc: In member function ‘ssize_t seastar::net::dns_resolver::impl::do_sendv(ares_socket_t, const iovec*, int)’:
../../src/net/dns.cc:818:58: error: use of deleted function ‘std::optional<seastar::output_stream<char> >& std::optional<seastar::output_stream<char> >::operator=(std::optional<seastar::output_stream<char> >&&)’
  818 |                         e.tcp.out = e.tcp.socket.output(0);
      |                                                          ^
In file included from /usr/include/c++/9/bits/node_handle.h:39,
                 from /usr/include/c++/9/bits/hashtable.h:37,
                 from /usr/include/c++/9/unordered_map:46,
                 from /usr/include/c++/9/functional:61,
                 from /usr/include/c++/9/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/9/algorithm:71,
                 from /usr/include/boost/iterator/iterator_concepts.hpp:26,
                 from /usr/include/boost/range/concepts.hpp:20,
                 from /usr/include/boost/range/size_type.hpp:20,
                 from /usr/include/boost/range/size.hpp:21,
                 from /usr/include/boost/range/functions.hpp:20,
                 from /usr/include/boost/range/iterator_range_core.hpp:38,
                 from /usr/include/boost/lexical_cast.hpp:30,
                 from ../../src/net/dns.cc:26:
/usr/include/c++/9/optional:656:11: note: ‘std::optional<seastar::output_stream<char> >& std::optional<seastar::output_stream<char> >::operator=(std::optional<seastar::output_stream<char> >&&)’ is implicitly deleted because the default definition would be ill-formed:
  656 |     class optional
      |           ^~~~~~~~
/usr/include/c++/9/optional:656:11: error: use of deleted function ‘std::_Enable_copy_move<false, false, true, false, _Tag>& std::_Enable_copy_move<false, false, true, false, _Tag>::operator=(std::_Enable_copy_move<false, false, true, false, _Tag>&&) [with _Tag = std::optional<seastar::output_stream<char> >]’
In file included from /usr/include/c++/9/optional:43,
                 from /usr/include/c++/9/bits/node_handle.h:39,
                 from /usr/include/c++/9/bits/hashtable.h:37,
                 from /usr/include/c++/9/unordered_map:46,
                 from /usr/include/c++/9/functional:61,
                 from /usr/include/c++/9/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/9/algorithm:71,
                 from /usr/include/boost/iterator/iterator_concepts.hpp:26,
                 from /usr/include/boost/range/concepts.hpp:20,
                 from /usr/include/boost/range/size_type.hpp:20,
                 from /usr/include/boost/range/size.hpp:21,
                 from /usr/include/boost/range/functions.hpp:20,
                 from /usr/include/boost/range/iterator_range_core.hpp:38,
                 from /usr/include/boost/lexical_cast.hpp:30,
                 from ../../src/net/dns.cc:26:
/usr/include/c++/9/bits/enable_special_members.h:258:5: note: declared here
  258 |     operator=(_Enable_copy_move&&) noexcept                         = delete;
      |     ^~~~~~~~
../../src/net/dns.cc: In constructor ‘seastar::net::dns_resolver::impl::sock_entry::sock_entry(seastar::net::dns_resolver::impl::sock_entry&&)’:
../../src/net/dns.cc:915:38: error: use of deleted function ‘seastar::net::dns_resolver::impl::tcp_entry& seastar::net::dns_resolver::impl::tcp_entry::operator=(seastar::net::dns_resolver::impl::tcp_entry&&)’
  915 |                 tcp = std::move(e.tcp);
      |                                      ^
../../src/net/dns.cc:880:12: note: ‘seastar::net::dns_resolver::impl::tcp_entry& seastar::net::dns_resolver::impl::tcp_entry::operator=(seastar::net::dns_resolver::impl::tcp_entry&&)’ is implicitly deleted because the default definition would be ill-formed:
  880 |     struct tcp_entry {
      |            ^~~~~~~~~
../../src/net/dns.cc:880:12: error: use of deleted function ‘std::optional<seastar::output_stream<char> >& std::optional<seastar::output_stream<char> >::operator=(std::optional<seastar::output_stream<char> >&&)’
[7/29] Building CXX object CMakeFiles/seastar.dir/src/net/net.cc.o
ninja: build stopped: subcommand failed.

**Comment by mjrao** [comment]
> Can you provide more context?

commit id:d2fb86f84cf66a8a5fc149e01a922f4bd5698060  had fix this error.
