### ISSUE TITLE
Support for Http / Https client

### ISSUE THREAD

**Issue by anujjamwal** [scylladb/seastar#761]
Currently, Seastar does not have any example/lib to support https calls. Is it possible to add atleast an example for https ?

**Comment by nyh** [comment]
Hi, I see you answered your own question on the mailing list, there is a test `tests/unit/tls_test.cc`, which does HTTPS requests (client side). 

If you want to keep this issue open, please be more explicit on what you are looking for in addition to this pointer. Are you hoping for easier to use HTTP client functions (like we have HTTPS server functions)? Or are you hoping for a section in the tutorial that explains how to do this?

**Comment by anujjamwal** [comment]
I was hoping to trigger a discussion a better http/https client in seastar.
