### ISSUE TITLE
how to use seastar coroutine??

### ISSUE THREAD

**Issue by anlongfei** [scylladb/seastar#763]
how to use seastar coroutine?? https://github.com/scylladb/seastar/blob/master/include/seastar/core/coroutine.hh
could someone give some examples(or general usage) and performance test case??
thanks!

**Comment by avikivity** [comment]
There are some examples in demos/coroutines_demo.cc and tests/unit/coroutines_test.cc.

**Comment by nyh** [comment]
@avikivity eventually we should also explain coroutines in tutorial.md. 
Moreover, maybe we should consider making coroutines the first and main API we suggest to use - with continuations being explained as a second choice, not the first choice. I'm not sure we're there yet - coroutines currently require very recent compilers, and I don't think we tested it (for correctness and performance) as rigorously as we tested continuations. But it does seem like that's where we're headed, right?

**Comment by avikivity** [comment]
yes

**Comment by anlongfei** [comment]
> There are some examples in demos/coroutines_demo.cc and tests/unit/coroutines_test.cc.
thanks :-)

**Comment by anlongfei** [comment]
> @avikivity eventually we should also explain coroutines in tutorial.md.
> Moreover, maybe we should consider making coroutines the first and main API we suggest to use - with continuations being explained as a second choice, not the first choice. I'm not sure we're there yet - coroutines currently require very recent compilers, and I don't think we tested it (for correctness and performance) as rigorously as we tested continuations. But it does seem like that's where we're headed, right?

great!

**Comment by niekbouman** [comment]
Dear @avikivity (and @nyh ),
Regarding the discussion of adopting coroutines as Seastar's 'idiomatic' api, 
I just watched your recent "Ask me anything" video interview, in which you mention that you are waiting for some fixes in GCC relating to their C++20 coroutines implementation.

Out of curiosity, which GCC-coroutine-bugs are you referring to, in that interview?

kind regards,
Niek

**Comment by avikivity** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95137

**Comment by niekbouman** [comment]
Thank you @avikivity .

Does the recently published release candidate of GCC 10.2 fix these issues?

**Comment by avikivity** [comment]
Not all AFAIK.

**Comment by mikhail-barg** [comment]
Any news on this? We are looking towards basing our new project on Seastar, and it looks like coroutine-style is much more readable than continuation-style. Also GCC seem to have coroutine issues fixed in 10.3 (not released yet, but available in master).

So what would you suggest? Is it OK to start a new project fully relying on coroutines? @avikivity @nyh Could you please share your opinions?

**Comment by avikivity** [comment]
Scylla is using coroutines. We switched to clang due to the gcc bugs in corotuines.
