### ISSUE TITLE
Reactor [1-3] were stuck in an inifite loop in smp::poll_queues() when using DefaultAllocator

### ISSUE THREAD

**Issue by xiaoming-qxm** [scylladb/seastar#770]
Hi, all. I compiled the following seastar's test program with DefaultAllocator(system malloc) option and the program got stuck when I use 4 cores. 

More specifically, reactor 1-3 were stuck in an infinite loop in smp::poll_queues(): they kept polling from the 'smp-queue', and always got 1 task back, while reactor 0 was sleeping all the time. 

The bug is pretty stable and can be reproduced with more than 85% chances.

### Environment Setup
OS: ubuntu18.04
C++ compiler: g++-8; 
Branch: [seastar-19.06-branch](https://github.com/scylladb/seastar/tree/seastar-19.06-branch)

### Command
`./test_app -c4 -m1G`

### Source code
```cpp
// test_app
#include <seastar/core/print.hh>
#include <seastar/core/reactor.hh>
#include <seastar/core/sleep.hh>
#include <seastar/core/app-template.hh>

using namespace seastar;
using namespace std::chrono_literals;

future<> send_message(unsigned c) {
    return smp::submit_to(c, [] {
        return make_ready_future<>();
    });
}

future<> simulation(unsigned num_message) {
    return parallel_for_each(boost::irange(0u, num_message), [] (unsigned i) {
        return send_message(i % smp::count).then([] {
            return make_ready_future<>();
        });
    });
}

int main(int ac, char** av) {
    app_template sys;
    sys.run_deprecated(ac, av, [] {
        return simulation(10000000).then([] {
        fmt::print("All works are done.\n");
            return sleep(5s);
        }).then([] {
            engine().exit(0);
        });
    });
    std::cout << "Exit actor system." << std::endl;
    return 0;
}
```

**Comment by avikivity** [comment]
Probably you ran out of memory. I think if you use sys.run() instead of run_deprecated() (and no need for engine().exit()) it will catch the exception and report it.

parallel_for_each() should be used with reasonable concurrency, not 10^8.

**Comment by xiaoming-qxm** [comment]
> Probably you ran out of memory. I think if you use sys.run() instead of run_deprecated() (and no need for engine().exit()) it will catch the exception and report it.

Actually there is hundreds of memory on my machine and it's enough for this program. Also, the program got stuck again when I use sys.run() and ran with `./test_app -c4 -m50G`. (In my option, the memory option is not useful for DefaultAllocator). 

> parallel_for_each() should be used with reasonable concurrency, not 10^8.

Is there a reasonable concurrent number for parallel_for_each()? And why it would cause  reactor 1-3 stuck in an infinite loop in smp::poll_queues()?


@avikivity

**Comment by avikivity** [comment]
> @avikivity Thanks for your quick reply.
> 
> > Probably you ran out of memory. I think if you use sys.run() instead of run_deprecated() (and no need for engine().exit()) it will catch the exception and report it.
> 
> Actually there is hundreds of memory on my machine and it's enough for this program. Also, the program got stuck again when I use sys.run() and ran with `./test_app -c4 -m50G`. (In my option, the memory option is not useful for DefaultAllocator).

Ah, I the system allocator and not the seastar allocator. Yes, -m does nothing. 

Maybe you can run it under gdb with `catch throw`.

> 
> > parallel_for_each() should be used with reasonable concurrency, not 10^8.
> 
> Is there a reasonable concurrent number for parallel_for_each()?

hundreds, or thousands. It depends on what you are doing. If you are performing disk I/O, then a few dozens. If you are running heavyweight compuations on many remote nodes, then around the number of remote nodes.

> And why it would cause reactor 1-3 stuck in an infinite loop in smp::poll_queues()?

It shouldn't. Something else happened that caused engine().exit() not to run.

**Comment by xiaoming-qxm** [comment]
We dug into the problem and found something new: 

In reactor-0, parallel_for_each() hung in the while loop. When hung, it only consumed <4G memory, so there was plenty of memory remaining. In my understanding, no code in parallel_for_each could stuck, even if we use a 10^8 concurrency. 

We add some debug information and found that:
(1)  the program was not stuck when submitting task to other shards because  smp_message_queue::submit_item() has plenty of semaphore resources to use
(2) the program might stuck in anywhere between line [129](https://github.com/scylladb/seastar/blob/aa46d84646b381da03dd9126015292686bd078da/include/seastar/core/future-util.hh#L129) to line [152](https://github.com/scylladb/seastar/blob/aa46d84646b381da03dd9126015292686bd078da/include/seastar/core/future-util.hh#L152)  in the  [parallel_for_each()](https://github.com/scylladb/seastar/blob/aa46d84646b381da03dd9126015292686bd078da/include/seastar/core/future-util.hh#L126) function.

**Comment by xiaoming-qxm** [comment]
The program works fine when I use seastar-20.05-branch, is it because there is a bug in seastar-19.06-branch?

**Comment by avikivity** [comment]
Possibly. You can try bisecting it.
