### ISSUE TITLE
Sanitizers not found!

### ISSUE THREAD

**Issue by aprilweet** [scylladb/seastar#773]
i built with `./cooking.sh` but failed, it says:
```
CMake Error at CMakeLists.txt:713 (message):
  Sanitizers not found!
```
This is error log:
[CMakeError.log](https://github.com/scylladb/seastar/files/4985998/CMakeError.log)

**Comment by avikivity** [comment]
Try installing libubsan/libasan/libtsan.

**Comment by nyh** [comment]
@avikivity isn't the whole point of "cooking.sh" that it will install all the dependencies for you? Or maybe the actual *compiler* (and its tools like the sanitizer, linker, assembler, etc.) is excluded?

**Comment by avikivity** [comment]
I don't know anything about cooking.sh.

**Comment by tchaikov** [comment]
> @avikivity isn't the whole point of "cooking.sh" that it will install all the dependencies for you? Or maybe the actual _compiler_ (and its tools like the sanitizer, linker, assembler, etc.) is excluded?

yeah, the dependencies provided by tool chain are excluded. 

long story: i think what `cooking.sh` is supposed to do is to cook the ingredients from recipes. the recipes define how the libraries and tools like ragel are built. but the sanitizers are a different story. for instance, the sanitizers support of GCC is builtin in GCC. in other words, one need to build GCC to get sanitizer libs. if we want to offer the tool chain dependencies, that'd be a huge pain. neither clang nor gcc is trivial thing to build.

**Comment by tchaikov** [comment]
i'd suggest close this issue.
