### ISSUE TITLE
add seastar add2line functionality to print_to_backtrace?

### ISSUE THREAD

**Issue by ideepika** [scylladb/seastar#789]
right now, as I see; what we do for getting the backtrace when we get `SIGTERM` is to append the addresses to a buffer which is then being printed out, current we use a different utility(seastar-addr2line) to paste that address o/p and then get the actual trace of failure.
Instead, would it possible to get the actual trace functionality integrated directly into seastar?

**Comment by ideepika** [comment]
@tchaikov @avikivity

**Comment by nyh** [comment]
There are several nuances that complicate this idea:

1. addr2line needs debugging information, which is often not available in the executable being run, and instead available somewhere else (another executable or a split debug information file), so the executable will need to somehow know where its debug information is located.
2. addr2line is fairly CPU and disk-intensive, but backtraces can be written to the log frequently in some cases (e.g., in case of large allocations,  stalls, etc.) so this can destroy performance. This can perhaps be solved by rate-limiting these backtrace resolutions.
3. Minor issue (maybe even a non-issue): The addr2line conversion can take a significant amount of time, which will delay the error message by some time and may make it harder to find exactly when the error happened originally (I guess we can just print another timestamp inside the message, so it's not a big problem).

**Comment by avikivity** [comment]
Closing as wontfix.
