### ISSUE TITLE
Use monotonic clock for timers

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#79]
Currently seastar timers are using `std::chrono::high_resolution_clock` which aliases to `system_clock`, which is a wall clock. This clock is not monotonic, which may cause unexpected behavior, eg. timers not expiring when expected. Also, `timer_set` relies on clock monotonicity. We should switch to `std::chrono::steady_clock` and `CLOCK_MONOTONIC`.

**Comment by tgrabiec** [comment]
@vladzcloudius Anything left to do here after your changes?

**Comment by vladzcloudius** [comment]
@tgrabiec Not that I'm ware of.
