### ISSUE TITLE
io_queue: diffirentiate coordinator and "client" side metrics

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/seastar#793]
HEAD: 8933f76d

*Description*
Today we account metrics (e.g. `bytes`) on the `io_queue` object that initiates it, namely on the shard where the corresponding I/O was requests.

However we have no visibility of what's going on a "coordinator" shard.

In particular if we wouldn't be able to distinguish the situation when reduced the number of coordinator shards using `--num-io-queues` and hit an I/O budget limit on one of the coordinator shards.

*Request*
Add a coordinator side metrics. The easy way to do so is to account the amount of actual I/O issued by the shard.

**Comment by xemul** [comment]
The concept of IO coordinators had gone
