### ISSUE TITLE
futures_test build error 

### ISSUE THREAD

**Issue by niekbouman** [scylladb/seastar#795]
Dear @bhalevy 

FYI Your commit 8933f76d3373db1a (from Wed Sept 9) breaks Seastar's release build (gcc version 10.2.1 20200723)

kind regards,
Niek

FAILED: tests/unit/CMakeFiles/test_unit_futures.dir/futures_test.cc.o 
/usr/bin/g++  -DBOOST_TEST_DYN_LINK -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=3 -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_DPDK -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_TESTING_MAIN -I../../tests/unit -I../../src -I../../include -Igen/include -isystem _cooking/installed/include/dpdk -O2 -g -DNDEBUG   -std=gnu++20 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -march=native -Wno-error=unused-result -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -MD -MT tests/unit/CMakeFiles/test_unit_futures.dir/futures_test.cc.o -MF tests/unit/CMakeFiles/test_unit_futures.dir/futures_test.cc.o.d -o tests/unit/CMakeFiles/test_unit_futures.dir/futures_test.cc.o -c ../../tests/unit/futures_test.cc
In file included from /usr/include/boost/test/test_tools.hpp:45,
                 from /usr/include/boost/test/unit_test.hpp:18,
                 from ../../include/seastar/testing/seastar_test.hh:27,
                 from ../../include/seastar/testing/test_case.hh:27,
                 from ../../tests/unit/futures_test.cc:22:
../../tests/unit/futures_test.cc: In member function ‘void test_max_concurrent_for_each::do_run_test_case()’:
../../tests/unit/futures_test.cc:1563:6: error: no matching function for call to ‘max_concurrent_for_each(std::vector<int>&, int, test_max_concurrent_for_each::do_run_test_case()::<lambda(int)>)’
 1563 |     }).get(), int, [] (int v) { return v == 5; });
      |      ^
In file included from ../../include/seastar/core/iostream-impl.hh:27,
                 from ../../include/seastar/core/iostream.hh:360,
                 from ../../include/seastar/core/reactor.hh:25,
                 from ../../tests/unit/futures_test.cc:24:
../../include/seastar/core/loop.hh:630:1: note: candidate: ‘template<class Iterator, class Func>  requires requires(Func f, Iterator i) {{f(*i++)} -> decltype(auto) [requires std::same_as<<placeholder>, seastar::future<> >];} seastar::future<> seastar::max_concurrent_for_each(Iterator, Iterator, size_t, Func&&)’
  630 | max_concurrent_for_each(Iterator begin, Iterator end, size_t max_concurrent, Func&& func) noexcept {
      | ^~~~~~~~~~~~~~~~~~~~~~~
../../include/seastar/core/loop.hh:630:1: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/test/test_tools.hpp:45,
                 from /usr/include/boost/test/unit_test.hpp:18,
                 from ../../include/seastar/testing/seastar_test.hh:27,
                 from ../../include/seastar/testing/test_case.hh:27,
                 from ../../tests/unit/futures_test.cc:22:
../../tests/unit/futures_test.cc:1563:6: note:   deduced conflicting types for parameter ‘Iterator’ (‘std::vector<int>’ and ‘int’)
 1563 |     }).get(), int, [] (int v) { return v == 5; });
      |      ^
In file included from ../../include/seastar/core/iostream-impl.hh:27,
                 from ../../include/seastar/core/iostream.hh:360,
                 from ../../include/seastar/core/reactor.hh:25,
                 from ../../tests/unit/futures_test.cc:24:
../../include/seastar/core/loop.hh:705:1: note: candidate: ‘seastar::future<> seastar::max_concurrent_for_each(Range&&, size_t, Func&&) [with Range = std::vector<int>&; Func = test_max_concurrent_for_each::do_run_test_case()::<lambda(int)>; size_t = long unsigned int]’
  705 | max_concurrent_for_each(Range&& range, size_t max_concurrent, Func&& func) noexcept {
      | ^~~~~~~~~~~~~~~~~~~~~~~
../../include/seastar/core/loop.hh:705:1: note: constraints not satisfied
In file included from ../../include/seastar/core/scheduling.hh:27,
                 from ../../include/seastar/core/task.hh:25,
                 from ../../include/seastar/core/future.hh:24,
                 from ../../include/seastar/testing/test_case.hh:25,
                 from ../../tests/unit/futures_test.cc:22:
../../include/seastar/core/loop.hh: In instantiation of ‘seastar::future<> seastar::max_concurrent_for_each(Range&&, size_t, Func&&) [with Range = std::vector<int>&; Func = test_max_concurrent_for_each::do_run_test_case()::<lambda(int)>; size_t = long unsigned int]’:
../../tests/unit/futures_test.cc:1558:5:   required from here
../../include/seastar/core/loop.hh:705:1:   required by the constraints of ‘template<class Range, class Func>  requires (range<Range>) && requires(Func f, Range r) {{f(*r.begin())} -> decltype(auto) [requires std::same_as<<placeholder>, seastar::future<> >];} seastar::future<> seastar::max_concurrent_for_each(Range&&, size_t, Func&&)’
../../include/seastar/core/loop.hh:702:1:   in requirements with ‘Func f’, ‘Range r’ [with Range = std::vector<int, std::allocator<int> >&; Func = test_max_concurrent_for_each::do_run_test_case::._anon_628]
../../include/seastar/core/loop.hh:702:88: note: ‘f((* r.begin()))’ does not satisfy return-type-requirement
  702 | SEASTAR_CONCEPT( requires std::ranges::range<Range> && requires (Func f, Range r) { { f(*r.begin()) } -> std::same_as<future<>>; } )
      |                                                                                       ~^~~~~~~~~~~~
../../include/seastar/util/concepts.hh:25:31: note: in definition of macro ‘SEASTAR_CONCEPT’
   25 | #define SEASTAR_CONCEPT(x...) x
      |                               ^
cc1plus: note: set ‘-fconcepts-diagnostics-depth=’ to at least 2 for more detail

**Comment by bhalevy** [comment]
Yes, my apologies. Thanks for reporting.
There's a patch to fix this already on the mailing list:
https://groups.google.com/g/seastar-dev/c/8MRXOIajdlg/m/DODi3pnVAQAJ

Can you please try it to make sure it fixes the issue for you?

Cc @scylladb/seastar-maint

**Comment by nyh** [comment]
Fixed by 861b17fd163fce590fb81e072bef244166b9a9d0

**Comment by niekbouman** [comment]
I can also confirm the fix. Thank you for your quick responses/actions!

Niek
