### ISSUE TITLE
io_queue: a vast bandwidth oversubscription 

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/seastar#798]
HEAD: 18275cbc
Application: scylla, version 4.1.5 (4.1.5 AMI)
HW: r3.2xl AWS VM

*Description*
io_queue allows a vast oversubscription on a single shard.

Config:
```
$ cat io_properties.yaml:
disks:
  - mountpoint: /var/lib/scylla
    read_iops: 39956
    read_bandwidth: 250131856
    write_iops: 32576
    write_bandwidth: 175260160

$ cat io.conf 
SEASTAR_IO="--io-properties-file=/etc/scylla.d/io_properties.yaml"
```

number of shards: 7

Here is a screenshot from the compaction throughput class:

![image](https://user-images.githubusercontent.com/6103981/93624381-4413de80-f9ae-11ea-9d10-1f3fc9727f0d.png)

io_queue divides resources statically and evenly between all  configures shards.

Namely the max I/O throughout for any class should be not more than
35733122 (read) + 25037166 (writes) =~ 61MB/sec

While in fact we see more than 100MB/sec 

If the same would happen on all shards at the same time that would cause at least 40% over-subscription and as result - overload of the disk which will result in high latenceis.

Interesting note that the phenomena took place when other I/O classes were idle.

**Comment by vladzcloudius** [comment]
@avikivity @slivne FYI

**Comment by vladzcloudius** [comment]
@raphaelsc FYI

**Comment by xemul** [comment]
The io-properties numbers give 26k of read request per tick and 18k of write request per tick. However _that_ time IO-scheduler limitation logic was

    if (resources_currently_executing > limit) {
        break;
    }
    resources_currently_executing += request.resource;
    request.dispatch();

Also at that time compaction didn't take into account IO-scheduler limits and just defined 128k as the maximum buffer to work with. So 128k per tick can easily overload the disk like you describe.

Modern seastar+scylla work together to get and use some relevant maximum request size. Also there's capacity sharing thing.

I propose to close this issue, @vladzcloudius .

**Comment by vladzcloudius** [comment]
> The io-properties numbers give 26k of read request per tick and 18k of write request per tick. However _that_ time IO-scheduler limitation logic was
> 
> ```
> if (resources_currently_executing > limit) {
>     break;
> }
> resources_currently_executing += request.resource;
> request.dispatch();
> ```
> 
> Also at that time compaction didn't take into account IO-scheduler limits and just defined 128k as the maximum buffer to work with. So 128k per tick can easily overload the disk like you describe.
> 
> Modern seastar+scylla work together to get and use some relevant maximum request size. Also there's capacity sharing thing.
> 
> I propose to close this issue, @vladzcloudius .

I don't mind - only, please, reference a seastar version that has this fixed, @xemul.

**Comment by xemul** [comment]
8a9643493711753ffa71b15a9f4795c68833fd9f
ad8220ce30528d975e54cfe54d73931797fee367
scylladb/scylla@ef2313325b888511ad5580b54132d997f73cc3aa
