### ISSUE TITLE
Seastar build and compilation errors on CenTos 7

### ISSUE THREAD

**Issue by aubi1kenobi** [scylladb/seastar#806]
Hello,
platform: centOS 7, kernel 4, gcc 10, compiling with c++17 flag.

1. building from source
install dependancies script installs older versions on centos, than required by te configure.py (eg: boost 1.53 gets installed, etc.). so, I had to build almost every dependency from source to get the versions right.
But even then, configure.py succeds, but "ninja -C build/release' fails. done this, and tried every combo from info on the net, not 1 single successful build in more than a week. Errors are numerous and chamging.

2. Compiling hellowworld with a "libseastar.a" from installing 'scyllaDB'
Running from the scylla build directory, ran the recommended g++ hw.cc 'pkg-config --cflags --libs $sdir/seastar.pc', with hw.cc before and after, adding '-lrt' etc. on the command line, and finaly, copying the seastar.pc content to a makefile (just in case).
None of all these combo works.
Getting 'undefined refs on everything; YAML, boost::program_options, pthread, etc. everything and for almost every call made to all external libs). Basically not finding the libs, not even pthread, numa, fmt, etc. And of course, printing dwarf messages in between (ld), so i get 30= pages of output errors.
another 3+ days, of trying to get the helloworld to compile with a libseastar.a from scylladb.
It's 2 extremely long weeks of frustrations and I havent written a single line of code in my application where i'm (still) hoping to use this lib.
Please help.

**Comment by aubi1kenobi** [comment]
I need help with Install on CentOS7, it doesn't matter, what I do. configure.py --cook fmt, with dpdk, without, with boost or without. Cook with some more ingredient or none, dev or release mode. Nothing, all fails 
Lost of warning about Boost. Usually fails on boost unit_test_framework, or it complains about yaml.cpp.
Now I got to the build phase, and it is now failing with 
    _libgnutls.so: undefined reference to `_idn2_punycode_decode'_

Yum says: 
    Package libidn-1.28-4.el7.x86_64 already installed and latest version
    Package libidn2-2.3.0-1.el7.x86_64 already installed and latest version

rpm -qa | grep gnutls
gnutls-dane-3.3.29-9.el7_6.x86_64
gnutls-3.3.29-9.el7_6.x86_64
gnutls-c++-3.3.29-9.el7_6.x86_64
gnutls-devel-3.3.29-9.el7_6.x86_64

Need your help please. Going past 3.5 weeks, just trying to get this to build so I can finally get to develop my application using your platform.

**Comment by nyh** [comment]
There is no need to have both this issue and #808 open, they are on exactly the same problem. I wrote a comment on #808, so closing this one.
