### ISSUE TITLE
HW versus SW raid and iotune

### ISSUE THREAD

**Issue by tarzanek** [scylladb/seastar#810]
2 SSDs on the same hardware, with different aproaches to raid:

Hardware raid0 
```
:::::::::::::: 
/etc/scylla.d/cpuset.conf 
:::::::::::::: 
CPUSET="--cpuset 1-23,25-47 " 
:::::::::::::: 
/etc/scylla.d/io.conf 
:::::::::::::: 
SEASTAR_IO="--num-io-queues=1 --io-properties-file=/etc/scylla.d/io_properties.yaml" 
:::::::::::::: 
/etc/scylla.d/io_properties.yaml 
:::::::::::::: 
disks: 
 - mountpoint: / 
   read_iops: 63143 
   read_bandwidth: 733626944 
   write_iops: 45624 
   write_bandwidth: 248903968 
:::::::::::::: 
:::::::::::::: 
```
Software raid0 
```
:::::::::::::: 
:::::::::::::: 
/etc/scylla.d/cpuset.conf 
:::::::::::::: 
CPUSET="--cpuset 1-23,25-47 " 
:::::::::::::: 
/etc/scylla.d/io.conf 
:::::::::::::: 
SEASTAR_IO="--num-io-queues=46 --io-properties-file=/etc/scylla.d/io_properties.yaml" 
:::::::::::::: 
/etc/scylla.d/io_properties.yaml 
:::::::::::::: 
disks: 
 - mountpoint: /data 
   read_iops: 138689 
   read_bandwidth: 963001664 
   write_iops: 127368 
   write_bandwidth: 867488384
```

- note that I don't know why the autodetection from iotune used only 1 queue, shouldn't we use more and not default to 1?
- Shouldn't iotune be smarted in the hw raid situation?

@xemul any ideas about above situation?

**Comment by tarzanek** [comment]
HW raid used is coming from PERC H740P

**Comment by xemul** [comment]
@tarzanek , how did you generate the io.conf? This repo's iotune doesn't write the `num-io-queues` parameter.

**Comment by gcarmin** [comment]
@xemul scylla version 2019.1.18. and we run scylla_setup

**Comment by xemul** [comment]
> HW raid used is coming from PERC H740P

And the software raid is ... ?

**Comment by xemul** [comment]
@gcarmin , 2019.1.18 is claimed not to start yet, is it 2019.1.17?

**Comment by dyasny** [comment]
> 
> And the software raid is ... ?

mdraid, same 2 ssd disks

**Comment by xemul** [comment]
OK. Let's clarify the version. The 2019.1.18 seems not to exist, and 2019.1.17 has seastar with buggy iotune which may report semi-random results. The fix is scylladb/seastar@83919516c9

**Comment by xemul** [comment]
Also there's scylladb/scylla#7146 that shows that IOPS evaluation is still problematic.

**Comment by gcarmin** [comment]
@xemul  sorry for the type -scylla version is  2019.1.8

**Comment by xemul** [comment]
@gcarmin , @tarzanek , the iotune in 2019.1.8 [has a BUG too](https://github.com/scylladb/seastar/issues/810#issuecomment-705020054) and it's totally worth backporting the fix before making any assumptions about the numbers.

**Comment by gcarmin** [comment]
@xemul  - is this BUG  [8391951](https://github.com/scylladb/seastar/commit/83919516c9)   is solved in  2020.1.3? 
(I may ask one of my customer to give it a shoot)

**Comment by xemul** [comment]
@gcarmin , no it's not yet there.

**Comment by gcarmin** [comment]
@xemul - Is it in latest OSS?
Is there a time-line to backport it to 2020.X

**Comment by xemul** [comment]
@gcarmin , yes 4.1.8 does have it. About backporting I think we should ask ... @bhalevy ?

**Comment by bhalevy** [comment]
> @gcarmin , yes 4.1.8 does have it. About backporting I think we should ask ... @bhalevy ?

I'm all for it.
@avikivity ?

**Comment by mykaul** [comment]
Closing, either irrelevant, fixed or the HW raid is not the best path - we prefer SW raid.
