### ISSUE TITLE
some file include even an invalid header !

### ISSUE THREAD

**Issue by YifangSun** [scylladb/seastar#814]
in branch seastar-20.05
https://github.com/scylladb/seastar/blob/seastar-20.05-branch/include/seastar/http/httpd.hh#L24
but there isn't this file in include/seastar/http 

similar problem appears several times,  is it really a release version?

**Comment by nyh** [comment]
I cannot reproduce this issue - I did
```
git checkout seastar-20.05-branch
./configure.py
dninja -C build/dev
```
And everything was built correctly.
What did you do differently?

**Comment by avikivity** [comment]
This file is generated, it will appear in build/{mode}/gen once you start building.
