### ISSUE TITLE
TLS init on seastar::memory::alloc_stats access takes significant amount of CPU

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#829]
Introduced in 1604eb57c9d7f3deb13f4da218cbeaf7f9a2d2aa.

A similar issue was fixed in the past in 42159d4a5b59f9805bc4947eec16d080a1d6c452

I measured extra 5% CPU overhead due to this in Scylla's `calculate_schema_digest()`. Memory allocations take 20% in that workload.

**Comment by avikivity** [comment]
This can be fixed with `constinit`.

**Comment by tgrabiec** [comment]
After putting the stats inside `cpu_pages` and thus eliminating TLS init code, performance is not significantly improved. So I presume this was a red herring. Probably icache misses.

**Comment by tgrabiec** [comment]
Revering 1604eb5 improves the performance though.

**Comment by avikivity** [comment]
Possibly. Allocation is a very hot path (coroutines coroutines coroutines). We can resolve the if ()s at the caller by pushing the increments to the places where whether it is a reactor thread or not is known.
