### ISSUE TITLE
Preferred span size calculation in small pool doesn't account for 2^n behavior of underlying allocator

### ISSUE THREAD

**Issue by travisdowns** [scylladb/seastar#836]
When creating a small pool of a given size, a _preferred_ span size is calculated: the pool will ask the underlying (buddy) allocator for spans of this size. The preferred size can be any integral number of pages and is calculated using a search for the smallest number of pages which satisfy "less than 5% waste" and "at least 4 objects fit" criteria:

~~~c++
    span_size = 1;
    while (_object_size > span_bytes()
            || (span_size < 32 && waste() > 0.05)
            || (span_bytes() / object_size < 4)) {
        ++span_size;
    }
~~~

This logic assumes that any number of pages can be requested, but the underlying allocator always returns power of two spans. This extra space isn't wasted, due to #625 - but it does mean the calculation above doesn't really DTRT: we might carefully select a 5 page span, but we'll actually get 8, which may have too much waste. 

I think we can just do `span_size *= 2` rather than `++span_size`. This reflects the underlying reality and the output of the diagnostics will be clearer about what span size is really being used.

This does change the selected span size quite a bit in several cases (since the "optimizing search" has many few points to check and the waste essentially varies randomly). Here are the existing span sizes and the new 2^n ones with the `span_size *= 2` change:

~~~
objsz	spansz	pow2sz
512	4K	4K	
640	12K	16K	
768	12K	16K	
896	8K	8K	
1024	4K	4K	
1280	20K	32K	
1536	12K	32K	
1792	16K	16K	
2048	8K	8K	
2560	20K	64K	
3072	12K	64K	
3584	28K	32K	
4096	16K	16K	
5120	20K	128K	
6144	24K	128K	
7168	28K	64K	
8192	32K	32K	
10240	40K	128K	
12288	48K	128K	
14336	56K	128K	
16384	64K	64K	
~~~

Given that, maybe a higher waste could be accepted (the waste is already being incurred with the existing code, of course), or a simpler algorithm could be chosen, e.g., just choose 64K for sizes above 2048 or whatever).

**Comment by avikivity** [comment]
Good catch, we used to have non-power-of-two spans, but ran into fragmentation problems.

I'm considering (for several years now) adding a 1.5 step. So a 4-page span can be split into a 3-page span and a 1-page span, not just 2 and 2. But for the pools, we may as well use powers of two.

**Comment by travisdowns** [comment]
@avikivity - it might also be worse considering making the minimum span size for the small pool 16K: I believe the small pool is the only thing requesting anything smaller than 16K (since that's the cutoff for the small pool), so under the theory that small allocation are worse for fragmentation, this would be a way to effectively bump the minimum allocation to 16K with little waste: only up 12K wasted per small pool over the lifetime of the process. So probably something like < 1 MB per shard worst case (and often much less than the worst case).

**Comment by avikivity** [comment]
The idea is to make intermediate-sized allocations less wasteful. Intermediate-size allocations usually come from vectors or blobs and can be any size (scylla splits anything over 128k into chunks, but still, why round 70k to 128k if you can round it to 96k.

**Comment by travisdowns** [comment]
> The idea is to make intermediate-sized allocations less wasteful. Intermediate-size allocations usually come from vectors or blobs and can be any size (scylla splits anything over 128k into chunks, but still, why round 70k to 128k if you can round it to 96k.

Right, sorry for any confusion: I wasn't talking about the 3/1 split here, it was basically a change of topic to something unrelated to the 3/1 split.

Just pointing how that worst-case fragmentation (which often ends up being "typical case" for a long-running process) is somehow related to the smallest allocated size in the buddy allocator (as well to the size you are trying to allocate: larger is worse). The buddy allocator _mostly_ handles > 16K allocations, because smaller ones are redirected to the small pool. However, the small pool itself makes allocations as small as 4K, directly to the buddy allocator. So the only reason the buddy allocator sees 4K, 8K allocations is the small pool. If you set the min span size in the small pool (or at least the preferred span size) to 16K, you'll cut out these small allocations entirely, at only a small and fixed per shard cost.

**Comment by avikivity** [comment]
I see. Maybe we should make the page size 16k.

But I'm concerned about wastage. Indeed I had thoughts about starting all small_pools at 4k, and only bumping to the ideal size once that 4k page was exhausted, and the small_pool proved it's not just a one-off size.

Bumping the page size will save some memory from the pages vector. struct page is 32 bytes in size, so it wastes just under 1% of memory.

I'm conflicted.

**Comment by travisdowns** [comment]
> I'm conflicted.

I guess I don't have any good handle on the per-core memory allotments for a "typical" seastar application (whatever that means), but the waste we are talking about seems quite small and fixed: I count only ~27 pools with preferred size of 4K (and two at 8K), and *worst case* additional waste at 16K is 12K, so across all pools that is 340K. You'd have to do something quite special to get to this worst case as well, I would put typical waste at half that, 170K. Even with a very small (I think?) per-core allotment of 100M, that's 0.34% worst-case waste. With a more usual (I think) 1G allotment, it's 10x less.

For what it's worth, this change already increased "waste" by a similar amount: as noted above and in the patch, fixing the search means that much larger preferred spans are selected for some sizes (e.g. 128K instead of 20K for 5120 bytes), which could certainly waste memory depending on how many objects of that size tend to be allocated (with enough objects, 128K will be more efficient as less internal fragmentation eventually overcomes the overhead of partially used blocks).
