### ISSUE TITLE
do_dump_memory_diagnostics free column is actually total

### ISSUE THREAD

**Issue by travisdowns** [scylladb/seastar#838]
The last part of the `do_dump_memory_diagnostics` is a span histogram, like so:

~~~
Page spans:
index	size	free	used	spans
0	4K	404K	400K	101
1	8K	280K	280K	35
2	16K	944K	928K	59
3	32K	626M	626M	20k
4	64K	832K	832K	13
5	128K	512K	384K	4
6	256K	256K	0B	1
7	512K	0B	0B	0
8	1M	1M	0B	1
9	2M	2M	0B	1
10	4M	0B	0B	0
11	8M	8M	0B	1
12	16M	0B	0B	0
13	32M	64M	32M	2
14	64M	64M	0B	1
15	128M	0B	0B	0
16	256M	256M	0B	1
17	512M	512M	0B	1
18	1G	2G	0B	2
19	2G	0B	0B	0
20	4G	0B	0B	0
21	8G	0B	0B	0
22	16G	0B	0B	0
23	32G	0B	0B	0
24	64G	0B	0B	0
25	128G	0B	0B	0
26	256G	0B	0B	0
27	512G	0B	0B	0
28	1T	0B	0B	0
29	2T	0B	0B	0
30	4T	0B	0B	0
31	8T	0B	0B	0
~~~

The column titled `free` is actually the total memory associated with spans of that size, not the free memory. This explains the suspicious behavior  where free is always greater than used, and also where free and used are almost exactly the same (in fact, it's because almost all spans of that that size are almost fully used).

The [relevant line](https://github.com/scylladb/seastar/blob/afafbaa8d43627fffa00541ac26a31904d0268ab/src/core/memory.cc#L1698) uses `total_pages * page_size`:

~~~
to_hr_size(total_pages * page_size),
~~~

Not sure what was the intent: it might be easier to fix the column header if you really want "used" or the calculation is easy to fix too.

**Comment by denesb** [comment]
@travisdowns thanks for noticing. It should have been `free_pages * page_size`, this is a typo. I will send a patch.

**Comment by denesb** [comment]
Or if you want to send a patch, go ahead, you did the investigatory work here after all.

**Comment by travisdowns** [comment]
> Or if you want to send a patch, go ahead, you did the investigatory work here after all.

I'm fine either way. Patches are sent to the mailing list?

**Comment by denesb** [comment]
Yes, to seastar-dev@googlegroups.com.

**Comment by travisdowns** [comment]
OK sure, I'll send one!

To confirm, you'd like to keep the column as `free` and change the calculation, right?

**Comment by denesb** [comment]
Yes, total is not that interesting, we want to see how much is used and where are the free spans accumulating at.
