### ISSUE TITLE
iostream: the skip method of the default data source may enter an infinite loop

### ISSUE THREAD

**Issue by wmitros** [scylladb/seastar#839]
https://github.com/scylladb/seastar/blob/afafbaa8d43627fffa00541ac26a31904d0268ab/include/seastar/core/iostream-impl.hh#L33-L47
If the source bytes end while skipping, the `get()` method will start returning empty buffers, so the statement `n -= buffer.size(); ` will not decrease the value of `n`. If the value of `n` remains unchanged, and every buffer from `get()` is empty, the value of the comparison `buffer.size() >= n` doesn't change either, so the loop can't end.

**Comment by raphaelsc** [comment]
good catch!

**Comment by xemul** [comment]
dup of #910
