### ISSUE TITLE
stall: print the backtrace of stall detector in one-line

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/seastar#843]
Roy says:

"we get too many backtraces from other shards and other log messages and they mixed with each other.
The way we detect them today is cumbersome and unsafe when decoding."

**Comment by bhalevy** [comment]
I suggest to add an option at the seastar level to allow printing of clocked-reactor backtraces on a single line
and then first use it where it makes sense (like Scylla SCT), before we change the default format.
