### ISSUE TITLE
gnutls version on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by rjammala** [scylladb/seastar#85]
The build seems to be succeed only after installing libgnutls28-dev, it fails with the following error when using the default libgnutls-dev

rjammala@gofast:~/seastar$ ninja 
[77/252] CXX build/release/net/tls.o
FAILED: g++-4.9 -MMD -MT build/release/net/tls.o -MF build/release/net/tls.o.d -O2 -I build/release/gen -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE   -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -c -o build/release/net/tls.o net/tls.cc
net/tls.cc: In lambda function:
net/tls.cc:312:48: error: ‘GNUTLS_NONBLOCK’ was not declared in this scope
                 gtls_chk(gnutls_init(&session, GNUTLS_NONBLOCK|uint32_t(t)));
                                                ^
[77/252] CXX build/release/tests/fstream_test.o
ninja: build stopped: subcommand failed.

Succeeds after doing the following:

rjammala@gofast:~/seastar$ sudo apt-get install libgnutls28-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libgcrypt11-dev libgnutlsxx27 libgpg-error-dev
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libgnutls-xssl0 libgnutlsxx28 nettle-dev
Suggested packages:
  gnutls-doc gnutls-bin guile-gnutls
The following packages will be REMOVED:
  libgnutls-dev
The following NEW packages will be installed:
  libgnutls-xssl0 libgnutls28-dev libgnutlsxx28 nettle-dev
0 upgraded, 4 newly installed, 1 to remove and 14 not upgraded.
Need to get 1,340 kB of archives.

**Comment by hartsantler** [comment]
i'm having the same problem on LinuxMint 17.2
```
brett@mintx ~/rusthon_cache/seastar $ ninja -j 1
ninja: warning: bad deps log signature or version; starting over
[6/240] CXX build/release/net/tls.o
FAILED: g++-4.9 -MMD -MT build/release/net/tls.o -MF build/release/net/tls.o.d -O2 -I build/release/gen -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE   -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -c -o build/release/net/tls.o net/tls.cc
net/tls.cc:22:27: fatal error: gnutls/gnutls.h: No such file or directory
 #include <gnutls/gnutls.h>
                           ^
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by avikivity** [comment]
Added warnings in ./configure.py if gnutls is not installed or if the wrong version is installed.

**Comment by npmadhu** [comment]
In porting this to a different environment - gnutls that has the GNUTLS_NONBLOCK defined is at-least gnutls-3.x - not sure what is reflected in the ubuntu package.  The correct dependency should be >=3.0.0 of gnutls
