### ISSUE TITLE
map memory leakage

### ISSUE THREAD

**Issue by seven7777777** [scylladb/seastar#850]
seastar 18.05:
in each shard,  I just new a std::unordered_map<uint64_t, uint64_t>, and insert 200 million kv pairs into map, and then delete the map.
for(int i=0;i<10;i++){
//new map object
//insert 1~200 million into map object
//delete map object
}

but the memory just could not be deallocated after these code.
any help? thanks.

**Comment by avikivity** [comment]
std::unordered_map is part of C++, not Seastar.

**Comment by seven7777777** [comment]
guess it's part of seastar's memory management.

**Comment by seven7777777** [comment]
Cause it did not happend when just do then samething with c++.

**Comment by seven7777777** [comment]
It turned out to be the #653 issue. I put more than 64GB memory to one shard, so it's undefined when free memory.
