### ISSUE TITLE
Save seq_cst fence on smp_message_queue::lf_queue::maybe_wakeup?

### ISSUE THREAD

**Issue by franz1981** [scylladb/seastar#856]
After reading the nice https://www.scylladb.com/2018/02/15/memory-barriers-seastar-linux/ article (BTW the images with code in the article are no longer visible!!) I've searched in the seastar source code to better understand it and I see on https://github.com/scylladb/seastar/blob/800f87a4398c5e4a529f00c872ab3e1aa548d96c/src/core/reactor.cc#L3132-L3146 that
a `std::atomic_signal_fence(std::memory_order_seq_cst);` is used without accounting for `systemwide_memory_barrier()` availability, that could reduce it to a simple compiler barrier instead.

It can be either that I've misread how membarrier work or I'm pointing to the wrong code referenced in the article, any help?

**Comment by avikivity** [comment]
atomic_signal_fence is a compiler barrier.

**Comment by franz1981** [comment]
with `std::memory_order_seq_cst`too?

**Comment by franz1981** [comment]
Sorry, my ignorance on c++ has been solved by looking better at the doc
```
this is equivalent to std::atomic_thread_fence, except no CPU instructions for memory ordering are issued
```
Thanks @avikivity !
