### ISSUE TITLE
io_queue.cc compilation failure with g++ 9.3.0 in ubuntu 20.04

### ISSUE THREAD

**Issue by FBryczak** [scylladb/seastar#862]
hello,
is it  me or some genuine problem?

`[3/233] Building CXX object CMakeFiles/seastar.dir/src/core/io_queue.cc.o`
`FAILED: CMakeFiles/seastar.dir/src/core/io_queue.cc.o `
`/usr/bin/g++  -DFMT_LOCALE -DSEASTAR_API_LEVEL=6 -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_DPDK -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -I../../include -Igen/include -I../../src -Igen/src -isystem _cooking/installed/include/dpdk -O2 -g -DNDEBUG   -std=gnu++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -march=native -Wno-error=unused-result -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -std=gnu++17 -MD -MT CMakeFiles/seastar.dir/src/core/io_queue.cc.o -MF CMakeFiles/seastar.dir/src/core/io_queue.cc.o.d -o CMakeFiles/seastar.dir/src/core/io_queue.cc.o -c ../../src/core/io_queue.cc`
`In file included from ../../src/core/io_queue.cc:27:`
`../../include/seastar/core/io_intent.hh: In constructor ‘seastar::io_intent::io_intent(seastar::io_intent&&)’:`
`../../include/seastar/core/io_intent.hh:85:98: error: use of deleted function ‘seastar::io_intent::references::references(seastar::io_intent::references&&)’`
`   85 |     io_intent(io_intent&& o) noexcept : _intents(std::move(o._intents)), _refs(std::move(o._refs)) {`
`      |                                                                                                  ^`
`../../include/seastar/core/io_intent.hh:60:9: note: ‘seastar::io_intent::references::references(seastar::io_intent::references&&) noexcept’ is implicitly deleted because its exception-specification does not match the implicit exception-specification ‘’`
`   60 |         references(references&&) noexcept = default;`
`      |         ^~~~~~~~~~`

Build configured with:
> sudo ./install-dependencies.sh
> ./configure.py --enable-dpdk --mode=release --c++-dialect=gnu++17

My setup is:
>$ cat /etc/os-release 
>NAME="Ubuntu"
>VERSION="20.04.2 LTS (Focal Fossa)"
>...
>$ /usr/bin/g++ -v
>...
>Target: x86_64-linux-gnu
>gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

**Comment by FBryczak** [comment]
Here's a minimal repro: https://wandbox.org/permlink/PP4qj2oXLhkwwCAz.

Apparently this will compile with P1286R2 implemented in compiler (like gcc 10.0.1). 
I can't find official status of where this fix is going to be propagated though...

**Comment by xemul** [comment]
[This](https://github.com/xemul/seastar/commit/ee3b520e92e4f4a9309c39812624afc7aa4fbd1a) should fix. If that's the only problem you have, I'll submit it for merging.

**Comment by FBryczak** [comment]
@xemul thank you sir, that almost does it, there's the same problem with the default constructor references() which oddly shows as late as when building unit tests. After fixing the default constructor as well the are no more problems.
