### ISSUE TITLE
Reloadable TLS inotify flags for files is wrong

### ISSUE THREAD

**Issue by elcallio** [scylladb/seastar#865]
They are set to close, not close_write|delete_self. This means reading the file as a result of change results in a change, which reads and results in a change... etc. 

Typo level fault, but really crap spinning in real life.

**Comment by nyh** [comment]
Fixed in commit 8d7c2dcae737d3de42159c8e63caca2fdfb4a685 but we forgot the "Fixes" so this issue wasn't closed. closing it now.
