### ISSUE TITLE
faster build?

### ISSUE THREAD

**Issue by hartsantler** [scylladb/seastar#87]
the front page says to run
```
./configure.py --compiler=g++-4.9
ninja
```
this crashes my netbook (with only 2GB of ram).  i had to instead run `ninja -j 1`, this takes 2 hours to compile seastar.  i noticed it builds alot of tests, is there a way to skip these to get a faster build?

**Comment by avikivity** [comment]
You can run `ninja build/release/apps/httpd/httpd` to build that artifact.
And a 2GB netbook is too weak to develop seastar on.

**Comment by hartsantler** [comment]
how do i just build the base library so i can link it to my hello world?

**Comment by avikivity** [comment]
`ninja build/release/libseastar`
