### ISSUE TITLE
perftune.py 'method' object is not iterable on 5.11.x kernel

### ISSUE THREAD

**Issue by ultrabug** [scylladb/seastar#888]
Following up on #887 I also experienced this when running Vlad's fixed version from #887 :

```
No non-NVMe disks to tune
Setting NVMe disks: nvme1n1, nvme2n1, nvme0n1...
Setting mask 00000001 in /proc/irq/101/smp_affinity
Setting mask 00000001 in /proc/irq/113/smp_affinity
Setting mask 10000000 in /proc/irq/115/smp_affinity
Writing 'none' to /sys/devices/virtual/nvme-subsystem/nvme-subsys1/nvme1n1/queue/scheduler
Writing '2' to /sys/devices/virtual/nvme-subsystem/nvme-subsys1/nvme1n1/queue/nomerges
Writing 'none' to /sys/devices/virtual/nvme-subsystem/nvme-subsys2/nvme2n1/queue/scheduler
Writing '2' to /sys/devices/virtual/nvme-subsystem/nvme-subsys2/nvme2n1/queue/nomerges
Writing 'none' to /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/queue/scheduler
Writing '2' to /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/queue/nomerges
Setting bond0 bonding interface...
ERROR: 'method' object is not iterable. Your system can't be tuned until the issue is fixed.
```

**Comment by vladzcloudius** [comment]
@roydahan Do we have a QA test that covers this? I wonder how come such a basic breakage got all the way to the Enterprise?

**Comment by roydahan** [comment]
The GCE test failed for issue https://github.com/scylladb/scylla-enterprise/issues/1740.
I don't know if you bump into this after fixing 1740 or before.

It reached "all the way to enterprise" because someone backported this fix although it fails also on master.
The gating tests aren't testing for artifacts tests, only dtest.

**Comment by roydahan** [comment]
Now that I read #887, if the issue is only on 5.11.x kernel, then of course we don't have a test that cover this.
We don't cover every kernel version.

**Comment by vladzcloudius** [comment]
> Now that I read #887, if the issue is only on 5.11.x kernel, then of course we don't have a test that cover this.
> We don't cover every kernel version.

This issue is not kernel-specific unlike #887, @roydahan

**Comment by vladzcloudius** [comment]
> The GCE test failed for issue scylladb/scylla-enterprise#1740.
> I don't know if you bump into this after fixing 1740 or before.

The above is a different issue (I have fixed it recently too). Do we test with bonding interfaces in QA, @roydahan ?

**Comment by vladzcloudius** [comment]
> > > Now that I read #887, if the issue is only on 5.11.x kernel, then of course we don't have a test that cover this.
> > > We don't cover every kernel version.
> > 
> > 
> > This issue is not kernel-specific unlike #887, @roydahan
> 
> The title says "on 5.11.x kernel"

After finding the root cause of the issue I can tell you that it is not kernel specific.

**Comment by vladzcloudius** [comment]
> > > The GCE test failed for issue [scylladb/scylla-enterprise#1740](https://github.com/scylladb/scylla-enterprise/issues/1740).
> > > I don't know if you bump into this after fixing 1740 or before.
> > 
> > 
> > The above is a different issue (I have fixed it recently too). Do we test with bonding interfaces in QA, @roydahan ?
> 
> No (AFAIR).

We should consider testing this, @roydahan

**Comment by roydahan** [comment]
> unlike



> > > > Now that I read #887, if the issue is only on 5.11.x kernel, then of course we don't have a test that cover this.
> > > > We don't cover every kernel version.
> > > 
> > > 
> > > This issue is not kernel-specific unlike #887, @roydahan
> > 
> > 
> > The title says "on 5.11.x kernel"
> 
> After finding the root cause of the issue I can tell you that it is not kernel specific.

Would be helpful if you edit the title and description of the root cause.

**Comment by vladzcloudius** [comment]
> > unlike
> 
> > > > > Now that I read #887, if the issue is only on 5.11.x kernel, then of course we don't have a test that cover this.
> > > > > We don't cover every kernel version.
> > > > 
> > > > 
> > > > This issue is not kernel-specific unlike #887, @roydahan
> > > 
> > > 
> > > The title says "on 5.11.x kernel"
> > 
> > 
> > After finding the root cause of the issue I can tell you that it is not kernel specific.
> 
> Would be helpful if you edit the title and description of the root cause.

It wasn't me who created the issue, @roydahan. So, I can't edit it.
I believe this shouldn't stop you, right?
