### ISSUE TITLE
scatter/gather variants of dma_read and dma_write throw "Error system:14 (Bad address)"

### ISSUE THREAD

**Issue by asomers** [scylladb/seastar#89]
Every time I try to use either file::dma_read or file::dma_write, it throws an exception that gets logged to the console as shown below.

> WARNING: exceptional future ignored of type 'std::system_error': Error system:14 (Bad address)

These functions don't seem to be used anywhere in Seastar (I didn't check Scylla), but the problem can be demonstrated by the attached test case.

My environment is Ubuntu Server 14.04.03 amd64, running under KVM.
[0001-Added-a-test-for-the-scatter-gather-variants-of-dma_.patch.zip](https://github.com/scylladb/seastar/files/62064/0001-Added-a-test-for-the-scatter-gather-variants-of-dma_.patch.zip)

**Comment by avikivity** [comment]
Fixed by 4280427a0ce5e03ca6e34d8939fce2841be4be3a
