### ISSUE TITLE
Why it's not a const ???

### ISSUE THREAD

**Issue by cybay** [scylladb/seastar#902]
https://github.com/scylladb/seastar/blob/master/include/seastar/core/app-template.hh

We have three signatures:

`int run_deprecated(int ac, char ** av, std::function<void ()>&& func);`
`int run(int ac, char ** av, std::function<future<int> ()>&& func);`
`int run(int ac, char ** av, std::function<future<> ()>&& func);`

Why every time we have 
`char ** av`
 instead of more right/appropriate
`const char** av`.

It makes writing actually unneeded cast `const_cast<char**>` from what we all originally have `const char**`. 

In addition it's very misleading - every time when we meet not const pointer - it means that value by this pointer will be modified. But in fact you do not do anything like this.

**Comment by avikivity** [comment]
It's modeled after main(int ac, char** av) which also uses non-const parameters.
