### ISSUE TITLE
Question About Semaphore

### ISSUE THREAD

**Issue by ben741863140** [scylladb/seastar#915]
I want to notify Reactor(the thread in seastar) with seastar::semaphore.signal() by my own thread(the thread not in seastar). Is it legal to use ? If not, is there any other ways for my thread to notify the thread in seastar ?

**Comment by nyh** [comment]
This is a bug tracker, please ask questions on the mailing list (seastar-dev in googlegroups.com) - where more people can see your question and when other subscribers can also learn from the answers.
We have the "alien" mechanism for communication between "alien" (non-Seastar) threads and Seastar threads.
