### ISSUE TITLE
reactor::sched_clock is intermixed with std::chrono::steady_clock

### ISSUE THREAD

**Issue by bhalevy** [scylladb/seastar#918]
Change 98630451a2b97ef37e95895ae2f4a43fa7017d92 introduced `reactor::sched_clock`.

However there are multiple places where it is used interchangeably with `std::chrono::steady_clock`.

For example:
https://github.com/scylladb/seastar/blob/0b8cec66398f969ac5c78f2db5b3d3cfc76dea51/src/core/reactor.cc#L2629

and when passed to the stall detector, that should have the same sched_clock type as the reactor.
E.g. https://github.com/scylladb/seastar/blob/0b8cec66398f969ac5c78f2db5b3d3cfc76dea51/src/core/reactor.cc#L2631

Besides the reactor and stall detector both using the same `sched_clock`, I suggest to also add `reactor::now()` that will return `sched_clock::now()` for simplicity.

**Comment by bhalevy** [comment]
@cmm anything else left or can we close the issue?

**Comment by cmm** [comment]
@bhalevy not to my knowledge.
(iirc some minor templatizing might be needed in case `seastar::sched_clock` becomes something with sub-microsecond resolution, but no need to go there for now)

**Comment by bhalevy** [comment]
Ok, so closing with ed7dd4e
