### ISSUE TITLE
Change concept naming convention from CamelCase to snake_case

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#924]
Our `coding_style.md` says about naming concepts that:

> Template parameters and concepts use `CamelCase`

This recommendation was based  old convention encouraged by the concepts TS and a lot of online examples, but the C++ standard committee have changed their mind, and now encourage `snake_case` for concept names. See the following documents:

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1754r1.pdf
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1851r0.html

Seastar should probably change its coding-style.md to recommend snake_case in new concept names, and also start renaming existing concepts (the second document linked above is about such a renaming process).

**Comment by bhalevy** [comment]
0f55321e4f0ce0638d07feaca14324bc4d16550a updated `coding-style.md`

**Comment by nyh** [comment]
So I'll close the issue. If anyone wants to track the **renaming** of the existing concepts, we can reopen this issue.
