### ISSUE TITLE
How to build seastar as a library?

### ISSUE THREAD

**Issue by shivshankardayal** [scylladb/seastar#93]
Forgive me if I am wrong. But the apps built after compilation are quite large and monolithic. Would it not be better to include a target of shared library so that applications can link to it? I am not sure if this really qualifies as issue.

**Comment by avikivity** [comment]
It's best to ask on the mailing list.

Try:

    ninja build/release/libseastar.a build/release/seastar.pc

**Comment by shivshankardayal** [comment]
Thanks.
