### ISSUE TITLE
DPDP学习资料推荐

### ISSUE THREAD

**Issue by wenchao1024** [scylladb/seastar#937]
【冲破内核瓶颈，让I/O性能飙升】DPDK工程师手册，官方文档，最新视频，开源项目，实战案例，论文，大厂内部ppt，知名工程师一览表
https://github.com/0voice/dpdk_engineer_manual

**Comment by nyh** [comment]
This is Seastar's **bug tracker**, not a collection of links. If you think this link would be useful for Seastar developers, please bring it up in the Seastar developers' mailing list, not here - and explain you you think it would be useful.
Also, please use the English language here and in th mailing-list. It is the only language that all Seastar developers understand.
