### ISSUE TITLE
Change configure.py code choosing default C++-dialect, and document it

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#943]
Today `README.md` states that:

> Seastar supports both C++17, and C++20. It can be selected with the `--c++-dialect=gnu++17` configure option or, if using CMake directly, by setting on the `Seastar_CXX_DIALECT` CMake variable.

This description makes it clear that it is necessary to pick one of the two dialects at build time (although does not explain *why*!), but doesn't say what happens in a recent distro which supports both dialects. Logic, and text's wording, suggests that by default we would get the latest dialect (C++20) and to change the default to c++17 you need an explicit `--c++-dialect` option, but this is not actually what happens in `configure.py`...

In `configure.py`, we have:
```python
if args.cpp_dialect == '':
    cpp_dialects = ['gnu++17', 'gnu++1z', 'gnu++14', 'gnu++1y']
    args.cpp_dialect = identify_best_dialect(cpp_dialects, compiler=args.cxx)
```

So actually, the build currently defaults to C++17, **not** to C++20, even if the latter is supported by the compiler. This fact should be mentioned in `README.md`. Also I think we should reconsider this default. Why would we _default_ to an older version that we plan to no longer support in two years?

Another problem in the above `configure.py` code is all those attempts to try even older versions like `gnu++14`. We explicitly do not support these versions, so `configure.py` should not pick them. If neither c++20 or c++17 is available in the current compiler, `configure.py` should fail - not try something we know is doomed to fail.

**Comment by jeffRTC** [comment]
I think this is what caused my issue :)
