### ISSUE TITLE
I/O controller: allow Full Duplex mode

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/seastar#967]
HEAD: 083898a172cb096738627974b499dde4cddefa4d

*Description*
Our current I/O scheduler implementation assumes the underlying HW to be half-Duplex blocking read operations if write budget limit has been reached and vise versa.

This definitely makes sense when the underlying HW configuration is such that doesn't allow separating reads and writes. 

However there are HW configurations when it IS possible: for instance RAID1 configuration of fast (less reliable) and slow (reliable) devices when a slow device is marked as "write-mostly".

```
mdadm --create /dev/mdYYY --level 1 --raid-devices=2 <fast device> --write-mostly <slow device>
```

In the example above we will always write to both devices but would read from the fast device as long as it's available.

Obviously the write capacity of such a configuration is going to be defined by a slower of the two devices while read capacity - by the faster.

And naturally we want to benefit from fast reads while allowing some queuing on a write queue.

However our current I/O controller wouldn't allow that by blocking reads as soon as write capacity is exhausted.

*Proposal*
Introduce a "Full Duplex" mode for I/O controller that would be disabled by default.

**Comment by vladzcloudius** [comment]
@xemul FYI

**Comment by xemul** [comment]
@vladzcloudius , `[PATCH 00/13] IO queue full-duplex mode` on the ML
