### ISSUE TITLE
Disable Nagle's algorithm in HTTP server

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#968]
A user reported on an application based on Seastar's HTTP server (see https://github.com/scylladb/scylla/issues/9619) that while most requests are answered in less than 2ms, some of them are answered in 40ms.
This number 40ms should be familiar to some of us - it is a telltale sign of the infamous interaction between Nagle's algorithm on one machine and Delayed Ack on the other machine (on Linux, delayed ack defaults to exactly 40ms).
I think what is happening is the following:

1. The HTTP server wishes to send a response that is slightly longer than one MSS (TCP maximum segment size). It sends the first packet, but then will not send the second, small, packet until receiving an ACK for the first one. That is Nagle's algorithm - the idea is that the OS hopes (without foundation) that the application will have more data to send so it can send it in the same packet.
2. The HTTP client, a Linux machine, receives the first packet but Linux does not ACK it yet. This is the Delayed Ack feature (in the client's OS, not related to any library they're using) - Linux doesn't ACK a single packet for 40ms, hoping it can piggy-back the ACK on a message it will need to send anyway soon - or ACK more than one packet in a single ACK.

To solve this problem, the server needs to disable Nagle's algorithm while sending responses. The classic way to do it is to enable TCP_NODELAY on the socket (on the server's side). This will cause every write to the socket to be immediately flushed to the network - even if it generates very small frames.
An alternative and more "elaborate" approach is to use TCP_CORK - which should be enabled when the server starts to send a response and disabled when the response completes. This way, even if the response is written in multiple writes (e.g., headers and data separately), the data will still be collected to full packets - until the last small packet, that is also sent out immediately.

The easiest solution is probably to do `fd.set_nodelay(true)` on the accepted connection. This would be in `http_server::do_accept_one()`, which needs to call `ar.connection.set_nodelay(true)`.

We need to verify that such a change will not have adverse affects. In particular, we should check with a packet sniffer that short responses still get sent in one packet - not headers in one packet and body in a second packet. using TCP_CORK instead of TCP_NODELAY can make this sure this problem doesn't happen - but it's a more elaborate solution and may be slower (requires more system calls).

**Comment by avikivity** [comment]
I don't think we need TCP_CORK - we already buffer in an output_stream. So we don't have the problem of isssuing separate sendmsg() calls for headers and body and having them egress as two packets.

We might even default tcp connection to NODELAY (and provide an option to disable it). Nagle makes sense for large transfers using small sendmsg() calls, but no one does that.

**Comment by nyh** [comment]
> I don't think we need TCP_CORK - we already buffer in an output_stream. So we don't have the problem of isssuing separate sendmsg() calls for headers and body and having them egress as two packets.

You're right - if we have a large-enough write buffer (more than MSS) and only write on `flush()` (or when this buffer is full), this makes TCP_CORK almost unnecessary. I'm saying "almost" because there is still a silly detail that if the buffer size is not a multiple of MSS, then if the buffer fills up and we write the entire buffer to the socket, we can end up with the few last bytes in a separate small packet, which get sent individually because of TCP_NODELAY.

But I agree that TCP_NODELAY is probably good enough, and what most servers out there use.
 
> We might even default tcp connection to NODELAY (and provide an option to disable it). Nagle makes sense for large transfers using small sendmsg() calls, but no one does that.

This is an interesting idea. Indeed nowadays a default of TCP_NODELAY definitely makes sense.
The only thing worrying me is that it means we would make Seastar sockets a little further removed from the traditional Unix sockets, and thus they will be slightly harder to understand when something doesn't behave as expected. On the other hand, it will reduce the chance of accidental bugs when people who don't know such arcane TCP/IP details use Seastar....

**Comment by psarna** [comment]
Defaulting to tcp_nodelay == true sounds good to me too. Meanwhile, even if it might be subject to discussion whether we want to do that or not for TCP in general, I think that everybody tends to agree that it's a good idea for our HTTP server. And it's most likely a one-line patch.

**Comment by avikivity** [comment]
> > I don't think we need TCP_CORK - we already buffer in an output_stream. So we don't have the problem of isssuing separate sendmsg() calls for headers and body and having them egress as two packets.
> 
> You're right - if we have a large-enough write buffer (more than MSS) and only write on `flush()` (or when this buffer is full), this makes TCP_CORK almost unnecessary. I'm saying "almost" because there is still a silly detail that if the buffer size is not a multiple of MSS, then if the buffer fills up and we write the entire buffer to the socket, we can end up with the few last bytes in a separate small packet, which get sent individually because of TCP_NODELAY.

That's a good thing. Someone called flush() because they want the bits on the wire. If they are fine with buffering, they should not call flush().

> 
> But I agree that TCP_NODELAY is probably good enough, and what most servers out there use.
> 
> > We might even default tcp connection to NODELAY (and provide an option to disable it). Nagle makes sense for large transfers using small sendmsg() calls, but no one does that.
> 
> This is an interesting idea. Indeed nowadays a default of TCP_NODELAY definitely makes sense. The only thing worrying me is that it means we would make Seastar sockets a little further removed from the traditional Unix sockets, and thus they will be slightly harder to understand when something doesn't behave as expected. On the other hand, it will reduce the chance of accidental bugs when people who don't know such arcane TCP/IP details use Seastar....

I agree with this. Mirroring the POSIX API is good, since it allows people to build on their experience (even if the experience is negative).

**Comment by nyh** [comment]
> > > I don't think we need TCP_CORK - we already buffer in an output_stream. So we don't have the problem of isssuing separate sendmsg() calls for headers and body and having them egress as two packets.
> > 
> > 
> > You're right - if we have a large-enough write buffer (more than MSS) and only write on `flush()` (or when this buffer is full), this makes TCP_CORK almost unnecessary. I'm saying "almost" because there is still a silly detail that if the buffer size is not a multiple of MSS, then if the buffer fills up and we write the entire buffer to the socket, we can end up with the few last bytes in a separate small packet, which get sent individually because of TCP_NODELAY.
> 
> That's a good thing. Someone called flush() because they want the bits on the wire. If they are fine with buffering, they should not call flush().

I agree. The only catch is that they don't know that they should do this (yes, I should have put a lot more work into the networking section of Seastar's tutorial...). Basically a Seastar application must call `flush()` when it wants everything it sent so far to be sent out now, and must not call `flush()` if it wants to perhaps wait a bit for more data to be available to send. 

What a Seastar application can't do, however, is implement Nagle's algorithm exactly, where the decision on whether to send the last packet or not depend on its size (because the Seastar application doesn't know about resulting packet sizes). But I think this is a good thing - I think Nagle's algorithm is worse than what a Seastar application can do based on the knowledge it does have - on the amount of data it is trying to write (regardless of the packet sizes).

**Comment by avikivity** [comment]
A Seastar application does not need to implement Nagle's algorithm, that's what the kernel is for.

Nagle's algorithm is good for two things:
 - badly written applications that call sendmsg() with partial messages
 - telnet over 300 baud modems
 
Seastar eliminates the first by buffering. The second can still happen, but it's an unlikely use case.
