### ISSUE TITLE
I/O scheduler: properly account outstanding read and write workload

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/seastar#973]
HEAD: 04c6787b35e344c1d4b7b8092d2afedf4c78d082

### The problem
Our I/O scheduler has a notion of a maximum bandwidth and rate for reads and writes.
However it doesn't take into an account the fact that storage devices are not full-duplex kind of devices and our experiments show that the nature of "half-duplexness" is not always linear.

Although most of the time we can interpolate it as a linear function like this:

```
R = k * W + d
```

where `R` is number of read operations, `W` is number of write operations and `k` and `d` and constants.

In a general case it can't be assumed that `k` and `d` are going to be the same for different types of I/O (e.g. big and small buffers).

However whatever these coefficients are the controller's policy needs to try to keep the outstanding requests as close to that "line" and not allow oversubscribing.

In particular we should not allow "almost the maximum" amount of read and write requests at the same time.

### The challenge
* We need `iotune` to at least estimate different `k` and `d` coefficients for different combinations of read and write payloads. Meaning we need to add a parametrized 'mixed' test-case to it.

* We should give a normalized weight to each I/O that would take into an account its type, size and testing results mentioned above.

**Comment by vladzcloudius** [comment]
cc @avikivity @xemul 
Guys, this GH issue is meant to be a context for the corresponding work.
Please, add the testing info you have and, of course, your thoughts.

**Comment by xemul** [comment]
@vladzcloudius , had the rl-scheduler (https://github.com/scylladb/seastar/commit/bf527a0ab15fe833135909aee3187975c393896f) fixed this?

**Comment by vladzcloudius** [comment]
> @vladzcloudius , had the rl-scheduler (https://github.com/scylladb/seastar/commit/bf527a0ab15fe833135909aee3187975c393896f) fixed this?

Dunno. You tell me. ;)

**Comment by xemul** [comment]
Then yes
