### ISSUE TITLE
Memory：when size == 0 and ptr == nullptr， realloc should allocate MIN_SIZE bytes 

### ISSUE THREAD

**Issue by solargg** [scylladb/seastar#978]
When size == 0 and ptr == nullptr, seastar's realloc will return nullptr. But in glibc, it will allocate MIN_SIZE bytes and return a valid ptr like malloc(0).This may cause compatibility bugs when integrating certain third-party libraries.

**Comment by bhalevy** [comment]
Hmm, https://en.cppreference.com/w/cpp/memory/c/realloc says the following:

> If ptr is a null pointer, the behavior is the same as calling [std::malloc](https://en.cppreference.com/w/cpp/memory/c/malloc)(new_size).

> If new_size is zero, the behavior is implementation defined: null pointer may be returned (in which case the old memory block may or may not be freed) or some non-null pointer may be returned that may not be used to access storage. Such usage is deprecated (via [C DR 400](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2396.htm#dr_400)). (since C++20)

And https://en.cppreference.com/w/cpp/memory/c/malloc:

> If size is zero, the behavior is implementation defined (null pointer may be returned, or some non-null pointer may be returned that may not be used to access storage, but has to be passed to [std::free](https://en.cppreference.com/w/cpp/memory/c/free))

Although the behavior is implementation defined, we do different things for `malloc(0)` (allocate an an object with the minimum size) vs. realloc(nullptr, 0) where we return nullptr, so this is worth fixing for consistency.

**Comment by raphaelsc** [comment]
> Hmm, https://en.cppreference.com/w/cpp/memory/c/realloc says the following:
> 
> > If ptr is a null pointer, the behavior is the same as calling [std::malloc](https://en.cppreference.com/w/cpp/memory/c/malloc)(new_size).
> 
> > If new_size is zero, the behavior is implementation defined: null pointer may be returned (in which case the old memory block may or may not be freed) or some non-null pointer may be returned that may not be used to access storage. Such usage is deprecated (via [C DR 400](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2396.htm#dr_400)). (since C++20)
> 
> And https://en.cppreference.com/w/cpp/memory/c/malloc:
> 
> > If size is zero, the behavior is implementation defined (null pointer may be returned, or some non-null pointer may be returned that may not be used to access storage, but has to be passed to [std::free](https://en.cppreference.com/w/cpp/memory/c/free))
> 
> Although the behavior is implementation defined, we do different things for `malloc(0)` (allocate an an object with the minimum size) vs. realloc(nullptr, 0) where we return nullptr, so this is worth fixing for consistency.

That sounds the correct direction to me, too.
