### ISSUE TITLE
confusing with the seastar's thread model

### ISSUE THREAD

**Issue by Xavier1994** [scylladb/seastar#982]
I' m reading the seastar's code, i's a little bit confusing with the thread model, for example, the belowed code

![image](https://user-images.githubusercontent.com/11145343/144990868-e8d52c05-b30a-4849-8633-c47a466864d1.png)

because i run this keep doing task on one core, is that means that all the tasks related to this code run on the same core? if that is true, even though i have multiple cores, the other core is idle?

**Comment by nyh** [comment]
This is Seastar's bug tracker, once you find a bug in Seastar or a missing feature. If you want ask questions or spark discussions, please use the Seastar mailing list (seastar-dev on googlegroups.com).
