### ISSUE TITLE
c++-dialect=c++17 doesn't work out of the box with (at least) gcc 9 and gcc 8

### ISSUE THREAD

**Issue by linguoxuan** [scylladb/seastar#992]
the previous two commands I input is :
./install-dependencies.sh
./configure.py --mode=release --enable-dpdk --c++-dialect=c++17
they both pass in my centos8.2.

But when I try ninja -C build/release, I meet a problem as follow? Do anyone know how to deal with it?
```
[root@VM-16-11-centos seastar]# ninja -C build/release      
ninja: Entering directory `build/release'
[1/300] Building CXX object CMakeFiles/seastar_testing.dir/src/testing/random.cc.o
FAILED: CMakeFiles/seastar_testing.dir/src/testing/random.cc.o 
/usr/bin/g++ -DBOOST_TEST_DYN_LINK -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_DPDK -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -I../../include -Igen/include -isystem _cooking/installed/include/dpdk -O2 -g -DNDEBUG -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -std=c++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -march=native -Wno-error=unused-result -MD -MT CMakeFiles/seastar_testing.dir/src/testing/random.cc.o -MF CMakeFiles/seastar_testing.dir/src/testing/random.cc.o.d -o CMakeFiles/seastar_testing.dir/src/testing/random.cc.o -c ../../src/testing/random.cc
In file included from ../../include/seastar/testing/test_runner.hh:28,
                 from ../../src/testing/random.cc:22:
../../include/seastar/core/future.hh:774:35: error: ‘no_unique_address’ attribute directive ignored [-Werror=attributes]
     [[no_unique_address]] Wrapper _wrapper;
                                   ^~~~~~~~
cc1plus: all warnings being treated as errors
[2/300] Building CXX object CMakeFiles/seastar_testing.dir/src/testing/entry_point.cc.o
FAILED: CMakeFiles/seastar_testing.dir/src/testing/entry_point.cc.o 
/usr/bin/g++ -DBOOST_TEST_DYN_LINK -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_DPDK -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -I../../include -Igen/include -isystem _cooking/installed/include/dpdk -O2 -g -DNDEBUG -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -std=c++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -march=native -Wno-error=unused-result -MD -MT CMakeFiles/seastar_testing.dir/src/testing/entry_point.cc.o -MF CMakeFiles/seastar_testing.dir/src/testing/entry_point.cc.o.d -o CMakeFiles/seastar_testing.dir/src/testing/entry_point.cc.o -c ../../src/testing/entry_point.cc
In file included from ../../include/seastar/testing/seastar_test.hh:29,
                 from ../../src/testing/entry_point.cc:24:
../../include/seastar/core/future.hh:774:35: error: ‘no_unique_address’ attribute directive ignored [-Werror=attributes]
     [[no_unique_address]] Wrapper _wrapper;
                                   ^~~~~~~~
cc1plus: all warnings being treated as errors
[3/300] Building CXX object CMakeFiles/seastar_testing.dir/src/testing/seastar_test.cc.o
FAILED: CMakeFiles/seastar_testing.dir/src/testing/seastar_test.cc.o 
/usr/bin/g++ -DBOOST_TEST_DYN_LINK -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_DPDK -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -I../../include -Igen/include -isystem _cooking/installed/include/dpdk -O2 -g -DNDEBUG -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -std=c++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -march=native -Wno-error=unused-result -MD -MT CMakeFiles/seastar_testing.dir/src/testing/seastar_test.cc.o -MF CMakeFiles/seastar_testing.dir/src/testing/seastar_test.cc.o.d -o CMakeFiles/seastar_testing.dir/src/testing/seastar_test.cc.o -c ../../src/testing/seastar_test.cc
In file included from ../../include/seastar/testing/seastar_test.hh:29,
                 from ../../src/testing/seastar_test.cc:27:
../../include/seastar/core/future.hh:774:35: error: ‘no_unique_address’ attribute directive ignored [-Werror=attributes]
     [[no_unique_address]] Wrapper _wrapper;
                                   ^~~~~~~~
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```
my g++ version is "g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)"

**Comment by eliransin** [comment]
I tried to run the same with:
```
./install-dependencies.sh
./configure.py --mode=release --enable-dpdk --c++-dialect=c++17 --cflags="-Wno-attributes"
```

but it still fails - this time on:
```
MD -MT CMakeFiles/seastar.dir/src/http/httpd.cc.o -MF CMakeFiles/seastar.dir/src/http/httpd.cc.o.d -o CMakeFiles/seastar.dir/src/http/httpd.cc.o -c ../../src/http/httpd.cc                                                                                                                                        [214/1912]
In file included from ../../include/seastar/core/metrics_api.hh:26,            
                 from ../../include/seastar/core/app-template.hh:29,                                                                                          
                 from ../../src/http/httpd.cc:23:                                                                                                             
../../include/seastar/core/sharded.hh: In instantiation of ‘seastar::future<> seastar::sharded<T>::invoke_on_all(seastar::smp_submit_to_options, Func, Args ...) [with Func = seastar::httpd::http_server_control::set_routes(std::function<void(seastar::httpd::routes&)>)::<lambda(seastar::httpd::http_server&)>; Args = {
}; Service = seastar::httpd::http_server]’:                                                                                                                   
../../include/seastar/core/sharded.hh:249:90:   required from ‘seastar::future<> seastar::sharded<T>::invoke_on_all(Func, Args ...) [with Func = seastar::httpd::http_server_control::set_routes(std::function<void(seastar::httpd::routes&)>)::<lambda(seastar::httpd::http_server&)>; Args = {}; Service = seastar::httpd::
http_server]’                                                                                                                                                 
../../src/http/httpd.cc:585:6:   required from here                                                                                                           
../../include/seastar/core/sharded.hh:767:78: error: cannot deduce template arguments for ‘tuple’ from ()                                                     
     return invoke_on_all(options, invoke_on_all_func_type([func, args = std::tuple(std::move(args)...)] (Service& service) mutable {                         
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~                                                   
```

**Comment by eliransin** [comment]
@linguoxuan it looks like we need the combination of two things in order to support this build:
1. add the cflags attribute:
 `./configure.py --mode=release --enable-dpdk --c++-dialect=c++17 --cflags="-Wno-attributes"`
2. Have at least gcc/g++ version 9.
For instruction on how to install gcc version 9 on centos 8: https://stackoverflow.com/a/61593093
@linguoxuan I am closing this, please reopen if you have more questions or if it doesn't work for you.

**Comment by nyh** [comment]
@eliransin I'm reopening and renaming the issue, I hope you don't mind (if you do, feel free to re-close it). I think it's a real bug that our build doesn't work as suggested in the README:

1. According to our README.md, `--c++-dialect=c++17` should work. How can a user guess that he needs to add `--cflags="-Wno-attributes" when using it? If dialect=C++17 really needs it, our configure.py should add it automatically. Better yet, it might be possible to avoid the warning by changing the code. In this case, maybe `no_unique_address` is new to C++20 so should be `#ifdef`/`#define`-ed out in C++17?

2. How can a user guess which version of gcc is new enough to be supported? Nothing I could find on the web suggests that gcc 8 doesn't fully (at least almost fully) support C++17 :-( We should either make an effort to make Seastar work on any compiler which claims to support C++17, or if we don't, our README.md should say which compilers we do support, and better yet - if we know exactly why gcc 8 isn't supported we can add a test for it in configure.py (even better - we could fix the code to avoid this problem, but I know there has been resistance to this direction).

**Comment by eliransin** [comment]
I agree. We should fix it :slightly_smiling_face:

**Comment by nyh** [comment]
It turns out that although `[[no_unique_address]]` is  C++ 20 only (see https://en.cppreference.com/w/cpp/language/attributes/no_unique_address), on gcc 9 and onward (for example) it is supported (see https://en.cppreference.com/w/cpp/compiler_support) and when it's supported, it's allowed even with `-std=c++17`.  I didn't test this on gcc 9, but did test it on gcc 11.

So the problem of `[[no_unique_address]]` is just for gcc 8.

So @eliransin maybe you're wrong, and if you upgrade to gcc 9 (your step 2), the `--cflags="-Wno-attributes"` (your step 1) is not necessary?

Finally, I just realized that README.md points you doc/compatibility.md, where @avikivity wrote:

> The last two major releases of a compiler are supported (e.g.
> gcc 9 and gcc 10). Patches to support older versions are welcome,
> as long as they don't require onerous compromises.

Today this means we officially decided to only support officially gcc 10 and gcc 11, and definitely not gcc 8. It would have been better to support older versions, but we'll need someone who actually cares about gcc 8 to test the build and the resulting code.

So I'm closing this issue yet again.

**Comment by eliransin** [comment]
> didn't test this on gcc 9, but did test it on gcc 11.

I did :slightly_smiling_face: 

> So @eliransin maybe you're wrong, and if you upgrade to gcc 9 (your step 2), the `--cflags="-Wno-attributes"` (your step 1) is not necessary?

It is necessary for something else, for `[[ likely ]] / [[ unlikely ]]` which you encounter the first error. This is related to the place
of the attribute and not the actual attribute. This is a warning that is treated as error.

So we will still need to either add ifdefs or add the warning disablement.

**Comment by nyh** [comment]
> > So @eliransin maybe you're wrong, and if you upgrade to gcc 9 (your step 2), the `--cflags="-Wno-attributes"` (your step 1) is not necessary?
> 
> It is necessary for something else, for `[[ likely ]] / [[ unlikely ]]` which you encounter the first error. This is related to the place of the attribute and not the actual attribute. This is a warning that is treated as error.

I see. According to https://gcc.gnu.org/projects/cxx-status.html, '[[likely]]' should work on gcc 9. But maybe it doesn't actually, or only works in c++20 mode (whereas in gcc 11, it works also with c++17 mode). Can you build with gcc 9 without the `c++-dialect=c++17`?

> So we will still need to either add ifdefs or add the warning disablement.

I think the former, not the latter, is the better solution. if `[[likely]]`, `[[unlikely]]`, and `[[no_unique_address]]`` is C++-20, we shouldn't be using it for a C++17 build. If we just ignore these warnings, we may miss a more important attribute being ignored.

Anyway, I can't make up my mind if we should reopen this issue yet again. According to doc/compatibility.md, we do not support gcc 9. We can reopen this issue if there anyone interested of actively making Seastar work with gcc 9. I don't have gcc 9 installed to even test it.

**Comment by eliransin** [comment]
@linguoxuan do you have access to a newer gcc? On gcc 9 I think I can guide you how to make it work. 
But beware there is no guarantee it will be supported in the future.
The fully supported way to solve your issue is to move to gcc 10 (at least) or one of the two latest major compiler
versions out there now. If it doesn't work for you then - it is probably a bug that we should fix.
Please don't hesitate to open a new issue if the methods mentioned here or upgrading your compiler didn't help.
